ibacm/prov/acmp/src/acmp.c

Fixes bugzilla bug 2605.
prov/acmp/src/acmp.c:2869]: (error) Width 32 given in format string (no. 1) is
larger than destination buffer 'opt[32]', use %31s to prevent overflowing it.
prov/acmp/src/acmp.c:2869]: (error) Width 256 given in format string (no. 2) is
larger than destination buffer 'value[256]', use %255s to prevent overflowing
it.
Signed-off-by: Sean Hefty <sean.hefty@intel.com>
This is a trivial fix, but it is untested.

ibacm: Fix possible buffer overrun

---

README.md
build.sh

This allows for a quick build instead of typing the whole mkdir, cd,
cmake and ninja sequence.
Signed-off-by: Christoph Hellwig <hch@lst.de>

Add a build.sh helper to allow for a one-stop build

---

librdmacm/examples/rping.c

When we get an RDMA_CM_EVENT_DEVICE_REMOVAL the cm_thread will
exit and because flush errors are ignored the cb->sem may not get signaled.
So just signal on device removal event.
Fixes: 612eae1f6fe3 ("rping: ignore flushed completions")
Signed-off-by: Mustafa Ismail <mustafa.ismail@intel.com>
Reviewed-by: Steve Wise <swise@opengridcomputing.com>

librdmacm: Avoid possible hang on device removal

---

libibverbs/init.c

This commit increases the length of the value[] array to 16 because 8 bytes is not long enough to read all valid /sys/class/infiniband/*/node_type files.  For example:
```
$ cat /sys/class/infiniband/usnic_0/node_type
6: usNIC UDP
```
Including \n, this is 13 characters.
More speicifcally, in the kernel IB core, drivers/inifiniband/core/sysfs.c returns "%d: usNIC UDP\n" as the value from catenating the node_type file.
Signed-off-by: Jeff Squyres jsquyres@cisco.com

ibverbs: increase value[] len to read all node_type values

---

COPYING.md
providers/rxe/rxe.c
providers/rxe/rxe.h

Remove the patent clauses from RXE copyright notice.
Reviewed-by: Jason Gunthorpe <jgunthorpe@obsidianresearch.com>

rxe: Use default dual-license instead of PathScale

---

providers/rxe/rxe-abi.h
providers/rxe/rxe_queue.h

RXE is using default dual-license instead of PathScale,
but commit 275684bf8cb1 didn't remove everything.
Fixes: 275684bf8cb1 ("rxe: Use default dual-license instead of PathScale")

rxe: Remove patent clause leftovers

---

rdma-core.spec
redhat/rdma-core.spec

RPM needs the Requires lines for systemd to be earlier.

Fix common rdma-core.spec for systemd systems

---

providers/rxe/rxe_cfg

Remove perl::switch dependency from RXE, since it is
not installed by default.
Signed-off-by: Yonatan Cohen <yonatanc@mellanox.com>

rxe: Remove perl::switch module dependancy

---

ibacm/src/acme.c

Comment in ibacm_addr.cfg mentions that default pkey is 0xffff while
the default pkey is the first entry in pkey table which may be
different from 0xffff. Hence, comment specifying default key as 0xffff
is misleading.
Signed-off-by: Jay Patel <jay.p.patel@intel.com>
Signed-off-by: Sean Hefty <sean.hefty@intel.com>

ibacm: Modify comment related to default pkey in ibacm_addr.cfg

---

providers/qedr/qelr_chain.c
providers/qedr/qelr_chain.h
providers/qedr/qelr_verbs.c

The pointer to a CQ, SQ or RQ may wrap before reaching the end of the
queue for certain queue depths. This is fixed by using a wrapping logic
based on a pointer rather than an index.
Reviewed-by: Elior, Ariel <Ariel.Elior@cavium.com>

libqedr: fix queue wrapping logic

---

debian/changelog
debian/copyright

This is a set of patches to fix up errors and warnings in the debian
files that reported by lintian [1]. It includes debian/copyright file
according to debian's format [2].
[1]
E: rdma-core changes: bad-distribution-in-changes-file unstable
W: rdma-core source: native-package-with-dash-version
E: rdma-core source: build-depends-on-build-essential build-depends
W: rdma-core source: no-debian-copyright
W: ibverbs-providers: new-package-should-close-itp-bug
E: ibverbs-providers: no-copyright-file
W: libibcm1-dbg: new-package-should-close-itp-bug
E: libibcm1-dbg: no-copyright-file
W: librdmacm1: new-package-should-close-itp-bug
E: librdmacm1: no-copyright-file
W: libibumad3-dbg: new-package-should-close-itp-bug
E: libibumad3-dbg: no-copyright-file
W: rdma-core: …

Debian fixes

---

.travis.yml
CMakeLists.txt

The vmw driver was done before the ARM32 support, and the merge didn't quite work out.
@aditr

Fix build failures on arm32

---

providers/qedr/qelr_verbs.c

libqedr: fix SQ/RQ wrap bug
libqedr: allow post send/recv if QP is in error state
Thanks,
Ram

A couple of fixes

---

libibverbs/examples/ud_pingpong.c
libibverbs/man/ibv_rc_pingpong.1
libibverbs/man/ibv_srq_pingpong.1
libibverbs/man/ibv_uc_pingpong.1
libibverbs/man/ibv_ud_pingpong.1
libibverbs/man/ibv_xsrq_pingpong.1

Several of the ibv pingpong utilities had inconsistent options listed in their usage and manpages.  This pull request aims to make them consistent by adding in the options where they were missing.  Additionally, ibv_{ud|uc|rc|srq}_pingpong manpages all have a pointer back to ibv_xsrq_pingpong's manpage, since ibv_xsrq_pingpong's manpage points out to all of them.

libibverbs: ibv_*_pingpong manpage and usage consistency

---

debian/control
debian/rules
debian/watch
ibacm/man/ib_acme.1
ibacm/src/acme.c
libibverbs/man/ibv_rereg_mr.3
libibverbs/verbs.h
providers/i40iw/i40iw_uverbs.c
providers/ocrdma/ocrdma_verbs.c
providers/qedr/qelr_hsi_rdma.h
providers/qedr/qelr_verbs.c
redhat/rdma.mlx4-setup.sh

A full review of the packaging differences between libibverbs 1.2.1-2 from Debian and the combined rdma-core package revealed some changes. These commits contain the changes that should be carried over to rdma-core.

Debian packaging changes from libibverbs 1.2.1-2

---

CMakeLists.txt
Documentation/versioning.md
buildlib/check-build
buildlib/travis-build
debian/changelog
debian/control
debian/libibverbs-dev.install
debian/libibverbs1.symbols
libibumad/CMakeLists.txt
libibverbs/CMakeLists.txt
libibverbs/compat-1_0.c
libibverbs/ibverbs.h
libibverbs/init.c
libibverbs/libibverbs.map
librdmacm/CMakeLists.txt
rdma-core.spec
redhat/rdma-core.spec

The first part is to remove the header files that define the
prototypes for these symbols from the set of packaged headers.
This ensures that nothing can compile and use these symbols.
Next we move the symbols into a new symbol version stanza only
for the private ABI. This breaks every existing out of-tree provider,
but the earlier change to ibv_cmd_create_ah already did that.
There are a few symbols that are still private by virtue of not being
in public headers, but these are used internally by the other libraries.
For distribution sanity continue to treat them as public ABI.

Make the provider facing libibverbs interface private

---

CMakeLists.txt
Documentation/versioning.md
buildlib/check-build
buildlib/travis-build
debian/changelog
libibumad/CMakeLists.txt
libibverbs/CMakeLists.txt
librdmacm/CMakeLists.txt
rdma-core.spec
redhat/rdma-core.spec

Teach travis to check that the shared library versions and their internal symvers match our internal scheme.
This is to prevent recent mistakes in missing the cmakefile update when changing the map file.
Also update the package version to 13.

Updates for versioning

---

libibverbs/driver.h
libibverbs/libibverbs.map
redhat/rdma-core.spec

Please pull the following commits:
1. Remove unused declarations
2. Add providers to redhat's rdma-core.spec - libqedr, libhns and libvmw_pvrdma
Thanks,
Ram

remove unused declarations; add providers to redhat's spec

---

debian/control
debian/libibverbs1.symbols

This merge proposal contains two different packaging changes: The handling of private symbols of libibverbs and multi-arch settings. Please see the individual git commit messages for details.

libibverbs Debian packaging improvements

---

providers/qedr/qelr_chain.c
providers/qedr/qelr_verbs.c

Ram Amrani (3):
libqedr: Check queue mapping return value correctly
libqedr: Remove redundant memset
libqedr: Remove redundant RQ configuration

libqedr: Three queue related fixes

---

.travis.yml
buildlib/travis-build
debian/libibverbs-dev.install
debian/rules

Requested by @rleon. This will help detect obvious missed things in patches - eg symbol version changes, new header files, shlibs, etc.
@talatb @bdrung

Run a debian package build as part of travis

---

buildlib/check-build
providers/mlx5/mlx5dv.h

The mlx5dv push included some warnings from travis:
build/include/infiniband/mlx5dv.h:83:11: warning: 'struct ibv_context' declared inside parameter list [enabled by default]
struct mlx5dv_context *attrs_out);
Which should have caused travis to fail.
Add the missing include to fix them..

Fix the travis header check to use -Werror

---

providers/mlx5/mlx5.c

-Rename the ConnectX-5 PCIe 4.0 to be ConnectX-5 Ex.
-Add the VF ID of the ConnectX-5 Ex.
-Add the upcoming ConnectX-6 ID and its VF.
Signed-off-by: Majd Dibbiny <majd@mellanox.com>
Reviewed-by: Yishai Hadas <yishaih@mellanox.com>

mlx5: Update PCI supported list

---

libibverbs/neigh.c
providers/qedr/qelr_verbs.c

Missed the capitalized versions last time we did this.

Get rid of more loose min/max definitions

---

providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h

The hardware allows now to use UARs with a fixed size of 4KB. To enable
this feature we need both firmware and driver to support this feature in
order to make benefit of this. Benefit is obtained when the system page
size is larger than 4KB, like power pc.
In order to support compatbility between any version of
library/driver/firmware we add a flags field to struct
mlx5_alloc_ucontext to notify the kernel driver whether this is a new
library that supports 4KB UARs. In response, the kernel driver will
return log_uar_size and number of UARs in a page.
We also make order in the terms used. So a "page" now refers to a system
page, "uar" refers to the 4KB UAR area and "uuar" or micro uar refers to
the section in the device registers that is used for posting doorbells.
In case of larger page …

mlx5: Add support for efficient UAR allocation

---

providers/rxe/rxe_queue.h

Dropping it was a typo.
Reported-by: Josh Beavers <josh.beavers@gmail.com>
Fixes: 6b26a9e24739 ("Use C11 atomics instead of wmb/rmb macros for CPU-only atomics")

rxe: Fix dropped padding in rxe_queue

---

providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

Refactor post send by creating a function that posts a single WR
that is invoked from a loop, early all WRs validity checks so that
WR posting won't even start if it is invalid, and move the edpm
structure outside of the QP structure as a preparation for dpm.
Version 2 differences:
* updated to the latest rdma-core (post udma barriers)
* re-directs a debug print to cxt->dbg_fp (rather stderr)
Signed-off-by: Ariel Elior <Ariel.Elior@cavium.com>

libqedr: Refactor post_send

---

providers/mlx5/cq.c

Yishai explains that this is writing to WC memory in uar, so it needs
to use the WC access pattern.
This increases the leading barrier to wc_wmb()
Fixes: b6cf27b267c4 ("mlx5: Update to use new udma write barriers")
Reviewed-by: Yishai Hadas <yishaih@dev.mellanox.co.il>

mlx5: Fix the barriers in mlx5_arm_cq

---

CMakeLists.txt
ibacm/prov/acmp/src/acmp.c
ibacm/src/acm.c
libibcm/examples/cmpost.c
libibverbs/examples/xsrq_pingpong.c
librdmacm/rsocket.c
providers/qedr/qelr_verbs.c

Now that Bart got sparse working these little bugs were detected by sparse.
They change behaviour so I think Sean/etc should look at rdma cm bits.

Sparse bugs

---

CMakeLists.txt

The sparse introduction patch did not get enough testing, this broke
native stdatomic detection on all systems.
Fixes: eaceda6636cc ("buildlib/fixup-include/endian.h: Introduce this header file")

Correct broken cmake test

---

librdmacm/cma.h
librdmacm/preload.c
librdmacm/rsocket.c
providers/vmw_pvrdma/pvrdma.h

This is the rest of the code change stuff from the core libraries that sparse did not like.
There is one bug fix in here, the missing swap on INADDR_LOOPBACK.

Sparse Code Changes

---

debian/changelog
debian/ibverbs-providers.symbols

Fixes: 9614ecdae2a6 ("Bump version and update debian")

Fix incorrectly exported MLX5 symbols map in debian

---

providers/mlx5/mlx5.c

Use calloc to allocate device context so the unset bytes are zero.
When building a *non* release mode (i.e. without DCMAKE_BUILD_TYPE=Release)
the below assert is applicable and might raise:
assert(dev->_ops._dummy1).
Fix below commit to use calloc instead of malloc for mlx5 as well.
Fixes: 85c449528709 ("providers: Make every provider allocate a
verbs_device")
Signed-off-by: Artemy Kovalyov <artemyko@mellanox.com>
Reviewed-by: Yishai Hadas <yishaih@mellanox.com>

mlx5: Fix device context allocation

---

debian/changelog

The debian's changelog is managed outside of rdma-core upstream package
and hence there is no need to add entry to it, just update version only.

debian: Squash changelog to be one entry

---

libibumad/tests/CMakeLists.txt
libibumad/tests/umad_compile_test.c
libibumad/umad.h
libibumad/umad_types.h
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.h

Use umad_class_port_info rather than srp_class_port_info in SRP daemon.
In umad_class_port_info, use umad_gid unions and deprecate original [redir trap]_gid fields.
Follow on to Bart's work in PR #104

Eliminate ClassPortInfo duplication between libibumad and srp_daemon

---

libibumad/tests/umad_compile_test.c
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.h

srp_daemon/srp_daemon.[h c]: Replace open coded STATIC_ASSERT with ccan BUILD_ASSERT
libibumad: Add additional umad structure checks to umad_compile_test.c

More srp_daemon/libibumad changes involving BUILD_ASSERT

---

libibverbs/cmd.c
libibverbs/kern-abi.h
libibverbs/man/ibv_create_cq_ex.3
libibverbs/man/ibv_create_flow.3
libibverbs/verbs.h
providers/mlx5/cq.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This patch set introduces to user applications some extra flow steering
specifications, the matching kernel part was already accepted in
kernel 4.10.

Flow specs

---

.travis.yml
buildlib/cbuild
buildlib/travis-build

This is a follow up on the conversation with Leon during OFA workshop.
The patch uses Linaro cross-compilation tool-chain to build aarch64 rdma-core.
In the process, I also discovered an issue in mthca provider which caused travis failure on aarch64.

ARM 64bit build on travis

---

srp_daemon/srp_daemon.c
srp_daemon/srp_handle_traps.c
srp_daemon/srp_sync.c

get_shared_pkeys has been using SubAdmGet rather than SubAdmGetTable since
commit 2ad09524931dbf98d412e1912c1bdbf22f8ac81d
srp_daemon: Work around SM bug over non-default P_Key support
so RMPP is no longer used in response so it's not safe to
rely on AttributeOffset field. Good MAD status is sufficient
to say that valid PathRecord was returned.
Found-by: Honggang LI <honli@redhat.com>
using embedded subnet manager running on an Intel True Scale
Edge Switch 12300.
This has been broken since srptools-1.0.1 which was first
release containing commit mentioned above.
Also, added trivial patches for:
srp_daemon/srp_daemon.c: Eliminate some unneeded code in get_shared_pkeys
srp_daemon: Use consistent format when printing LID

srp_daemon/srp_daemon.c: Don't rely on attribute offset in get_shared_pkeys

---

debian/control
debian/ibverbs-providers.symbols
debian/libibverbs-dev.install

Here are some Debian packaging changes that I found while reviewing the changes from libibumad 	1.3.10.2-2 to rdma-core.

Debian packaging changes from libibumad review

---

CMakeLists.txt
MAINTAINERS
providers/bnxt_re/CMakeLists.txt
providers/bnxt_re/bnxt_re-abi.h
providers/bnxt_re/db.c
providers/bnxt_re/flush.h
providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/memory.c
providers/bnxt_re/memory.h
providers/bnxt_re/verbs.c
providers/bnxt_re/verbs.h

This series introduces the user space RoCE driver for the Broadcom
NetXtreme-E 10/25/40/50 RDMA Ethernet Controller. This driver
is dependent on the bnxt_re driver posted earlier to linux-rdma
community and is under reveiw.
This patch series is based on the latest master of rdma-core
repository hosted at https://github.com/linux-rdma/rdma-core.git
The GIT for this library is hosted at following URL on github
https://github.com/dsharma283/bnxtre-rdma-core.git
branch: bnxtre-v5
Please review and give your valuable feedback for the
betterment.
v4->v5
-- Removed unwanted inline function definition from
patch-0008
v3->v4
-- Call correct memory-barrier functions before
db ring and before CQE read.
-- Fix sparse warnings.
-- Fix ABI structures and allow byte conversion
when assiging the actual …

[rdma-core v5 0/8] Broadcom User Space RoCE Driver

---

debian/rdmacm-utils.install
librdmacm/examples/cmtime.c
librdmacm/man/CMakeLists.txt
librdmacm/man/cmtime.1
librdmacm/man/rstream.1
librdmacm/man/udpong.1

Needed for Debian release
Also, a couple of trivial fixes:
Fix transfer_count default in rstream man page
Add retries option to usage in cmtime example

Primarily add some missing librdmacm man pages

---

debian/control
debian/copyright
debian/rdma-core.lintian-overrides
debian/rules
debian/srptools.install
srp_daemon/CMakeLists.txt

I continued the review on the combined source packages. See the individual commits for details. Please review them carefully and ask in case of questions.

Debian packaging changes (from review)

---

libibverbs/man/ibv_query_device.3

This patch corrects ambiguity in documentation of max_sge and max_sge_rd
fields.

verbs: Corrected description of max_sge and max_sge_rd

---

COPYING.md
debian/control
debian/srptools.default
debian/srptools.init

As discussed on the linux-rdma mailing list, add support for querying the status of the srp_daemon(s) to the srptools init script.

Implement "status" command for Debian srptools init script

---

providers/bnxt_re/bnxt_re-abi.h
providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/memory.h
providers/bnxt_re/verbs.c

[PATCH 0/5] libbnxt_re: Critical bug fix series
These are set of bug fix patches for the libbnxt_re user
space RDMA provider library. This patch series goes
hand-in-hand with recent bnxt_re kernel driver bug fixes.
Devesh Sharma (2):
libbnxt_re: unmap DB page during uninit ucontext
libbnxt_re: reset head and tail when moving to RST
Somnath Kotur (3):
libbnxt_re: sq needs to be augmented by 128B
libbnxt_re: fix wqe size for the 0-len posting
libbnxt_re: move rts to rts after a threshold
providers/bnxt_re/bnxt_re-abi.h |  2 +
providers/bnxt_re/main.c        |  9 +++++
providers/bnxt_re/main.h        |  3 ++
providers/bnxt_re/memory.h      | 10 ++++-
providers/bnxt_re/verbs.c       | 81 +++++++++++++++++++++++++++++++----------
5 files changed, 84 insertions(+), 21 deletions(-)

libbnxt_re: Critical bug fix series

---

librdmacm/examples/rping.c
librdmacm/man/rping.1

This is useful if you have multiple adapters on the same
network or have custom routing that you want to test.
Signed-off-by: Robert LeBlanc <robert@leblancnet.us>

rping: Add config to bind to source IP address like ping.

---

debian/libibumad3.install
debian/srptools.install
libibumad/CMakeLists.txt
libibumad/libibumad.udev-rules
redhat/rdma-core.spec
srp_daemon/CMakeLists.txt
srp_daemon/srp_daemon.1.in
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.rules
srp_daemon/srp_daemon.service.5
srp_daemon/srp_daemon.service.in
srp_daemon/srp_daemon.sh.in
srp_daemon/srp_daemon_port@.service.5
srp_daemon/srp_daemon_port@.service.in
srp_daemon/start_on_all_ports

Split srp_daemon.service into srp_daemon.service and the srp_daemon_port@.service template. The former does not start any srp_daemon process but controls the latter. srp_daemon_port@.service instances are started automatically upon hot-add of an RDMA port to support hot-plugging.

srp_daemon: Rework systemd integration

---

CMakeLists.txt
librdmacm/cma.c

In uClibc some flags are not defined by default.
And that's the case for O_CLOEXEC for example, see
https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/libc/sysdeps/linux/arm/bits/fcntl.h#n52
Its definition only happens if _GNU_SOURCE is defined.
Thus users of O_CLOEXEC must define _GNU_SOURCE before inclusion of
related headers.
This solves configuration issue:
-------------------------->8---------------------
-- Performing Test HAS_CLOEXEC
-- Performing Test HAS_CLOEXEC - Failed
CMake Error at CMakeLists.txt:198 (message):
O_CLOEXEC/SOCK_CLOEXEC/fopen(..,"e") support is required but not found
-- Configuring incomplete, errors occurred!
-------------------------->8---------------------
And later compilation issue:
-------------------------->8---------------------
.../librdmacm/cma.c: …

Fix configuration and building with uClibc

---

util/udma_barrier.h

Due to a missing #else, udma_barrier.h failed on sparc and s390x
Reviewed-by: Jason Gunthorpe <jgunthorpe@obsidianresearch.com>

util: Fix mmio_flush_writes for SPARC and S390x

---

libibverbs/cmd.c
libibverbs/kern-abi.h
libibverbs/man/ibv_create_flow.3
libibverbs/verbs.h

Allows a user space application to create a drop flow specification.
This is the complementary user space part of the kernel code that was merged
into 4.12.

verbs: Introduce flow steering drop action

---

CMakeLists.txt
librdmacm/cma.c

In commit 83a8a7bd4cf "Fix configuration and building with uClibc"
we simply inserted _GNU_SOURCE definitions in configuration utility
and one source file which uses O_CLOEXEC. This solved compilation
issue against uClibc but strictly speaking that was improper solution
because O_CLOEXEC became a part of POSIX 2008 still uClibc library was
never updated accordingly and still believes it's a glibc's extension.
Essentially the most correct solution is to update uClibc and that
should be done anyways yet another short-term solution is try to
figure out if with defined _GNU_SOURCE O_CLOEXEC flags gets recognized
by the toolchain and then add built-wise definition of _GNU_SOURCE.
That way we keep sources pristine while achieving initial goal.
Signed-off-by: Jason Gunthorpe …

Improve configuration and building for uClibc

---

providers/qedr/qelr_verbs.c

Configure the byte_len field in the work completions of the RDMA READ
and RDMA SEND as it was never set.
Fixes: c0965e4fe6fe ("libqedr (qelr) verbs")

qedr: Configure byte_len in read/send WC

---

providers/qedr/qelr_verbs.c

v2 adds a Signed-off-by.
Reminding of my comment in v1, that I am going to handle the Sparse errors after a re-code that I'll introduce soon.
***
Enhanced Direct Packet Mode doesn't require flipping of bytes as it
is sent directly to the transmitting HW and isn't processed by the
FW that requires specific order.
Fixes: c0965e4fe6fe ("libqedr (qelr) verbs")

[v2] qedr: Set immediate data sent via EDPM as is.

---

buildlib/FindLDSymVer.cmake
buildlib/FindUDev.cmake
buildlib/RDMA_BuildType.cmake
buildlib/RDMA_DoFixup.cmake
buildlib/RDMA_EnableCStd.cmake
buildlib/RDMA_LinuxHeaders.cmake
buildlib/RDMA_Sparse.cmake
buildlib/cbuild
buildlib/check-build
buildlib/gen-sparse.py
buildlib/publish_headers.cmake
buildlib/rdma_functions.cmake
buildlib/relpath
buildlib/sparse-include/endian.h
buildlib/sparse-include/pthread.h
buildlib/sparse-include/stdatomic.h
debian/copyright
rdma-ndd/CMakeLists.txt

I reviewed `debian/copyright` and here are the commits to fix the stuff I found. The top commit adds the license explicitly to the source code that just refers to the COPYING file.
Sadly, following files do not carry a copyright holder and the COPYING file does not define copyright holders for this case.
```
buildlib/config.h.in
buildlib/github-release
buildlib/provider.map
buildlib/travis-build
buildlib/fixup-include/rdma-rdma_netlink.h
buildlib/fixup-include/valgrind-drd.h
buildlib/fixup-include/valgrind-memcheck.h
buildlib/sparse-include/19/netinet-in.h.diff
buildlib/sparse-include/23/sys-socket.h.diff
buildlib/sparse-include/23/netinet-in.h.diff
buildlib/sparse-include/25/netinet-in.h.diff
ccan/CMakeLists.txt
ccan/*
Documentation/*
ibacm/CMakeLists.txt
ibacm/ibacm.init.in …
```

Debian copyright review

---

debian/control

rdma-core ships /usr/sbin/rdma-ndd which was part of infiniband-diags until versions 2.0.0. Thus rdma-core and infiniband-diags < 2.0.0 cannot be installed in parallel and needs to declare a conflict.

debian: Let rmda-core conflict with infiniband-diags < 2.0.0

---

debian/copyright

The file providers/mlx4/mmio.h was removed. Thus it doesn't need to be mentioned in the copyright file any more.

debian: Remove providers/mlx4/mmio.h from copyright

---

providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/srq.c
providers/mlx4/verbs.c

Cleanup driver resources upon device fatal on closing commands. (e.g.
destroy qp/srq/cq etc.)

mlx4: Cleanup resources upon device fatal

---

providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

DPM stands for Direct Packet Mode while EDPM stands for Enhanced DPM.
Give more meaningful naming to the structures and functions to reduce
possible confusion.
Also avoid entering E/DPM functions if not in E/DPM to begin with.
Signed-off-by: Ariel Elior <Ariel.Elior@cavium.com>

libqedr: Sort out dpm/edpm naming

---

CMakeLists.txt
providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

Patch 1:
Properly use __be and __le types and their conversions.
Do not use values stored in firmware structures.
Patch 2:
Enable sparse for libqedr.

libqedr: fix sparse warnings

---

providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

Fix byte swapping function (pointer must advance).
Fix WQE size to be multiples of 16 bytes, not 8 bytes.
Pass a pointer to wqe_size to allow it to be updated.
Update the immediate value before the wqe is copied.
Fixes: 259ddded0e16 ("libqedr: fix sparse warnings")

libqedr: fix bugs introduced in "sparse fixes"

---

debian/libibverbs1.symbols
libibverbs/device.c
libibverbs/driver.h
libibverbs/ibverbs.h
libibverbs/init.c
libibverbs/libibverbs.map
providers/cxgb3/iwch.c
providers/cxgb4/dev.c
providers/hfi1verbs/hfiverbs.c
providers/hns/hns_roce_u.c
providers/i40iw/i40iw_umain.c
providers/ipathverbs/ipathverbs.c
providers/mlx4/mlx4.c
providers/mlx5/mlx5.c
providers/mthca/mthca.c
providers/nes/nes_umain.c
providers/ocrdma/ocrdma_main.c
providers/qedr/qelr_main.c
providers/rxe/rxe.c
providers/vmw_pvrdma/pvrdma_main.c
srp_daemon/srp_daemon.h
util/util.h

This series adds a device hot plug support based on the RFC and its follows discussion.

Device hot plug support

---

.travis.yml
buildlib/travis-checkpatch

The rdma-core library is tightly coupled to the linux-rdma kernel
and developed mostly by the same kernel developers. Enforcement of
the same coding style as used for kernel development has potential
to reduce errors and improve readability.
Despite the fact that checkpatch is written as general tool, the
differences between kernel and user space requires from us to
skip kernel types, file movement and execute permissions checks.

travis: Enforce kernel coding style on rdma-core

---

libibverbs/init.c

Small fix up for a case that there is a kernel driver without a matching user driver.
Drivers name list is built only once as part of read_config() and freed
upon load_drivers(). As such, calling load_drivers() more than one time has no sense and
might bring an oops in case there is some kernel driver without a
matching user driver upon the second call.

verbs: Avoid load drivers more than one time

---

buildlib/travis-checkpatch

The commit ecc5ff0c5090 ("travis: Enforce kernel coding style on rdma-core")
was proven as too optimistic, but the quality of rdma-core doesn't allow
us to treat warnings as errors.
The following patch relaxes the checks for the warnings.

travis: relax checkpatch checks by skipping warnings

---

debian/iwpmd.install
iwpmd/CMakeLists.txt
iwpmd/iwarp_pm_server.c
iwpmd/iwpmd.8.in
iwpmd/iwpmd.conf.5.in
iwpmd/iwpmd.service
rdma-ndd/rdma-ndd.c
redhat/rdma-core.spec
srp_daemon/srp_daemon.1.in
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon_port@.service.in

These were found during my kernel-boot work
- Broadly make iwpmd work sanely as a daemon with systemd, do not fork, use the right daemon name
for syslog, and do not send stderr to /dev/null
- Fix duplicated log messages in srp_daemon by removing LOG_PERROR when in systemd mode
@bvanassche @tatyana-en @larrystevenwise

Various related fixes for daemons

---

debian/rdma-core.install

After moving rxe.md into rdma-core, keep the documentation file in /usr/share/doc/rdma-core instead of moving it to /usr/share/doc/ibverbs-providers/
Fixes: 5c6372e6f17 ("Move rxe_cfg to the rdma-core package")

debian: Keep rxe.md in rdma-core directory

---

buildlib/fixup-include/systemd-sd-daemon.h
ibacm/ibacm.service.in
ibacm/src/acm.c
iwpmd/CMakeLists.txt
iwpmd/iwarp_pm_server.c
iwpmd/iwpmd.service.in
rdma-ndd/CMakeLists.txt
rdma-ndd/rdma-ndd.8.in
rdma-ndd/rdma-ndd.8.in.rst
rdma-ndd/rdma-ndd.c
rdma-ndd/rdma-ndd.service.in

This adds calls to sd_notify for iwpmd, ibacm and rdma-ndd daemons.
This allows systemd to know when the daemon has completed startup and is ready to act. This is a necessary element to solve bootup races.
The choice is to use sd_notify instead of Type=forking, mainly because most of our daemons are using threads and moving the fork point till after the threads are setup (where sd_notify is placed) is a major change in daemon design..

sd_notify for daemons

---

CMakeLists.txt
buildlib/check-build
buildlib/config.h.in
buildlib/rdma_functions.cmake
debian/ibverbs-providers.install
libibverbs/CMakeLists.txt
libibverbs/driver.h
libibverbs/ibverbs.h
libibverbs/init.c
libibverbs/libibverbs.map.in

This should have been changed when the private provider API was
introduced..
The intent of the 'rdmav2' suffix was to indicate the provider is ABI
compatible with the libibverbs loading it, with the new scheme the only
providers which are compatible have the same ABI private version.
Change the suffix to be rdmav15 to match the current private version,
and set things up to be able to track the map file/etc.

verbs: Change the provider library file name suffix

---

providers/mlx5/mlx5.c

Small change in mlx5 driver to return the CQ doorbell directly.

mlx5: Return pointer to CQ doorbell

---

CMakeLists.txt
buildlib/config.h.in
buildlib/rdma_functions.cmake
debian/ibverbs-providers.symbols
libibverbs/compat-1_0.c
libibverbs/device.c
libibverbs/ibverbs.h
libibverbs/verbs.c
providers/mlx5/CMakeLists.txt
providers/mlx5/libmlx5.map
providers/mlx5/mlx5.c
providers/mlx5/mlx5dv.h
util/CMakeLists.txt
util/symver.h

Provide two implementations of mlx5dv_init_obj, one that has the
historical behaviour that has existed until now of returning the
void **uar and a new version that returns the 'void *' version
renamed to arb_db.
Apps that use this feature must refer to it as arb_db, they will not
compile on pre-rdma-core 15 releases, and they will not dynamically
link to old versions either. This provides a sane level of safety for
the end users of this library.
Fixes: c6e3439aaa93 ("mlx5: Return pointer to CQ doorbell")

mlx5: Fix ABI break from revising the UAR pointer

---

CMakeLists.txt
buildlib/config.h.in
buildlib/rdma_functions.cmake
libibverbs/compat-1_0.c
libibverbs/device.c
libibverbs/ibverbs.h
libibverbs/verbs.c
util/CMakeLists.txt
util/symver.h

This allows libibverbs to be built statically and actually work reliably. When building statically the compat symbols will be totally discarded and normal un-versioned symbols are provided for the latest symbol.
This also fixes the problems with uclibc by providing an operating mode that produces shlibs that do not include any compat symbols, allowing them to work properly with dynamic linkers that  do not support symbol versions. @abrodkin @vennila-21

Improve symbol version macros

---

buildlib/config.h.in
libibverbs/driver.h
libibverbs/libibverbs.map.in

This causes the symbol table to look like:
208: 000000000000c000   142 FUNC    GLOBAL DEFAULT   13 verbs_register_driver_15@@IBVERBS_PRIVATE_15
Which encodes the expected private ABI version inside the symbol name
as well as with the symbol version.
This ensures that the ABI version is checked even if the linking
environment does not include symbol versions, for instance if an
end user is linking a provider static library to the system dynamic
libibverbs.

verbs: Encode the private ABI version number in verbs_register_driver

---

buildlib/travis-checkpatch

Checkpatch is not always reliable and it forces us to merge pull
requests despite the fact that they are marked as failed.
The travis triggers for every such merge and propagates such wrong
status to master branch.
Let's avoid this check on any type of git update except pull request.

travis: Limit checkpatch checks on pull requests only

---

buildlib/cbuild

Any failure should throw an exception and the return code from the
cmd_* functions should be ignored. This bogus if statement is hold
over from an earlier revision of this script.
This supersedes #190

cbuild: Do not return a failure exit code on success

---

buildlib/cbuild

buildlib: fix syntax error in cbuild

---

kernel-boot/rdma-description.rules

This provider support roce
Tested-by: Adit Ranadive <aditr@vmware.com>

kernel-boot: Add missed vmw_pvrdma

---

libibverbs/enum_strs.c

The enum value was added without adding an entry to event_type_str[].
Signed-off-by: Roland Dreier <roland@purestorage.com>

verbs: Add missing string decode for IBV_EVENT_WQ_FATAL

---

providers/mlx4/man/mlx4dv_init_obj.3
providers/mlx4/mlx4.c
providers/mlx4/mlx4dv.h

Extend mlx4dv_get_cq to return cq_uar to enable applications
direct access as part of arm_cq flow.

mlx4: Extend mlx4dv_get_cq to return uar

---

libibverbs/init.c
providers/ocrdma/ocrdma_main.c
providers/ocrdma/ocrdma_main.h
util/util.h

This is a precursor to a larger series. The big item switches verbs/init.c to use ccan lists and slightly reworks how the earlier patch to update the device list works.

Small verbs fixes

---

providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

I've adhered to the checkpatch and sparse complaints.
Added myself as signoff.
I will address the writel/mmio_write issue in a separate patch.
Thank you,
Ram
---
Introduce IS_IWARP / IS_ROCE macros for libqedr as there are no global
macros for this in rdma-core.
There is a second doorbell required for RQ.
QP states in user lib are not updated, as they are updated implicitly by
the driver and not driven by modify_qp as they are in ib / roce.
For this reason, decisions based on states are encapsulated in IS_ROCE.
Signed-off-by: Michal Kalderon <Michal.Kalderon@cavium.com>

libqedr: Add iWARP support for user-space lib

---

debian/ibverbs-providers.symbols
providers/mlx4/libmlx4.map
providers/mlx4/man/CMakeLists.txt
providers/mlx4/man/mlx4dv_query_device.3
providers/mlx4/mlx4-abi.h
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/mlx4dv.h
providers/mlx4/qp.c
providers/mlx4/verbs.c

Add mlx4 support for inline-receive, the matching kernel part was already merged into 4.14.

mlx4: Add inline-receive support

---

libibverbs/examples/devinfo.c
libibverbs/man/ibv_create_wq.3
libibverbs/verbs.h

This patch is the supplementary part of the kernel part that was accepted
upstream into 4.14. It enables the delay drop option on a WQ.

verbs: Add support for delay drop ability in a WQ

---

libibverbs/cmd.c
libibverbs/kern-abi.h
libibverbs/man/ibv_create_qp_ex.3
libibverbs/verbs.h
providers/mlx5/mlx5.h
providers/mlx5/qp.c
providers/mlx5/verbs.c
providers/mlx5/wqe.h

This patch set is the supplementary part of the kernel series that was accepted
upstream into 4.14. It enables QP creation with a given source QPN.

Source QPN support

---

ibacm/src/acm.c

Cleanup of the open port is needed when program fails to register MAD
port.
Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>

ibacm: Close MAD port when umad_register fails

---

providers/i40iw/i40iw_uk.c
providers/i40iw/i40iw_user.h

If RTR WQE is posted and QP is flushed, a CQE is
incorrectly generated for the RTR WQE. Add code
to look for the RTR and not generate a CQE when
QP is flushed.
Signed-off-by: Mustafa Ismail <mustafa.ismail@intel.com>

providers/i40iw: Do not generate CQE for RTR on QP flush

---

libibverbs/verbs.h

The commit 983f80191923 ("verbs: fix compilation error with ICC") fixed
warning by using UINTPTR_MAX, however such change breaks compilation
of C++ applications.
On some systems, the stdint.h contains the following ifdef to protect UINTPTR_MAX
"#if !defined __cplusplus || defined __STDC_LIMIT_MACROS"
The simple inclusion of <cstdint> header is not enough too to fix
compilation error, because that file was added in C++11 standard and
it produces following error while using it:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires
compiler and library support for the ISO C++ 2011 standard. This support is currently
experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
So let's fix C++ compilation break by using numeric_limits to …

verbs: Fix C++ compilation break

---

iwpmd/iwarp_pm.h
iwpmd/iwarp_pm_helper.c
iwpmd/iwarp_pm_server.c

Port-mapper returns a duplicate mapping error and no
mapped port if an attempt is made to add a mapping for
a new connection which re-uses the local port on active side.
Fix this by finding the existing  mapping for the re-used
local port and return the mapped port. Also, change ref_cnt
in struct iwpm_port to be atomic and use it to track the
references to a mapping.
Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>
Reviewed-by: Steve Wise <swise@opengridcomputing.com>

iwpmd: Return existing mapping if port reused on active side

---

ibacm/src/acm.c
ibacm/src/acm_util.c

Also, improve some other related acm log messages.

ibacm: In acm_util.c:acm_if_iter_sys, try IPv4 if IPv6 doesn't find any appropriate interfaces

---

libibverbs/verbs.h

The include of limits.h in case of C++ application throws the following
error during the compilation.
/usr/include/c++/4.8.2/limits:303:3: error: template with C linkage
template<typename _Tp>
^
The reason to such failure is the location of limits.c, it is supposed
to be included outside of C-block, so let's move it to avoid the error.
Fixes: 6a74285158a1 ("verbs: Fix C++ compilation break")

verbs: Fix declaration of C++ include file in C-block

---

providers/qedr/qelr_verbs.c

Advance target pointer during data copy.

libqedr: fix inline data copy

---

providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This patch set for mlx5 is the supplementary part of the kernel series that was
accepted upstream into 4.14.  It reports software parsing capabilities through the mlx5 DV API.

mlx5 sw parser

---

libibumad/umad.c

This can cause ibpanic in ibstat when width is not set properly
as can occur when QSPF is not plugged into port.
ibpanic: [7851] main: stat of IB device 'mlx5_1' failed: Invalid argument
It's caused by kernel sysfs.c:show_rate returning -EINVAL
and that error being treated as failure in umad.c:get_port.
With this change, Rate is displayed as 0 with ibstat for this scenario.

libibumad/umad.c: In get_port, ignore sysfs rate file errors

---

librdmacm/cma.c

Passing zero as third argument to memcpy() is allowed so the if-test is
not necessary. Hence leave it out.
Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>

librdmacm: Remove unneeded condition

---

providers/bnxt_re/main.h
providers/bnxt_re/verbs.c

Patch 1: address the memory barrier changes Jason asked while reviewing a similar change in bnxt_re driver.
Patch2: Fixes psn calculations when sending out a zero length packet. This was found during internal testing.

libbnxt_re bug fix series

---

libibverbs/cmd.c
libibverbs/verbs.h

At least the RDMA CM in 4.3 will give user space structs with these bits
set. Those kernels require user space to pass those set bits back to the
kernel. Blocking them causes RDMA CM to be unusable on older kernels.
Fixes: 3ca7a1031486 ("ibverbs: Add support for packet pacing")
Reported-by: Ram Amrani <Ram.Amrani@cavium.com>
Signed-off-by: Jason Gunthorpe <jgunthorpe@ziepe.ca>

verbs: Do not block QP attr_masks used by older kernels

---

libibverbs/cmd.c
libibverbs/driver.h
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/verbs.c
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series aligns in the user space area the flow steering uverbs commands
with other objects (e.g. QP, CQ, etc.) such that the commands don't allocate and
free the ib_flow but are just responsible to issue the comamnd.
The second patch in the series in mlx4 handles the cleanup on fatal scenario as
already done for other destroy commands on top of the above change.

Flow cleanup

---

buildlib/fixup-include/rdma-vmw_pvrdma-abi.h
providers/vmw_pvrdma/pvrdma-abi-fix.h
providers/vmw_pvrdma/pvrdma.h
providers/vmw_pvrdma/pvrdma_main.c
providers/vmw_pvrdma/pvrdma_ring.h
providers/vmw_pvrdma/qp.c

Enable userlevel applications to use SRQs.
Reviewed-by: Adit Ranadive <aditr@vmware.com>
Reviewed-by: Aditya Sarwade <asarwade@vmware.com>
Reviewed-by: Jorgen Hansen <jhansen@vmware.com>
Reviewed-by: Nitish Bhat <bnitish@vmware.com>

vmw_pvrdma: Add SRQ support

---

debian/librdmacm-dev.install
debian/librdmacm1.symbols
librdmacm/CMakeLists.txt
librdmacm/cma.c
librdmacm/examples/mckey.c
librdmacm/librdmacm.map
librdmacm/man/CMakeLists.txt
librdmacm/man/mckey.1
librdmacm/man/rdma_join_multicast_ex.3
librdmacm/rdma_cma.h
librdmacm/rdma_cma_abi.h

This adds support for the 'send only, full member' multicast join type added to a recent InfiniBand spec.
This join type allows the joiner to avoid recieving traffic from the group, without some of the downsides of the existing send only join.
This is from the mailing list, but I fixed several more problems while applying it:
- Issues with debian packagin
- Missing man page updates
- English
- check patch failures
@hnrose @shefty

Support for the MC join flag in RDMA CM

---

libibumad/umad.h
libibumad/umad_cm.h
libibumad/umad_sa.h
libibumad/umad_sm.h
libibumad/umad_str.h
libibumad/umad_types.h
libibverbs/driver.h
libibverbs/marshall.h
libibverbs/tm_types.h
libibverbs/verbs.h

to reduce symbol pollution
Replace these macros with open coding

Eliminate BEGIN_C_DECLS and END_C_DECLS macros in libibverbs and libibumad headers

---

libibumad/CMakeLists.txt
libibumad/tests/CMakeLists.txt
libibumad/tests/umad_sa_mcm_rereg_test.c
libibumad/umad_sa.h
libibumad/umad_sa_mcm.h

Add umad_sa_mcm.h to support SA MCMemberRecord
and add umad_sa_mcm_rereg_test.c (rewrite of infiniband-diags umad_rereg_test) using this new header.
Update umad_sa.h with some common enums, defines, and helpers shared with SA PathRecord and MultiPathRecord.

libibumad: Add support for SA MCMemberRecord

---

providers/cxgb3/iwch.c

Otherwise there are random crashes during device discovery.

cxgb4: Add missing null termination of hca_table

---

.travis.yml
Documentation/stable.md
buildlib/cbuild
buildlib/check-build

Add scripts to generate an ABI dump and compare against a ref.
Both tools (abi-dumper and abi-consistency-check) were imported as the
system version do not work on Travis.
Travis will automatically do that if a ref is present.
Ref should be added at stable-* branch creation (see doc update)
It seems the 1st patch is too big for the ML. So a PR will have to do.

ABI consistency check

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

This patch implements rq inline data feature in hip08
userspace.
Signed-off-by: Lijun Ou <oulijun@huawei.com>

libhns: Add rq inline data support for hip08 RoCE user mode

---

debian/ibverbs-providers.symbols
libibverbs/driver.h
providers/mlx4/verbs.c
providers/mlx5/CMakeLists.txt
providers/mlx5/libmlx5.map
providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series exposes to mlx5 DV users the ability to create an RQ with the striding functionality.
The kernel part was already merged into 4.15.

mlx5: Add striding RQ support via the DV API

---

CMakeLists.txt
buildlib/check-build
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Minor version are required for releases on stable branches.
They cannot be included in PACKAGE_VERSION as it would change library names.
- Add PACKAGE_MINOR_VERSION to CMakeList.txt
- Generate PACKAGE_VERSION.PACKAGE_MINOR_VERSION in version string in cbuild.
- Update spec file version to 16.0

Add a minor version

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_verbs.c

This patch adds the rereg mr verbs in userspace.
Signed-off-by: Shaobo Xu <xushaobo2@huawei.com>
Signed-off-by: Lijun Ou <oulijun@huawei.com>
Signed-off-by: Wei Hu (Xavier) <xavier.huwei@huawei.com>

libhns: Add rereg mr interface in userspace

---

debian/ibverbs-providers.symbols
libibverbs/man/ibv_create_qp_ex.3
libibverbs/verbs.h
providers/mlx5/libmlx5.map
providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series is the supplementary part of the kernel series that was merged into 4.15.
It introduces the following support for tunneling packets:
1) RSS on the tunneled packet.
2) Tunneling offloads support for mlx5 devices via the DV API.

Add tunnel support

---

libibverbs/examples/rc_pingpong.c
libibverbs/examples/srq_pingpong.c
libibverbs/examples/uc_pingpong.c
libibverbs/examples/ud_pingpong.c
libibverbs/man/ibv_rc_pingpong.1
libibverbs/man/ibv_srq_pingpong.1
libibverbs/man/ibv_uc_pingpong.1
libibverbs/man/ibv_ud_pingpong.1

To ease debugging of data-path issues a recv buffer validation is needed.
Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>

libibverb/examples: Add command line option to enable buffer validation

---

srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.h
srp_daemon/srp_handle_traps.c

This patch series fixes two issues of srp_daemon which occur when the master SM switches.
Both causes a failure to register to SM traps.

srp_daemon fixes

---

buildlib/cbuild

When running commands in the travis configuration it needs access to
the git history to run checkpatch, but if the local repo is using
alternates that fails.
The simple solution is to just map the alternate directories into the
container as well.

Have cbuild map the git alternates

---

libibverbs/verbs.h
librdmacm/rsocket.c
providers/bnxt_re/main.h
providers/cxgb3/iwch.h
providers/cxgb4/libcxgb4.h
providers/hfi1verbs/hfiverbs.h
providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/i40iw/i40iw_umain.c
providers/i40iw/i40iw_umain.h
providers/ipathverbs/ipathverbs.h
providers/mlx4/mlx4.h
providers/mlx5/mlx5.h
providers/mthca/mthca.h
providers/nes/nes_umain.c
providers/nes/nes_umain.h
providers/ocrdma/ocrdma_main.c
providers/ocrdma/ocrdma_main.h
providers/qedr/qelr.h
providers/qedr/qelr_main.c
providers/rxe/rxe.h
providers/vmw_pvrdma/pvrdma.h

There are several places that open code container_of and do it more poorly than the ccan version. Replace them all with ccan container_of then fix all the compile errors from the additional checking ccan container_of does.
Remove container_of from verbs.h to avoid namespace pollution and to ensure we use the ccan version.
Tidy some uses of nested container_of
Remove some pointless assignments and unnecessary function prototypes.

Various small fixes

---

libibverbs/driver.h
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_alloc_parent_domain.3
libibverbs/man/ibv_alloc_td.3
libibverbs/verbs.h
providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series enables grouping verbs objects together for the purpose of optimizing the behavior of the driver in a multi-threaded environment.
The first use of this will be for mlx5 to group UAR registers in a way that avoids needing locking on the post send path.
The series follows an RFC and a detailed discussion over it in the ML, the matching kernel side was sent to rdma-next for 4.16.

Add thread domain support

---

libibverbs/man/ibv_create_qp.3
libibverbs/man/ibv_create_qp_ex.3
libibverbs/verbs.h
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series adds the DC support to the mlx5 driver by using the IBV_QPT_DRIVER and some extensions in the mlx5 DV path to create a QP.
It's the supplementary part of the kernel series that was accepted for 4.16.

Introduce IBV_QPT_DRIVER for mlx5 DC

---

providers/mlx5/mlx5dv.h

The 'off_t' type requires the #include <sys/types.h> in some environments.
This patch adds this header file explicitly in mlx5dv.h and prevents the
need from applications to explicitly add it.
Reported-by: Shahaf Shuler <shahafs@mellanox.com>
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>

mlx5: Add missing include file in mlx5dv.h

---

providers/vmw_pvrdma/qp.c

Use the correct SQN reported by the driver.
Fixes: 4c8ed14eb6b7 ("vmw_pvrdma: Add SRQ support")
Reviewed-by: Adit Ranadive <aditr@vmware.com>
Reviewed-by: Bryan Tan <bryantan@vmware.com>
Signed-off-by: Aditya Sarwade <asarwade@vmware.com>
Cc: stable@linux-rdma.org

vmw_pvrdma: Fix SRQN returned to library

---

CMakeLists.txt
buildlib/config.h.in
buildlib/travis-build
libibverbs/CMakeLists.txt
libibverbs/cmd.c
libibverbs/cmd_cq.c
libibverbs/cmd_fallback.c
libibverbs/cmd_ioctl.c
libibverbs/cmd_ioctl.h
libibverbs/cmd_write.h
libibverbs/device.c
libibverbs/driver.h
libibverbs/ibverbs.h
libibverbs/kern-abi.h
libibverbs/libibverbs.map.in
libibverbs/verbs.h
providers/cxgb4/verbs.c
providers/hfi1verbs/verbs.c
providers/ipathverbs/verbs.c
providers/mlx4/verbs.c
providers/rxe/rxe.c

This series implements the new kabi for RDMA core, using all the functions currently implemented in the kernel as an example. It relies on all the latest kernel patches to work correctly.
It implements create_cq, create_cq_ex and destroy_cq using the new kabi.
The library continues to support the write interface, and a compile time switch is provided to select which kernel APIs will be supported. By default today only write is used.

New kabi support for rdma-core

---

ibacm/src/acm.c

Unix timestamps are great for computers, but not so great for humans. RFC3339 format looks like 2018-02-25T15:27:41.091
Signed-off-by: Matt Ezell <ezellma@ornl.gov>

ibacm: Log using RCF3339 timestamps

---

providers/qedr/qelr_verbs.c

Assign to a wc it's relevant wr_id in each completion status
(not only in success)
Signed-off-by: Yuval Bason <Yuval.Bason@cavium.com>
Signed-off-by: Michal Kalderon <Michal.Kalderon@cavium.com>

libqedr: fix wc wr_id initialization on failure cases

---

CMakeLists.txt
buildlib/fixup-include/assert.h
buildlib/make_abi_structs.py
kernel-headers/CMakeLists.txt
kernel-headers/kern-abi.c
kernel-headers/rdma/ib_user_verbs.h
kernel-headers/rdma/mlx4-abi.h
kernel-headers/rdma/rdma_user_ioctl.h
libibverbs/CMakeLists.txt
libibverbs/cmd.c
libibverbs/cmd_cq.c
libibverbs/cmd_fallback.c
libibverbs/ibverbs.h
libibverbs/kern-abi.h
providers/mlx4/verbs.c
providers/mlx5/verbs.c
providers/rxe/rxe-abi.h

This is the last step in the project to remove the kernel header duplication from libibverbs/kern-abi.h. After this step is done the drivers can be converted to remove their duplication as well.
The basic approach preserves the existing code base by not changing the struct tags with the help of a simple pre-processing script run by cmake.  The script extracts the struct members from the kernel uapi header and emits a series of #defines that create a matching anonymous and tagless struct. 
The macros then use this to build up the required struct, for instance dereg_mr will be built up as:
```c
#define _STRUCT_ib_uverbs_dereg_mr struct { __u32 mr_handle; }
struct ibv_dereg_mr {
struct ib_uverbs_cmd_hdr hdr;
union {
_STRUCT_ibv_uverbs_dereg_mr;
struct ib_uverbs_dereg_mr core_payload;
};
}; …
```

Complete removing duplication in libibverbs/kern-abi.h

---

libibverbs/driver.h
libibverbs/dummy_ops.c
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_modify_qp_rate_limit.3
libibverbs/verbs.h
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series extends verbs packet pacing QP rate limiting with burst info to allow user space application finer grain control of the QP send rate.
The matching kernel part was lastly sent into rdma-next.

Packet pacing

---

providers/mlx4/verbs.c

Enable WQ creation with the IBV_WQ_FLAGS_SCATTER_FCS flag.
Prior to using this option an application should check whether the
IBV_RAW_PACKET_CAP_SCATTER_FCS capability is set on the device's
raw_packet_caps.
The matching kernel patch for mlx4 that reports the required capability was already merged into rdma-next.

mlx4: Enable WQ creation with IBV_WQ_FLAGS_SCATTER_FCS

---

kernel-headers/CMakeLists.txt
kernel-headers/rdma/bnxt_re-abi.h
kernel-headers/rdma/cxgb3-abi.h
kernel-headers/rdma/cxgb4-abi.h
kernel-headers/rdma/hfi/hfi1_ioctl.h
kernel-headers/rdma/hfi/hfi1_user.h
kernel-headers/rdma/hns-abi.h
kernel-headers/rdma/i40iw-abi.h
kernel-headers/rdma/ib_user_cm.h
kernel-headers/rdma/ib_user_ioctl_verbs.h
kernel-headers/rdma/ib_user_mad.h
kernel-headers/rdma/ib_user_verbs.h
kernel-headers/rdma/mlx4-abi.h
kernel-headers/rdma/mlx5-abi.h
kernel-headers/rdma/mthca-abi.h
kernel-headers/rdma/nes-abi.h
kernel-headers/rdma/ocrdma-abi.h
kernel-headers/rdma/qedr-abi.h
kernel-headers/rdma/rdma_user_cm.h
kernel-headers/rdma/rdma_user_rxe.h
kernel-headers/rdma/vmw_pvrdma-abi.h
providers/cxgb3/iwch-abi.h
providers/cxgb3/iwch.c
providers/cxgb3/verbs.c
providers/hns/hns_roce_u_abi.h
providers/hns/hns_roce_u_verbs.c
providers/ocrdma/ocrdma_abi.h
providers/ocrdma/ocrdma_main.c
providers/ocrdma/ocrdma_verbs.c
providers/rxe/rxe.c

This syncs the rxe headers with the accepted kernel patches and provides the rxe patch to enforce ABI version on 32 bit.
Only the last two patches here are in this series, but the series is based on #315

Update RXE to use the latest kernel headers with the ABI change

---

kernel-headers/CMakeLists.txt
kernel-headers/rdma/cxgb3-abi.h
kernel-headers/rdma/mlx4-abi.h
kernel-headers/rdma/ocrdma-abi.h
kernel-headers/rdma/qedr-abi.h
kernel-headers/rdma/rdma_user_cm.h
kernel-headers/rdma/rdma_user_rxe.h
kernel-headers/rdma/vmw_pvrdma-abi.h
providers/cxgb3/iwch-abi.h
providers/cxgb3/iwch.c
providers/cxgb3/verbs.c
providers/hns/hns_roce_u_abi.h
providers/hns/hns_roce_u_verbs.c
providers/ocrdma/ocrdma_abi.h
providers/ocrdma/ocrdma_main.c
providers/ocrdma/ocrdma_verbs.c

Now that the kernel patches have landed this does the rest of the providers except for hfi1 and ipath, as rdmavt does not use ABI structs at all.

Convert remaining providers to use DECLARE_DRV_CMD

---

kernel-headers/rdma/mlx5-abi.h
kernel-headers/rdma/rdma_netlink.h
kernel-headers/rdma/rdma_user_cm.h
libibverbs/kern-abi.h

This pull request fixes a regression from the DECLARE_DRV_CMD series in mlx 4 as it was trying to use an ABI struct of 4 bytes through the ex interface. That was fixed in the kernel side by making the struct 8 bytes long.
Also add static assertions to make sure this case is not happening to any other structs and does not happen again.

Update kernel headers

---

CMakeLists.txt
kernel-headers/CMakeLists.txt
kernel-headers/rdma/ib_user_ioctl_cmds.h
kernel-headers/rdma/ib_user_verbs.h
kernel-headers/rdma/mlx5-abi.h
kernel-headers/rdma/mlx5_user_ioctl_cmds.h
kernel-headers/rdma/mlx5_user_ioctl_verbs.h
libibverbs/CMakeLists.txt
libibverbs/cmd.c
libibverbs/cmd_dm.c
libibverbs/driver.h
libibverbs/dummy_ops.c
libibverbs/examples/devinfo.c
libibverbs/examples/rc_pingpong.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_alloc_dm.3
libibverbs/man/ibv_post_send.3
libibverbs/man/ibv_query_device_ex.3
libibverbs/man/ibv_reg_mr.3
libibverbs/memory.c
libibverbs/verbs.h
providers/mlx5/man/mlx5dv_init_obj.3
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/qp.c
providers/mlx5/verbs.c

Many types of user space applications can get a real performance gain by
using the internal memory of an IB device.
This series is the supplementary part of the kernel series that was sent to rdma-next and enables user space applications to alloc and use directly the device memory.
This PR is on top of the IPSEC/ESP PR that is pending to be merged as it touches few shared places.

Device memory support 

---

providers/mlx5/verbs.c

Currently, the lock on an extended CQ is still taken even if the user
sets the IBV_CREATE_CQ_ATTR_SINGLE_THREADED flag. This is because the
MLX5_CQ_FLAGS_SINGLE_THREADED flag is not set before mlx5_cq_fill_pfns.
This patch sets the MLX5_CQ_FLAGS_SINGLE_THREADED flag after allocating
the extended CQ and before calling mlx5_cq_fill_pfns, allowing correct
control on the lock in mlx5_start_poll and mlx5_end_poll.

mlx5: Fix bug in disabling lock on extended CQ

---

kernel-headers/rdma/mlx5-abi.h
providers/mlx5/mlx5dv.h

Introduce a new mlx5 mini-CQE format in the DV API, the matching kernel part was already sent into rdma-next for 4.18.

mlx5: new mini-CQE format

---

ccan/CMakeLists.txt
ccan/array_size.h
providers/mlx5/verbs.c

This series fixes mlx5 to work properly with IB static rate limit by converting from the IB static rate value to
to mlx5 internal static rate value.

Mlx5 static rate limit

---

CMakeLists.txt
buildlib/RDMA_EnableCStd.cmake
util/CMakeLists.txt

On older GCC versions (at least on v4.8), SSE is not enabled by default for x86.
This causes rdma-core compilation to fail on util/mmio.c as it uses SSE functions.
This series adds a CMake helper that enables -msse if available and
adds a HAVE_SSE_EXTENSIONS flags.
mmio.c was also tweaked to support compiler without SSE.

Fix SSE support for older GCC     

---

buildlib/RDMA_EnableCStd.cmake

Travis was broken when this patch was accepted, so this was missed.
Non-x86 arches do not like the attribute(target) on main, so conditionalize
the entire thing.
Cc: stable@linux-rdma.org # v15

buildilb: Fix -msse breakage on ARM builds

---

libibverbs/cmd.c
libibverbs/man/ibv_create_flow.3

This change allows user to provide an inner MPLS flow specification among the filters list.
The matching kernel code was already accepted into rdma-next for 4.18 as part of the MPLS series.

verbs: Allow creation of inner MPLS flow spec

---

providers/mlx5/buf.c

This patch fixes a case of allocation within a huge page where the requested size is 0.

mlx5: Allocate huge page chunks only when needed

---

libibverbs/cmd_counters.c

The read counters verb uses 3 attributes and not 4, fix the number of
allocated attributes by the macro DECLARE_COMMAND_BUFFER to avoid
allocation of unnecessary memory.

verbs: Fix number of attributes allocated in read command buffer

---

CMakeLists.txt
debian/control
debian/libibverbs1.symbols

The first patch to break the provider ABI since v18 was
611f133fc193 ("verbs: Introduce counters object and its
create/destroy verbs") with many more after.

Update IBVERBS_PABI_VERSION to 19

---

buildlib/travis-build
providers/mlx5/mlx5dv.h

This series fixes compilation on 32 bit systems when sse3 is on and turns on a Travis check for that mode.

Fix compilation on 32 bit systems when sse3 is on

---

kernel-headers/rdma/cxgb4-abi.h
providers/cxgb4/cq.c
providers/cxgb4/cxgb4-abi.h
providers/cxgb4/t4.h
providers/cxgb4/verbs.c

This series adds support for user-space cxgb4 to extend cqe from existing 32Byte size to 64Byte.

cxgb4: Add support for 64Byte cqes

---

providers/rxe/rxe_cfg.in

Hi,
rxe_cfg script is throwing a warning error when bonding is configured:
Argument "" isn't numeric in numeric eq (==) at /usr/bin/rxe_cfg line 141.
This seems to happens because mentioned script parse all /sys/class/net/ path expecting there only devices. However when bonding is in use, also the bonding_masters file will be present. This is the output from my RHEL7 test system:
$ uname -r
3.10.0-693.5.2.el7.x86_64
$ rpm -q libibverbs
libibverbs-15-7.el7_5.x86_64
$ ll /sys/class/net/
total 0
lrwxrwxrwx 1 root root    0 Jul 18 10:34 bond0 -> ../../devices/virtual/net/bond0
-rw-r--r-- 1 root root 4096 Jul 18 10:34 bonding_masters
lrwxrwxrwx 1 root root    0 Jul 17 14:16 enp0s10 -> ../../devices/pci0000:00/0000:00:0a.0/net/enp0s10
lrwxrwxrwx 1 root root    0 Jul 17 14:16 enp0s3 -> …

bugfix, handled harmless warning when bonding is used

---

CMakeLists.txt
libibverbs/dummy_ops.c

gcc-8 now warns on the void (*)(void) cast, use the less pedantically
correct (void *) cast instead.
../libibverbs/dummy_ops.c:526:28: warning: cast between incompatible function types from ‘struct ibv_pd * (* const)(struct ibv_context *)’ to ‘void * (*)(void)’ [-Wcast-function-type]
(ptr)->_compat_##name = (void *(*)(void))ops->name;    \
Reviewed-by: Bart Van Assche <bart.vanassche@wdc.com>

verbs: Fix warning from gcc-8

---

CMakeLists.txt
debian/control
debian/ibverbs-providers.symbols
debian/libibverbs1.symbols
kernel-headers/rdma/ib_user_ioctl_verbs.h
kernel-headers/rdma/mlx5_user_ioctl_cmds.h
libibverbs/libibverbs.map.in
providers/mlx5/CMakeLists.txt
providers/mlx5/libmlx5.map
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series adds support for mlx5 flow steering to match the kernel series that was sent to rdma-next.
It's done in a way that enables the driver to get its specific device attributes in a raw data to match its underlying specification while still using the generic ibv_flow object for cleanup and code sharing.

mlx5 flow steering

---

kernel-headers/rdma/cxgb4-abi.h
providers/cxgb4/cq.c
providers/cxgb4/dev.c
providers/cxgb4/libcxgb4.h
providers/cxgb4/qp.c
providers/cxgb4/t4.h
providers/cxgb4/t4fw_api.h
providers/cxgb4/t4fw_ri_api.h
providers/cxgb4/verbs.c

This series adds support for rdma write with immediate and write with completion
WRs.
These are generated on top of the following iw_cxgb4 submission
#359 #360 
Corresponding kernel submission for this PR is at
https://marc.info/?l=linux-rdma&m=153181311509759&w=2

Support rdma write with immediate and write with completion WRs

---

libibverbs/cmd.c
libibverbs/cmd_counters.c
libibverbs/cmd_cq.c
libibverbs/cmd_dm.c
libibverbs/cmd_fallback.c
libibverbs/cmd_flow_action.c
libibverbs/cmd_write.h
libibverbs/driver.h
libibverbs/init.c
libibverbs/libibverbs.map.in
libibverbs/man/ibv_open_device.3
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/srq.c
providers/mlx4/verbs.c
providers/mlx5/verbs.c

This series allows destroy commands to succeed after device disassociation, this comes to prevent memory leakage in the user space area.
Setting the environment variable RDMAV_ALLOW_DISASSOC_DESTROY tells the library to relate an EIO from destroy commands as a success as the kernel resources were already released.
Applications using this flag cannot call ibv_get_cq_event or ibv_get_async_event concurrently with any call to an object destruction function.

verbs: Allow destroy after device disassociation

---

kernel-headers/rdma/hns-abi.h
providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

These patch series include the two patch-sets. The first patch-set
is("Two updates for libhns"), the second patch-set
is ("libhns: Support flush cqe for hip08 in user space")

Please pull rdma-core change for hns

---

providers/mlx4/mlx4.c

Microsoft Azure supports Mellanox MLX4 RDMA devices in HPC VM SKUs. The device
is virtualized and exposed over VMBUS, and registered as a MLX4 Infininband
hardware in RDMA layer.
This devcie is on VMBUS, not on PCI tree. Add it to the HCA table so it can
be properly discovered by user-mode driver.

Add Microsoft Azure RDMA device to MLX4 HCA table

---

libibverbs/verbs.c

Avoid accessing released memory.

verbs: Fix dereg MR

---

libibverbs/cmd_cq.c
libibverbs/man/ibv_create_cq_ex.3
libibverbs/verbs.h
providers/mlx5/mlx5-abi.h
providers/mlx5/verbs.c

This series enables creating a CQ which doesn't pass to error state if overrun, CQE always will be written to the next entry by the device.
The kernel part was accepted long time ago, this is the supplementary user space part.

CQ ignore overrun

---

providers/mlx5/man/mlx5dv_init_obj.3
providers/mlx5/mlx5.c
providers/mlx5/mlx5dv.h

Extend mlx5dv_init_obj() function to extract the device WQE address vector for the given ibv_ah.

mlx5: Expose device WQE address vector via DV

---

librdmacm/examples/CMakeLists.txt
librdmacm/examples/cmatose.c
librdmacm/examples/cmtime.c
librdmacm/examples/common.c
librdmacm/examples/common.h
librdmacm/examples/mckey.c
librdmacm/examples/rcopy.c
librdmacm/examples/riostream.c
librdmacm/examples/rping.c
librdmacm/examples/rstream.c
librdmacm/examples/udaddy.c
librdmacm/examples/udpong.c

Most of the librdmacm demos call rdma_create_event_channel() as their
first call.  Currently, when there are no RDMA devices detected, the
user gets a message like "rdma_create_event_channel: No such device".
This can be confusing as it implies that there is an issue with the
event channel mechanism, rather than an issue with the RDMA device
configuration.
Since we know why this function sets errno to ENODEV, print a specific
error message indicating that no RDMA devices were detected, so that the
user knows where to start troubleshooting.
This fixes every librdmacm example program, except for udpong's server
side, which due to the control flow does not have an obvious call that
will check for the presence of an RDMA device before entering its main
loop.
Signed-off-by: Patrick MacArthur …

librdmacm: Update message in example tools when no RDMA devices

---

providers/mlx5/mlx5.h

Flow tag is 24 bits so the mask should be 0x00ffffff instead of 0x000fffff. 
20 bits mask caused loss of MSBs in read_flow_tag().

mlx5: Fix flow tag mask

---

providers/bnxt_re/bnxt_re-abi.h
providers/bnxt_re/db.c
providers/bnxt_re/main.h
providers/bnxt_re/verbs.c

Adding support to enable shared receive queue creation,destruction,
query, post-wqes and poll for cqes. The patch is tested for
functionality.
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>

bnxt_re: Add shared receive queue support to broadcom's roce driver

---

CMakeLists.txt
debian/control
debian/ibverbs-providers.symbols
debian/libibverbs1.symbols
libibverbs/device.c
libibverbs/driver.h
libibverbs/libibverbs.map.in
providers/bnxt_re/main.c
providers/cxgb3/iwch.c
providers/cxgb4/dev.c
providers/hfi1verbs/hfiverbs.c
providers/hns/hns_roce_u.c
providers/i40iw/i40iw_umain.c
providers/ipathverbs/ipathverbs.c
providers/mlx4/mlx4.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_open_device.3.md
providers/mlx5/mlx5.c
providers/mlx5/mlx5dv.h
providers/mthca/mthca.c
providers/nes/nes_umain.c
providers/ocrdma/ocrdma_main.c
providers/qedr/qelr_main.c
providers/rxe/rxe.c
providers/vmw_pvrdma/pvrdma_main.c

Extend verbs_device_ops to get vendor data as part of alloc_context, this functionality is used by mlx5 driver to allocate a DEVX context.

Enable allocating a context with vendor data

---

buildlib/cbuild
redhat/rdma-core.spec

RHEL gets perl dependencies automatically, but Fedora requires the
perl-generators BuildRequires for it to work right.
Cc: stable@linux-rdma.org

rpm: Set perl dependencies on Fedora

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h

It needs to post the work request of atomic type
when the run atomic function by the hardware
supported. it incldues fetchadd and cmpswap
operation.
Signed-off-by: Lijun Ou <oulijun@huawei.com>

libhns: Add atomic support for hip08 user mode

---

kernel-headers/rdma/mlx5_user_ioctl_cmds.h
kernel-headers/rdma/rdma_user_ioctl_cmds.h
libibverbs/cmd_counters.c
libibverbs/cmd_ioctl.c
libibverbs/cmd_ioctl.h
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_create_flow.3.md
providers/mlx5/man/mlx5dv_create_flow_matcher.3.md
providers/mlx5/verbs.c

This series extends the existing mlx5 DV flow steering APIs to support flow actions and egress traffic. 
The verbs infrastructure was aligned with the kernel code to support passing an array of IDRs, this is used for passing an array of flow actions.

mlx5: Extend flow steering support

---

kernel-headers/rdma/ib_user_verbs.h
kernel-headers/rdma/mlx5-abi.h
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_create_qp.3.md
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series enhances the RAW QP support as follows:
1) It enables configuring self-loopback traffic.
2) It enables getting the low level device handles for the created QP.
The kernel part was already merged into 'for-next'.

mlx5: Enhance RAW QP support via the DV API

---

debian/ibverbs-providers.symbols
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_devx_obj_create.3.md
providers/mlx5/man/mlx5dv_devx_umem_reg.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series introduces the initial DEVX APIs for mlx5 driver, it enables to create a devx object and query/modify/destroy it.
In addition, the general DEVX command and the umem APIs are added as well.
The matching kernel size was already merged.

mlx5: Introduce DEVX APIs

---

ibacm/src/acm.c

When addresses are deleted, ibacm needs to call the provider to
let it know that the address has been deleted and allow it to
remove the address from its addr_info[].

ibacm: remove endpoint IP address from provider when address deleted

---

kernel-headers/rdma/mlx5_user_ioctl_cmds.h
providers/mlx5/man/mlx5dv_create_flow.3.md
providers/mlx5/verbs.c

Allow passing a flow tag value in mlx5dv_create_flow, the matching kernel code was already merged into 'for-next'.

mlx5: Allow passing a flow tag value in mlx5dv_create_flow

---

providers/bnxt_re/db.c
providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/memory.h
providers/bnxt_re/verbs.c

libnxt_re bug fixes
This pull request mainly handles the performance improvement
fixes done in the libbnxt_re code with an exception of patch
0004 which handles a bug in flush wqe management code.
Patch 0001, 0002 and 0003 are focused to optimize the doorbell
code and acquire-lock optimizations.
Devesh Sharma (3):
bnxt_re/lib: Reduce memory barrier calls
bnxt_re/lib: Remove db_lock around doorbell ring
bnxt_re/lib: Fix the frequency of acquiring flush lock
Selvin Xavier (1):
bnxt_re/lib: Fix flush list processing during poll_cq

bnxt_re/lib: libnxt_re bug fixes

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

This patchset adds memory window (mw) support for hip08,
including mw alloc, dealloc and bind.
Signed-off-by: Yixian Liu liuyixian@huawei.com
---
v2->v3:
1. according to Jason'comments, give the list of supported, not unsupported.
v1->v2:
1. revise according to Jason'comments, remove unsupported checking, reture 0.

libhns: Add mw support for hip08 in user space

---

providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_create_cq.3.md
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

Adds an option for mlx5dv_create_cq to control the CQE size
per CQ in a thread safe manner.

mlx5: CQE size control

---

debian/ibverbs-providers.symbols
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_devx_alloc_uar.3.md
providers/mlx5/man/mlx5dv_devx_query_eqn.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series introduces the DEVX APIs to work with UAR and EQ, the matching kernel size was already merged  upstream.

mlx5: Introduce DEVX APIs for UAR and EQ

---

ibacm/prov/acmp/src/acmp.c

ibacm: Check return value when deleting a cache entry

---

ibacm/prov/acmp/src/acmp.c

Some use cases establish IB communication within an IB port or between
local ports. That is, both the source and destination addresses could
be local to the node. When an IP address is removed,
acmp_remove_addr() destroys the address, but does not anticipate that
the address could be a local destination address as well. Hence, in
addition to deleting the source address, we iterate over all devices,
their ports, and endpoints, to see if the address we are removing also
is a local destination address. If so, we delete it from the cache.
Without this fix, we have:
inet 192.168.200.202/24 scope global ib0
inet 192.168.200.203/24 scope global ib1
Destination: 192.168.200.202
Source: 192.168.200.203
dgid: fe80::21:2800:1ce:ac17
sgid: fe80::21:2800:1ce:ac18
dlid: 245
slid: 246
Now, move the ib0 …

ibacm: Flush cache in provider when local address is removed

---

librdmacm/cma.c

The RDMA CM documentation indicates it supports being used for communication
management only (I.E. application manages QP). This change enables using the
RDMA CM for connected QP communication management without it managing the QP.
Since the Connection Response event is consumed in the library on the active
side, the application must ensure it closes the race of transitioning the QP
to RTR.
This change only impacts the current error path when QP are not managed
and is consistent with the other unmanaged QP checks done throughout the code.
Signed-off-by: Steve Welch <swelch@systemfabricworks.com>
Signed-off-by: James Swaro <jswaro@cray.com>

librdmacm: Allow RDMA CM use with connected QP when it is not managing the QP

---

librdmacm/examples/cmtime.c
librdmacm/examples/rdma_server.c

please consider applying these patches
- rdma_server currently can't run with default parameters over iWARP device
- cmtime leaks QP resources

Small fixes for librdmacm example applications

---

ibacm/src/acme.c

When using ib_acme to query a Path Record, ib_acme's exit status
should reflect success or failure.
Further, no need to verify the result of a failed query.

ibacm: Fix proper return value from ib_acme

---

debian/ibacm.install
debian/ibacm.maintscript
debian/rules

This is a successor to the abandoned #393
Per Discussion on the [Mailing list](https://www.spinics.net/lists/linux-rdma/msg70203.html) and some iterations on the [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/rdma-core/+bug/1794825) I think we should drop the sysV script.
For now it seems the most clear way to get rid of unconditionally starting ibacm (including failing to do so depending on the environment and breaking the postinst actions) due to debhelper actions and IMHO I don't think pre-systemd backports are important for the .deb packages anymore.
I'm open to suggestions how to convince dh_* otherwise to do the right thing, but please check out the [LP bug](https://bugs.launchpad.net/ubuntu/+source/rdma-core/+bug/1794825) about the most obvious approaches that were …

Debian avoid unconditional ibacm start

---

providers/mlx5/man/mlx5dv_init_obj.3
providers/mlx5/mlx5.c
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series exposes via the DV API few device handles that weren't handled yet, it includes: pdn, srqn and tirn for RSS QP.
The matching kernel code was already accepted.

mlx5: Expose device handles via the DV API

---

ibacm/include/acm_mad.h
ibacm/prov/acmp/src/acmp.c
libibumad/umad_sa.h
libibumad/umad_sa_mcm.h

Use existing helper functions to avoid the use of literal
constants. Took the liberty to also use those defines in some helper
functions where appropriate.
Added an enum for the Multicast Address Scope values.

ibacm: Use helper functions and existing defines to avoid literal use

---

ibacm/prov/acmp/src/acmp.c
ibacm/src/acm.c

In the default provider, acmp, the port's sa_dest.refcnt is
initialized to one in acmp_init_dest(). When a port associated with
the device is added, the refcnt is set once again to one in
acmp_port_up().
For a system with VFs enabled, the ports for both the PF and the VFs
are added. Here an extract from the log file on a system with a single
VF enabled:
acmp_port_up: mlx4_0 1
acmp_port_up: mlx4_0 1 is up
acmp_port_up: mlx4_0 1
acmp_port_up: mlx4_0 1 is up
Now, when/if this ports goes down, acmp_port_down() will be called. It
decrements the refcnt and waits endlessly until it becomes zero. For
the first call to acmp_port_down(), it becomes zero, but the
subsequent call will loop forever in said busy-waiting loop, due to
the refcnt becoming minus one.
Fixed by changing the atomic_set() to …

ibacm: Fix improper refcnt and address compare issues

---

CMakeLists.txt
debian/control
debian/libibverbs1.symbols
libibverbs/cmd.c
libibverbs/cmd_cq.c
libibverbs/cmd_fallback.c
libibverbs/cmd_ioctl.c
libibverbs/cmd_write.h
libibverbs/driver.h
libibverbs/ibverbs.h
libibverbs/kern-abi.h
libibverbs/verbs.c
providers/mlx4/verbs.c
providers/mlx5/verbs.c

This series reworks all the places that execute commands to use a consistent set of helpers around write(). The helpers are designed to accept the location of all 5 buffers (hdr, cmd, drv_cmd, resp, drv_resp) involved with a command.
This cleanup removes a bunch of duplicated code and paves the way to add more options for delivering commands to the kernel.

Execute rework

---

buildlib/travis-build

CMAKE_BUILD_TYPE can be one of five types: empty, Debug, Release,
RelWithDebInfo and MinSizeRel. Unfortunately, the cmake documentation
is not clear what will be set in "empty" type.
We remove the ambiguity by setting Debug mode.

travis: Explicitly set debug as cmake build type

---

providers/mlx4/mlx4dv.h
providers/mlx4/qp.c
providers/mlx5/verbs.c

This series handles 2 issues in mlx drivers:
- Fix SL to Ethernet priority conversion in mlx5
- Allow loopback when using raw Ethernet QP in mlx4

mlx: Fix few Ethernet related issues

---

kernel-headers/rdma/ib_user_ioctl_cmds.h
kernel-headers/rdma/ib_user_ioctl_verbs.h
libibverbs/CMakeLists.txt
libibverbs/cmd_ioctl.h
libibverbs/cmd_mr.c
libibverbs/driver.h
libibverbs/dummy_ops.c
libibverbs/examples/rc_pingpong.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_advise_mr.3.md
libibverbs/man/ibv_rc_pingpong.1
libibverbs/verbs.h
libibverbs/verbs_api.h
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series Introduces a new verb named ibv_advise_mr(), it includes:
- The application interface.
- The command interface with the kernel.
The purpose of this verb is to give an advice to the kernel about an address range belongs to a memory region.
Performance - applications that are aware of future access patterns can use this verb in order to leverage this knowledge to improve system or application performance.
One example is for pre-fetching a range part of an on-demand paging MR which is implemented by this series.
The kernel part was already sent into rdma-next.

verbs: Introduce ibv_advise_mr() verb

---

.travis.yml
CMakeLists.txt
Documentation/pyverbs.md
README.md
buildlib/Findcython.cmake
buildlib/cbuild
buildlib/pyverbs_functions.cmake
buildlib/travis-build
debian/control
debian/python3-pyverbs.install
debian/rules
pyverbs/CMakeLists.txt
pyverbs/addr.pxd
pyverbs/addr.pyx
pyverbs/base.pxd
pyverbs/base.pyx
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/enums.pyx
pyverbs/examples/ib_devices.py
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/pyverbs_error.py
pyverbs/run_tests.py
pyverbs/tests/device.py
redhat/rdma-core.spec
suse/rdma-core.spec

In this patch set we introduce python bindings (pyverbs) for
rdma-core in its initial form. It will cover libibverbs and will be
expanded to support librdmacm in the future.
Prior to developing pyverbs, the existing python-rdma package [1] was
evaluated, but a new package was built using newer Cython and Python
versions, in order to provide a more comfortable user experience.
The main goal of pyverbs is to provide the user a simple API that
makes working with verbs easier. Among other things, it allows
setting up RDMA resources quickly.
In the future, it will also suggest default configuration (e.g.
default values for QP attributes, which the user can override) and
further bring up shortcuts will be provided (e.g. QPs can change state
internally, without user intervention).
The above …

Python binding

---

ibacm/src/acm.c

The current ibacm.log file shows that there is a bug in
acm_assign_ep_names():
2018-12-21T07:49:26.410: acm_assign_ep_names: system1 mlx4_0 1 default
2018-12-21T07:49:26.410: acm_assign_ep_names: assigning system1
2018-12-21T07:49:26.410: acmp_add_addr:
2018-12-21T07:49:26.410: acmp_acquire_dest: type 1 addr system1????????
2018-12-21T07:49:26.410: acmp_get_dest: type 1 system1???????? not found
2018-12-21T07:49:26.410: acmp_alloc_dest: system1????????
2018-12-21T07:49:26.410: acmp_get_dest: system1????????
2018-12-21T07:49:26.410: acmp_put_dest: system1????????
2018-12-21T07:49:26.410: acmp_add_addr: added loopback dest system1????????
In acm_assign_ep_names(), ACM_ADDRESS_NAME type names are copied
into a buffer(which is eventually sent to the provider) without
the terminating NULL …

ibacm: ACM_ADDRESS_NAME names missing terminating NULL character

---

libibverbs/CMakeLists.txt
libibverbs/cmd.c
libibverbs/cmd_ah.c
libibverbs/cmd_fallback.c
libibverbs/cmd_flow.c
libibverbs/cmd_mw.c
libibverbs/cmd_pd.c
libibverbs/cmd_rwq_ind.c
libibverbs/cmd_xrcd.c

This series provides native ioctl implementations for trivial destroy, in case the kernel doesn't support it a fallback to the write mode will take place.
The first patch fixes a bad flow to set the error code upon execute_ioctl_fallback().

verbs: Provide native ioctl implementations for trivial destroy

---

libibverbs/cmd_ioctl.c

To prevent handling uninitialized attrs upon finalize_attrs(), mark where
attributes array ends.

verbs: Fix attribute preparation

---

libibverbs/man/ibv_uc_pingpong.1

This looks a simple typo in man doc.

fixed the typo in ibv_uc_pingpong doc

---

redhat/rdma-core.spec
suse/rdma-core.spec

The RH systems before 7.6 didn't have %python_provide macro and it
caused to rpmbuild failures on such platforms. Don't ever check
python_provide if pyverbs is not build.
Signed-off-by: Tzafrir Cohen <tzafrir@debian.org>

specs: Disable package python3-pyverbs if no python_provide macro

---

libibverbs/examples/srq_pingpong.c
libibverbs/examples/uc_pingpong.c
libibverbs/examples/ud_pingpong.c
libibverbs/examples/xsrq_pingpong.c

The buffer allocated in the UD test has extra 40 bytes reserved for
GRH for both the client and the server, while the actual payload starts
at offset 40.
Since the buffer validation applies to the payload only, we should take
this offset into account:
As the sender, make sure to fill the payload starting at offset 40 as
all data before that will not be sent on ibv_post_send.
As the receiver, make sure to validate the payload starting at offset 40
as all data before that is not part of the actual payload (GRH/not
valid).
Also, The buffer validation option doesn't require an extra parameter,
remove the extra ':' from all ibv_*_pingpong examples.
Fixes: 099c5aa50bc8 ("libibverb/examples: Add command line option to enable buffer validation")
Cc: Yuval Shaia <yuval.shaia@oracle.com> …

verbs: Fix pingpong buffer validation

---

debian/librdmacm-dev.install
debian/librdmacm1.symbols
librdmacm/CMakeLists.txt
librdmacm/cma.c
librdmacm/examples/rping.c
librdmacm/librdmacm.map
librdmacm/man/CMakeLists.txt
librdmacm/man/rdma_establish.3.md
librdmacm/man/rdma_init_qp_attr.3.md
librdmacm/man/rping.1
librdmacm/rdma_cma.h

This series enables application control in some flows as follows:
It exposes the internal function 'rdma_init_qp_attr' as an external librdmacm API.
As such an application can get the parameters for creating AH (needed for DC QP), or control QP attributes after its creation.
In addition,
It exposes CONNECT_RESPONSE event and rdma_establish() API.
Applications which do not create a QP through rdma_create_qp() may want to postpone the ESTABLISHED event on the passive side, to let the active side complete an application-specific connection establishment phase. For example, modify a QP created by the application to RTR, or make some preparations for receiving messages from the passive side.

rdmacm:  Enable application control in some flows

---

CMakeLists.txt
ibacm/CMakeLists.txt
ibacm/src/acm.c
ibacm/src/acm_util.c
ibacm/src/acm_util.h

The first commit in this series re-factors the code which iterates
through the system interfaces. The code used the ioctl SIOCGIFCONF,
which only returns "running" interfaces. Restricting the enumeration
to only "running" interfaces poses several problems. The problems are
not solved by the first commit, but the third commit, "ibacm: Unable
to resurrect an interface".
As such, the first commit does not alter any functionality.
The second commit is small fix in a debug print.
The third commit is the new implementation of
https://patchwork.kernel.org/patch/10748357, which was NAKed. This
commit is now based on the netlink re-factoring from commit one.
The forth commit aligns the use of interface names vs. interface
aliases (label) with how the ip utility works.
v1 -> v2:
* Added r-b for 2nd …

Ibacm use nl instead of ioctl

---

ibacm/src/acm.c
ibacm/src/acm_util.h

This is a small fix enabling logging of an unknown netlink client ID, and also introduces a log once functionality.

Ibacm log wrong client

---

ibacm/src/acm_util.h

While do - do while, that's how the rhythm goes.
Fixes: 51c084b2a971 ("ibacm: Introduce acm_log_once()")

ibacm: Fix acm_log_once

---

providers/cxgb4/qp.c

Remove it because it is not needed.  If we're flushing the qp, it is
because we've had a fatal error, so just set the user qp state to ERR
and continue on.
Signed-off-by: Steve Wise <swise@opengridcomputing.com>

cxgb4: remove update_qp_state()

---

libibverbs/man/ibv_query_device_ex.3
libibverbs/verbs.h
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

This series exposes PCI atomic operations capabilities to user space applications
PCI atomic operations were first introduced in PCIe Base Specification
2.1. The supported operations are swap, fetch & add and compare & swap.
Each operation can be supported in a few different operation sizes therefore we expose the capabilities in a bitmask of supported operation
sizes per operation type.
Each device needs to enable the above PCI capabilities and report on to let applications use them.
The mlx5 driver exposes the capabilities by using the DEVX interface.

verbs: Expose PCI atomic capabilities

---

kernel-headers/rdma/ib_user_verbs.h
kernel-headers/rdma/rdma_user_rxe.h
libibverbs/verbs.c
providers/mlx5/verbs.c
providers/rxe/rxe.c
providers/vmw_pvrdma/verbs.c

Add support for resolving the destination MAC address when creating the AH.
The dmac will be used by the driver to mark loopback packets if the dmac and the smac are equal.

librxe: Resolve dmac in create AH

---

providers/mlx5/verbs.c

Driver allocates memory based on wqe count and checks whether the memory
allocation succeeded. However, this memory check should not be performed
when wqe count is 0.

mlx5: Fix incorrect error handling when SQ wqe count is 0

---

iwpmd/iwarp_pm.h
iwpmd/iwarp_pm_helper.c
iwpmd/iwarp_pm_server.c

A soft iwarp driver that uses the host TCP stack via a kernel mode
socket does not need port mapping.  In fact, if the port map daemon,
iwpmd, is running, then iwpmd must not try and create/bind a socket to
the actual port for a soft iwarp connection, since the driver already
has that socket bound.
Yet if the soft iwarp driver wants to interoperate with hard iwarp
devices that -are- using port mapping, then the soft iwarp driver's
mappings still need to be maintained and advertised by the iwpm protocol.
This series updates iwpmd V4 of the IWPM ABI to support soft iwarp.
The ABI version define has been created in rdma_netlink.h so both kernel
and user code can share it.  The iwcm and iwpmd negotiate the ABI version
to use with a new HELLO netlink message.
The corresponding kernel changes …

Support for no port mapping requirements

---

ibacm/src/acm.c

Using ibacm in an environment with limited pkeys, it is unable to
obtain a Path Record (PR) in some situations.
The use of limited pkey implies communication over the logical
partition where one peer is a full member and the other is limited.
When comparing pkey values, the above difference will yield a
mismatch, even if the logical partitions of the two pkeys compared are
the very same.
Fixed by introducing a helper function which compares the logical
partitions.
Querying a PR on the peer which uses the full partition, we see
without this commit:
ib_acme -s 192.168.200.203 -d  192.168.200.200 -v
Service: /usr/local/var/run/ibacm-unix.sock
Destination: 192.168.200.200
Source: 192.168.200.203
Path information
dgid: fe80::21:2800:1a1:7c97
sgid: fe80::21:2800:1ce:ac18
dlid: 243
slid: 246 …

ibacm: Compare logical partitions instead of pkeys

---

libibverbs/cmd.c

Make sure we clear the cmd buffer, not doing so will make the kernel to
fail the command.

verbs: clear cmd buffer when creating indirection table

---

libibverbs/cmd.c
libibverbs/examples/devinfo.c
libibverbs/examples/rc_pingpong.c
libibverbs/man/ibv_query_device_ex.3
libibverbs/man/ibv_reg_mr.3
libibverbs/verbs.h

This series exposes the option to register an implicit ODP MR by user space applications.
The matching kernel code was already accepted.

verbs: Implicit ODP support

---

libibverbs/examples/rc_pingpong.c
providers/mlx5/verbs.c

This series includes few fixes for the device memory functionality as follows:
1) In mlx5 driver revises the flow of copying data from the device memory buffer to not use memcpy.
2) Avoid inline send when using device memory in rc_pingpong.

Device memory fixes

---

providers/mlx4/buf.c
providers/mlx4/cq.c
providers/mlx4/dbrec.c
providers/mlx4/man/CMakeLists.txt
providers/mlx4/man/mlx4dv_init_obj.3
providers/mlx4/man/mlx4dv_set_context_attr.3.md
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/mlx4dv.h
providers/mlx4/qp.c
providers/mlx4/srq.c
providers/mlx4/verbs.c

This series extends the DV API to control some internal resources as of memory and UAR.
For that it enables setting an external memory allocator and returns the UAR mapping information.

mlx4:  Extend the DV API to control some internal resources 

---

providers/bnxt_re/bnxt_re-abi.h
providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/verbs.c

This is to add Broadcom's 57500 series of adapters support
to RoCE from libbnxt_re. Listing below the significant changes
done as part of the patch.
- Added the pci-id of the basic gen-p5 chip.
- Adjust psn search memory allocation to suite new search
psn structure.
- Added chip context structure to select the appropriate
execution flow in data-path and control path.
- bumped up the ABI version to 2.
- Fill psn search area as per new or older chip execution
flow.
- removed duplicate declaration of BNXT_RE_ABI_VERSION macro
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>

bnxt_re/lib: Enable Broadcom's 57500 RoCE adapter

---

.travis.yml
Documentation/pyverbs.md
MAINTAINERS
buildlib/Findcython.cmake
buildlib/cbuild
buildlib/travis-build
debian/rules
pyverbs/CMakeLists.txt
pyverbs/addr.pxd
pyverbs/addr.pyx
pyverbs/base.pxd
pyverbs/base.pyx
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/mr.pxd
pyverbs/mr.pyx
pyverbs/pd.pxd
pyverbs/pd.pyx
pyverbs/tests/device.py
pyverbs/tests/mr.py
pyverbs/tests/pd.py
pyverbs/tests/utils.py

This pull requeset adds pyverbs support for PD and MR related classes,
divided as follows:
- General fixes prior to addition of new classes:
- Rename Gid class to GID and use as will be done from now on for all
acronyms.
- Unify close() functions of pyverbs objects to a single cpdef
function.
- Switch to Python-style properties, replacing the deprecated legacy
syntax.
- Add PD and MR related classes: PD, MR, MW, DM and DMMR. This part also
adds support for ibv_query_device_ex(), as it is needed for new
capabilities checks. Those patches also include unittests (for path
only).
- Add support for ibv_query_port() in Context class. This is a very
basic capability that doesn't depend on any missing infrastructure.
- Some technical/build-related commits: update MAINTAINERS file and fix
build …

Pyverbs additions

---

ibacm/src/libacm.c
iwpmd/iwarp_pm_helper.c
iwpmd/iwarp_pm_server.c
providers/hns/hns_roce_u_verbs.c

malloc() returns void* output which doesn't need to be casted.

treewide: Don't cast malloc() output

---

README.md

See https://en.opensuse.org/Help:Style#openSUSE_spelling for explanation.

README.md: Correct spelling of openSUSE

---

pyverbs/libibverbs_enums.pxd

Clean RESERVED enum members as we don't expect real applications to
use them.
Reviewed-by: Maor Gottlieb <maorg@mellanox.com>

pyverbs: Remove RESERVED entries

---

CMakeLists.txt
buildlib/cbuild
debian/rules
ibacm/src/acm_util.c

Certain versions of linux-headers nad glibc-headers had both an enum with
identifiers name IFF_* (e.g.: IFF_UP). See e.g.:
https://bugzilla.redhat.com/show_bug.cgi?id=1300256 .
Remove inclusion if <net/if.h> (<linux/if.h> is included through the
netlink3 headers).
Fixes: db109a15 ('ibacm: Replace ioctl with netlink')
Signed-off-by: Tzafrir Cohen <tzafrirc@mellanox.com>

ibacm: remove include of net/if.h due to conflict

---

buildlib/package-build-test

Change SuSE package target to leap due to random sigfaults while
running zypper command in tumbleweed under Travis CI environment.

travis: Change SuSE package target due to Travis CI failures

---

ibacm/src/acm.c

When using partitioning in a virtualized system, the Physical Function
(PF) is assigned all pkeys used by the PF and the VFs assigned to the
VMs. Typically, there will be no IPoIB interfaces plumbed, which use
the pkeys assigned to the VMs.
This is logged as errors using log level zero by the ibacm running on
the KVM server or in Xen's Dom0:
acm_ep_up: ERROR - unable to assign EP name for pkey 0x7fff
acm_ep_up: ERROR - unable to assign EP name for pkey 0x2a00
acm_ep_up: ERROR - unable to assign EP name for pkey 0xa001
acm_ep_up: ERROR - unable to assign EP name for pkey 0xa002
acm_ep_up: ERROR - unable to assign EP name for pkey 0xa003
acm_ep_up: ERROR - unable to assign EP name for pkey 0xa004
acm_ep_up: ERROR - unable to assign EP name for pkey 0xa005
acm_ep_up: ERROR - unable to assign …

ibacm: lower level of log message

---

providers/mlx5/mlx5.c

Add ConnectX-6 DX HCA ID.
In addition, add "ConnectX family mlx5Gen Virtual Function" device ID.
Every new HCA VF will be identified with this device ID.

mlx5: Add new device IDs

---

libibverbs/cmd_ioctl.c

Fix copying of returned attributes to chained buffers.

verbs: Fix attribute returning

---

providers/mlx5/srq.c

It looks likely some of the srq code was copied from qp.c and some
references to mlx5_qp and MLX5_QP* not properly replaced with their
mlx5_srq and MLX5_SRQ* equivalanets.
Signed-off-by: Mark Haywood <mark.haywood@oracle.com>

mlx5: fix erroneous mlx5_qp and MLX5_QP* references

---

providers/hns/hns_roce_u_verbs.c

This patch modifies the minimum CQ depth specification of hip08
and is consistent with the processing of hip06.
Signed-off-by: chenglang <chenglang@huawei.com>

libhns: limit minimum ROCE CQ depth to 64

---

Documentation/pyverbs.md
pyverbs/CMakeLists.txt
pyverbs/cq.pxd
pyverbs/cq.pyx
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/tests/cq.py
pyverbs/tests/device.py
pyverbs/tests/mr.py
pyverbs/tests/pd.py
pyverbs/tests/utils.py

The following patches enable creating completions queues and related
objects such as completion channel in pyverbs. These patches have
matching unit-tests patches.
The series also includes an update to pyverbs' documentation and a patch
to fix pylint issues.

pyverbs: Add completions support

---

buildlib/check-build
debian/ibverbs-providers.symbols
debian/libibverbs1.symbols
libibverbs/CMakeLists.txt
libibverbs/cmd.c
libibverbs/driver.h
libibverbs/examples/rc_pingpong.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_create_qp_ex.3
libibverbs/man/ibv_rc_pingpong.1
libibverbs/man/ibv_wr_post.3.md
libibverbs/verbs.c
libibverbs/verbs.h
providers/mlx5/CMakeLists.txt
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_create_qp.3.md
providers/mlx5/man/mlx5dv_wr_post.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/qp.c
providers/mlx5/verbs.c

Introduce a new set of QP send operations which allow extensibility for new send opcodes.
This concept lets to add vendor specific send opcodes, users can also require a set of supported QP send ops specified during QP creation.
This new API was implemented by the mlx5 driver for the general send opcodes, in addition a driver specific opcode for DC was implemented over the DV API.

verbs:  Introduce a new post send API

---

debian/ibverbs-providers.symbols
libibverbs/man/ibv_poll_cq.3
libibverbs/man/ibv_post_send.3
libibverbs/verbs.h
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_create_mkey.3.md
providers/mlx5/man/mlx5dv_create_qp.3.md
providers/mlx5/man/mlx5dv_wr_post.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/qp.c
providers/mlx5/verbs.c
providers/rxe/rxe.c

This series introduces UMR (i.e. user memory registration) builders over the DV API, it is implemented on top of the post_send refactoring series, this PR includes both to let it being compiled and work.
The new builders enable an application to register an mkey with some device specific memory layouts and then use it as part of RDMA operations.
The series uses the DEVX API as part of its implementation.

mlx5: Add UMR builders over the DV API 

---

providers/mlx5/mlx5dv.h

Fix a compiler warning when -Wcast-qual is used by adding the missing
'const' type qualifier when casting.

mlx5: Fix a compiler warning when -Wcast-qual is used

---

libibverbs/examples/srq_pingpong.c
libibverbs/examples/xsrq_pingpong.c

ibv_{xsrq,srq}_pingpong use SRQ, no need to check for IB_ODP_SUPPORT_RECV device capability to use ODP, IBV_ODP_SUPPORT_SRQ_RECV is enough.

verbs: Don't check IBV_ODP_SUPPORT_RECV in ibv_{xsrq,srq}_pingpong

---

buildlib/RDMA_BuildType.cmake

The build type was declared As "String" instead of "STRING" and it
produced the following warning while rdma-core was built.
CMake Warning (dev) at buildlib/RDMA_BuildType.cmake:11 (set):
implicitly converting 'String' to 'STRING' type.
Call Stack (most recent call first):
CMakeLists.txt:170 (RDMA_BuildType)
This warning is for project developers.  Use -Wno-dev to suppress it.
Fixes: 7cb1daa8d9e6 ("Be consistent about defining NDEBUG")

cmake: Explicitly convert build type to be STRING

---

providers/mlx5/verbs.c

Fix masking of service level when creating AH to 4 bits in case of IB link layer to match the device specification.

mlx5: Fix masking service level in mlx5_create_ah

---

README.md

Fix 'python3-deve' -> 'python3-devel'.

README.md: Fix incorrect package name in zypper install command

---

ibacm/src/libacm.c

This series of patches fixes a problem in ib_acm_connect() when the ibacm server mode is not
"unix". Decomposing ib_acm_connect() into two helper functions first is  done to be more inline with
coding conventions.
Running the ibacm server in mode loopback or open and then trying to run
ib_acme against it, fails:
$ ib_acme -S 127.0.0.1 -v -f i -s 10.196.100.60 -d 10.196.1.60
*** Error in `ib_acme': double free or corruption (fasttop): 0x000000000177c380 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f540121d619]
/lib64/libc.so.6(freeaddrinfo+0x28)[0x7f5401282fe8]
ib_acme[0x4049eb]
ib_acme[0x401841]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f54011c2c05]
ib_acme[0x40315b]
After this series of patches:
$ ib_acme -S 127.0.0.1 -v -f i -s 10.196.100.60 -d 10.196.1.60
Service: …

ibacm: acme does not work if server_mode != unix

---

libibverbs/examples/xsrq_pingpong.c

$ ibv_xsrq_pingpong -c 2
Segmentation fault
The getopt_long() optstring was modifed by 257470c2 to remove ':' from
the string leaving an optstring of "p:d:i:s:m:q:r:n:l:eg:c". The
explanation for this change in 257470c2 is:
"Also, The buffer validation option doesn't require an extra parameter,
remove the extra ':' from all ibv_*_pingpong examples."
In other ibv_*_pingpong examples, the "-c" option refers to the chk
(buffer validation) option. So, it made sense to make the change in
those example programs, but not in ibv_xsrq_pingpong.
Fixes: 257470c2 ("verbs: Fix pingpong buffer validation")
Signed-off-by: Mark Haywood <mark.haywood@oracle.com>

verbs: The ibv_xsrq_pingpong "-c" option is broken

---

Documentation/udev.md
debian/rdma-core.install
kernel-boot/CMakeLists.txt
kernel-boot/rdma-persistent-naming.rules
kernel-boot/rdma_rename.c
providers/rxe/rxe_cfg.in
redhat/rdma-core.spec
suse/rdma-core.spec

Generalize the naming scheme for RDMA devices, so users will always
see names based on topology/GUID information. Such naming scheme has
big advantage that the names are fully automatic, fully predictable
and they stay fixed even if hardware is added or removed (i.e. no
reenumeration takes place) and that broken hardware can be replaced
seamlessly.

Predictable RDMA Interface Names

---

kernel-boot/rdma_rename.c

Debian jessie provides a very ancient libnl3 version without NLA_NUL_STRING.
In order to do not disable persistent naming on such systems, we prefer
to loose our netlink type validation.
Fixes: 6b4099d47be3 ("kernel-boot: Perform device rename to make stable names")

kernel-boot: Fix build failure with ancient libnl3 versions

---

Documentation/pyverbs.md
buildlib/pyverbs_functions.cmake
pyverbs/CMakeLists.txt
pyverbs/addr.pxd
pyverbs/addr.pyx
pyverbs/cq.pxd
pyverbs/cq.pyx
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/pd.pxd
pyverbs/pd.pyx
pyverbs/qp.pxd
pyverbs/qp.pyx
pyverbs/tests/addr.py
pyverbs/tests/qp.py
pyverbs/tests/utils.py
pyverbs/utils.py
pyverbs/wr.pxd
pyverbs/wr.pyx

This PR adds the support for RDMA traffic in pyverbs. It's
consisted roughly of three parts - Address handle support, QP
support and example (RC pingpong).

Add traffic in pyverbs

---

rdma-ndd/rdma-ndd.c

Attempts to run rdma-ndd before device renames produces the following
warnings in /var/log/messages, which are harmless, but annoying.
May 15 20:56:38 server rdma-ndd[23474]: Failed to open /sys/class/infiniband/mlx4_0/node_desc
May 15 20:56:38 server rdma-ndd[23474]: set Node Description failed on mlx4_0
Fixes: 6b4099d47be3 ("kernel-boot: Perform device rename to make stable names")

rdma-ndd: Execute rdma-ndd after device rename

---

suse/module-setup.sh
suse/rdma-core.spec

SUSE dracut does not support /etc/dracut.conf.d but /usr/lib/dracut/modules.d
Replace redhat script by a simpler one that reuses the standard
udev/systemd scripts
Cc: stable@linux-rdma.org #v15

suse: fix dracut support

---

librdmacm/man/rsocket.7.in
librdmacm/rsocket.c

This series adjusts the behavior or rsockets to align with sockets.  Specifically, it adds a service thread to processing connection requests and accept them without using the application thread to drive the CM states.  This allows a single-threaded application to connect to itself, and fixes an issue in rsockets where newly accepted sockets were forced to inherit the nonblocking semantics of the listening socket.  This conflicted with normal socket behavior.
The last patch fixes the behavior of rpoll() in multi-threaded use cases.  It uses a signaling mechanism to wake up blocked threads whenever the state of an rsocket might have changed, so that the polling threads can re-check the rsocket states.
An email thread for the issues should be available here: …

rsockets: Align rsocket behavior with socket behavior

---

kernel-boot/rdma_rename.c

In our flows, we fill buffer with larger number of literals than
in second run. It causes to situation where "junk" from previous
call is left in buffer and breaks second parsing.
Fixes: 6b4099d47be3 ("kernel-boot: Perform device rename to make stable names")

kernel-boot: Reset buffer before refill

---

buildlib/azp-checkpatch
buildlib/azure-pipelines.yml
buildlib/cbuild
infiniband-diags/smpdump.c

Azure Pipelines is intended to replace travis as the CI for rdma-core.
Build times are much faster at around 5 mins (vs 23 mins for travis) and
because it is built on pre-built containers it should not suffer from the
same flakiness that travis historically has. We can now also scale up the
number of distros we are testing.
This commit replicates all the functionality of travis, except for the
automatic .tar.gz upload on release. That requires a more careful
security analysis first.
However AZP is setup to use a bionic based container, not the ancient
xenial stuff. This container uses the built in bionic arm64 and 32 bit x86
cross compiler, including all the support libraries. This means it can now
cross build everything except for pyverbs.
The GitHub experience is similar with two …

azp: Set up CI with Azure Pipelines

---

infiniband-diags/CMakeLists.txt

Incorrect linkage type causes to linkage errors on PPC platform.
[267/395] Linking C executable bin/mcm_rereg_test
FAILED: bin/mcm_rereg_test
: && /usr/bin/cc  -std=gnu11 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wmissing-prototypes -Wmissing-declarations
-Wwrite-strings -Wformat=2 -Wformat-nonliteral -Wredundant-decls -Wnested-externs -Wshadow -Wno-missing-field-i
nitializers -Wstrict-prototypes -Wold-style-definition -Wredundant-decls -O2 -g  -Wl,--as-needed -Wl,--no-undefined
infiniband-diags/CMakeFiles/mcm_rereg_test.dir/mcm_rereg_test.c.o  -o bin/mcm_rereg_test  ccan/libccan.a util/librdma_util
.a -lPRIVATE lib/libibumad.so.3.0.25.0 lib/libibmad.so.5.3.25.0 infiniband-diags/libibdiags_tools.a lib/libibumad.so.3.0.25.0
-Wl,-rpath,/tmp/rdma-core/build/lib &&
: /usr/bin/ld: …

ibdiags: Fix linkage error on PPC platform due to typo

---

librdmacm/rsocket.c

This is to fix the error:
```
[117/380] Building C object librdmacm/CMakeFiles/rdmacm.dir/rsocket.c.o
FAILED: librdmacm/CMakeFiles/rdmacm.dir/rsocket.c.o
/usr/bin/cc  -D_FILE_OFFSET_BITS=64 -Drdmacm_EXPORTS -Werror -m32
-std=gnu11 -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter
-Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wformat=2
-Wformat-nonliteral -Wredundant-decls -Wnested-externs -Wshadow
-Wno-missing-field-initializers -Wstrict-prototypes
-Wold-style-definition -Wredundant-decls -O2 -g  -fPIC -Iinclude -MMD
-MT librdmacm/CMakeFiles/rdmacm.dir/rsocket.c.o -MF
"librdmacm/CMakeFiles/rdmacm.dir/rsocket.c.o.d" -o
librdmacm/CMakeFiles/rdmacm.dir/rsocket.c.o   -c ../librdmacm/rsocket.c
../librdmacm/rsocket.c: In function ‘rs_get_comp’:
../librdmacm/rsocket.c:2148:15: …
```

rsockets: fix variable initialization

---

buildlib/cbuild
kernel-boot/rdma_rename.c

Use of PyYAML's yaml.load function without specifying the Loader=...
parameter, has been deprecated. In PyYAML version 5.1.
Before PyYAML 5.1, the PyYAML.load function could be easily exploited
to call any Python function. That means it could call any system command
using os.system().

cbuild: Upgrade PyYAML load call to v5.1

---

CMakeLists.txt
buildlib/pyverbs_functions.cmake
pyverbs/addr.pxd
pyverbs/base.pxd
pyverbs/cq.pxd
pyverbs/cq.pyx
pyverbs/device.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/mr.pxd
pyverbs/pd.pxd
pyverbs/pd.pyx
pyverbs/qp.pxd
pyverbs/qp.pyx
pyverbs/wr.pxd
pyverbs/wr.pyx

The following is a series of fixes to pyverbs:
The first two patches clean the compilation warning introduces in
Fedora 30.
The third patch fixes a wrong casting.
The last one fixes the handling of bad work requests in post send and
post recv operations.

pyverbs fixes

---

CMakeLists.txt
buildlib/pyverbs_functions.cmake

There is already a scheme to do this, don't duplicate it.
Fixes: fe53213d5b6e ("build: Remove warning-causing compilation flag from pyverbs")

build: Do not open code compiler flag detection

---

libibverbs/cmd.c

Initialize the reserved fields in create AH command to eliminate
valgrind warnings such as:
==18022== Syscall param write(buf) points to uninitialised byte(s)
==18022==    at 0x513A894: write (in /usr/lib64/libc-2.26.so)
==18022==    by 0x4E440C0: _execute_cmd_write (cmd_fallback.c:250)
==18022==    by 0x4E418BC: ibv_cmd_create_ah (cmd.c:1443)
==18022==    by 0x7E9E0F7: efa_create_ah (verbs.c:1180)
==18022==    by 0x4E4C120: ibv_create_ah@@IBVERBS_1.1 (verbs.c:641)
==18022==    by 0x403191: pp_connect_ctx (ud_pingpong.c:117)
==18022==    by 0x402694: main (ud_pingpong.c:741)
==18022==  Address 0x1ffefffe0c is on thread 1's stack
==18022==  in frame #2, created by ibv_cmd_create_ah (cmd.c:1425)

verbs: Initialize reserved attributes in create AH command

---

debian/ibverbs-providers.symbols
providers/efa/verbs.c

Remove field_avail macro and use the existing vext_field_avail.

efa: Remove reimplementation of field_avail macro

---

providers/cxgb4/dev.c

match_device handler is no longer needed after latest device binding changes.
Signed-off-by: Potnuri Bharat Teja <bharat@chelsio.com>

cxgb4: remove unused c4iw_match_device

---

providers/efa/efa.h
providers/efa/efa_io_defs.h
providers/efa/verbs.c

Hi,
Another round of fixes for the EFA provider.
First patch is a simple removal of unused fields from various structs.
Second patch is fixing an unprotected access to the wrid pool in poll_cq flow by acquiring the wqlock.
The third patch is a bit tricky as it turns out we forgot to fill the send operation type in the TX WQE (always passed 0 - invalid), which the device wrongly treated as send.
We fixed it in a backwards compatible way by changing the zero value to be send, and removed the invalid operation type.
Thanks,
Gal

2019 08 15 fixes

---

libibverbs/enum_strs.c
libibverbs/examples/devinfo.c
libibverbs/init.c
libibverbs/verbs.h

Kernel commit f95be3d28d89 ("RDMA: Add EFA related definitions")
introduced the unspecified node/transport types, reflect them in
libibverbs.

verbs: Add unspecified node/transport types

---

debian/ibverbs-providers.symbols
providers/efa/efa.c
providers/efa/efa.h
providers/efa/efadv.h
providers/efa/libefa.map
providers/efa/man/efadv_create_qp_ex.3.md
providers/efa/verbs.c
providers/efa/verbs.h

The following series from Daniel adds support for extended QP creation and the new verbs send API to the EFA provider.
Short summary of the series:
* Set errno in case of different verbs failures.
* Refactor the code to helper functions that will later be shared between post_send and the new API flows (no functional changes).
* Allow creation of extended QPs.
* Add a direct verb that creates EFA specific extended QPs, for now it allows creation of SRD extended QPs.
* Add support for the new verbs send API.

efa: Extended QP and new send API support

---

providers/mlx5/dr_devx.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5.h
providers/mlx5/srq.c
providers/mlx5/verbs.c

This reverts commit 9f35ce228f9a6c6fc4575d56a15d1b26ff7b9467.
Basic usage of ilog32 doesn't work properly, for example ilog32(64)
returns -25 and driver is broken.
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>

Revert "mlx5: Use ilog32 instead of mlx5_ilog2"

---

suse/rdma-core.spec

Lib major version should only be prefixed by a '-' if the libname itself
ends with a number (ie libibverbs1, libmlx5-1)

suse: packaging fixes

---

buildlib/check-build

The current regular expression doesn't take into account that the
package version might contain a ".a" as part of the vendor version, for
example, vXX.amznX.
Explicitly check for strings that end with ".a" by adding a $.

Fix static library regex check

---

providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

Add support to allow the opening of an existing XRC QP. This
support existed in downstream mlx5 and is needed to share
an XRC Receive QP between processes using rdma-core.
Signed-off-by: Steve Welch <swelch@systemfabricworks.com>

mlx5: Add support for ibv_open_qp

---

libibverbs/examples/ud_pingpong.c
providers/mlx4/verbs.c
pyverbs/qp.pxd
pyverbs/qp.pyx

This pull request fixes a few issues found in rdma-core:
1. In UD pingpong, change the default MTU value to be smaller than the default MTU for Ethernet devices, to avoid an error.
2. Fix a wrong assignment done in pyverbs.
3. Add missing errno reports in mlx4 (CQ creation, QP creation and AH creation).

General fixes

---

libibverbs/man/ibv_wr_post.3.md

The example in the man page refers to a non-existing field.
Update to the correct field name.
Fixes: 58ef962809865 ('verbs: Introduce a new post send API')

Fix a wrong field name in ibv_wr_post's man page

---

providers/mlx5/dr_action.c
providers/mlx5/dr_crc32.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series extends the direct rule functionality to support Geneve packets as part of the flex parser.
It includes some refactoring of the VXLAN GPE mode in the flex parser area to enable smooth adding of the Geneve support.
In addition, some typos were fixed.

mlx5: Extend direct rule support

---

providers/mlx5/dr_rule.c

Duplicate rules were not allowed to be configured with SW steering, unlike when working over root, fix to allow that. This functionality is useful for replacing rules without dropping
packets.

mlx5: Allow insertion of duplicate rules using DR API

---

libibverbs/cmd.c

Set missing errno in ibv_cmd_reg_mr() when implicit MR is used.

verbs: Set missing errno in ibv_cmd_reg_mr

---

buildlib/centos6.spec

fix centos6 Azure pipeline failure:
....
-rw-r--r-- vsts_azpcontainer/vsts_azpcontainer  2789 2019-11-05 09:51
rdma-core-27.0/buildlib/pandoc-prebuilt/9fcf3f165ed59609a3e94199a5b963ba461c423a
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd rdma-core-26.0
/__w/1/s/tmp/rpm-tmp.oWTBf9: line 38: cd: rdma-core-26.0: No such file or directory
error: Bad exit status from /__w/1/s/tmp/rpm-tmp.oWTBf9 (%prep)
Fixes: 35f5864d6fd2 ("Update library version to be 27.0")
Reported-by: Michal Kalderon <mkalderon@marvell.com>

Update centos6 spec file to library version 27.0

---

providers/cxgb4/dev.c

This pull request containesfixes:
- freeing the right pointer in error case.
- properly initializing the chip version.

cxgb4: general fixes around c4iw_alloc_context()

---

providers/vmw_pvrdma/pvrdma-abi.h
providers/vmw_pvrdma/pvrdma.h
providers/vmw_pvrdma/qp.c

These patches allow the vmw_pvrdma driver to expose different values for qp handle and qp num to userspace.

Use physical resource ids from device

---

Documentation/pyverbs.md
buildlib/pyverbs_functions.cmake
pyverbs/CMakeLists.txt
pyverbs/cm_enums.pyx
pyverbs/cmid.pxd
pyverbs/cmid.pyx
pyverbs/device.pyx
pyverbs/librdmacm.pxd
pyverbs/librdmacm_enums.pxd
pyverbs/pd.pyx
tests/CMakeLists.txt
tests/base.py
tests/rdmacm_utils.py
tests/test_pd.py
tests/test_rdmacm.py

The following patches add support for RDMACM in pyverbs. Currently
only synchronous data path is supported (creation using rdma_create_ep).
Testing infrastructure for RDMACM is also added as well as a synchronous
traffic test.

Introducing RDMACM support in pyverbs

---

libibverbs/man/ibv_alloc_dm.3

ibv_reg_dm_mr returns a struct ibv_mr pointer while man page defined
it as returning an int. Fix the description.
Fixes: e1cebbf50c262 ('verbs: Add device memory (DM) support in libibverbs')

man: Fix return value for ibv_reg_dm_mr

---

providers/mlx5/mlx5.c

Update list of supported PCI devices with Mellanox BlueField-2
integrated ConnectX-6 Dx network controller.
Signed-off-by: Shani Shapp <shanish@mellanox.com>
Reviewed-by: Eran Ben Elisha <eranbe@mellanox.com>

mlx5: Add ConnectX-6 DX Bluefield 2 to the list of supported devices

---

providers/qedr/qelr_verbs.c

The create_qp response structure needs to be zeroed before receiving
data from kernel, otherwise, when running over an old kernel we can get
garbage for db_rec_addr and fail when attempting to map it.
Signed-off-by: Ariel Elior <ariel.elior@marvell.com>
Signed-off-by: Michal Kalderon <michal.kalderon@marvell.com>

libqedr: Fix doorbell recording compatibility

---

pyverbs/qp.pyx

A common practice in C is to modify QP capabilities as follows:
qp_init_attr.cap.max_send_wr = <some value>
It's impossible to use this syntax in pyverbs, since qp_init_attr.cap
is a getter which returns a copy of the QP caps to the user rather
than an object which holds the same C QP caps.
Add new properties to QPInitAttr and QPInitAttrEx to allow direct
modification these values, e.g.:
qp_init_attr.max_send_wr = <some value>

pyverbs: Allow users to set QP caps through QPInitAttr and QPInitAttrEx

---

README.md
buildlib/cbuild
redhat/rdma-core.spec
redhat/rdma.udev-rules

Add EFA to redhat's udev rules and add an explicit udev trigger.
Cbuild is modified to support for Amazon Linux 1 & 2 packaging.

Misc build updates

---

Documentation/pyverbs.md
pyverbs/cq.pyx
pyverbs/libibverbs_enums.pxd
pyverbs/providers/mlx5/libmlx5.pxd
pyverbs/providers/mlx5/mlx5dv.pxd
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/providers/mlx5/mlx5dv_enums.pxd
pyverbs/qp.pyx
tests/CMakeLists.txt
tests/test_cqex.py
tests/utils.py

This series adds the needed infrastructure to pyverbs to allow users
to create mlx5 CQ and QP.
Tests using the extended CQ were added as well.

pyverbs: Expose additional DV objects

---

providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5.c
providers/mlx5/mlx5dv.h

Added a new mlx5dv context mask value so that HCA clock address can be
queried via mlx5dv_query_device.

mlx5: Add support to query HCA clock via mlx5dv_query_device

---

pyverbs/qp.pyx

When using QPAttr's ah_attr getter, a new AHAttr object is created.
Port number wasn't passed to its constructor, so the default value (1)
was used.
Pass the current port number to AHAttr constructor.
Signed-off-by: Ido Kalir <idok@mellanox.com>
Reviewed-by: Noa Osherovich <noaos@mellanox.com>

pyverbs: return correct port number in QPAttr's AH property

---

providers/mlx5/verbs.c

Atomic operations are supported when either the device supports IBV_ATOMIC_HCA or IBV_ATOMIC_GLOB.
Allow QP to execute atomic operations when atomic device capabilities are not zero (i.e. not IBV_ATOMIC_NONE).

mlx5: Support atomic operations when device reports IBV_ATOMIC_GLOB

---

librdmacm/rsocket.c

glibc redirects pthread_yield to sched_yield additionally we get it
working with musl on linux
Signed-off-by: Khem Raj <raj.khem@gmail.com>

librdmacm: Use sched_yield instead of pthread_yield

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c

These two patches were in previous series "Support UD on hip08"
(PR: https://github.com/linux-rdma/rdma-core/pull/587) which was closed because of the UD issue with hip08.
Although we have decided to not support UD, these two patches is still
significant to simplify codes of post_send/recv.

libhns: Refactor post send/recv

---

pyverbs/addr.pyx
pyverbs/base.pxd
pyverbs/base.pyx
pyverbs/cmid.pyx
pyverbs/cq.pyx
pyverbs/device.pyx
pyverbs/mr.pyx
pyverbs/pd.pyx
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/qp.pyx
pyverbs/srq.pyx
pyverbs/wr.pyx
pyverbs/xrcd.pyx
tests/test_mr.py
tests/test_pd.py
tests/test_qp.py
tests/utils.py

The following series refactors pyverbs' objects creation process and
cleans up some redundant tests:
The first patch removes its close_weakrefs() out of the base objects,
as it doesn't use 'self' and is called during teardown, when the
object might not be fully valid.
The second patch switches pyverbs to use Python's init method rather
thab Cython's cinit method, during which the Python object is not yet
valid. Calling rdma-core's objects creation methods can be done in
init just as well.
The last patch removes some unneeded tests and adapts QP creation
tests to consider TSO existance when setting QP caps.

pyverbs: Code refactoring

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_action.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_domain.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

In switchdev mode, all unmatched traffic in FDB flow table should go to the eswitch manager, the first patch from the series makes this to work as expected.
The next two patches introduce some extra DV APIs to expose the device metering functionality to applications.

mlx5: SW steering improvements

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h

Support extended atomic operations including cmp & swap and fetch & add
of 8 bytes, 16 bytes, 32 bytes, 64 bytes on hip08.

libhns: Add support for extended atomic

---

providers/mlx5/mlx5.c

Update list of supported PCI devices with Mellanox ConnectX-7 network controller.

mlx5: Add ConnectX-7 to the list of supported devices

---

libibverbs/man/ibv_reg_mr.3
libibverbs/verbs.h
pyverbs/libibverbs_enums.pxd
pyverbs/mem_alloc.pyx
pyverbs/mr.pxd
pyverbs/mr.pyx
tests/test_odp.py
tests/utils.py

This series exposes the IBV_ACCESS_HUGETLB access flag to indicate that the MR range will be mmaped by huge pages, the flag is applicable only with conjunction of IBV_ACCESS_ON_DEMAND.
In addition, the series includes some pyverbs infrastructure to enable using this flag and some new ODP test on top.

verbs: Expose IBV_ACCESS_HUGETLB access flag

---

tests/run_tests.py

Avoid the following failure when running the tests from the tests
directory.
[root@rdma-dev-25 tests]$ python3 run_tests.py -v
File "run_tests.py", line 11, in <module>
tests = SourceFileLoader('tests', module_path).load_module()
File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
File "<frozen importlib._bootstrap_external>", line 907, in load_module
File "<frozen importlib._bootstrap_external>", line 732, in load_module
File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
File "<frozen importlib._bootstrap>", line 696, in _load
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 724, in exec_module
File "<frozen importlib._bootstrap_external>", …

tests: Fix exception when running the tests from the tests directory

---

debian/copyright
debian/srptools.install
redhat/rdma-core.spec
srp_daemon/CMakeLists.txt
srp_daemon/ibsrpdm.1
srp_daemon/srp_daemon.8.in
suse/rdma-core.spec

A quote from Benjamin Drung: "The command in /sbin or /usr/sbin are
system administration commands; their manpages thus belong in section
8, not section 1."
Cc: Benjamin Drung <benjamin.drung@cloud.ionos.com>
Signed-off-by: Bart Van Assche <bvanassche@acm.org>

srp_daemon: Move man page from section 1 to section 8

---

providers/vmw_pvrdma/cq.c
providers/vmw_pvrdma/pvrdma.h
providers/vmw_pvrdma/qp.c

After the change to distinguish QP numbers and QP handles, the
cqe->qp field contains the QP handle so as to make lookup for
QPs simple. Flushing CQEs upon destroy of QP needs to be done
by comparing the cqe->qp field with the QP handle, not the QP
number. This change fixes this issue.
Fixes: 3dbaeba640d7  ("vmw_pvrdma: Use resource ids from physical device
if available")
Reviewed-by: Jorgen Hansen <jhansen@vmware.com>
Reviewed-by: Rajesh Jalisatgi <rjalisatgi@vmware.com>

vmw_pvrdma: Use QP handle when attempting to flush CQEs

---

pyverbs/cq.pxd
pyverbs/cq.pyx
tests/CMakeLists.txt
tests/test_cq_events.py
tests/utils.py

CQ events have to be acked prior to CQ destruction. Otherwise, CQ
destruction will wait indefinitely for those events to be acked.
In Python it's possible for a simple syntax error to cause a runtime
error which leads to teardown of all objects. For CQ, this can mean
a destruction without acking CQ events.
To avoid that, keep track of the number of events and during teardown,
if there are events that weren't acked, do so implicitly.
The first patch adds this support. The second one adds a simple
traffic test that uses CQ events mechanism rather than poll.

pyverbs: Support CQ events properly

---

providers/mlx5/dr_action.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv_dr.h

This series enhances modify header DR action to support copy.
Copy allows to copy header fields and metadata.
The first patch is some refactoring for the modify header existing options (i.e. add/set), the second patch adds the copy support.

mlx5: Enhance modify header to support copy

---

tests/test_parent_domain.py

Avoid the following exception when no IB device found, by skipping the test.
ERROR: test_default_allocators (tests.test_parent_domain.ParentDomainTestCase)
File "/home/kheib/git/upstream/rdma-core/tests/test_parent_domain.py", line 35, in setUp
dev = d.get_device_list()[-1]
IndexError: list index out of range
Fixes: 4fec6737c9bd ("tests: Add a test for parent domain")

tests: test_parent_domain: Fix exception when no IB device found

---

Documentation/pyverbs.md
debian/ibverbs-providers.symbols
kernel-headers/rdma/mlx5_user_ioctl_cmds.h
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_alloc_var.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/providers/mlx5/libmlx5.pxd
pyverbs/providers/mlx5/mlx5dv.pxd
pyverbs/providers/mlx5/mlx5dv.pyx
tests/CMakeLists.txt
tests/test_mlx5_var.py

This series exposes mlx5 direct verbs to allocate/free a VAR.
The allocated VAR can be used in Virtio environment to set a DB and also with some DEVX commands by vDPA applications.
The series includes also some pyverbs infrastructure and test on top which uses the new APIs.
The matching kernel part was already sent into rdma-next.

mlx5: Expose VAR DV APIs

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h

When poll cqe successfully, more cqe information needs to be recorded into
wc.

libhns: Record more info into wc after poll cqe

---

tests/base.py

Avoid the following error by iterating over the availbe gid range.
File "/home/rdma-core/tests/test_cq_events.py", line 26, in setUp
super().setUp()
File "/home/rdma-core/tests/base.py", line 122, in setUp
self._add_gids_per_device(ctx, dev_name)
File "/home/rdma-core/tests/base.py", line 149, in _add_gids_per_device
self._add_gids_per_port(ctx, dev, port+1)
File "/home/rdma-core/tests/base.py", line 138, in _add_gids_per_port
gid = ctx.query_gid(port, idx)
File "device.pyx", line 195, in pyverbs.device.Context.query_gid
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to query gid 1 of port 1
Fixes: bb5958680256 ("tests: RDMATestCase")

tests: Fix exception when query GIDs

---

pyverbs/cmid.pxd
pyverbs/cmid.pyx
pyverbs/librdmacm.pxd
tests/base.py
tests/rdmacm_utils.py
tests/test_rdmacm.py

This series exposes asynchronous RDMACM control path and adds a new related test.
Pyverbs:
With CMEvent and CMEventChannel (wrapper objects of rdma_cm_event and
rdma_event_channel) we allow CMID object to establish a connection
using the events API.
Expansion of CMID object:
Added necessary API for asynchronous control path e.g. bind_addr(),
resolve_addr(), resolve_route(), establish() and more.
tests:
Added necessary API to CMResources object which is the base aggregation
object for RDMACM and expended rdmacm_utils.py for asynchronous control
path.

pyverbs: Support asynchronous RDMA CM 

---

providers/hns/hns_roce_u_hw_v2.c

CQ has its private error codes, there is no need to use other error codes
in hns_roce_handle_recv_inl_wqe(), which will affect the return value of the
poll cq function.
And if the err state is V2_CQ_POLL_ERR, the ci pointer needs to be
updated as the cqe has already been generated.

libhns: Fix for the error code when polling cq

---

providers/mlx5/mlx5dv.h

Change flow_meter_parameter type from __be64[] to void *.
It allows to user to assign pre allocated buffer.

mlx5: Change flow_meter_parameter to be void *

---

librdmacm/rsocket.c

Rsockets will use a thread to drive connection state. However,
checks against the rsocket state are made outside of locks in
send/recv/poll.  If the state is still listed as opening, 
rs_do_connect will be called, where the state will be checked
under lock.  Because a separate thread is driving the connection
state, the rsocket state may be connected at this point.
Update rs_do_connect to return 0 (success) if the rsocket
is already in the connected state.  This fixes failures using
rsockets in the JDK test set.
Signed-off-by: Sean Hefty <sean.hefty@intel.com>

rsockets: Add check for established connection

---

ibacm/src/acm.c

Commit 26e05f8304a5 ("ibacm: use ccan/list.h") introduced a bug in
acm_get_ep() by not incrementing inx.
Fixes: 26e05f8304a5 ("ibacm: use ccan/list.h")

ibacm: Fix bug in acm_get_ep()

---

tests/test_mlx5_var.py
tests/test_parent_domain.py

Instead of comare strings, use the stored error code in the
PyverbsRDMAError exception to determine the failure.

tests: Use error code to determine the failure

---

Documentation/udev.md
kernel-boot/rdma_rename.c

The multi-function devices have same system image GUID while presented
with multiple IB devices. This leads to the failures for NAME_GUID
option to rename second device. Instead of system image GUID use
node GUID as a unique identifier.
Cc: <stable@linux-rdma.org>
Fixes: 6b4099d47be3 ("kernel-boot: Perform device rename to make stable names")

kernel-boot: Use node GUID instead of system image GUID

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_dbg.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_rule.c
providers/mlx5/dr_table.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dump.3.md
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series introduces few DV APIs that allows the dumping of existing DR resources to a provided file.  
The output file can be parsed as part of debugging/analyzing the DR state,  the data format is mlx5 vendor specific.

mlx5: Introduce DV APIs to dump DR information

---

tests/test_device.py

In some devices, the page_size_cap is equal to PAGE_SIZE.
Fixes: 9d66a1abc0bd ("pyverbs: Add support for extended query_device")

tests: Fix checking page_size_cap

---

tests/test_device.py

Avoid code duplication by move the code of getting the available devices
to a separate function.
Fixes: 8c55be00ced5 ("tests: Skip old tests when no IB devices are found")

tests: Avoid code duplication

---

ibacm/man/ibacm.1
ibacm/prov/acmp/src/acmp.c
ibacm/src/acm.c

This is a re-wrap of my series made in November 2018.
On a system with a CX-3, which has 8 VFs enabled, this series has been tested by adding thousands of addresses and deleting them in parallel, concurrently with issuing path queries by means of ib_acme.
On top of this cmtime has been run in a loop creating/deleting 1000 QPs per invocation.
On top of the above, Oracle's Active/Active RDMA failover mechanism, https://blogs.oracle.com/linux/resilient-rdma-ip-addresses, has been triggered to move the above IP addresses back and forth between the ports by means of IB port down/up transitions.

ibacm: Allocate end-point addresses dynamically

---

providers/efa/efa.c

The EFA provider cannot work correctly when there's no udata in
create_ah verb, as we must get the AH number from the kernel.
Without this patch, the provider assumes the AH number is zero for all
AHs, which results in unexpected behavior.
On context allocation, identify kernels that don't support udata and
exit.

efa: Fail context allocation in case create AH verb doesn't have udata

---

providers/vmw_pvrdma/qp.c

qp->sq.lock is currently unlocked twice when the ring state is invalid.
Fix this by removing the goto, and also set bad_wr correctly.
Fixes: 36756a63b3b5 ("libpvrdma: Add queue pair functions")
Cc: stable@linux-rdma.org
Reviewed-by: Vishnu Dasa <vdasa@vmware.com>
Reviewed-by: Adit Ranadive <aditr@vmware.com>
Reviewed-by: Rajesh Jalisatgi <rjalisatgi@vmware.com>

vmw_pvrdma: Avoid double unlock on qp->sq.lock

---

providers/qedr/qelr_main.c

The user context alloc request structure introduced a new field
to indicate doorbell recovery is supported. This field was added so
that additional features could be added in the future by setting a
capability flag. However, the field wasn't zeroed, and was initialized
using "|=" instead of "=" leading to garbage in the other bits.
For forward compatability, we need to make sure all other bits are
zero.
Cc: stable@linux-rdma.org # v27 v28
Fixes: d9b2ba480af5 ("libqedr: Add support for Doorbell Overflow Recovery")
Signed-off-by: Ariel Elior <ariel.elior@marvell.com>
Signed-off-by: Michal Kalderon <michal.kalderon@marvell.com>

libqedr: Fix user context allocation forward compatibility

---

providers/hns/hns_roce_u_hw_v2.c

The state of ibvqp will be updated after calling modify_qp(), because the
assignment of ibvqp->state is out of hns driver, it can't be guaranteed
that the configuration of ibvqp->state will take effect immediately. This
may cause hns_roce_u_v2_modify_qp() in post_send/post_recv process is
skipped.
Therefore, update value of ibvqp->state in modify_qp().

libhns: Update ibvqp->state in hns_roce_u_v2_modify_qp()

---

providers/hns/hns_roce_u_hw_v2.c
providers/mlx5/dr_dbg.c

Fix few compilation issues in i386 with the below pattern of errors.
../providers/hns/hns_roce_u_hw_v2.c: In function 'set_atomic_seg':
../providers/hns/hns_roce_u_hw_v2.c:93:12: error: cast to pointer from
integer of different size [-Werror=int-to-pointer-cast]
(void *)wr->wr.atomic.swap);
../providers/mlx5/dr_dbg.c:91:29: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]

Fix compilation on i386 with gcc

---

librdmacm/rsocket.c

In rs_do_connect, if the rsocket state is not connected, we set
errno = EINVAL and ret = -1.  Later in the code, we modify the
rsocket state to an error state and save errno with the rsocket.
Apps can obtain the error data through getsockopt.
This can result in overwriting real connection error data that
may have been saved with the rsocket.  The JDK catches this error
in a negative test case.  It reads the EINVAL error code from the
socket, when it expects ECONNREFUSED.
Update the code so that we only save the error with the socket if
it came from a connection error.  In other cases, simply set errno
and return a failure.  We add explicit state checks for the other
non-connected rsocket cases.
Signed-off-by: Sean Hefty <sean.hefty@intel.com>

rsockets: Do not overwrite connection failure error code

---

providers/mlx5/mlx5.c

Update PCI ID table to support Mellanox ConnectX-6 LX cards.
Signed-off-by: Moshe Tal <moshet@mellanox.com>
Reviewed-by: Feras Daoud <ferasda@mellanox.com>

mlx5: Add Mellanox ConnectX-6 LX PCI ID

---

providers/hns/hns_roce_u_hw_v2.c

When a firmware reset occurred because of some errors, modify qp to error
in post_send() will be failed. The bad_wr will be returned to the user,
then the user won't wait for the corresponding wc. But as sq db has been
updated, the driver will return a software wc to the user, which may cause
unexpected behaviours.
Because the result of modifying qp is meaningless in this scenario, codes
to handle the return value are removed.

libhns: Not process return value of flushing cqe

---

infiniband-diags/ibstat.c

Compare CA device names by using the maximum length between them in order to
avoid matches of sub strings between CA device names that can match the
wrong device.
Example before the fix:
Input CA name: abc_11
List CA names: abc_1, def_1
When running : ibstat abc_11, the output will be the details of abc_1 even
though abc_11 does not exist.
After the fix, the output of this case will be:
'abc_11' IB device can't be found
Signed-off-by: Haim Boozaglo <haimbo@mellanox.com>

ibdiag: Compare CA device names by using the maximum length between them

---

providers/efa/verbs.c

The TX Low Latency Queue (LLQ) is stored on the device's BAR, hence
mmio_flush_writes should be used instead of udma_to_device_barrier
before ringing the doorbell.
Fixes: f7f275ff2b1a ("efa: Elastic Fabric Adapter (EFA) userspace RDMA provider")
Fixes: f189a2ac12d6 ("efa: Support send using extended QP API")

efa: Use the correct barrier between BAR writes on post send flow

---

providers/efa/efa.h

The preferred mechanism to declare variable-length types is using a
flexible array member.
By using a flexible array we'll get a compiler warning in case the
flexible array does not occur last in the struct.

efa: Replace zero-length array with flexible-array member

---

providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_wr_post.3.md

Improve UMR man page by setting an explicit link between the general builder man page (i.e. mlx5dv_wr_post.3) to its verbs.
Also add some note regarding its mkey usage.

mlx5: Improve UMR man page

---

pyverbs/cmid.pyx
tests/base.py
tests/rdmacm_utils.py
tests/test_rdmacm.py

This series adds missing infrastructure to enable external QP usage with rdmacm.
It includes a simple rdmacm asynchronous traffic test that uses an external created QP.

pyverbs: Support external QP usage with rdmacm 

---

providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c

Prevent uninitialized fields when new fields are added, and make code look simpler.
P.S. There is a patch with the same purpose in kernel, but there is no relationship between them.

libhns: Initialize all fields of doorbells to zero

---

libibverbs/man/ibv_create_cq_ex.3
libibverbs/verbs.h
providers/mlx5/cq.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c
pyverbs/cq.pxd
pyverbs/cq.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/pd.pxd
pyverbs/pd.pyx
tests/test_parent_domain.py

The parent domain object enables some functionality for a given verb object once it's attached to.
This series extends CQ creation to get a parent domain object to enable using its functionality.
This new option is used by mlx5 driver to allow custom memory allocation for a CQ.

verbs: Enable CQ creation with a parent domain

---

buildlib/cbuild

For some reason the apt-get update command fails with the following
error message:
W: http://apt.llvm.org/bionic/dists/llvm-toolchain-bionic-8/InRelease: No system certificates available. Try installing ca-certificates.
W: http://apt.llvm.org/bionic/dists/llvm-toolchain-bionic-8/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'http://apt.llvm.org/bionic llvm-toolchain-bionic-8 Release' does not have a Release file.
Which fails the entire build.
However, everything else works correctly if continuing instead of
exiting because of the &&.

azp: Fix azp image build

---

providers/hns/hns_roce_u_hw_v2.c

It is meaningless to lock sq & rq before checking state of qp, so move
them to a more reasonable location.

libhns: Move lock of sq & rq to the reasonable location

---

pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
tests/base.py

Avoid RoCEv2 GIDs on unsupported devices.
To be able to do that, ibv_query_gid_type was added to Pyverbs' infrastructure.

tests: Avoid RoCEv2 GIDs on unsupported devices

---

providers/mlx5/mlx5.c
providers/mlx5/verbs.c

This series includes two patches as follows:
The first one enables devx by default in case supported by the underlay mlx5 device. 
The second one fixes a memory leak in some bad flow of CQ creation.

mlx5: Misc items

---

ibacm/src/acm.c

end-point addresses in acm are represented by an array of acmc_addr
structures. This array is reallocated each time a new address is
added to the endpoint. The acmc_addr structure, itself,  contains
an acm_address structure:
struct acm_address {
struct acm_endpoint     *endpoint;
union acm_ep_info       info;
char                    *id_string;
uint16_t                type;
};
struct acmc_addr {
struct acm_address    addr;
void                  *prov_addr_context;
char                  string_buf[ACM_MAX_ADDRESS];
};
The id_string field in the acm_address structure points back to the
string_buf field in the acmc_addr structure.
After a realloc() of the array of acmc_addr structures, the id_string
pointers for each acm_address should be reset to point at the
reallocated string_buf field in …

ibacm: Fix id_string pointers after end-point address re-allocation

---

libibverbs/dummy_ops.c
libibverbs/man/ibv_query_device_ex.3
libibverbs/verbs.h

Following thread on broken compatibility between v28 and older version:
https://www.spinics.net/lists/linux-rdma/msg89386.html
Implement query_device_ex dummy function for all providers.
Returning EOPNOTSUPP broke compatibility with apps compiled against
older rdma-core
Suggested-by: Jason Gunthorpe <jgg@mellanox.com>
Cc: stable@linux-rdma.org # v28
Fixes: commit c28410765bdf ("libibverbs: Fix incorrect return code")
Signed-off-by: Michal Kalderon <michal.kalderon@marvell.com>

libibverbs: Fix query_device_ex dummy function not to return EOPNOTSUPP

---

libibverbs/man/ibv_create_flow.3
libibverbs/verbs.h
providers/mlx5/verbs.c
pyverbs/libibverbs_enums.pxd

This series includes two patches in verbs and mlx5 as follows.
The first one deprecated a non-used bit in the steering area from verbs, this bit is not in use at all not in kernel and not in userspace.
The second one introduces some verbs helper function to set flow_label and RoCEv2 UDP source port for datagram QP, this routine in used in mlx5 driver.

verbs: Misc items

---

ibacm/src/acm.c

acm_open_providers() reads filenames and checks to see if the filenames
contain the .so (shared object) extension via strstr(). But this does
not verify that the extension is found at the end of the filename - only
that .so is a substring somewhere in the filename. This means filenames
of the sort "libibacmp.so.org" will be matched and loaded as providers.
The check should be modified to verify that the extension is at the end
of the filename.
Signed-off-by: Mark Haywood <mark.haywood@oracle.com>

ibacm: check provider file ends with .so extension

---

infiniband-diags/ibdiag_common.c

Use local port subnet prefix when constructing PathRecord request
while resolving destination.
Signed-off-by: Haim Boozaglo <haimbo@mellanox.com>

ibdiag: Set the right subnet prefix when using the -G option

---

providers/mlx5/man/mlx5dv_create_mkey.3.md

Scatter to CQE shouldn't be used while receive buffer SGE points to an indirect MKEY, add a man page note for.

mlx5: Add a man page note regarding DV indirect MKEY

---

Documentation/testing.md

The shell commands to execute the tests were formatted incorrectly, add
the missing ```.

Documentation: Fix formatting of shell commands

---

providers/mlx5/CMakeLists.txt
providers/mlx5/dr_buddy.c
providers/mlx5/dr_icm_pool.c
providers/mlx5/mlx5dv_dr.h

This series includes few memory improvements in the DR area as follows.
The first patch changes to allocate an accurate aligned DM memory size instead of wasting some memory by allocating double size as was done before.
The next two patches introduce and use a buddy system memory allocation algorithm, this enables a flexible way to manage the ICM memory which reduces the memory consumption comparing the bucket management that was used before.

mlx5: Memory improvements in the DR area 

---

debian/control
ibacm/man/ibacm.8

The man page of ibacm was moved from section 1 to section 8, but the man page itself still claimed to be in section 1.
Also Bump Standards-Version of the Debian package to 4.5.0.

ibacm: Fix move of man page from section 1 to section 8

---

tests/CMakeLists.txt
tests/args_parser.py
tests/base.py
tests/run_tests.py
tests/test_device.py

Add support for passing the device name command-line arguments to the test cases, This is needed to give the users the ability to run the tests on a specific device on systems with multiple devices.

Add support for passing device name as command-line argument

---

redhat/rdma-core.spec

https://fedoraproject.org//wiki/Changes/UnversionedDocdirs
By having the documentation directories unversioned, they and
the files in them become inherently easier/stabler to bookmark,
cross-reference from other docs, Systemd unit Documentation= etc.

redhat: unversioned documentation directory

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Calculating process of WQE buffer is not clear enough to understand, so
optimize the code to improve the readability.
Changelog:
v3:
- Use align() directly instead of defining a new macro hr_hw_page_align().
v2:
- Remove meaningless judgment of count in #1 as Leon suggests.
- Rewrite commit message of both patch.

libhns: Optimize buffer calculating process

---

buildlib/azure-pipelines-release.yml
buildlib/azure-pipelines.yml
buildlib/cbuild
buildlib/check-build
buildlib/gen-sparse.py
buildlib/pyverbs_functions.cmake
buildlib/sparse-include/31/bits-sysmacros.h.diff
buildlib/sparse-include/31/netinet-in.h.diff
buildlib/sparse-include/31/stdlib.h.diff
buildlib/sparse-include/31/sys-socket.h.diff
ibacm/prov/acmp/src/acmp.c
ibacm/src/acm.c
ibacm/src/libacm.c
librdmacm/acm.h

Various churn in Ubuntu and clang land broke building the azp image, fix it up, and update clang, gcc and base OSs.
Fedora should be updated too, but it is currently broken.

Fixup AZP compilations and update to newer everything

---

tests/test_rdmacm.py

Getting the device name is already handled by the RDMATestCase, so
remove it.

tests: Delete code duplication from CMTestCase

---

providers/hns/hns_roce_u_hw_v2.c

There are some codes need to be simplified or optimized on the processing path of post_send/recv and poll_cq.

libhns: Cleanups for post and poll

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_domain.c
providers/mlx5/dr_icm_pool.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series improves the memory usage in the DR area by enabling an option to reclaim device memory which is not in use.
In addition, the hot memory calculations to consider whether sync call is required was refactored to prevent redundant checks and improve performance.

mlx5: Improve memory usage in the DR area

---

debian/libibverbs1.symbols
kernel-headers/rdma/rdma_user_cm.h
libibverbs/CMakeLists.txt
libibverbs/device.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_get_device_guid.3.md
libibverbs/man/ibv_get_device_index.3.md
libibverbs/man/ibv_get_device_list.3.md
libibverbs/verbs.h
librdmacm/cma.c
librdmacm/rdma_cma_abi.h

In current implementation of RDMA-CM, if IB device resets itself, the
application and librdmacm can't recognise that the device is different,
because device identification is done based on node_guid. That node_guid
is the same before and after reset, but the device is different from the
kernel perspective.
This disconnect between kernel and rdma-cm is the reason why users need
to actually restart applications.
In the following patches, we will connect kernel and rdma-cm differently.
his will allow them to be in-sync. Once device "disappears" from the kernel,
it will be removed from librdmacm too. The "addition" of new device, will
reflect in addition in librdmacm too.

RDMA-CM disassociate support

---

kernel-headers/rdma/mlx5_user_ioctl_cmds.h
providers/mlx5/man/mlx5dv_create_flow.3.md
providers/mlx5/mlx5dv.h
providers/mlx5/verbs.c

Add support for steering default miss.
When packet matched the default miss rule then it's steered to the default miss of the verbs steering domain.

mlx5: Add support for steering default miss

---

libibverbs/examples/devinfo.c

Fix displaying "max_tso" and "supported_qp" by adding extra tab.
Fixes: 4e03cc1693c3 ("Add support for TCP segmentation offload (TSO)")

libibverbs: Fix display tso_caps section

---

providers/mlx5/dr_dbg.c

This series improves the DR dump information by including some extra data and by dropping some redundant commas from some records.

mlx5: Improve the DR dump information

---

libibverbs/man/ibv_create_wq.3

It seems "verbs_exp.h" is OFED only, so replace it with "verbs.h".

libibverbs/man/ibv_create_wq.3 replace verbs_exp.h with verbs.h

---

pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/providers/mlx5/mlx5dv.pxd
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/qp.pxd
pyverbs/qp.pyx

This series includes the following fixes and improvements:
- Add Memory Windows (MWs) weakrefs to QPEx so they would be automatically closed upon closing the relevant QPs.
- Remove add_ref from Mlx5Context, so it can be used by non-mlx5-only objects

pyverbs: Fixes and improvements

---

libibverbs/device.c

The assignment of ABI_placeholder1 and ABI_placeholder2 must be
after the provider populated context_ex->ibv_create_flow and
context_ex->ibv_destroy_flow.
Applications, which compiled against old libibverbs released between
commit 501b53b30752 and 1111cf9895bb, will fail if they are linked
with libibverbs released after 1111cf9895bb and call ibv_create_flow.
[1] 501b53b30752 ("Fix create/destroy flow API")
Fixes: 1111cf9895bb ("verbs: Always allocate a verbs_context")

libibverbs: Fix ABI_placeholder1 and ABI_placeholder2 assignment

---

tests/test_addr.py
tests/test_cq_events.py
tests/test_device.py
tests/test_mr.py
tests/test_qp.py
tests/test_qpex.py
tests/test_relaxed_ordering.py

Misc fixes to make pyverbs tests skip on unsupported operations.

Misc pyverbs tests fixes

---

providers/efa/verbs.c

EFA device only supports UD QP, therefore in case QP type is not UD
an errno of EOPNUTSUPP should be returned.
Signed-off-by: Chen Brasch <cbrasch@amazon.com>

efa: Update correct errno return on create extended QP function

---

providers/efa/efa.h
providers/efa/verbs.c

Keep the provider specific attributes in EFA context instead of device.
This allows for faster access as the context is frequently accessed
(opposed to the device), consistent struct to store all device
attributes, and better fits the design of the provider.

EFA ucontext attributes

---

providers/mlx5/qp.c

Fix potential arithmetic overflow that was reported by Coverity.

mlx5: Fix potential arithmetic overflow

---

libibverbs/cmd_cq.c
libibverbs/driver.h
providers/mlx4/cq.c
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/verbs.c
providers/mlx5/cq.c
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

Extended QP implementation has a nice verbs_qp abstraction which does
not exist for extended CQs, this patch modifies CQ to be similar.
The verbs_cq struct is a union of both CQ and extended CQ, which allows
access for both. In addition, converting a CQ to the provider's CQ can
now be done using container_of, without explicit casts.

verbs: Introduce verbs_cq for extended CQ operations

---

redhat/rdma-core.spec

The cited commit enabled pyverbs build by default for Fedora 32 and up.
However, it broke enalbing pyverbs build when passing '--with pyverbs' flag.
Fix the condition so that now the behavior for Fedora 32 and up will be:
* Default: pyverbs enabled.
* --with pyverbs: pyverbs enabled.
* --without pyverbs: pyverbs disabled.
Fixes: 07b304b75186 ("redhat: Build pyverbs for Fedora greater than release 31")
Signed-off-by: Alaa Hleihel <alaa@mellanox.com>
Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
Tested-by: Edward Srouji <edwards@mellanox.com>
CC: Honggang Li <honli@redhat.com>
Acked-by: Honggang Li <honli@redhat.com>

redhat: Fix the condition for pyverbs enablement on Fedora 32 and up

---

pyverbs/cq.pyx
pyverbs/libibverbs_enums.pxd
tests/base.py
tests/test_device.py
tests/test_mr.py
tests/test_qp.py

Another set of pyverbs fixes which allow tests of unsupported devices to skip.

Misc pyverbs tests fixes round 2

---

providers/mlx5/cq.c

Fix compilation errors when compiling with MLX5_DEBUG.
The break occurred when the 'verbs_cq' patch was introduced, however it didn't replace the code under the MLX5_DEBUG mode to match its change.

mlx5: Fix compilation errors when compiling with MLX5_DEBUG

---

providers/mlx5/dr_devx.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv_dr.h

This series enables SW Steering RX/TX domains when force-loopback is supported while RoCE is enabled.
When using loopback QP the gid index is not required and the code is safe from any gid change scenario, this enables opening the RX/TX domains paths.

mlx5:  Enable SW Steering RX/TX domains

---

tests/utils.py

The shared PD test triggers a flow that tries to create an MR through
QpExRCRDMAWrite class with access flags that might not be supported on
some devices, skip the test in that case.

tests: Skip tests with unsupported MR access flags

---

pyverbs/mr.pyx
tests/base.py
tests/test_odp.py
tests/utils.py

This series introduces new tests for ODP, in addition to infrastructure extensions and a refactoring of the ODP tests, which allows more flexibility for adding new tests in the future.
This includes:
- Support for registering an implicit ODP MR (with a test)
- An ODP test with UD traffic

pyverbs: ODP refactoring and extensions 

---

pyverbs/mem_alloc.pyx

Initialize the allocated memory with zeros in posix_memalign pyverbs
wrapper. Otherwise, the parent domain allocators that were using
posix_memalign were not fulfilling the requirement of the parent
domain callbacks (allocated buffers must be initialized with zeros).

pyverbs: Memset the memory after posix_memalign

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h
providers/mlx5/verbs.c

This series adds an action to enable creating rules that steer packets to a DEVX TIR object.

mlx5: Add DEVX TIR support in the DR area

---

CMakeLists.txt

Handles case where nl-route-3 and nl-3 libs are not installed in
a standard location.  pkg_check_modules() puts the location it
got from pkgconfig in the NL_LIBRARY_DIRS variable.
For example, I have a test copy of nl-route-3 and nl-3 in /tmp/test/lib.  There is no other version of these libs installed on my system.   I can configure rdma-core with:
<pre>
cmake -DCMAKE_PREFIX_PATH=/tmp/test -DCMAKE_INSTALL_PATH=/tmp/test -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=YES ../rdma-core
</pre>
Without the fix, the compile will fail with:
<pre>
[  7%] Linking C executable ../bin/rdma_rename
/usr/bin/ld: cannot find -lnl-route-3
/usr/bin/ld: cannot find -lnl-3
collect2: error: ld returned 1 exit status
</pre>
because the "-L" linking information returned by pkg_check_modules() in ${NL_LIBRARY_DIRS}  is …

add ${NL_LIBRARY_DIRS} to link_directories()

---

providers/mlx5/dr_devx.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c
providers/mlx5/mlx5dv_dr.h

This series introduces few improvements in the DR area as of removing unneeded checks, renaming to better general names, refactor in some places, etc.

mlx5: Few improvements in the DR area

---

kernel-headers/update

Commit messages usually end with a dot, do that in the script as well.

Add a dot to kernel headers update script commit message

---

providers/mlx5/verbs.c

The index of the uuar inside the UAR need to be considered when working with the legacy dynamic UAR mode.
Without that on P9 where there are more than two uuars the third one won't be set correctly.

mlx5: Fix an issue on P9 with legacy UAR

---

pyverbs/cmid.pxd
pyverbs/cmid.pyx
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/librdmacm.pxd
pyverbs/mr.pxd
pyverbs/mr.pyx
tests/base_rdmacm.py
tests/rdmacm_utils.py
tests/test_rdmacm.py

The series adds:
- Support for rdma_get_devices and ibv_get_device_index.
- rdmacm remote read/write APIs which allow reading/writing using internal QPs and registering memory buffers using the rdmacm APIs.
- rdmacm remote traffic tests.

pyverbs: Extend rdmacm support in Pyverbs

---

Documentation/pyverbs.md
pyverbs/libibverbs.pxd
pyverbs/mr.pxd
pyverbs/mr.pyx
pyverbs/qp.pyx
pyverbs/wr.pyx
tests/test_mr.py
tests/test_qpex.py
tests/test_shared_pd.py
tests/utils.py

Until now, Pyverbs partially supported MWs (Memory Windows).
Bind and usage of MWs were partially supported, only for the new post send APIs.
This series extends the support of MWs by adding the ability to bind both MW types and adding
new tests that include bad flows (invalidating the MW in different ways and trying to access its memory).

pyverbs: Extend memory window support

---

tests/test_mlx5_lag_affinity.py
tests/test_qp.py

Avoid test failure by skip the test if create Raw Packet QP is not
supported.

tests: Skip test if create Raw Packet QP is not supported

---

CMakeLists.txt

allow install to complete even if no prebuilt man pages are available
If pandoc and rst2man are available, they are used to create man
page sources.  If not, then the build looks for prebuilt man pages
in ${CMAKE_SOURCE_DIR}/buildlib/pandoc-prebuilt.   If that directory
is not present (e.g. because you are compiling from a fresh checkout
of master from github), then rdma-core will compile fine but the
"make install" operation will fail.
This patch adds a new cmake cache variable NO_MAN_PAGES (default=0).
If set, it disables man page processing and allows "make install" to
succeed (without man pages) when neither pandoc/rst2man nor pandoc-prebuilt
are present.

allow install to complete even if no prebuilt man pages are available

---

libibverbs/cmd_qp.c

Fix a comment typo 'optinal' -> 'optional'.

verbs: Fix typo 'optinal' -> 'optional'

---

tests/test_device.py

Removed a test case which requires vendor_part_id to be non zero.
Per IBTA A3.3.1 VENDOR INFORMATION it is not required that the
vendor part ID field be set to a non-zero value:
The following components are vendor specific: VendorID, DeviceID, De-
vice Version, Subsystem VendorID, SubsystemID, ID String.
The vendor places its IEEE assigned Organization Unique Identifier
(OUI) in the VendorId field and *MAY PLACE ANY VALUE IN THE DEVICEID* and
Device Version fields. The vendor may also provide an ASCII string of its
choice in the ID String field.
The Subsystem VendorID and SubsystemID provide additional informa-
tion when a subsystem vendor uses components provided by other ven-
dors. In this case the subsystem vendor provides its OUI in the Subsystem
VendorID field and may specify any …

tests: Allow zero vendor_part_id

---

kernel-headers/rdma/efa-abi.h
providers/efa/efa.h
providers/efa/efadv.h
providers/efa/man/efadv_query_device.3.md
providers/efa/verbs.c
pyverbs/providers/efa/efadv.pyx
pyverbs/providers/efa/efadv_enums.pxd

This series adds support for RNR retry counter on SRD QPs through the modify QP verb.
Kernel submission:
https://lore.kernel.org/linux-rdma/20200731060420.17053-1-galpress@amazon.com/

EFA RNR retry

---

libibverbs/verbs.h

It is supposed to return an errno value, but was returning -EOPNOTSUPP
(note the negative).

Fix return value of ibv_destroy_flow when not supported

---

libibverbs/ibdev_nl.c
libibverbs/ibverbs.h
libibverbs/init.c

We need to check that the device could be accessed before it is added to the device list.
Currently, it's done only in the sysfs fallback, do it in the netlink flow as well.

verbs: Try access the device before adding it to the device list

---

kernel-boot/rdma-hw-modules.rules

Usually the initramfs is built with the device driver modules which are
the mlx4_core and mlx5_core for Mellanox HW. The mlx4_ib and mlx5_ib are
usually not packed inside the initramfs.
Hence, when an InfiniBand only card is installed on a system, the current
udev rules will not work and the needed RDMA driver is not loaded, that is
because we do not have an ethernet netdev, so we don't have an interface
that can match on the ID_NET_DRIVER check, that can work only when we have
a device that loads an ethernet netdev by default.
Note that both of mlx4 and mlx5 drivers call request_module_nowait() to
load their corresponding RDMA module, but that cannot work if only the
core module exists inside the initramfs.
Fix this by looking at the pci subsystem events and load the needed RDMA
module …

kernel-boot: Load mlx5_ib and mlx4_ib also for InfiniBand only cards

---

Documentation/testing.md
tests/base.py

As parametrize isn't used - remove it.

tests: Remove parametrize

---

tests/test_qp.py

As not all providers support all QP types, split the tests to be based
on the QP type, this is needed to make sure that all QP types that are
supported by a specific provider are tested.

tests: Split QP tests based on QP types

---

pyverbs/device.pyx
pyverbs/libibverbs.pxd
tests/test_device.py

Add test for testing ibv_query_pkey() to test_device.py.

tests: Add test for ibv_query_pkey

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c

According to the IB Specifications, the verbs should return an immediate error when the users set an unsupported opcode. Furthermore, refactor codes about opcode in process of set_rc_wqe() to make the differences between opcodes clearer.

libhns: Refactor process about opcode in set_rc_wqe()

---

pyverbs/qp.pxd
pyverbs/qp.pyx
pyverbs/srq.pxd
pyverbs/srq.pyx
tests/base.py
tests/test_cq_events.py
tests/test_cqex.py
tests/test_mr.py
tests/test_odp.py
tests/test_qpex.py
tests/test_relaxed_ordering.py
tests/test_shared_pd.py
tests/utils.py

This series supports the creation and usage of multiple QPs with SRQ in the rdma-core tests.
Up until now, each basic traffic resource (that inherits from the TrafficResources class) was able to create one QP. With this extension, it would be able to choose the number of QPs to be created and used for traffic.
In addition, a SRQ test that uses multiple QPs was added to the ODP test cases.

tests: Extend SRQ and QP support

---

pyverbs/qp.pyx

Add properties to the ECE's attributes in order to access them from a Python code.

pyverbs: Add access to ECE's attributes

---

libibverbs/dummy_ops.c
libibverbs/examples/devinfo.c

All of structrue ibv_device_attr_ex should be set to zero if a provider don't support query_device_ex(), or the fields which are not included in attr->orig_attr will get a random value.
Fixes: 58ccb638b540 ("libibverbs: Fix query_device_ex dummy function not to return EOPNOTSUPP")

verbs: Set attributes to zero if query_device_ex() is not supported

---

tests/test_device.py

As max_pkeys attr is not required by all providers, verify it only when
the node type is CA.

tests: Verify max_pkeys only for CA

---

providers/mlx5/dr_devx.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_icm_pool.c
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series enhances the device memory usage by increasing ICM action memory allocation size up-to 8MB based on capabilities.
In addition, it enables on demand sync to free the cached memory for both STE and actions.

mlx5: DR, enhance the device memory usage

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_table.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5.h
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h
providers/mlx5/verbs.c

This series adds support for flow sampler action, this action is used for sampling some ratio of the packets
without disrupting the traffic.
When a packet enters the sampler object it will be duplicated and sent to the sampling flow table as well as the default flow table. On the sampler table we can execute other actions on the sampled packet.

mlx5: DR, Add support for flow sampler action

---

libibverbs/memory.c

If the interval passed to madvise() covers both mapped and unmapped address ranges error will be returned but mapped address ranges still will be processed.
Remove the VM_DONTCOPY flag if MADV_DOFORK has failed by iterating the suspicious region page-by-page.

verbs: Make sure VM_DONTCOPY removed

---

providers/mlx5/CMakeLists.txt
providers/mlx5/dr_dbg.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c
providers/mlx5/dr_ste.h
providers/mlx5/dr_ste_v1.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv_dr.h

This series adds DR support for ConnectX6DX.
Since the STE and actions formats are different on this new HW we implemented the HW specific STEv1 layer to
support all the functionalities as previous devices.

mlx5: Add DR support for ConnectX6DX

---

tests/test_rdmacm.py
tests/utils.py

Avoid test failure by skipping the test if multicast is not supported.

tests: Skip test if multicast is not supported

---

pyverbs/providers/efa/efadv.pxd
pyverbs/providers/efa/efadv.pyx
pyverbs/providers/efa/efadv_enums.pxd
pyverbs/providers/efa/libefa.pxd
tests/base.py
tests/test_addr.py
tests/test_efadv.py
tests/test_qp.py
tests/utils.py

This series contains a small fix to skip SRQ tests on unsupported devices and adds more efadv functionality to the testing infra.

More efadv pyverbs tests

---

srp_daemon/srp_daemon.c

There is no need to create a world-writable lock file.
It's enough to have an RW permission for the file owner only.
Fixes: ee138ce1e40d ("Cause srp_daemon launch to fail if another srp_daemon is already working on the same HCA port.")
Signed-off-by: Sergey Gorenko <sergeygo@nvidia.com>
Reviewed-by: Max Gurtovoy <mgurtovoy@nvidia.com>
Reviewed-by: Bart Van Assche <bvanassche@acm.org>

srp_daemon: Avoid extra permissions for the lock file

---

providers/hns/hns_roce_u_hw_v2.c

For SEND_WITH_INV operation, the field named inv_key in rc_sq_wqe should be
filled instead of the strong order flag.
Fixes: 42ae41c628f1 ("libhns: Refactor process about opcode in set_rc_wqe()")

libhns: Fix wrong assignment of send with invalid operation

---

tests/test_odp.py
tests/utils.py

This mini-series contains two commits that extend the ODP tests with implicit and explicit ODP MRs and more advice options.

 tests: Add more ODP tests

---

libibverbs/cmd.c
libibverbs/driver.h
libibverbs/verbs.c

ODP is immune to the COW problem because it directly tracks the page tables.
As such prevents dontfork on ODP MR which might fail in case by the registration time there is still no physical memory mapping.

verbs: Prevent dontfork on ODP MR

---

providers/mlx5/mlx5.h
providers/mlx5/verbs.c

Add fork support for DEVX umem by adding the required ibv_dofork_range() / ibv_dontfork_range() calls.
This is done in a similar way as of MR registration and deregistration.

mlx5: Add fork support for DEVX umem

---

tests/test_device.py

Some devices report zero max_sge_rd,
change query device test to check for '>=' instead of '>'.
Signed-off-by: Chen Brasch <cbrasch@amazon.com>

tests: Change max_sge_rd verification

---

debian/ibverbs-providers.symbols
providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/dr_devx.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series introduce an action which replicates a packet to multiple destinations, each destination can have an attached reformat action which will be applied to the packet before steered to this destination.

mlx5: DR, Introduce an action which replicates a packet to multiple destinations

---

providers/siw/siw.c

libibverbs is taking care of return the right error code when the
provider callbacks aren't supported.

siw: Remove pointless callbacks

---

debian/libibverbs1.symbols
kernel-headers/rdma/ib_user_ioctl_cmds.h
kernel-headers/rdma/ib_user_ioctl_verbs.h
libibverbs/CMakeLists.txt
libibverbs/cmd_device.c
libibverbs/driver.h
libibverbs/examples/devinfo.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_query_gid_ex.3.md
libibverbs/man/ibv_query_gid_table.3.md
libibverbs/verbs.c
libibverbs/verbs.h
providers/mlx5/verbs.c
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
tests/base.py
tests/test_device.py

When an application is not using RDMA CM and if it is using multiple RDMA devices with one or more RoCE ports, finding the right GID table entry is a long process.
For example, with two RoCE dual-port devices in a system, when IP failover is used between two RoCE ports, searching a suitable GID entry for a given source IP, matching netdevice of given RoCEv1/v2 type requires iterating over all 4 ports * 256 entry GID table.
Even though the best first match GID table for given criteria is used, when the matching entry is on the 4th port, it requires reading 3 ports * 256 entries * 3 files (GID, netdev, type) = 2304 files.
The GID table needs to be referred on every QP creation during IP failover on other netdevice of an RDMA device.
We introduce this series of patches, which introduces an …

verbs: Query GID table API

---

tests/__init__.py
tests/args_parser.py

Add a --dry_run command-line argument that prints a list of the full
test names that are loaded by default and exit without running them.

tests: Add a dry run option

---

providers/qedr/qelr_main.c

No changes are required for rdma-core either to support the
newly added device ids.
Signed-off-by: Michal Kalderon <michal.kalderon@marvell.com>

libqedr: Add additional device ids supported by this lib

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

HIP08 supports RC inline up to size of 32 Bytes, and all data should be
put into SQWQE. For HIP09, this capability is extended to 1024 Bytes, if
length of data is longer than 32 Bytes, they will be filled into extended
sge space.

libhns: Support inline data in extented sge space for RC

---

pyverbs/providers/mlx5/libmlx5.pxd
pyverbs/providers/mlx5/mlx5dv.pxd
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/qp.pyx
tests/CMakeLists.txt
tests/base.py
tests/mlx5_base.py
tests/test_mlx5_dc.py
tests/utils.py

This series adds support to mlx5 DC QPs traffic usage.
In addition, two new DC traffic tests were added (Send and RDMA Write).

pyverbs: Add mlx5 DC support

---

tests/test_device.py

Avoid the following failure over devices with multiple ports (like mlx4)
by calculating the max_entries for both ports.
$ ./build/bin/run_tests.py -v test_device -k test_query_gid_table
test_query_gid_table (tests.test_device.DeviceTest)
Test ibv_query_gid_table() ... ERROR
ERROR: test_query_gid_table (tests.test_device.DeviceTest)
Test ibv_query_gid_table()
File "/home/rdma-core/tests/test_device.py", line 99, in test_query_gid_table
raise ex
File "/home/rdma-core/tests/test_device.py", line 94, in test_query_gid_table
ctx.query_gid_table(max_entries)
File "device.pyx", line 261, in …

tests: Fix calculate gid max_entries

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

The new version of RoCEE supports using CQE in size of 32B or 64B. The performance of bus can be improved by using larger size of CQE. 
The kernel parts ("RDMA/hns: Add support for CQE in size of 64 Bytes") has been merged and the ABI related changes has been synchronized by ad9987ed8e6f ("Update kernel headers").

libhns: Add support for CQE in size of 64 Bytes

---

tests/test_device.py

ibv_query_gid_table() returns the number of entries that were read on
success or negative errno value on error - fix the check when the
query_gid_table() is not supported by the providers.
Fixes: bbbdd13fe356 ("tests: Add tests for ibv_query_gid_table and ibv_query_gid_ex")
Reported-by: Edward Srouji <edwards@nvidia.com>

tests: Fix check for providers that do not support query_gid_table

---

libibverbs/cmd_device.c

The gid type is IB by default, remove the error code return.

verbs: Set default gid type for unspecified link layer

---

Documentation/udev.md
buildlib/azure-pipelines.yml
debian/control
libibverbs/driver.h
libibverbs/man/ibv_query_gid_table.3.md
librdmacm/examples/rping.c
librdmacm/man/rdma_init_qp_attr.3.md
tests/base_rdmacm.py
tests/rdmacm_utils.py

The patch only makes grammar-related fixes. It fixes misspelled abbreviations for Remote Direct Memory Access and incorrect use of the article "a" with "RDMA".
The changes include:
* Changed "a RDMA" to "an RDMA"
* Changed "RMDA" to "RDMA".

Grammar-related fixes

---

libibverbs/man/ibv_modify_qp.3
libibverbs/man/ibv_query_qp.3

The sq_psn field is valid for all QP types, not just RC/UC.

verbs: Remove incorrect comment on SQ PSN from documentation

---

providers/mlx5/dr_devx.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv_dr.h

This series improves rule insertion rate by using an isolated VL on the send QP.
This can be achieved only if force loop-back is supported and isolate_vl_tc cap is enabled.

mlx5: DR, Improve rule insertion rate

---

providers/mlx5/dr_dbg.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c
providers/mlx5/dr_table.c
providers/mlx5/mlx5dv_dr.h

This series improves the internal DR locking to enable parallel rule insertions in FDB mode.
In addition, it improves the rule tracking which dramatically reduces its memory consumption.

mlx5: DR, Improve locking and memory usage

---

providers/mlx5/dr_domain.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv_dr.h
providers/mlx5/verbs.c

This series fixes the DR send flow to use NC UAR with its matching locking as currently the DB mode is in use.
In addition, as there is no real need for dedicated NC UARs, the driver code was refactored to use a singleton one.

mlx5: NC UAR improvements

---

redhat/rdma-core.spec

We have issue to build rpm from upstream rdma-core repo with Fedora 32+ .
This PR backport some commits from Fedora repo to address such issue.

backport some spec file commits from Fedora repo

---

libibmad/rpc.c

As the static variable 'ibdebug' is hard-coded, libibmad users have
to change the initialization value of 'ibdebug' and recompile liblimad.

libibmad: allow set debug level via environment variable

---

debian/ibverbs-providers.symbols
providers/mlx5/CMakeLists.txt
providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_ste_v0.c
providers/mlx5/dr_ste_v1.c
providers/mlx5/libmlx5.map
providers/mlx5/man/CMakeLists.txt
providers/mlx5/man/mlx5dv_dr_flow.3.md
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h
providers/mlx5/mlx5dv_dr.h

This series adds support for push / pop VLAN actions, this will allow HW offloading of those actions.

mlx5: DR, Add support for push / pop VLAN actions

---

providers/hns/hns_roce_u.c

The 200G device has a new device ID 0xA228, add it to the PCI table.

libhns: Add new PCI device matching for HIP09
