libibverbs/examples/rc_pingpong.c

Fixes: d89522c4f4cb ("ccan: Add CCAN min and max functionality")

verbs: Use inttypes.h format string macros

---

Documentation/ibacm.md
MAINTAINERS
README.md
libibverbs/ibverbs.h
libibverbs/init.c
providers/hfi1verbs/hfiverbs.h
providers/i40iw/i40iw_umain.h
providers/ipathverbs/ipathverbs.h
providers/mlx4/mlx4.h
providers/mlx5/mlx5.h
providers/mthca/mthca.h
providers/nes/nes_umain.h

Someone will have to update patchworks
@rleon

Patches From list

---

.travis.yml
CMakeLists.txt
buildlib/FindLDSymVer.cmake
buildlib/RDMA_EnableCStd.cmake
ibacm/prov/acmp/src/acmp.c
libibverbs/examples/rc_pingpong.c
libibverbs/examples/srq_pingpong.c
libibverbs/examples/uc_pingpong.c
libibverbs/examples/ud_pingpong.c
providers/cxgb4/cq.c
providers/cxgb4/libcxgb4.h
providers/cxgb4/qp.c
providers/mlx4/mlx4.h
providers/mlx4/qp.c
providers/mlx5/mlx5.h
providers/mlx5/qp.c
providers/mthca/qp.c
util/CMakeLists.txt
util/compiler.h

This is the last batch of stuff to be able to build with clang 3.9 and turn it on in travis.
I need to look at the travis results from this PR, I'll add a comment when I'm happy with that and it is safe to merge.

Final clang support

---

providers/rxe/rxe_cfg

These five patches is what I came up with after having had a look at the                                                                              
rxe_cfg source code.

RXE config fixes

---

libibumad/sysfs.h

libibumad/sysfs.h: Add copyright

---

CMakeLists.txt
MAINTAINERS
README.md
providers/qedr/CMakeLists.txt
providers/qedr/common_hsi.h
providers/qedr/qelr.h
providers/qedr/qelr_abi.h
providers/qedr/qelr_chain.c
providers/qedr/qelr_chain.h
providers/qedr/qelr_hsi.h
providers/qedr/qelr_hsi_rdma.h
providers/qedr/qelr_main.c
providers/qedr/qelr_main.h
providers/qedr/qelr_verbs.c
providers/qedr/qelr_verbs.h
providers/qedr/rdma_common.h
providers/qedr/roce_common.h

This is a pull request for libqedr, the userspace library for qedr.
Thanks,
Ram

libqedr pull request

---

providers/qedr/qelr.h
providers/qedr/qelr_verbs.c

I have fixed all the issues captured by Travis CI and verified on a local RH6.8. I hope this will make the CI happy.

libqedr: fix 32-bit compilation

---

providers/qedr/qelr_main.c
providers/qedr/qelr_verbs.c
providers/qedr/qelr_verbs.h

Hi Jason/Doug,
Following your comments I have fixed several issues.
Thank you for pointing them out,
Ram

libqedr various fixes

---

README.md
buildlib/cbuild
rdma-core.spec
redhat/rdma-core.spec

This is the easiest way to test package building on the range of distros we support.
I ran through all the distro permutations and fix a few minor mistakes.

Docker based cross-distro build script

---

libibverbs/cmd.c
libibverbs/kern-abi.h
libibverbs/man/ibv_create_flow.3
libibverbs/verbs.h

This series aligns user space with latest flow steering functionally that was accepted into 4.9.

Flow steering

---

providers/qedr/qelr_verbs.c

This request contains an assortment of four bug fixes.

libqedr: multiple bug fixes

---

providers/cxgb4/dev.c
providers/cxgb4/libcxgb4.h

Signed-off-by: Steve Wise <swise@opengridcomputing.com>

libcxgb4: fixes for debug build

---

debian/control
debian/ibacm.install
debian/iwpmd.install
debian/srptools.install
rdma-core.spec
redhat/rdma-core.spec
srp_daemon/CMakeLists.txt
srp_daemon/logrotate-srp_daemon
srp_daemon/rsyslog-srp_daemon.conf

This is just a sweep of the obviously ok packaging changes, including a few patches from #50 
@jarodwilson I dropped the logrotate stuff from your specfile patch and included that missed srp permissions thing.
@relon please rebase #50 
@talatb @bdrung interested too.

Packaging Patches

---

providers/qedr/qelr_verbs.c

Remove the invocations of the macro FP_DP_VERBOSE().
They are not useful as enabling them causes a flood of prints.

libqedr: remove fast-path debug prints

---

libibverbs/cmd.c
libibverbs/driver.h
libibverbs/libibverbs.map
providers/hfi1verbs/verbs.c
providers/ipathverbs/verbs.c
providers/mlx5/mlx5-abi.h
providers/mlx5/mlx5.h
providers/mlx5/verbs.c
providers/ocrdma/ocrdma_verbs.c
providers/rxe/rxe.c

This patch set is the supplementary part of the kernel series that was lastly sent upstream.

Optimize RoCE address handle creation for userspace

---

providers/vmw_pvrdma/pvrdma_main.c

Whenever a new RDMA device appears, the RDMA stack tries to attach each
driver to the new device to see which is the correct driver. We need to
check the vendor ID and device ID to make sure we don't accidentally
attach to another device.
Reviewed-by: Aditya Sarwade <asarwade@vmware.com>
Signed-off-by: Adit Ranadive <aditr@vmware.com>

vmw_pvrdma: Check vendor and device ID on driver init

---

providers/cxgb4/t4.h
providers/hns/hns_roce_u.h
providers/i40iw/i40iw_umain.h
providers/mlx4/cq.c
providers/mlx4/mlx4-abi.h
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/verbs.c
providers/mlx5/mlx5.h
providers/nes/nes_umain.h
util/compiler.h

This series implements the libibverbs 'Completion timestamping' API
in the mlx4 provider.

Timestamp support in mlx4 provider

---

buildlib/cbuild
ibacm/prov/acmp/src/acmp.c
ibacm/src/acm.c
libibverbs/examples/asyncwatch.c
libibverbs/init.c
librdmacm/examples/riostream.c
librdmacm/examples/rstream.c
librdmacm/examples/udpong.c
providers/hns/hns_roce_u_hw_v1.c
providers/mlx4/cq.c
providers/mlx5/cq.c
providers/mlx5/verbs.c
providers/ocrdma/ocrdma_verbs.c
providers/qedr/qelr_verbs.c
util/CMakeLists.txt
util/compiler.h
util/util.h

Hopefully we can enable this on travis soon..
gcc 7 has a few new warning classes that hit interesting things.

Updates for GCC 7

---

providers/cxgb3/cq.c
providers/cxgb3/cxio_wr.h
providers/cxgb4/qp.c
providers/cxgb4/t4.h
providers/cxgb4/verbs.c
providers/hns/hns_roce_u_hw_v1.c
providers/i40iw/i40iw_osdep.h
providers/i40iw/i40iw_uk.c
providers/mlx4/cq.c
providers/mlx4/qp.c
providers/mlx4/srq.c
providers/mlx5/cq.c
providers/mlx5/mlx5.h
providers/mlx5/qp.c
providers/mlx5/srq.c
providers/mthca/cq.c
providers/mthca/doorbell.h
providers/mthca/qp.c
providers/mthca/srq.c
providers/nes/nes_uverbs.c
providers/ocrdma/ocrdma_verbs.c
providers/qedr/qelr_verbs.c
providers/vmw_pvrdma/cq.c
providers/vmw_pvrdma/qp.c
util/udma_barrier.h

I've tried to be very conservative here, but honestly, some of the drivers are a mess.
A future project would be to determine if the machine instructions we are using are they right ones.

Revise the DMA barrier macros

---

debian/control

Signed-off-by: Talat Batheesh <talatb@mellanox.com>

debian: Adding uploaders field

---

libibverbs/cmd.c
libibverbs/examples/devinfo.c
libibverbs/kern-abi.h
libibverbs/man/ibv_create_cq_ex.3
libibverbs/man/ibv_create_qp_ex.3
libibverbs/man/ibv_create_wq.3
libibverbs/man/ibv_modify_wq.3
libibverbs/man/ibv_query_device_ex.3
libibverbs/verbs.h
providers/mlx5/cq.c
providers/mlx5/verbs.c

This series is the complementary user space part of the kernel code that was merged into 4.11 around raw packet offloads.

Raw offloads

---

libibumad/man/umad_set_addr_net.3

Consistent with change in commit 8a342f390e7af71bba0d8794d741453604647e98
umad: Add missing be annotation

libibumad/man/umad_set_addr_net.3: Update function signature to be consistent with umad.h

---

libibumad/man/umad_get_ca_portguids.3
libibumad/sysfs.c
libibumad/sysfs.h
libibumad/umad.c
libibumad/umad.h
librdmacm/rsocket.c
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.h
srp_daemon/srp_ib_types.h
srp_daemon/srp_sync.c

Additionally, simplify rs_host_is_net().

Enable endianness checking for GIDs

---

libibumad/tests/umad_compile_test.c
libibumad/umad_types.h
srp_daemon/srp_daemon.c
srp_daemon/srp_daemon.h
srp_daemon/srp_handle_traps.c
srp_daemon/srp_ib_types.h

Also, some srp_daemon cleanups

Better srp_daemon/libibumad integration

---

CMakeLists.txt
providers/mlx4/cq.c
providers/ocrdma/ocrdma_abi.h
providers/ocrdma/ocrdma_verbs.c
providers/rxe/rxe.c

Have rxe, ipath, hfi1 and ocrdma enable sparse in travis
Found two more bugs.

More sparse stuff

---

buildlib/RDMA_Sparse.cmake
buildlib/cbuild
buildlib/check-build
buildlib/sparse-include/endian.h
buildlib/travis-build
libibumad/tests/umad_compile_test.c
libibverbs/man/ibv_poll_cq.3
providers/mthca/cq.c

Mostly for sparse and travis items.

Various Fixes

---

debian/control
debian/ibverbs-providers.install
debian/ibverbs-providers.lintian-overrides
debian/libibverbs-dev.install
iwpmd/iwpmd_init

Lintian fixes (that were discussed on the mailing list)

Lintian fixes

---

rdma-core.spec
redhat/rdma-core.spec

The original commit that did this was not complete.
Fixes: 9614ecdae2a ("Bump version and update debian")

Update version numbers to version 14

---

CMakeLists.txt
debian/changelog
rdma-core.spec
redhat/rdma-core.spec

Bump version to be v15

---

buildlib/rdma_functions.cmake

@vennila-21 reported that was was broken since mlx5 become a non-provider library

Fix static library support

---

debian/control
debian/copyright
debian/libibumad-dev.lintian-overrides
debian/libibumad3.lintian-overrides
debian/srptools.links

More changes for the Debian packaging. See the individual commit messages for details.

Debian packaging changes

---

.travis.yml
buildlib/travis-build
providers/bnxt_re/verbs.c
srp_daemon/srp_ib_types.h

@rleon  This has your patch and others to switch travis to newer compilers.
@bvanassche the srp patch is interesting..

Update Compilers for Travis

---

CMakeLists.txt
buildlib/fixup-include/rdma-vmw_pvrdma-abi.h
libibverbs/man/ibv_create_cq_ex.3
libibverbs/man/ibv_post_send.3
libibverbs/verbs.h
providers/mlx4/cq.c
providers/mlx4/dbrec.c
providers/mlx4/mlx4.h
providers/mlx4/mlx4dv.h
providers/mlx4/qp.c
providers/mlx4/verbs.c
providers/mlx5/cq.c
providers/mlx5/dbrec.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/qp.c
providers/mlx5/verbs.c
providers/mlx5/wqe.h
providers/mthca/cq.c
providers/mthca/memfree.c
providers/mthca/mthca.h
providers/mthca/qp.c
providers/mthca/wqe.h
providers/vmw_pvrdma/pvrdma.h
providers/vmw_pvrdma/verbs.c

This does the mellanox providers and vmw_pvrdma

More sparse work for more providers

---

debian/control
debian/rules
providers/rxe/CMakeLists.txt
providers/rxe/rxe_cfg
providers/rxe/rxe_cfg.in

Based on some light testing of the Debian packaging.
@bdrung @monis410

Fixes for rxe_cfg

---

Documentation/udev.md
debian/control
debian/rdma-core.install
ibacm/CMakeLists.txt
ibacm/ibacm.init.in
ibacm/ibacm.service.in
ibacm/ibacm.socket
iwpmd/iwpmd.service.in
kernel-boot/CMakeLists.txt
kernel-boot/rdma-hw.target.in
kernel-boot/rdma-load-modules@.service.in
kernel-boot/rdma-ulp-modules.rules
rdma-ndd/rdma-ndd.service.in
redhat/rdma-core.spec
srp_daemon/srp_daemon.service.in
srp_daemon/srp_daemon_port@.service.in

This focuses on adjusting the dependencies of the systemd unit files to create a structured system for ordering the boot up process.

Revise systemd unit files

---

debian/rules

Debian packaging fixes

---

providers/vmw_pvrdma/verbs.c

Use a libibverbs function to resolve the destination MAC address
for a non-default GID in UD QPs.
Signed-off-by: Adit Ranadive <aditr@vmware.com>

vmw_pvrdma: Add L2 MAC resolution for UD QPs

---

librdmacm/rsocket.c

Patches from @jti-lanl on the mailing list.
These should go in before the 15 release since they fix crashes a user had hit.

Fix rsockets crashes

---

buildlib/cbuild

There were tested by @nmorey 
This can probably be merged after the release.

cbuild updates to better support opensuse

---

buildlib/cbuild

Provide TRAVIS_BRANCH and TRAVIS_EVENT_TYPE to mimic the pull request.

travis: Update travis image to run latest version of checkpatch

---

ibacm/ibacm.socket
ibacm/src/acm.c
librdmacm/rsocket.c
srp_daemon/srp_daemon.c
util/CMakeLists.txt
util/util.c
util/util.h

This makes it less likely that messages from the kernel that should be handled by acm are lost during bootup due to various boot time races.
For after v15

Use systemd ListenNetlink to open the RDMA_NL_GROUP_LS ibacm socket

---

providers/vmw_pvrdma/verbs.c

Rely on the IP_BASED_GIDS flag to use the ibv_resolve_eth_l2_from_gid function when creating the AH. Otherwise, fallback to the set_mac_from_gid function to set the DMAC.

vmw_pvrdma: Explicitly check for IP_BASED_GIDS port flag

---

suse/rdma-core.spec

suse: remove requirement on dracut

---

CMakeLists.txt
Documentation/versioning.md
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be v16.

Bump version to be v16

---

libibverbs/cmd.c
libibverbs/driver.h
libibverbs/examples/devinfo.c
libibverbs/kern-abi.h
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_modify_cq.3
libibverbs/man/ibv_query_device_ex.3
libibverbs/verbs.h
providers/mlx4/mlx4.c
providers/mlx4/mlx4.h
providers/mlx4/verbs.c
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series is the supplementary part of the kernel series that was sent for 4.15 to support CQ moderation.

CQ moderation

---

debian/rules

This patch from @bdrung  fixes it, apply it right away.

Fix build breakage in travis

---

providers/mlx4/mlx4-abi.h
providers/mlx4/verbs.c

Report few extra RSS capabilities, the matching kernel part was already merged into 4.15.

mlx4: report few extra RSS capabilities

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Bump version to 15.1

---

debian/changelog
debian/control
debian/rules

This patch set contains the packaging changes from the Debian unstable 15.1-1 upload.

Debian 15.1-1 changes

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be 17.0

---

srp_daemon/srp_handle_traps.c

Master SM changes can take more than three seconds. Hence increase
the time during which to wait for a master SM to appear from 3 to 5
seconds.
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
Cc: Hal Rosenstock <hal@dev.mellanox.co.il>
Cc: Nicolas Morey-Chaisemartin <NMoreyChaisemartin@suse.de>

register_to_trap(): Specify number of iterations once 

---

srp_daemon/srp_daemon.c

srp_daemon.c: Cosmetic change to some error messages

---

libibverbs/cmd.c
libibverbs/device.c
libibverbs/driver.h
libibverbs/libibverbs.map.in
libibverbs/man/ibv_query_device.3
libibverbs/verbs.h
providers/mlx4/cq.c
providers/mlx4/mlx4.c
providers/mlx5/cq.c
providers/mlx5/mlx5.c
providers/mlx5/mlx5.h

Various minor bothers I've noticed recently.

Small cleanups for verbs

---

.travis.yml
buildlib/cbuild
buildlib/travis-build

Fix the unconditional travis failures with the latest suse tumbleweed docker images
Fix perplexing travis failures with no output from sparse.
Use clang 5.0

Fixes for cbuild and travis

---

ibacm/src/acm.c
libibumad/tests/umad_sa_mcm_rereg_test.c
librdmacm/preload.c

Various fixes spotted by cppcheck followed Ubuntu security team review:
https://bugs.launchpad.net/ubuntu/+source/rdma-core/+bug/1732892

Small bunch of cppcheck fixes 

---

CMakeLists.txt
buildlib/RDMA_EnableCStd.cmake
providers/mlx4/mlx4dv.h

All have been on the list for several days now
- Fix compiler warnings on PPC64
- Fix failure to build on Centos6
- Fix signedness trap in mlx4dv

Various minor fixes

---

ibacm/src/acm.c

Signed-off-by: Matt Ezell <ezellma@ornl.gov>

ibacm: Support FDR and EDR rates

---

providers/hns/CMakeLists.txt
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_abi.h
providers/hns/hns_roce_u_db.c
providers/hns/hns_roce_u_db.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

This patch-set updates to support rq record doorbell and cq record doorbell in the user space.

Support rq and cq record doorbell

---

MAINTAINERS

Signed-off-by: Yuval Bason <yuval.bason@cavium.com>
Signed-off-by: Michal Kalderon <michal.kalderon@cavium.com>
Signed-off-by: Ariel Elior <ariel.elior@cavium.com>

qedr: Update MAINTAINERS

---

Documentation/versioning.md

Documentation/versioning.md: Fix sentence and a typo

---

providers/mlx5/mlx5.c
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series improves mlx5 locking-control for different verbs objects and scenarios.
It was already sent and discussed over the list.

mlx5 locking-control

---

.travis.yml
buildlib/cbuild
buildlib/package-build-test

Use the clang that comes with travis instead of downloading it via apt

Fixup travis builds

---

debian/control
debian/libibverbs-dev.install
libibverbs/man/ibv_create_cq_ex.3
libibverbs/man/ibv_create_flow_action.3.md
librdmacm/cma.c
providers/hns/hns_roce_u_hw_v2.c
providers/mlx5/man/mlx5dv_flow_action_esp.3.md

Loose patches from the mailing list

Ml 2018 05 16

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be 19.0

---

CMakeLists.txt
kernel-headers/update
libibverbs/driver.h
providers/cxgb4/cq.c
providers/cxgb4/libcxgb4.h
providers/cxgb4/qp.c
providers/cxgb4/verbs.c
providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c

Patches from mailing list 2018-05-23

ML 2018 05 23

---

librdmacm/cma.c
srp_daemon/srp_daemon.c

Ml 2018 06 04

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be 20.0

---

debian/control
providers/rxe/rxe_cfg.in
suse/rdma-core.spec

Updated from ML:
- Switch from ifconfig to iproute2
- Fix missing dependencies for SUSE RPM

rxe_cfg fixes

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be 21.0

---

buildlib/cbuild

buildlib: update SUSE validation targets

---

providers/i40iw/i40iw_uverbs.c

The SEND_WITH_INVAL operation is supported in i40iw
driver but accidentally missed out in user-space.
Add the support in libi40iw.
Reported-by: Benjamin Walker <benjamin.walker@intel.com>
Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>

providers/i40iw: Add SEND_WITH_INVAL support

---

providers/hns/hns_roce_u_hw_v2.c

This patch series fix a bug with atomic as well as
add local invalidate support for user mode.

two misc fixes for libhns

---

ibacm/src/acme.c

ibacm: Remove trailing blanks

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Update library version to be 22.0

---

ibacm/src/acm.c

When ibacm receives an IB re-registration event (see 14.4.11 CLIENT
REREGISTRATION in IBTA spec), it checks to see if the port state is
active and that the acmp's port has the prov_port_context set.
If not, it ignores the event.
But, a normal sequence is that the re-registration event is sent
before the port active event, as can be seen from this output from
ibv_asyncwatch:
event_type IBV_EVENT_PORT_ERR (10), port 1
event_type IBV_EVENT_CLIENT_REREGISTER (17), port 1
event_type IBV_EVENT_PORT_ACTIVE (9), port 1
Here, we first see the error event due to the port going down, then we
see the two events associated with the port coming up.
But due to the above depicted construct in ibacm, it will not
re-register. In order to handle the above sequence of events, we make
a record of it in the …

ibacm: Handle rereg event coming before link active event

---

ibacm/prov/acmp/src/acmp.c

In the default provider, acmp, the port's sa_dest.refcnt is
initialized to one in acmp_init_dest(). When a port associated with
the device is added, the refcnt is set once again to one in
acmp_port_up().
For a system with VFs enabled, the ports for both the PF and the VFs
are added. This because ibacm uses the Node GUID, Port, and pkey
triple to designate an endpoint. Since the Node GUID is the very same
for the PF and VFs, we will get several port up events.
acmp_port_up: mlx4_0 1
acmp_port_up: mlx4_0 1 is up
acmp_port_up: mlx4_0 1
acmp_port_up: mlx4_0 1 is up
Now, when/if this ports goes down, acmp_port_down() will be called. It
decrements the refcnt and waits endlessly until it becomes zero. For
the first call to acmp_port_down(), it becomes zero, but the
subsequent call will loop …

ibacm: Fix improper refcnt

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

This patchset fix two bugs for the hns userspace driver.

hns userspace driver fixes

---

libibverbs/cmd.c
libibverbs/examples/devinfo.c
libibverbs/examples/srq_pingpong.c
libibverbs/examples/xsrq_pingpong.c
libibverbs/man/ibv_query_device_ex.3
libibverbs/verbs.h
providers/mlx5/cq.c
providers/mlx5/mlx5.h
providers/mlx5/mlx5dv.h
providers/mlx5/srq.c
providers/mlx5/verbs.c

This series enhanced the ODP functionality in the user space area as follows:
- It reports ODP related capabilities on XRC and SRQ.
- It handles some page fault flow in the mlx5 driver .
The matching kernel part was already merged into for-next.

Verbs: Enhanced ODP functionality 

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u_buf.c
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

This series optimizes some functions for reducing complexity as well as fix a bug.

Misc updates for libhns

---

librdmacm/examples/rping.c

When the user is working with self created QP, the rdma_disconnect
doesn't issue modify to error on the QP and it's the application's
responsibility to do so.
When running with '-C' option, not doing so will cause the CQ thread to
get stuck waiting for FLUSHED completions in the teardown flow.

rping: Move QP to error in self created QP mode

---

CMakeLists.txt
debian/changelog
redhat/rdma-core.spec
suse/rdma-core.spec

Bump rdma-core library version to be 24.0

Update library version to be 24.0

---

.mailmap

Link my previous accounts to my gmail account.
Signed-off-by: Steve Wise <larrystevenwise@gmail.com>

.mailmap: add Steve Wise aliases

---

MAINTAINERS

MAINTAINERS: Update libibumad maintainer

---

pyverbs/CMakeLists.txt
pyverbs/cq.pxd
pyverbs/cq.pyx
pyverbs/device.pyx
pyverbs/libibverbs.pxd
pyverbs/libibverbs_enums.pxd
pyverbs/tests/base.py
pyverbs/tests/cq.py
pyverbs/tests/device.py
pyverbs/tests/mr.py
pyverbs/tests/pd.py
pyverbs/tests/utils.py

This series precedes pyverbs' traffic series with some needed changes:
- Some enums were missing.
- Modify some of the user-visible prints for a more readable output
as well as to avoid an exception thrown when printing an
uninitialized object.
- Tests: Coverage and performance improvements.
- Add events support.

Pyverbs improvements

---

buildlib/cbuild
srp_daemon/srp_daemon.c

Cbuild fc30

---

CMakeLists.txt
buildlib/cbuild

Run through cbuild and the compiler choices again to make sure everything is working before the release.

cbuild fixes

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v1.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

Here is optimize some codes for hns userspace drvier as well as fixes a bug with nvme application。

libhns: Code optimization and bugfixes for libhns

---

CMakeLists.txt
buildlib/RDMA_Sparse.cmake
buildlib/cbuild
buildlib/gen-sparse.py
buildlib/github-release
buildlib/sparse-include/27/bits-sysmacros.h.diff
buildlib/sparse-include/27/netinet-in.h.diff
buildlib/sparse-include/27/stdlib.h.diff
buildlib/sparse-include/27/sys-socket.h.diff
ibacm/src/acm_util.c
providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c

Various small mistakes I noticed while updating the CI build to run on a bionic based container.

More fixes for building

---

buildlib/gen-sparse.py
ibacm/linux/osd.h
providers/bnxt_re/verbs.c
providers/bnxt_re/verbs.h
providers/efa/verbs.c
providers/mlx5/dr_action.c
providers/mlx5/dr_domain.c
providers/mlx5/dr_send.c
providers/ocrdma/ocrdma_verbs.c
providers/qedr/qelr_verbs.c
pyverbs/device.pyx

Supporting xenial and bionic together requires the script to only apply patches from a single glibc release, and not try and stack them.

Fix sparse in travis

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Here are some fixes for hip08 user driver from reviews and test bug.

Bugfixes for hip08 userspace

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Here fixes a bug for processing srq's sge as well as clean some unused codes.

Updates for hip08

---

debian/control
debian/ibverbs-providers.lintian-overrides
debian/rules
libibverbs/man/ibv_modify_qp_rate_limit.3
libibverbs/man/ibv_wr_post.3.md

This patch set contains the packaging changes from the Debian unstable 24.0-2 upload.

Debian 24.0-2 changes

---

debian/ibverbs-providers.symbols
providers/efa/CMakeLists.txt
providers/efa/efadv.h
providers/efa/libefa.map
providers/efa/man/efadv_query_ah.3.md
providers/efa/man/efadv_query_device.3.md
providers/efa/verbs.c

Hi,
This PR adds a couple of new DVs to the EFA provider.
Patch 1 is query device DV and patch 2 is query AH DV.

Couple of EFA direct verbs

---

providers/efa/efa.c
providers/efa/verbs.c

Hi,
Submission includes a few fixes for the EFA provider, see individual commits for info.

efa: 2019 08 04 misc fixes

---

kernel-headers/rdma/siw-abi.h
providers/siw/siw.c

Signed-off-by: Bernard Metzler <bmt@zurich.ibm.com>

siw: Change user mmapped CQ notifications flags to 32bit.

---

providers/mlx5/man/mlx5dv_query_device.3
providers/mlx5/mlx5.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv.h

Report ODP capabilities for DC through mlx5dv_query_device.
Signed-off-by: Michael Guralnik <michaelgur@mellanox.com>
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>

mlx5: Report ODP capabilities for DC transport

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_buf.c
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5.h
providers/mlx5/srq.c
providers/mlx5/verbs.c

Here are some fixes and codes optimization for libhns.

Fixes and code optimization for libhns

---

debian/libibumad3.symbols
infiniband-diags/ibstat.c
libibumad/CMakeLists.txt
libibumad/libibumad.map
libibumad/man/umad_free_ca_device_list.3.md
libibumad/man/umad_get_ca_device_list.3.md
libibumad/umad.c
libibumad/umad.h

Add ability to get more than 32 available InfiniBand device names.
New APIs were added:
umad_get_ca_namelist
umad_free_ca_namelist

Support get ca name list greater than 32

---

providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/mlx5dv_dr.h

This series fixes few issues in the direct rule area of mlx5 driver, details exist as part of the commit messages.

mlx5: Few fixes in the direct rule area

---

debian/copyright
debian/libibverbs1.symbols
libibverbs/man/ibv_create_flow_action.3.md
libibverbs/man/ibv_read_counters.3.md

This patch set contains the packaging changes from the Debian unstable 26.0-1 upload.

Debian 26.0-1 changes

---

buildlib/pyverbs_functions.cmake
pyverbs/CMakeLists.txt
pyverbs/device.pxd
pyverbs/device.pyx
pyverbs/providers/mlx5/CMakeLists.txt
pyverbs/providers/mlx5/libmlx5.pxd
pyverbs/providers/mlx5/mlx5_enums.pyx
pyverbs/providers/mlx5/mlx5dv.pxd
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/providers/mlx5/mlx5dv_enums.pxd
pyverbs/qp.pyx

Direct verbs (DV) provide fast data path execution. This series introduces the DV infrastructure to pyverbs:
Allow providers to open contexts rather than use ibv_open_device.
Add Mlx5Context and expose the mlx5dv_query_device.

pyverbs: Introducing direct verbs

---

buildlib/pyverbs_functions.cmake
pyverbs/base.pyx
pyverbs/device.pyx
pyverbs/libibverbs_enums.pxd
pyverbs/mr.pyx
pyverbs/pd.pyx
pyverbs/qp.pyx
pyverbs/srq.pyx
pyverbs/wr.pyx
pyverbs/xrcd.pyx

Various fixes to the use of cython and the pyverbs test runner.

Pyverbs fixes

---

srp_daemon/srp_daemon.c

"ib_srp.ko" module with immediate data support use (8 * 1024)
as default immediate data size. When immediate data support enabled
for "ib_srp.ko" client, the default maximum initiator to target IU
size will greater than (8 * 1024). That means it also greater than
the default maximum initiator to target IU size set by old
"ib_srpt.ko" module, which does not support immediate data.
Pass remote maximum initiator to target IU size as a login parameter,
when immediate data size greater than remote maximum initiator to
target IU size.
This patch fixes backward compatibility for "ib_srp.ko" with [1]
and old srp target does not support immediate data.
[1] 547ed331bbe8 ("RDMA/srp: Add parse function for maximum
initiator to target IU size")

srp_daemon: Use maximum initiator to target IU size

---

Documentation/testing.md
tests/utils.py

Update testing documentation and properly handle GRH offset for UD
QP in the tests/ section.

tests: A few fixes

---

buildlib/azure-pipelines.yml
buildlib/cbuild

Fixup some container build problems
Update to Fedora 31

Cbuild updates

---

Documentation/udev.md
README.md

A couple of documentation fixes.

Documentation fixes

---

buildlib/azure-pipelines.yml

buildlib: Build devel stable branches on Azure

---

providers/mlx5/dr_action.c

Current modify header supports 8 modify actions, dropped this hard coded
limit and made it dynamic.

mlx5: Extended modify header to support more than 8 modify actions

---

kernel-headers/rdma/efa-abi.h
providers/efa/efa.h
providers/efa/efa_io_defs.h
providers/efa/efadv.h
providers/efa/man/efadv_query_device.3.md
providers/efa/verbs.c

Support RDMA operations through the new verbs send API and report RDMA capabilities through the query device direct verb.

EFA RDMA read

---

providers/efa/verbs.c

Various updates for the EFA provider.

EFA misc updates pr

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Various fixes on library of hip08.

Bugfix for hip08

---

infiniband-diags/man/infiniband-diags.8.in.rst

lintian found some spelling mistakes in the infiniband-diags man page.

Fix spelling mistakes in infiniband-diags man page

---

debian/upstream/metadata

Set upstream metadata fields: Repository, Repository-Browse.
This merge proposal was created automatically by the Janitor bot
(https://janitor.debian.net/lintian-fixes).
You can follow up to this merge proposal as you normally would.
Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/rdma-core/b0e948bb-bbde-4baa-a912-a10455afd82b.

Fix lintian issues: Set upstream metadata fields: Repository, Repository-Browse.

---

Documentation/testing.md

Update testing.md to properly reflect recent changes to the test suite
execution.
Fixes: d6c1c233 ('tests: Fix test locating process')

Documentation: Update testing doc

---

debian/ibverbs-providers.maintscript
debian/upstream/metadata

This patch set contains the packaging changes from the Debian unstable 27.0-2 upload.

Debian 27.0-2 changes

---

suse/rdma-core.spec

Fix path to udevadm
And add missing owner to python tests directory

SUSE Fixes

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h
providers/hns/hns_roce_u_verbs.c

This series include various cleanups, no code logic is changed.

libhns: Various cleanups

---

pyverbs/pyverbs_error.py
pyverbs/qp.pyx
pyverbs/xrcd.pyx
tests/base.py
tests/test_addr.py
tests/test_cq.py
tests/test_cqex.py
tests/test_mr.py
tests/test_qp.py

This series includes patches to avoid failures when certain features are not supported by some devices.

tests: Avoid failures when features aren't supported

---

libibverbs/cmd.c
libibverbs/driver.h
libibverbs/dummy_ops.c
libibverbs/man/ibv_advise_mr.3.md
libibverbs/man/ibv_create_counters.3.md
libibverbs/man/ibv_modify_qp_rate_limit.3
libibverbs/verbs.h
providers/mlx5/qp.c
providers/mlx5/verbs.c

The proper return code is EOPNOTSUPP when an operation is not supported.

Fix incorrect return code

---

redhat/rdma-core.spec
suse/rdma-core.spec

'make -v' is version information.
Signed-off-by: Tzafrir Cohen <mellanox@cohens.org.il>

Proper command for verbose make

---

Documentation/versioning.md

A couple of fixes to the versioning documentation.

Versioning documentation fixes

---

buildlib/azure-pipelines.yml
buildlib/cbuild

Lets test Xenial too, it is popular still.

Test xenial builds on AZP

---

libibverbs/examples/devinfo.c

It becomes difficult to make out from the output of ibv_devinfo
if a particular gid index is RoCE v2 or not.
Adding a string to the output of ibv_devinfo -v to display the
gid type at the end of gid.
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>

rdma-core/libibverbs: display gid type in ibv_devinfo

---

pyverbs/cmid.pxd
pyverbs/cmid.pyx
pyverbs/device.pyx
pyverbs/xrcd.pyx
tests/test_addr.py
tests/test_cq.py
tests/test_mlx5_var.py
tests/test_mr.py
tests/test_pd.py

This series includes some bug fixes in the tests and infrastructure.
In addition, unused imports were removed (or moved to the relevant files).

pyverbs: Bug fixes and imports cleanup

---

infiniband-diags/perfquery.c

Dump only supported port extended counters instead of dump
all extedned port counters that some of them may be not supported
and dumped with zero values.
When IsExtendedWidthSupported detected, the following fields will be
dumped:
PortUnicastXmitPkts
PortUnicastRcvPkts
PortMulticastXmitPkts
PortMulticastRcvPkts
When IsAdditionalPortCountersExtendedSupported detected, the following
fields will be dumped:
CounterSelect2
SymbolErrorCounter
LinkErrorRecoveryCounter
LinkDownedCounter
PortRcvErrors
PortRcvRemotePhysicalErrors
PortRcvSwitchRelayErrors
PortXmitDiscards
PortXmitConstraintErrors
PortRcvConstraintErrors
LocalLinkIntegrityErrors
ExcessiveBufferOverrunErrors
VL15Dropped
PortXmitWait
QP1Dropped
Signed-off-by: Haim Boozaglo <haimbo@mellanox.com>

ibdiags: Dump only supported extended port counters

---

providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c

This series includes few fixes and improvements in the DR area, some of are coming to improve performance and reduce memory, while others are direct functional related.

mlx5: DR enhancements

---

pyverbs/addr.pyx
pyverbs/cmid.pyx
pyverbs/cq.pyx
pyverbs/device.pyx
pyverbs/mr.pyx
pyverbs/pd.pyx
pyverbs/providers/mlx5/mlx5dv.pyx
pyverbs/qp.pyx
pyverbs/srq.pyx
pyverbs/wr.pxd
pyverbs/wr.pyx
pyverbs/xrcd.pyx

This series include some bug fixes and improvements in Pyverbs' infrastructure.

Pyverbs: Bug fixes and improvements

---

tests/base.py

Avoid the following exception when running RDMATestCase tests over none
Mellanox devices:
File "/home/rdma-core/tests/test_cq_events.py", line 26, in setUp
super().setUp()
File "/home/rdma-core/tests/base.py", line 129, in setUp
self._add_gids_per_device(ctx, dev_name)
File "/home/rdma-core/tests/base.py", line 161, in _add_gids_per_device
self._add_gids_per_port(ctx, dev, port+1)
File "/home/rdma-core/tests/base.py", line 154, in _add_gids_per_port
vendor_pid in ROCEV2_UNSUPPORTED_DEVS[dev_attrs.vendor_id]:
KeyError: 5348
Fixes: f65543c15ea4 ("tests: Avoid RoCEv2 GIDs on unsupported devices")

tests: Fix check for unsupported RoCEv2 devices

---

pyverbs/CMakeLists.txt
pyverbs/device.pyx
pyverbs/providers/efa/CMakeLists.txt
pyverbs/providers/efa/efadv.pxd
pyverbs/providers/efa/efadv.pyx
pyverbs/providers/efa/efadv_enums.pxd
pyverbs/providers/efa/libefa.pxd
tests/CMakeLists.txt
tests/test_efadv.py

Add pyverbs support for EFA direct verbs and introduce a simple test for it.

EFA pyverbs

---

debian/libibverbs1.symbols
kernel-headers/rdma/rdma_user_cm.h
libibverbs/CMakeLists.txt
libibverbs/device.c
libibverbs/libibverbs.map.in
libibverbs/man/CMakeLists.txt
libibverbs/man/ibv_get_device_guid.3.md
libibverbs/man/ibv_get_device_index.3.md
libibverbs/man/ibv_get_device_list.3.md
libibverbs/verbs.h
librdmacm/cma.c
librdmacm/rdma_cma_abi.h

Provide a way to identify the device in unique way.

RDMA-CM unique device identifier

---

tests/CMakeLists.txt
tests/base.py
tests/base_rdmacm.py
tests/rdmacm_utils.py
tests/test_rdmacm.py

RDMACM tests infrastructure refactoring which includes:
1. Add Async and Sync CMResources. These aggregation objects inherit
from CMResources and implement resources creation accordingly.
2. Add CMConnection class which is responsible for CMResources
initialization, connection establishment and traffic between two peers.
3. Separate RDMACM aggregation objects from Verbs objects for easier
maintenance.
This allows easier adoption of rdmacm upcoming tests.

tests: RDMACM tests infrastructure refactoring

---

providers/mlx5/man/mlx5dv_create_qp.3.md
providers/mlx5/mlx5.h
providers/mlx5/verbs.c

This series includes the below two enhancements:
- man page improvement of mlx5dv_create_qp().
- cleanup of some un applicable code.

mlx5: Few enhancements 

---

providers/efa/verbs.c

The provider should not access the 'ibv_resp' parts of the response
structure, use the max_inline_data in ibv_qp_init_attr_ex instead.
This issue can be observed when using the ioctl interface for the
create/destroy QP verbs, which keeps the 'ibv_resp' part of the response
cleared.
Suggested-by: Jason Gunthorpe <jgg@ziepe.ca>

efa: Fix create QP command over ioctl interface

---

providers/mlx5/dr_matcher.c
providers/mlx5/dr_ste.c

This series in the DR area introduces few optimizations in some flows, in addition it fixes an issue when matching on a vport gvmi is handled.

mlx5: DR improvements 

---

providers/efa/efa.h
providers/efa/verbs.c

A few cleanups to the EFA provider.
No functional changes in this series.

EFA summer cleanups

---

buildlib/azure-pipelines-release.yml
buildlib/azure-pipelines.yml
buildlib/cbuild

Azp update

---

libibverbs/cmd_wq.c

Use WQ creation flags properly by considering its input comp_mask.

verbs: Use WQ creation flags properly

---

kernel-headers/rdma/efa-abi.h
kernel-headers/rdma/mlx5_user_ioctl_cmds.h
kernel-headers/rdma/rdma_netlink.h
kernel-headers/rdma/rdma_user_ioctl.h
providers/efa/efa-abi.h
providers/efa/efa.c
providers/efa/efa.h
providers/efa/verbs.c

Kernel submission:
v1: https://lore.kernel.org/linux-rdma/20200709083630.21377-1-galpress@amazon.com/
v2: https://lore.kernel.org/linux-rdma/20200720080113.13055-1-galpress@amazon.com/
v3: https://lore.kernel.org/linux-rdma/20200721133049.74349-1-galpress@amazon.com/
v4: https://lore.kernel.org/linux-rdma/20200722140312.3651-1-galpress@amazon.com/

Add support for 0xefa1 device

---

providers/efa/efa-abi.h
providers/efa/efa.c
providers/efa/efa.h
providers/efa/verbs.c
providers/efa/verbs.h
tests/test_cqex.py

Add support for extended CQ to the efa provider.

EFA extended CQ

---

tests/test_qp.py

When trying to create a RAW packet QP over devices with multiple ports
(like mlx4) make sure to pass the port number to the QPAttr() to avoid
creating RAW packet QP over an IB port.

tests: Make sure to set the port_num when creating RAW packet QP

---

CMakeLists.txt
buildlib/fixup-include/sys-random.h
providers/mlx5/verbs.c
util/util.c
util/util.h

Add get_random() API to get random data with static seed, which is generated with getrandom() for better randomness.

mlx5: Use getrandom() to seed a strong PRNG

---

providers/mlx5/dr_action.c
providers/mlx5/dr_rule.c

This series includes few optimizations in the DR area within the sampler and the matcher parts.
It includes also a bug fix in some unwind flow.

mlx5: DR, misc items

---

providers/mlx5/mlx5.c

The `alloc_context` function is supposed to take ownership of `cmd_fd` and close it if it fails and returns `NULL`.  This was not done in early exit error paths from `mlx5_init_context` (called from `mlx5_alloc_context`).

Fix cmd_fd leak in mlx5_init_context

---

kernel-headers/rdma/rdma_user_rxe.h
providers/rxe/rxe.c
providers/rxe/rxe.h

Rxe network type

---

providers/efa/verbs.c

An mmio_wc_start() is needed before writing to the LLQ memory in order
to prevent the WQEs copy from being reordered relative to other mmio
writes, such as tx doorbells.
Placing the mmio_wc_start() before each WQE memcpy is wasteful, as the
doorbell write doesn't happen on each iteration. Instead, it is placed
right after the doorbell write, as a preparation for the next batch of
WQEs.
This prevents provider to issue more than max_tx_batch LLQ writes
between two doorbells. This is especially relevant when the user calls
the _post API with more WQEs than max_tx_batch.
Fixes: 7aad28d ("efa: Respect maximum TX doorbell batch")
Signed-off-by: Shadi Ammouri <sammouri@amazon.com>

efa: Flush write combining writes before writing to the LLQ

---

CMakeLists.txt
debian/control
debian/libibverbs1.symbols
libibverbs/device.c
libibverbs/driver.h
libibverbs/ibdev_nl.c
libibverbs/libibverbs.map.in
librdmacm/examples/udaddy.c
util/rdma_nl.c

This series includes a fix in some udaddy bad flow.
In addition it cleans-up some unused stuff in the verbs area related to 'fw_ver'.

Verbs: Misc items

---

pyverbs/providers/efa/CMakeLists.txt
pyverbs/providers/efa/efa_enums.pyx
pyverbs/providers/efa/efadv.pxd
pyverbs/providers/efa/efadv.pyx
pyverbs/providers/efa/libefa.pxd
tests/CMakeLists.txt
tests/efa_base.py
tests/test_efa_srd.py
tests/test_efadv.py
tests/utils.py

This series adds send and send with immediate pyverbs tests over SRD QPs.

Pyverbs SRD traffic

---

pyverbs/qp.pyx
tests/CMakeLists.txt
tests/base.py
tests/mlx5_base.py
tests/test_mlx5_cq.py

Add tests for mlx5dv CQ.
The tests include traffic and some bad creation flows.

tests: Add mlx5 CQ tests

---

pyverbs/cq.pyx
pyverbs/libibverbs.pxd
tests/test_cq.py
tests/test_cqex.py

This series includes refactoring and removal of some tests under test_cq,
such as removing meaningless iterations and unnecessary cases which are
already included in other tests.
In addition, support to resize is added, along with new additional tests.

tests: Improve and extend CQ tests

---

tests/test_device.py

Add a test that queries the gid_table with an insufficient
amount of entries.
Add a test that uses query_gid_ex with a non-existent gid index.

tests: Add query_gid_table and query_gid_ex bad flows

---

.mailmap
librdmacm/man/rdma_server.1

Allow to the various statistics tools to combine all my
addresses under the major one.

mailmap: Add my addresses to the mailmap

---

providers/efa/efa.h
providers/efa/verbs.c

Minor cleanups to the EFA provider.

EFA provider minor cleanups

---

infiniband-diags/ibnetdiscover.c

Add NDR support in ibnetdiscover.
Reference: IB Spec 1.5 draft September 29, 2020.
Signed-off-by: Gregory Linschitz <gregoryl@nvidia.com>

ibdiag: Add NDR support in ibnetdiscover

---

providers/hns/hns_roce_u.h
providers/hns/hns_roce_u_hw_v1.c
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Refactor libhns codes to make them easier to understand and maintain.

libhns: Codes refactor

---

kernel-headers/rdma/rdma_user_rxe.h
providers/rxe/rxe-abi.h
providers/rxe/rxe.c
providers/rxe/rxe.h
providers/rxe/rxe_queue.h

A series of 5 commits to implement the extended verbs APIs
- ibv_query_device_ex
- ibv_create_cq_ex
- ibv_create_qp_ex

rxe extended verbs support

---

tests/efa_base.py
tests/test_efa_srd.py
tests/utils.py

The first patch adds SRD RDMA read test, and the next two patches add send and send with immediate testing on SRD extended QPs with old send API.

More SRD pyverbs testing

---

tests/test_mlx5_cq.py

Add a CQE compression capability check in mlx5 CQ tests before creating
a CQ. If the device does not support the requested CQE compression type,
the test will be skipped.

tests: Check CQE compression cap before using it

---

kernel-boot/rdma-persistent-naming.rules
kernel-boot/rdma_rename.c

usage:  ```rdma_rename <old-name> NAME_FIXED <new-name>```

Add NAME_FIXED option for rdma_rename

---

pyverbs/device.pyx
pyverbs/mr.pyx
tests/base.py
tests/test_device.py
tests/test_mr.py

The series extends the write method of DMMR with an offset parameter and adds new device memory tests that include control and data path.

tests: Add device memory tests

---

tests/test_mr.py

Class MRRes is defined twice, remove the first unused class.

tests: Remove unused class MRRes

---

redhat/rdma.modules-setup.sh

redhat: Do not add rdma-ndd to initramfs

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_hw_v2.h

Make the process of filling segments of atomic operation clearer.

libhns: Refactor atomic operation

---

libibverbs/cmd_ioctl.h
providers/mlx4/verbs.c
providers/mlx5/dr_domain.c

This series includes few small fixes in both verbs and mlx drivers.

verbs: Misc fixes

---

suse/module-setup.sh
suse/rdma-core.spec

It should be /usr/lib/dracut not /usr/libexec/dracut

suse: Fix path to dracut dir

---

providers/bnxt_re/bnxt_re-abi.h
providers/bnxt_re/db.c
providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/verbs.c

This patch series is a part of bigger feature submission which
changes the wqe posting logic. The current series adds the
ground work in the direction to change the wqe posting algorithm.

Broadcom's rdma provider lib update

---

tests/test_mlx5_flow.py

Verify that reformat action is supported on both receive and transmit
flow tables in Mlx5MatcherTest.test_tx_packet_reformat().
Skip the test if it's not supported.

tests: Query NIC flow table caps before reformat

---

providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Fix an issue during calculation of extended sge and then do some cleanups.

libhns: Few changes about sge

---

Documentation/contributing.md
README.md

Discuss how to use GitHub properly and document the special kernel-headers
process.

docs: Add a contributing.md

---

libibnetdisc/ibnetdisc.c
libibverbs/examples/devinfo.c

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

minor cleanups

---

buildlib/azure-pipelines-release.yml
buildlib/azure-pipelines.yml
buildlib/cbuild
pyverbs/wr.pyx

- gcc 11
- clang 12
- Debian 10 i386 native compiler with cython

Azp update with new compilers and full 32 bit

---

Documentation/azure-pipelines.md
Documentation/contributing.md
Documentation/release.md
Documentation/udev.md

Misc typo fixes in the documentation files.

docs: Fix misc documentation typos

---

tests/test_efa_srd.py
tests/test_qpex.py

Add a couple of traffic tests (UD & SRD) for zero size RX/TX.

Zero size traffic pyverbs tests

---

librdmacm/cma.c

Hi, I have a node equipped with 2x dual-port Mellanox HDR adapters (4 ports in total) and running Ubuntu 20.04.
That node is hosting a Docker container where only 2 ports (out of 4) have a uverbs device exposed to the Docker container.
Here is how the system looks like inside the container:
```
mlx5_0  mlx5_1  mlx5_2  mlx5_3
rdma_cm  ucm0  ucm2  uverbs0  uverbs2
```
(uverbs1 and uverbs3 are not listed as you can see above).
With that setup, any application based on the RDMA CM library would fail in rdma_get_devices() with an ENODEV error. Here, I would expect rdma_get_devices() to return an array of ibv_context * for the 2 verbs devices that are available in the container (uverbs0 and uverbs2) even if not all the 4 devices are configured.
I looked at the librdmacm source code and I found …

librdmacm: Do not fail init completely if one device is failing

---

tests/mlx5_base.py

The fix skips running the bad flow DCS stream channel test if
cap log_max_dci_errored is 0. Also removed code that resets errored
streams explicitly after resetting a QP.

tests: Fixed DCS stream channel tests

---

providers/mlx5/cq.c
providers/mlx5/mlx5.h
providers/mlx5/qp.c
providers/mlx5/verbs.c

This series includes few fixes in the block signature area, details exist as part of the commit logs.

mlx5: Few fixes in the block signature area

---

buildlib/check-build
kernel-headers/CMakeLists.txt
kernel-headers/linux/stddef.h
kernel-headers/rdma/rdma_netlink.h
kernel-headers/rdma/rdma_user_rxe.h
providers/rxe/rxe.c

To commit fa55b7dcdc43 ("Linux 5.16-rc1").
Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>

Update kernel headers

---

ibacm/ibacm.service.in
iwpmd/iwpmd.service.in
rdma-ndd/rdma-ndd.service.in

SUSE is launching a system wide effort to harden systemd service files:
See https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort

systemd hardening

---

tests/test_qp.py

The initial QP state for iWARP providers is IBV_QPS_INIT (not
IBV_QPS_RESET), Change the test to handle this case.

tests: Fix comparing qp_state for iWARP providers.

---

providers/rxe/rxe.c

They have been on my hand for a long time. Both of them are found during reviewing the code.

Misc fixes

---

MAINTAINERS

Updating the Maintainer of bnxt_re and ocrdma providers.
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>

MAINTAINERS: Update bnxt_re and ocrdma maintainer

---

providers/hns/hns_roce_u_hw_v2.c

The HIP09 requires the driver to clear the unused data segments in wqe
buffer to make the hns ROCEE stop reading the remaining invalid sges for
RQ.

libhns: Clear remaining unused sges when post recv

---

util/udma_barrier.h

Add barriers support for RISC-V architecture
Signed-off-by: v.v.mitrofanov <v.v.mitrofanov@yadro.com>

util: Add barriers support for RISC-V

---

providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/dr_devx.c
providers/mlx5/dr_icm_pool.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_ste.c
providers/mlx5/dr_ste.h
providers/mlx5/dr_ste_v0.c
providers/mlx5/dr_ste_v1.c
providers/mlx5/dr_ste_v2.c
providers/mlx5/mlx5_ifc.h
providers/mlx5/mlx5dv_dr.h

This series in mlx5 DR area introduces few enhancements and optimizations as follows.
- Support full tunnel headers match.
- Add RX source port optimization to definers.
- Improve insertion rate by pre-allocating STE shadow memory.
- Optimize modify header of single action.
- Reduce memory allocation for struct mlx5dv_dr_action.

mlx5: DR, Few enhancements

---

libibverbs/man/ibv_modify_qp.3

Align flag usage format.
Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>

verbs: fix document format for ibv_modify_qp

---

CMakeLists.txt
buildlib/cbuild
providers/ipathverbs/CMakeLists.txt
providers/mlx4/CMakeLists.txt
suse/rdma-core.spec

Some minor tuning and fixes on the SUSE spec file
And a change to allow modprobe.d to be moved to /lib instead of /etc

suse tweaks

---

tests/base.py
tests/mlx5_base.py
tests/mlx5_prm_structs.py
tests/test_mlx5_dr.py
tests/test_mlx5_lag_affinity.py
tests/test_mlx5_vfio.py
tests/test_qp.py

The series includes multiple fixes for some specific tests or flows and general improvements in the tests infrastructure.

tests: Fixes and improvements

---

pyverbs/mem_alloc.pyx

Add C style general read and write functions to the mem_alloc pyverbs
module. A request that came from multiple users.

pyverbs: Add a read/write functions to mem_alloc

---

pyverbs/providers/mlx5/mlx5dv.pyx

Extend Wqe class to support segments in a PRM format (bytes or PRM
class), instead of WqeSeg instance only.

pyverbs: Extend segments format of WQE class

---

Documentation/testing.md

Signed-off-by: Liu, Changcheng <changcheng.liu@aliyun.com>

Documentation: corret underscore usage in markdown

---

pyverbs/cmid.pxd
pyverbs/cmid.pyx
tests/rdmacm_utils.py

support set rdamcm private data for rdma_connect/accept
Signed-off-by: Liu, Changcheng <changcheng.liu@aliyun.com>

pyverbs: add set rdmacm private_data API

---

tests/test_qp.py

Add coverage for the error conditions of QP
creation limits check.
Signed-off-by: Shuki Zanyovka <shukiz@amazon.com>

tests: add error flow tests for qp creation

---

librdmacm/examples/mckey.c

As not all the providers support the rdma_create_qp_ex(), change the code to use rdma_create_qp_ex() only when loopback prevention is requested.
Fixes: 40806cc22936 ("rdma-core: Add support for multicast loopback prevention to mckey")

mckey: Use rdma_create_qp_ex only for loopback prevention

---

tests/base.py
tests/base_rdmacm.py
tests/rdmacm_utils.py
tests/test_rdmacm.py

The series adds a new RDMACM multicast leave coverage test and adjusts some tests for better stabilization.

tests: Add and adjust RDMACM tests

---

providers/erdma/erdma_hw.h
providers/erdma/erdma_verbs.c

Hi,
This PR introcuces atomic operations (FAA and FCS) support for erdma user space driver.
Thanks,
Cheng Xu

providers/erdma: Add atomic operation support

---

providers/rxe/rxe.c

Fixes incorrect negative error numbers returned by rxe.c

Fix negative errors

---

providers/mlx5/dr_arg.c
providers/mlx5/dr_ste_v1.c

This series includes a few fixes in the DR area of mlx5.
Extra details exist as part of the commit logs.

mlx5: DR, Few fixes

---

pyverbs/providers/mlx5/dr_rule.pyx
pyverbs/providers/mlx5/mlx5dv_flow.pyx
tests/test_flow.py
tests/test_mlx5_crypto.py
tests/utils.py

A small test fix in Crypto tests and a patch that avoids using empty lists as default function parameter values due to
mutability.

tests: Minor test fix and enhancement 

---

pyverbs/providers/mlx5/dr_action.pxd
pyverbs/providers/mlx5/dr_action.pyx
pyverbs/providers/mlx5/libmlx5.pxd
tests/CMakeLists.txt
tests/base.py
tests/test_mlx5_dr.py
tests/test_mlx5_huge_page.py
tests/utils.py

Extend steering tests to include flow sampler Pyverbs support and test coverage.
Also, add huge-page allocation tests.

tests: add huge page allocation and steering coverage

---

README.md

$ ls rdma-core/providers/
bnxt_re  cxgb4  efa  erdma  hfi1verbs  hns  ipathverbs  irdma  mana  mlx4  mlx5  mthca  ocrdma  qedr  rxe  siw  vmw_pvrdma

Add bnxt_re.ko in the supported userspace component list

---

infiniband-diags/dump_fts.c
libibnetdisc/chassis.c
util/node_name_map.c
util/node_name_map.h

fix a couple of static checker-found bugs

Fix a couple of static checker-found bugs

---

tests/mlx5_prm_structs.py
tests/test_mlx5_dr.py
tests/test_mlx5_flow.py
tests/utils.py

Extend mlx5 DR (SW Steering) tests with reformat actions and GENEVE coverage.

tests: Extend mlx5 DR tests

---

providers/irdma/umain.c
providers/irdma/umain.h
providers/irdma/uverbs.c

Add support for ibv_reg_dmabuf_mr verb to the irdma provider.
Signed-off-by: Zhu Yanjun <yanjun.zhu@linux.dev>

irdma: Add support for ibv_reg_dmabuf_mr

---

providers/mlx5/dr_action.c
providers/mlx5/dr_dbg.c
providers/mlx5/dr_icm_pool.c
providers/mlx5/dr_matcher.c
providers/mlx5/dr_ptrn.c
providers/mlx5/dr_rule.c
providers/mlx5/dr_send.c
providers/mlx5/dr_ste.c
providers/mlx5/dr_table.c
providers/mlx5/mlx5dv_dr.h

This series adds a few enhancements in the DR area as of below.
- Fix error flow in creating modify header pattern.
- Refactor the modify header pattern alloc/free flows to have a cleaner code.
- Remove ICM chunk fields that can be calculated separately.

mlx5: DR, Add a few enhancements

---

MAINTAINERS

Change EFA maintainer from Gal Pressman to myself.

MAINTAINERS: Update EFA provider maintainer

---

providers/hns/hns_roce_u_hw_v2.c

This PR contains 3 bugfixes relative to the process of post send/recv.

libhns: Bugfixes for post send/recv

---

providers/bnxt_re/main.c
providers/bnxt_re/main.h
providers/bnxt_re/verbs.c

Minor update to improve the performance and some code refactoring.

bnxt_re update

---

providers/mlx5/dr_devx.c
providers/mlx5/mlx5.h
providers/mlx5/srq.c
providers/mlx5/verbs.c

This series includes the below few enhancements.
-  Enhance SRQ performance by better following the HW pre-fetch algorithm
-  Fix in the DR area the 'dest root table' action for NIC TX.

mlx5: Few enhancements

---

providers/efa/verbs.c

When trying to destroy QP or CQ, we first release rdma-core resources for the relevant object (mapping for address ranges, refcounts, locks etc.) and only then request the driver to destroy the object. If the driver or the device fails, the object isn't fully destroyed so the user can try to destroy the object again which will lead to trying to release already released rdma-core resources for the object. Change deallocation order to first call kernel and driver code and if succeeded release rdma-core resources.

efa: Change resource deallocation order in QP and CQ

---

providers/irdma/abi.h
providers/irdma/umain.c
providers/irdma/umain.h
providers/irdma/uverbs.c

Add API callback to support re-registering a  memory region.

providers/irdma: Add support to re-register a memory region.

---

providers/efa/efa.h
providers/efa/efa_trace.h
providers/efa/verbs.c

Add device name and operation type to EFA LTTng trace points.

efa: Extend trace parameters

---

providers/irdma/uverbs.c

The allocation of IRDMA_MEMREG_TYPE_QP needs to be aligned to the OS page size to allow for sharing the SQ area between the kernel iwarp cm processing and user SQ posts.  The kernel code stores the struct page pointer for later use, so the allocation must be aligned to the OS page size.
Use sysconf to get the OS page size and add a new allocator and use that for iwarp IRDMA_MEMREG_TYPE_QP allocations. The old allocator is now a wrapper that is used for all other call sites.

providers/irdma: Handle OS page size of 64k

---

providers/irdma/uk.c
providers/irdma/uverbs.c

Irdma fixes

---

providers/efa/efa.c

Add 0xefa3 devices to the pciid match table.

efa: Add EFA 0xefa3 PCI ID

---

buildlib/azure-pipelines.yml
buildlib/cbuild

cbuild: Update to Fedora 41

---

providers/hns/hns_roce_u.c
providers/hns/hns_roce_u_hw_v2.c
providers/hns/hns_roce_u_verbs.c

Add error logs to help diagnosis.

libhns: Add error logs to help diagnosis

---

providers/mlx5/man/mlx5dv_wr_set_mkey_sig_block.3.md

s/mlx5dv_sig_block_size/mlx5dv_block_size/

mlx5: update set_mkey_sig_block doc for readability

---

iwpmd/iwarp_pm_common.c

Fix the following:
/iwpmd/iwarp_pm_common.c:214:2: var_decl: Declaring variable "opt_len" without initializer. /iwpmd/iwarp_pm_common.c:255:2: uninit_use_in_call: Using uninitialized value "opt_len" when calling "getsockopt".

iwpmd: Fix uninitialized value

---

Documentation/azure-pipelines.md
Documentation/contributing.md
Documentation/librdmacm.md
Documentation/pyverbs.md
Documentation/stable.md
Documentation/udev.md
Documentation/versioning.md

Fix some files in Documentation directory.

Documentation: Fix spelling and grammatical errors

---

providers/efa/verbs.c

Add two optimizations for poll CQ functions:
1. Single sub CQ poll variant
2. single threaded CQ

efa: CQ polling optimizations
