linux-rdma/rdma-core

tests/test_odp.py, tests/utils.py
When submitting a work request, its address handle must remain valid
until the corresponding completion is polled.
Move the AH allocation outside of the send function and make sure it's
not destroyed before we're finished using it.
Signed-off-by: Chen Brasch <cbrasch@amazon.com>
=> tests: Don't use destroyed address handle

CMakeLists.txt, buildlib/FindLDSymVer.cmake, buildlib/config.h.in, iwpmd/iwarp_pm_common.c, libibumad/umad.c, libibverbs/verbs.c, redhat/rdma-core.spec, suse/rdma-core.spec, util/symver.h
Now that gcc has defined attribute symver we can make LTO support work on compilers that support the new attribute.
@nmorey @Honggang-LI
=> Fix LTO support

providers/qedr/qelr_main.c
As libqedr support both RoCE and iWarp, make sure to return EOPNOTSUPP
from qelr_create_qp_ex() when running in iWarp mode.
Fixes: cae4a99ae679 ("libqedr: add support for XRC-SRQ's.")
=> libqedr: Fix return code when qelr_create_qp_ex() isn't supported

debian/ibverbs-providers.symbols, providers/mlx5/dr_action.c, providers/mlx5/dr_dbg.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h, providers/mlx5/verbs.c
This series Introduces few ASO actions as of first hit and flow metering.
The first hit action allows tracking when a rule is hit by a packet, the flow metering action allows monitoring the packet rate for specific flows.
=> mlx5: DR, Introduce ASO actions

librdmacm/cma.c
Before open an eXtended Reliable Connection (XRC) domain, a protection
domain should be established. So, close the XRC domain before close
protection domain.
=> librdmacm: close XRC domain before close the protection domain

libibverbs/examples/devinfo.c
Avoid reporting link_layer "InfiniBand" for efa devices.
Before:
$ ibv_devinfo
hca_id:	efa_0
transport:			unspecified (4)
fw_ver:				0.0.0.0
node_guid:			0000:0000:0000:0000
sys_image_guid:			0000:0000:0000:0000
vendor_id:			0x1d0f
vendor_part_id:			61344
hw_ver:				0xEFA0
phys_port_cnt:			1
port:	1
state:			PORT_ACTIVE (4)
max_mtu:		4096 (5)
active_mtu:		4096 (5)
sm_lid:			0
port_lid:		0
port_lmc:		0x01
link_layer:		InfiniBand
After:
$ ibv_devinfo
hca_id:	efa_0
transport:			unspecified (4)
fw_ver:				0.0.0.0
node_guid:			0000:0000:0000:0000
sys_image_guid:			0000:0000:0000:0000
vendor_id:			0x1d0f
vendor_part_id:			61344
hw_ver:				0xEFA0
phys_port_cnt:			1
port:	1
state:			PORT_ACTIVE (4)
max_mtu:		4096 (5)
active_mtu:		4096 (5)
sm_lid:			0
port_lid:		0
port_lmc:		0x01
link_layer: …
=> libibverbs: Fix reporting link_layer for efa devices

pyverbs/pd.pxd, pyverbs/pd.pyx, tests/test_parent_domain.py
Extend parent domain tests to include traffic.
The series includes: UD traffic, RC traffic with/without SRQ
extended CQ and huge pages.
=> tests: Extend parent domain tests

providers/efa/man/CMakeLists.txt
Include all the provider's man pages in CMakeLists.txt.
=> efa: Add missing man pages to CMakeLists.txt

providers/mlx5/buf.c, providers/mlx5/cq.c, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/qp.c, providers/mlx5/verbs.c
Replace the legacy fprintfs with mlx5_err() wrapper to better control output according to debug mode.
=> mlx5: Add mlx5_err() wrapper to control output

debian/ibverbs-providers.symbols, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_modify_qp_sched_elem.3.md, providers/mlx5/man/mlx5dv_sched_node_create.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/device.pxd, pyverbs/device.pyx, pyverbs/providers/mlx5/CMakeLists.txt, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, pyverbs/providers/mlx5/mlx5dv_sched.pxd, pyverbs/providers/mlx5/mlx5dv_sched.pyx, tests/CMakeLists.txt, tests/test_mlx5_sched.py
Expose DV APIs to control the transmit scheduler, this allows enforcing QoS policies.
The internal implementation was done over DEVX, detailed man pages to describe the usage are part of the series.
Note:
The first 9 patches in the series were taken from https://github.com/linux-rdma/rdma-core/pull/890 as the series touches the same area of the context capabilities.
=> mlx5: Expose DV APIs to control the transmit scheduler

debian/ibverbs-providers.symbols, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_modify_qp_udp_sport.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, tests/CMakeLists.txt, tests/base.py, tests/test_mlx5_lag_affinity.py, tests/test_mlx5_udp_sport.py
This series Improves the entropy support in few areas as of below.
It enables modifying the configured UDP source port of a given RC/UC QP when QP is in RTS state over DV & DEVX.
In addition, it extends mlx5dv_modify_qp_lag_port() to support extra QP types based on device capabilities.
A matching pyverbs stuff was added to demonstrate the usage.
=> mlx5: Improve the entropy support in few areas

providers/mlx5/verbs.c
In case application uses a single threaded mode even a UAR that is shared between QPs
doesn't need to take a lock.
=> mlx5: Consider single threaded mode for shared UAR

libibmad/dump.c, libibmad/fields.c, libibmad/mad.h
Added support new speed 106.25
Added support for NDRFECModeSupported & NDRFECModeEnabled
Added support for IsLinkSpeedNDRSupported (PortInfo.CapabilityMask2)
Added support for other lost flags of PortInfo.CapabilityMask2
6: IsMKeyProtectBitsExtSupported
7: IsEnhancedTrap128Supported
8: IsPartitionTopSupported
9: IsEnhancedQoSArbiterSupported
=> ibdiag: Initial NDR support

librdmacm/cma.c
Some functions reports fixed ENOMEM when getting any failure, so
it's hard for user to know which actual error happens on them.
Fixes: 663098bfc3ac ("Rename librdmacm")
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>
=> librdmacm: Don't overwrite errno returned from libibverbs

libibverbs/man/ibv_alloc_parent_domain.3, libibverbs/verbs.h
Fix 'my' -> 'may' and 'referance' -> 'reference' typos in parent domain
documentation.
=> verbs: Fix a few typos in parent domain documentation

providers/efa/efa_io_defs.h, providers/hns/hns_roce_u.c, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h, providers/hns/hns_roce_u_verbs.c, providers/mlx5/bitmap.h, util/util.h
Add service type of Unreliable Datagram support for HIP09 by achieving Address Handle related interfaces and adding a branch in hns_roce_post_send().
=> libhns: Add support of UD for HIP09

tests/test_device.py
This change fixes two issues:
1. Avoid the failure of query_gid_table() by calculating the max_entries
for all ports when running the test over devices with multiple ports.
2. Avoid the failure of successfully queried non-existing gid index when
the gid_tbl_len=1, This happen because the possible_indices was wrongly
calculated to query the only exist gid over port one.
Fixes: cbb04cdfaff1 ("tests: Add query_gid_table and query_gid_ex bad flow")
=> tests: Fix test_query_gid_ex_bad_flow

providers/qedr/qelr_verbs.c
Report EINVAL when trying to call qelr_create_cq() with number of CQEs
bigger than the supported max_cqes, also fix the printed range.
Fixes: c0965e4fe6fe ("libqedr (qelr) verbs")
=> libqedr: Fix reported error code from create_cq

providers/cxgb4/verbs.c
Report EINVAL when trying to call c4iw_create_cq() with number of CQEs
out of the supported range.
Fixes: d6e6ae69be5e ("Add libcxgb4 files.")
=> cxgb4: Fix reported error code from create_cq

providers/efa/efa.h, providers/efa/efa_io_defs.h, providers/mlx5/cq.c, util/util.h
This commit matches the EFA_GET/SET() macros with their kernel
counterparts.
This change clears the mask before assigning the new value, and makes
use of FIELD_GET/PREP() which makes the various *_SHIFT definitions
redundant.
=> efa: EFA_GET/SET() fixes

libibverbs/man/ibv_bind_mw.3, libibverbs/man/ibv_create_cq_ex.3, libibverbs/man/ibv_modify_qp.3, libibverbs/man/ibv_poll_cq.3, libibverbs/man/ibv_post_send.3, libibverbs/man/ibv_query_qp.3
The type of some variables has been changed from int to
unsigned int thus update the corresponding documents.
Fixes: 8fe7f12f1723 ("verbs: Bitwise flag values should be unsigned")
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>
=> verbs: Update the type of some variables in documents

pyverbs/device.pyx
Prepare support for a new IB speed rate (NDR).
A translation was added to the active speed attribute.
=> pyverbs: Add a new active speed translation

libibverbs/man/ibv_create_qp.3, libibverbs/man/ibv_create_qp_ex.3
Fix copy/paste mistake.
Fixes: 9845a77c8812 ("Add remaining libibverbs manpages")
Fixes: 058c67977dad ("XRC man pages")
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>
=> verbs: Replace SQ with RQ in max_recv_sge's documents

tests/args_parser.py, tests/base.py, tests/test_addr.py, tests/test_device.py, tests/test_efadv.py, tests/test_qp.py
This PR adds the '--port' command line option that will be used to run the pyverbs on a specific device port, This is needed when there are multiple ports supported by one device, so the tests will run on the specified device port instead of on all of them.
=> tests: Port command line option

providers/bnxt_re/verbs.c
Report EINVAL when trying to call bnxt_re_create_cq() with number of CQEs
out of the supported range.
Fixes: fa8dce26b88c ("libbnxt_re: Add support for CQ and QP management")
=> bnxt_re: Fix reported error code from create_cq

redhat/rdma-core.spec
Depends on base package is useful for RDMA users. Unfortunately,
it will pull unwanted packages for Cloud or Edge users who may
don't have RDMA hardware.
=> redhat: Remove base package dependency from all sub-packages

CMakeLists.txt, debian/control, debian/libibverbs1.symbols, libibverbs/cmd_cq.c, libibverbs/driver.h, providers/efa/verbs.c, providers/mlx4/verbs.c, providers/mlx5/verbs.c, providers/rxe/rxe.c
Let kernel knows whether TS is required for a given CQ, this is done by choosing the
ibv_cmd_create_cq_ex() path from mlx5 in the general case.
In addition, a driver can mark whether to not fallback to the 'write EX' mode in case 'ioctl' create CQ is not supported, this is required only for mlx5.
=> verbs: Let kernel knows whether TS is required for a given CQ

srp_daemon/srp_daemon.service.in
remote-fs-pre.target is a passive target that is not loaded without someone
actively requiring it. Even is remote-fs.target is active.
This means that srp_daemon will not get started at boot
unless another service explicitely requires remote-fs-pre.target.
This solves the issue by having the srp_daemon service itself actively
asking for remote-fs-pre.target to be loaded.
Fixes: 08f689176497 (Revise systemd dependencies for all units)
=> srp_daemon: Fix systemd dependency

providers/mlx5/verbs.c
Fix uuars to have the 'uar_mmap_offset' data.
This enables an application to get this value directly on the created object (UAR / QP) instead of the need
to search for the matching parent UAR and take it from there.
=> mlx5: Fix uuars to have the 'uar_mmap_offset' data

pyverbs/libibverbs.pxd, pyverbs/libibverbs_enums.pxd, pyverbs/mr.pyx, pyverbs/pd.pxd, pyverbs/pd.pyx, pyverbs/utils.py, tests/test_mr.py
This series adds ibv_rereg_mr support to Pyverbs and adds multiple rereg MR tests.
It also includes the following changes:
- Removal of multiple MR tests that were basic sanity checks as they are already covered by other tests.
- Some MR tests were modified to run only over one device instead of running in a loop over all the rdma devices that exist.
=> tests: Add rereg MR tests

pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/test_mlx5_dc.py
This series adds the ability to query DC ODP caps and adds an mlx5 test that runs DC traffic with ODP.
=> tests: Add mlx5 ODP DC test

tests/test_mr.py, tests/test_qpex.py
The library was changed and now mlx5 doesn't print to stdout by
default, so those tests that were deleted can be retrieved back.
This reverts commit a48b9b172d8018c83f960f08d0e4bcce0e29fc2d.
=> tests: Retrieve tests that generates mlx5 CQE errors

providers/efa/verbs.c
When checking if the input length is bigger than the struct itself the
'efa_attr' pointer must be dereferenced, otherwise we will get the size
of the variable holding the pointer.
In addition, when making sure the extension is cleared, the pointer must
be casted to 'uint8_t *' first for proper pointer arithmetic.
Fixes: be808de2a19c ("efa: Verify DV input is cleared")
=> efa: Fix DV extension clear check

buildlib/pyverbs_functions.cmake, debian/libibverbs1.symbols, kernel-headers/rdma/ib_user_ioctl_cmds.h, libibverbs/CMakeLists.txt, libibverbs/cmd_mr.c, libibverbs/driver.h, libibverbs/dummy_ops.c, libibverbs/libibverbs.map.in, libibverbs/man/ibv_reg_mr.3, libibverbs/verbs.c, libibverbs/verbs.h, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/verbs.c, pyverbs/CMakeLists.txt, pyverbs/dmabuf.pxd, pyverbs/dmabuf.pyx, pyverbs/dmabuf_alloc.c, pyverbs/dmabuf_alloc.h, pyverbs/libibverbs.pxd, pyverbs/mr.pxd, pyverbs/mr.pyx, tests/args_parser.py, tests/test_mr.py, tests/utils.py
This is the user space counter-part of the kernel patch set to add 
dma-buf support to the RDMA subsystem. This patch series adds user 
space API for registering dma-buf based memory regions, updates 
pyverbs with the new API, and adds new tests. 
This series consists of six patches. The first patch updates the 
kernel headers for dma-buf support. Patch 2 adds the new API function 
and updates the man pages. Patch 3 implements the new API in the mlx5 
provider. Patch 4 adds new class definitions to pyverbs for the new API. 
Patch 5 adds a set of new tests for the new API. Patch 6 fixes bug in 
the utility code of the tests.
=> Add user space dmabuf support

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/buf.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_reserved_qpn_alloc.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, tests/CMakeLists.txt, tests/base_rdmacm.py, tests/rdmacm_utils.py, tests/test_mlx5_rdmacm.py, tests/test_rdmacm.py, tests/utils.py
This series exposes DV APIs to allocate/deallocate reserved QPNs over DEVX.
When working with RDMA-CM over TCP_PS and external QP support, a client node needs GUID level unique QP numbers to comply with the CM's timewait logic.
If a real unique QP is not allocated, a device global QPN value is required and can be allocated via this interface.
The mlx5 DCI QP is such an example.
The series includes also some pyverbs fixes and tests in the RDMA-CM area to use those new DV APIs.
=> mlx5: Expose DV APIs to allocate/deallocate reserved QPNs

debian/control
No changes are needed to support the new Debian policy version. See
https://www.debian.org/doc/debian-policy/ for details.
=> debian: Bump Standards-Version to 4.5.1

CMakeLists.txt, libibverbs/cmd_mr.c, libibverbs/verbs.c, pyverbs/CMakeLists.txt, pyverbs/dmabuf.pyx, pyverbs/dmabuf_alloc.c, pyverbs/dmabuf_alloc.h, pyverbs/dmabuf_alloc_stub.c, pyverbs/mr.pyx, tests/test_mr.py
This series fixes a few issues related to the dma-buf support. It consists
of three patches. The first patch fixes a compilation warning for 32-bit 
builds. Patch 2 renames a function parameter and expands an abbreviation.   
Patch 3 adds check for DRM headers.
=> Dma-buf related fixes

ibacm/src/acme.c, libibverbs/examples/devinfo.c
This series includes two fixes to prevent a possible port loop overflow when calling ibv_query_port().
=> verbs: Fix possible port loop overflow

suse/rdma-core.spec
Without the udev trigger, the node description does not get updated until the next reboot.
Fixes: f5b6677a311a (suse: trigger udev update in post install)
=> suse: trigger udev rules after installing rdma-ndd

suse/rdma-core.spec
Backport out of tree patches applied to SUSE spec
=> suse spec file resync

tests/base.py, tests/test_addr.py, tests/test_cq.py, tests/test_cqex.py, tests/test_device.py, tests/test_efadv.py, tests/test_mlx5_rdmacm.py, tests/test_mlx5_sched.py, tests/test_mr.py, tests/test_pd.py, tests/test_qp.py
Modify the base test classes (PyverbsAPITestCase and RDMATestCase) to statically pick one device by default, in case --dev was not passed.
Tests that were affected by the PyverbsAPITestCase change were modified accordingly to run over the selected device.
=> tests: Statically choose default device for tests

kernel-boot/rdma_rename.c
In function get_virtfn_info() we only compared the PCI function
number. That is not enough as we can match with wrong device.
This issue can be seen on systems with a large numbers of VFs.
Fix it by also comparing the PCI slot numbers.
Fixes: 72f852c72a78 ("kernel-boot: Separate PCI fill function")
Signed-off-by: Alaa Hleihel <alaa@nvidia.com>
Reviewed-by: Leon Romanovsky <leonro@nvidia.com>
=> kernel-boot: Fix VF lookup

libibnetdisc/ibnetdisc.c
Add protection for find port by lid in order to avoid
crash in case of getting nil item from lid2guid map.
=> ibnetdisc: Add protection for find port by lid

providers/hns/hns_roce_u.c, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
The RQ/SRQ of HIP08 needs one special sge to stop receive reliably. So the driver needs to allocate at least one SGE when creating RQ/SRQ and ensure that at least one SGE is filled with the special value during post_recv.
We should first get the SRQ's specification from kernel, and then adjust the value according to whether we need to reserve a recv SGE.
=> libhns: Allocate one more recv SGE for HIP08

debian/libibverbs1.symbols, libibverbs/CMakeLists.txt, libibverbs/libibverbs.map.in, libibverbs/man/CMakeLists.txt, libibverbs/man/ibv_is_fork_initialized.3.md, libibverbs/memory.c, libibverbs/verbs.h
Add ibv_is_fork_initialized verb which allows the app to query whether
fork support (ibv_fork_init) is enabled/disabled.
The verb returns an enum with the disabled/enabled value, and could
later be extended to return a "not required" value if in the future a call
to ibv_fork_init() will not be required.
Motivation and more information:
https://lists.openfabrics.org/pipermail/ofiwg/2020-October/001969.html
https://lists.openfabrics.org/pipermail/ofiwg/2020-October/001978.html
=> verbs: Introduce ibv_is_fork_initialized verb

debian/ibverbs-providers.symbols, kernel-headers/rdma/hns-abi.h, kernel-headers/rdma/mlx5_user_ioctl_cmds.h, kernel-headers/rdma/vmw_pvrdma-abi.h, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_devx_umem_reg.3.md, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c
This series exposes a DEVX API named mlx5dv_devx_umem_reg_ex() to let application controlling the required UMEM page size for the given registration.
=> mlx5: Expose a DEVX API to control UMEM page size

rdma-ndd/rdma-ndd.8.in, rdma-ndd/rdma-ndd.8.in.rst
rdma-core/rdma-ndd/rdma-ndd.c
296                 static const struct option long_opts[] = {
297                         { "foreground",   0, NULL, 'f' },
298                         { "systemd",      0, NULL, 's' },
299                         { "help",         0, NULL, 'h' },
300                         { "debug",        0, NULL, 'd' },
301                         { }
302                 };
=> rdma-ndd: fix 'debug' long opt in manpage

providers/hns/hns_roce_u_verbs.c
The memory of wqe_list will be freed in hns_roce_free_recv_inl_buf() if we
fail to allocate memory for sg_list in hns_roce_alloc_recv_inl_buf(). So
the codes to free wqe_list should be removed, or the pointer will be double
freed.
Fixes: 9a6132e4178a ("libhns: Package some lines for calculating qp buffer size")
=> libhns: Avoid double release of a pointer

Documentation/pyverbs.md, pyverbs/CMakeLists.txt, pyverbs/flow.pxd, pyverbs/flow.pyx, pyverbs/libibverbs.pxd, pyverbs/qp.pxd, pyverbs/qp.pyx, pyverbs/spec.pxd, pyverbs/spec.pyx, tests/CMakeLists.txt, tests/base.py, tests/test_flow.py, tests/utils.py
The series introduces ibv_flow support and tests.
Flow steering rules define packet matching done by the hardware.
Multiple matching specifications, that describe packet matching on a specific layer (L2, L3, etc.), were added, including extended IPv4, IPv6, Ethernet, TCP, and UDP.
Traffic tests were added to cover each one of the newly added specs.
=> pyverbs: Add flow steering support and tests

providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h
The width of tag field of normal doorbell should be 24 bits, and some other
fields of doorbell can be adjusted.
Fixes: 6fe30a1a705f ("libhns: Introduce QP operations referred to hip08 RoCE device")
=> libhns: Correct definition of DB_BYTE_4_TAG_M

rdma-ndd/rdma-ndd.c
After read the system hostname, the function `monitor` calls function
`set_rdma_node_desc` to initialize the node description for HCAs had
been detected by kernel.
For system with multiple InfiniBand HCAs, only the first HCA is
guaranteed to be detected by kernel at this point. The systemd udev
"add" event for the rest HCAs may be emitted before rdma-ndd listen
udev event via function `get_udev_fd`. That means the "add" event
will never be sent to rdma-ndd service, as rdma-ndd not ready for udev
even yet. So, the node description for those HCAs may not be updated
by rdma-ndd during system boot.
With this patch, rdma-ndd will initialize the node description after
it listen to udev. InfiniBand HCAs detected after the initialization
will be handled by udev even.
Reported-by: Georg Sauthoff …
=> rdma-ndd: fix udev racy issue for system with multiple InfiniBand HCAs

providers/hns/hns_roce_u_db.c, providers/hns/hns_roce_u_hw_v2.c
There is some redundant code in libhns, just remove it.
=> libhns: Remove some dead code

librdmacm/man/rdma_getaddrinfo.3
Return GAI-specific error codes to fix return value and errno.
If  `rdma_getaddrinfo`->`ucma_getaddrinfo()`->`getaddrinfo()` flow fails with an error, it returns some GAI-specific error and sets errno only if `EAI_SYSTEM` is a return value.
Align `rdma_getaddrinfo()` with `getaddrinfo()` to return more informative errors which can be handled by users appropriate and `gai_strerror()` can be used to get a human-readable string for a return value. If it fails due to some system error (e.g. memory allocation error), return `EAI_SYSTEM` and set a specific `errno` (e.g. `ENOMEM`) - introduce and use `GAI_ERR()` function.
Fix `rdma_getaddrinfo` man copying `EAI_*` return values description + minor fixes in `rdma_getaddrinfo` man.
=> Return GAI-specific error codes to fix return value and errno

librdmacm/cma.c
Fix `rdma_get_request()` function according to `rdma_get_request` man:
```
RETURN VALUE
Returns 0 on success, or -1 on error.  If an error occurs, errno will be set to indicate the failure reason.”
```
If event is `RDMA_CM_EVENT_REJECTED`, set `ECONNREFUSED` to errno.
If event's status is set to any value (i.e. a non-zero value), set errno to `-event->status`.
=> Set correct errno in rdma_get_request

CMakeLists.txt, pyverbs/dmabuf_alloc.c
Some vendor specific DRM headers may be missing on systems with old
kernels. Make sure that all headers needed by pyverbs/dmabuf_alloc.c
are present before enabling that module.
Remove unused reference of "radeon_drm.h" from pyverbs/dmabuf_alloc.c.
Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>
=> configure: Check the existence of all needed DRM headers

libibverbs/cmd_cq.c, tests/test_parent_domain.py
This series fixes the ibv_cmd_create_cq_ex() flow to support CQ creation with parent domain.
A matching pyverbs coverage was dropped by mistake sometimes ago, adding it back.
=> verbs: Fix CQ creation with parent domain

infiniband-diags/ibtracert.c
Change fdb data member in Switch structure to uint8_t instead of
int8_t in case we have 128 ports and up.
=> ibtracert: Change fdb data member in Switch structure to uint8_t

libibverbs/examples/devinfo.c
Print the number of completion vectors among the other information in
ibv_devinfo.
=> verbs: Print number of completion vectors in ibv_devinfo

MAINTAINERS, debian/control, debian/copyright
The email domain changed. The old email address still forwards to the new name (unsure how long).
=> Update my email address

tests/base.py, tests/test_flow.py, tests/test_mlx5_dc.py, tests/test_mlx5_lag_affinity.py, tests/test_parent_domain.py
Close device contexts of server/client (if they exist) in RDMATestCase's
tearDown() method.
Remove redundant tearDowns after this change.
Remove a previous tearDown duplicated method.
=> tests: Close device contexts in RDMATestCase tests

providers/hns/hns_roce_u.c
Add device ID for VF to support VF initialization.
Signed-off-by: Wei Xu <xuwei5@hisilicon.com>
=> libhns: Add RoCE VF device ID for HIP08

libibverbs/cmd_device.c, libibverbs/driver.h, libibverbs/ibdev_nl.c, libibverbs/man/ibv_query_device_ex.3, libibverbs/verbs.h, providers/mlx5/dr_dbg.c, providers/mlx5/dr_domain.c, providers/mlx5/mlx5dv_dr.h, pyverbs/device.pyx, pyverbs/libibverbs.pxd, tests/test_device.py, util/rdma_nl.c
This series adds a verbs API to retrieve IB device number of ports via netlink.
The new API is used by mlx5 in the DR area.
=> verbs: Add an API to retrieve IB device number of ports via netlink

infiniband-diags/ibroute.c
Change lft to unsigned uint8_t in dump_unicast_tables method instead
of char in case we have 128 ports and up.
=> ibtroute: Change lft to uint8_t in dump_unicast_tables method

CMakeLists.txt, buildlib/RDMA_EnableCStd.cmake
The gcc version 4.8.5 in Centos 7 fails to compile rdma-core with
the following error:
-- Performing Test HAVE_TARGET_SSE
-- Performing Test HAVE_TARGET_SSE - Failed
-- Performing Test NEED_MSSE_FLAG
-- Performing Test NEED_MSSE_FLAG - Failed
CMake Error at buildlib/RDMA_EnableCStd.cmake:128 (message):
Can not figure out how to turn on sse instructions for i386
Call Stack (most recent call first):
CMakeLists.txt:398 (RDMA_Check_SSE)
Instead of aborting the compilation, compile the library without that flag.
Fixes: bf343ecc783c ("buildlib: Use -msse if the compiler does not support target(sse)")
=> buildlib: Continue build on old GCC versions without SSE

tests/test_addr.py
To avoid the following failure when running test_addr over ib_qib,
make sure to set the dlid when the port is set to INFINIBAND.
```
ERROR: test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah.
File "/home/rdma-core/tests/test_addr.py", line 49, in test_create_ah
raise ex
File "/home/rdma-core/tests/test_addr.py", line 45, in test_create_ah
AH(pd, attr=ah_attr)
File "addr.pyx", line 410, in pyverbs.addr.AH.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to create AH. Errno: 22, Invalid argument
```
=> tests: Make sure to set dlid when creating AH

tests/test_rdmacm.py
To avoid the following failure when running test_rdmacm over ib_qib,
make sure to set the port_space to RDMA_PS_IPOIB when the port is set to
INFINIBAND.
```
ERROR: test_rdmacm_async_ex_multicast_traffic (tests.test_rdmacm.CMTestCase)
File "/home/rdma-core/tests/utils.py", line 912, in inner
return func(instance)
File "/home/rdma-core/tests/test_rdmacm.py", line 181, in test_rdmacm_async_ex_multicast_traffic
self.two_nodes_rdmacm_traffic(CMAsyncConnection,
File "/home/rdma-core/tests/test_rdmacm.py", line 88, in two_nodes_rdmacm_traffic
raise(res)
threading.BrokenBarrierError
```
Signed-off-by: Kamal Heib …
=> tests: Set port_space based on link_layer

providers/mlx5/qp.c
- fixed typo in _common_wqe_finalize function name
Signed-off-by: Sergey Oblomov <sergeyo@nvidia.com>
=> Fixed typo in _common_wqe_finalize

providers/efa/verbs.c
The query device response struct must be cleared before passing it to
the kernel ioctl call. Otherwise, old drivers that do not fill the
entire response would cause the userspace to read uninitialized data.
Fixes: c95038eb598f ("efa: Move the context initialization out of efa_query_device_ex()")
=> efa: Fix use of uninitialized query device response

CMakeLists.txt, infiniband-diags/CMakeLists.txt
The rdma-core doesn't really need anything specific from 2.8.11, so
simply raise the minimal level to be 2.8.12 and silence the warning
below.
CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
=> cmake: Bump minimal cmake version

kernel-headers/rdma/rdma_netlink.h, libibverbs/ibdev_nl.c, libibverbs/man/ibv_is_fork_initialized.3.md, libibverbs/memory.c, util/rdma_nl.c, util/rdma_nl.h
Followup from #883, this series identifies kernel with copy-on-fork support and reports that through the recently introduced ibv_is_fork_initialized() verb.
Kernel submission:
v1: https://lore.kernel.org/linux-rdma/20210405114722.98904-1-galpress@amazon.com/
v2: https://lore.kernel.org/linux-rdma/20210407101606.80737-1-galpress@amazon.com/
v3: https://lore.kernel.org/linux-rdma/20210412064150.40064-1-galpress@amazon.com/
v4: https://lore.kernel.org/linux-rdma/20210418121025.66849-1-galpress@amazon.com/
=> Report when ibv_fork_init() is not needed

providers/mlx5/mlx5.c, providers/mlx5/verbs.c, pyverbs/device.pyx, pyverbs/libibverbs.pxd, pyverbs/libibverbs_enums.pxd, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, tests/CMakeLists.txt, tests/test_mlx5_timestamp.py
The series adds Pyverbs support for timestamp of mlx5 devices (both nanoseconds and real-time values).
The tests include traffic and basic timestamp verification.
Two minor fixes were added to the beginning of the series.
=> pyverbs/mlx5: Add timestamp support and tests

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_map_ah_to_qp.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, tests/test_mlx5_dc.py
This series exposes a DV API to enable mapping the destination path information in address handle (AH) to the information extracted from the QP.
This enables DC/UD QPs to use multiple CC algorithms in the same data center.
=> mlx5: Add a DV API to map between AH to QP

providers/mlx5/dr_action.c, providers/mlx5/dr_dbg.c, providers/mlx5/dr_devx.c, providers/mlx5/dr_domain.c, providers/mlx5/dr_icm_pool.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_rule.c, providers/mlx5/dr_send.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste.h, providers/mlx5/dr_ste_v0.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/dr_table.c, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv_dr.h
This series adds definers support in the DR area.
Definers are FW/HW objects created over DEVX, the definer ID is used inside each steering entry based on the mask.
Definers allow to optimize PPS by matching on multiple fields compared to regular hash table entries. 
Definer creation and selection is done inside the DR code if supported without any special configuration from
the user.
Current definers cover a variety of common use cases such as ipv4 5tuple and ipvs6 5tuple as well as other customer use cases.
This feature is supported from ConnectX6-DX devices.
=> mlx5: DR, Add definers support

libibverbs/man/ibv_fork_init.3.md
It was not clear to me from the man page that ibv_fork_init actually
has a detection if memory was already registered before calling this
function. I guess EINVAL might be most likely reason why
ibv_fork_init might fail and it also can be used to give a program
failure reason to the end user.
Signed-off-by: Bernd Schubert <bschubert@ddn.com>
=> man page: Document EINVAL meaning for ibv_fork_init()

debian/ibverbs-providers.symbols, providers/mlx5/dr_domain.c, providers/mlx5/dr_rule.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h
Add support to allow or prevent insertion of duplicate rules, this enables user to choose one behavior from:
- Detect already existing rule and fail.
- Allow it, which enables to update the rule's action, but this will take affect once the previous rule will be deleted.
By default duplicate rules are allowed.
=> mlx5: DR, Support ability to allow/prevent duplicate rules

tests/test_qpex.py
The patch fixes two bugs: creating a QP without RDMA Write access, and
creating a MR without MW Bind access.
=> tests: Fix QP extended MW bind test

debian/libibverbs1.symbols, libibverbs/CMakeLists.txt, libibverbs/driver.h, libibverbs/dummy_ops.c, libibverbs/libibverbs.map.in, libibverbs/man/CMakeLists.txt, libibverbs/man/ibv_query_qp_data_in_order.3.md, libibverbs/verbs.c, libibverbs/verbs.h, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/verbs.c, pyverbs/libibverbs.pxd, pyverbs/qp.pyx, tests/test_qp.py
This series Introduces ibv_query_qp_data_in_order() API.
This enables an application to check whether WQE data is guaranteed to be written in-order on the given QP and thus reader may poll for data instead of poll for completion.
The API was implemented by mlx5 driver over DEVX.
A detailed man page and some pyverbs stuff were added as well.
=> verbs: Introduce ibv_query_qp_data_in_order() API

pyverbs/CMakeLists.txt, pyverbs/fork.pyx, pyverbs/libibverbs.pxd, pyverbs/libibverbs_enums.pxd, tests/CMakeLists.txt, tests/test_fork.py
This PR adds basic fork unit testing by calling ibv_fork_init() and ibv_is_fork_initialized().
The fork tests are impacted by the order of tests execution, for example, if a previous test has registered an MR then ibv_fork_init() is expected to fail. If only the fork tests are run, it should succeed.
=> Pyverbs fork tests

kernel-headers/rdma/rdma_user_rxe.h, providers/rxe/rxe.c
From 7a6feeb37a9816497b8c59905d7d46979262cc57 Mon Sep 17 00:00:00 2001
From: Bob Pearson <rpearsonhpe@gmail.com>
Date: Thu, 17 Jun 2021 23:16:51 -0500
Subject: [PATCH v3 0/2] Implement memory windows support for rxe
These patches makes the required changes to the rxe provider and the
rxe ABI to support the kernel memory windows patches to the rxe driver.
The kernel patches are accepted upstream in linux-rdma for-next.
Signed-off-by: Bob Pearson <rpearsonhpe@gmail.com>
---
Bob Pearson (2):
Update kernel headers
Providers/rxe: Implement memory windows
kernel-headers/rdma/rdma_user_rxe.h |  10 ++
providers/rxe/rxe.c                 | 199 +++++++++++++++++++++++-----
2 files changed, 175 insertions(+), 34 deletions(-)
=> Rxe Implement Memory Windows

libibverbs/man/ibv_poll_cq.3, libibverbs/verbs.h, providers/mlx5/cq.c, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_wr_post.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, pyverbs/libibverbs_enums.pxd, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/CMakeLists.txt, tests/test_mlx5_raw_wqe.py
Introduce mlx5dv_wr_raw_wqe builder to be used for building a raw work request.
The user needs to set the raw WQE according to mlx5 device specification, the driver internally may override some fields which are state related. 
The work completion opcode for a raw WQE will be IBV_WC_DRIVER2 that was added for a specific driver operation. 
Man pages were updated with the expected usage accordingly.
The series includes also some pyverbs stuff to test this functionality.
=> mlx5: Introduce mlx5dv_wr_raw_wqe builder

debian/ibverbs-providers.symbols, kernel-headers/rdma/mlx5-abi.h, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_create_qp.3.md, providers/mlx5/man/mlx5dv_dci_stream_id_reset.3.md, providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/man/mlx5dv_wr_post.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, providers/mlx5/verbs.c, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/mlx5_base.py, tests/test_mlx5_dc.py, tests/utils.py
This series adds DCS offload support by exposing some DV API stuff.
DCS is an offload to SW load balancing of DC initiator work requests.
A single DCI can be connected to only one target at the time and can't start a new connection until the previous work request is completed. This limitation will cause a delay when the initiator process needs to transfer data to multiple targets at the same time.
The SW solution is to use a process that handling and spreading the work request on many DCIs according to destinations.
This feature is an offload to this process and coming to reduce the load from the CPU and improve the performance.
Detailed man pages were added, the series includes also some pyverbs stuff which tests the functionality.
=> mlx5: Add DCS offload support

util/udma_barrier.h
Add barriers support for LoongArch architecture(a new RISC architecture).
=> util: Add barriers support for LoongArch

Documentation/libibverbs.md, buildlib/RDMA_BuildType.cmake, libibverbs/driver.h, libibverbs/init.c, libibverbs/libibverbs.map.in, providers/efa/efa.c, providers/efa/verbs.c, providers/hns/hns_roce_u_hw_v1.c, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c, providers/siw/siw.c
This PR adds a generic logging API to libibverbs and its providers controlled by a new environment variable VERBS_LOG_LEVEL.
This PR demonstrates the API usage by the EFA provider, other providers (mlx5, hns for ex.) can be converted to make use of it as well.
=> Verbs logging API

tests/base.py
The args list is missing the fifth MAC element which results in an
IndexError exception.
ERROR: test_qp_ex_srd_old_send (tests.test_efa_srd.QPSRDTestCase)
File "/home/ec2-user/rdma-core/tests/test_efa_srd.py", line 18, in setUp
super().setUp()
File "/home/ec2-user/rdma-core/tests/efa_base.py", line 42, in setUp
super().setUp()
File "/home/ec2-user/rdma-core/tests/base.py", line 216, in setUp
self._select_config()
File "/home/ec2-user/rdma-core/tests/base.py", line 269, in _select_config
self.mac_addr = args[4]
IndexError: list index out of range
Fixes: db19c366f123 ("tests: Add MAC address to the tests' args") …
=> tests: Add missing MAC element to args list

providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/db.c, providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c
The main focus of this patch series is to move SQ and RQ
wqe posting indices from 128B fixed stride to 16B aligned stride.
This allows more flexibility in choosing wqe size.
This is a re-submission of patch series posted in the pull request 
https://github.com/linux-rdma/rdma-core/pull/1007
=> bnxt_re library update

tests/test_qpex.py
The exception must be raised again to avoid the fall-through to the
rest of the test.
Additionally, the "if" statement checking for EOPNOTSUPP was not
properly aligned.
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>
We had a case where `ibv_reg_mr(3)` was failing, but the error reported by the test suite was confusing as the test ignored the exception being thrown:
```console
$ ./build/bin/run_tests.py -v -k test_qp_ex
[...]
ERROR: test_qp_ex_rc_atomic_cmp_swp (tests.test_qpex.QpExTestCase)
File "/workspace/rdma-core/tests/test_qpex.py", line 243, in test_qp_ex_rc_atomic_cmp_swp
client, server = …
```
=> tests: Fix exception handling in QpExTestCase

libibverbs/man/ibv_poll_cq.3, libibverbs/verbs.h, providers/mlx5/cq.c, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/man/mlx5dv_wr_post.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, providers/mlx5/verbs.c, providers/mlx5/wqe.h, pyverbs/libibverbs_enums.pxd, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/CMakeLists.txt, tests/base.py, tests/mlx5_base.py, tests/test_mlx5_dma_memcpy.py, tests/test_mlx5_raw_wqe.py, tests/utils.py
This series Introduces mlx5dv_wr_memcpy builder to be used for building a DMA memcpy request.
DMA memcpy is one of several Memory to Memory Offloads (MMO) available from BlueField-2 onwards.
It utilizes the GGA modules on the DPU to perform DMA memcpy, thus improving performance.
The series includes a detailed man page for the expected usage and pyverbs stuff over the new functionality.
=> mlx5: Introduce mlx5dv_wr_memcpy builder

debian/ibverbs-providers.symbols, providers/mlx5/dr_dbg.c, providers/mlx5/dr_domain.c, providers/mlx5/dr_icm_pool.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_rule.c, providers/mlx5/dr_send.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste_v0.c, providers/mlx5/dr_table.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h
This series enhanced the DR support in few area as of below.
- It includes some bug fixes and cleanups.
- Introduce a new DV API to control the DR matcher layout.
- Add multi-queues support for post sending rules, this is applicable when matcher layout is set to non-resizable.
- Improve locking scheme in few places to enable adding rules in parallel.
=> mlx5: DR, Enhance support in few areas

providers/mlx5/mlx5_vfio.c, providers/mlx5/qp.c, providers/mlx5/verbs.c
Fix some compilation issues as of below on 32 bit systems with gcc 7.5.
error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
=> mlx5: Fix compilation on 32 bit systems with gcc 7.5

README.md
Include instructions for using dnf builddep, missed irdma change and
mention Centos 8 which is similar to Fedora.
Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
=> README: Modernize some of the readme text

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/dr_action.c, providers/mlx5/dr_dbg.c, providers/mlx5/dr_devx.c, providers/mlx5/dr_domain.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_rule.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste_v0.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/dr_vports.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h
This series enhances the DR support in few areas as of below. 
- Query vports dynamically to support SFs.
- Support ECPF vport.
- Add destination IB port action.
- Extend misc4 flex parsers support.
=> mlx5: DR, Enhance the support in few areas

redhat/rdma-core.spec
%{_libdir}/ibacm/libibacmp.so is a plugin for librdmacm dlopen.
It is not for library linking.
=> redhat: rdma-core-devel should not require ibacm

debian/ibverbs-providers.symbols, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_create_mkey.3.md, providers/mlx5/man/mlx5dv_crypto_login.3.md, providers/mlx5/man/mlx5dv_dek_create.3.md, providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/man/mlx5dv_wr_mkey_configure.3.md, providers/mlx5/man/mlx5dv_wr_set_mkey_crypto.3.md, providers/mlx5/man/mlx5dv_wr_set_mkey_sig_block.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, providers/mlx5/verbs.c, providers/mlx5/wqe.h, pyverbs/pd.pxd, pyverbs/pd.pyx, pyverbs/providers/mlx5/CMakeLists.txt, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_crypto.pxd, pyverbs/providers/mlx5/mlx5dv_crypto.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/CMakeLists.txt, tests/test_mlx5_crypto.py
This series exposes some DV APIs to enable configuring and using MKEY with crypto offloads.
With this, the device can encrypt/decrypt data when transmitting data from memory to network and when receiving data from network to memory. 
Crypto properties can be configured along with signature properties.
Detailed man pages were added to describe the expected usage and flow.
In addition, the series includes some pyverbs testing over the new functionality.
=> mlx5: Add DV APIs to support MKEY with crypto offloads

debian/control
No changes are needed to support the new Debian policy version. See https://www.debian.org/doc/debian-policy/ for details.
The library packages do not contain any maintainer scripts and for any pair of architectures, the common files have equal content. Thus it should be safe to mark the package `Multi-Arch: same`.
=> debian: Bump Standards-Version to 4.6.0 and mark libraries as Multi-Arch: same

tests/CMakeLists.txt, tests/base.py, tests/base_rdmacm.py, tests/test_atomic.py, tests/test_qpex.py, tests/utils.py
Add new atomic traffic tests to cover multiple atomic flows.
The tests cover both FETCH_AND_ADD and CMP_AND_SWP opcodes including
data validation and some bad flows.
=> tests: Add atomic traffic tests

libibverbs/examples/devinfo.c
The print_all_port_gids() return value was not assigned to the rc
variable, hence it did not propagate the error in the cleanup flow and
return success in case of an error.
=> libibverbs/examples: Fix gid query silent error in devinfo

providers/irdma/uk.c
Remove optimization algorithm for QP doorbell, because
without an mfence the algorithm incorrectly skips ringing
the doorbell. This causes applicaitons like OpenMPI with
high number of connections to stall waiting for completion.
Enforcing the order of the write of the WQE valid bit
and the read of the SQ tail is required by the algorithm,
but furher investigation is necessary because this does not
appear sufficient for the algorithm to work. In the meantime,
remove the doorbell optimization and fix the MPI failures.
=> irdma: Remove optimization algorithm for QP doorbell

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/dr_action.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_rule.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste.h, providers/mlx5/dr_ste_v0.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/dr_vports.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h
This series extends the DR support in few areas as of below.
- Add support for definer 33.
- Add support for ASO CT cross domain.
In addition, it includes two fixes from the team.
=> mlx5: DR, Extend support in few areas

providers/efa/efa.c, providers/efa/verbs.c, providers/efa/verbs.h
Add support for ibv_reg_dmabuf_mr verb to the EFA provider.
Signed-off-by: Gal Pressman <gal.pressman@linux.dev>
=> efa: Add support for ibv_reg_dmabuf_mr

pyverbs/device.pxd, pyverbs/device.pyx, pyverbs/providers/mlx5/dr_action.pxd, pyverbs/providers/mlx5/dr_action.pyx, pyverbs/providers/mlx5/dr_domain.pxd, pyverbs/providers/mlx5/dr_domain.pyx, pyverbs/providers/mlx5/dr_matcher.pyx, pyverbs/providers/mlx5/dr_table.pxd, pyverbs/providers/mlx5/dr_table.pyx, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, pyverbs/providers/mlx5/mlx5dv_flow.pyx, tests/args_parser.py, tests/base.py, tests/mlx5_prm_structs.py, tests/test_mlx5_dr.py, tests/test_mlx5_flow.py, tests/test_mlx5_mkey.py, tests/utils.py
This series adds support for almost all the missing mlx5 direct rules (mlx5_dr) APIs in Pyverbs, as well as extends and adds more tests to cover the newly added domains, actions, matchers and rules.
=> tests: Add coverage for mlx5 dr steering

providers/hns/hns_roce_u_db.h, providers/hns/hns_roce_u_hw_v1.c, providers/hns/hns_roce_u_hw_v2.c
The DB data is a __le32[] value instead of uint32_t[], and the DB register
should be written with a little-endian data instead of uint64_t.
Fixes: 1523fbb1ea8e ("libhns: Add verbs of cq support")
Signed-off-by: Yixing Liu <liuyixing1@huawei.com>
=> libhns: Fix wrong data type when writing doorbell

libibverbs/man/ibv_query_device_ex.3, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/man/mlx5dv_wr_mkey_configure.3.md, providers/mlx5/verbs.c, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_flow.pyx
The word `concurrent` is misspelled in several places (including structs and variables). Fix the spelling mistake in the comment and text output. Fixing `concurrent` in the structs and variables should be done separately.
The expression "allow(s) to" is not correct. It must be either "allow(s) doing" or "allow(s) one to".
=> Fix spelling mistake

providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h
Mainly about:
1. Separate the differences between various objects (such as sq, rq, srq)
into functions.
2. Optimize function names, variable names, and comments to increase code
readability.
3. Use map instead of switch branch to simplify the code.
Signed-off-by: Yixian Liu <liuyixian@huawei.com>
Signed-off-by: Yangyang Li <liyangyang20@huawei.com>
Signed-off-by: Xinhao Liu <liuxinhao5@hisilicon.com>
=> libhns: Refactor the poll one interface

providers/hns/hns_roce_u.h
The compiler will check whether the modifiers of the function are of the
correct type.
=> libhns: hr_ilog32() should be represented by a function instead of a macro

libibverbs/cmd_qp.c
This fix sets the srq field in ibv_qp_init_attr, which wasn't being
copied into ibv_qp_init_attr_ex, causing kernel drivers to not get
the srq field in the create QP path.
Fixes: 74af92ae ("ibverbs: Don't memcpy padding in ibv_qp_init_attr")
=> ibverbs: Fix missing copy for srq field in ibv_cmd_create_qp

providers/hns/hns_roce_u_hw_v2.c
The size of CQE is different for different versions of hardware, so the
driver needs to specify the size of CQE explicitly.
Fixes: 3546e6b69ac8 ("libhns: Add support for CQE in size of 64 Bytes")
=> libhns: Fix the size setting error when copying CQE in clean cq()

providers/hns/hns_roce_u_verbs.c
XRC QP does not require RQ, so RQ should not be created.
Fixes: 4ed874a5cf30 ("libhns: Add support for XRC for HIP09")
=> libhns: Fix the problem that XRC does not need to create RQ

infiniband-diags/ibsysstat.c
increase maximum number of CPUs may result too much cpu info
Fixes: c381cfa26 ("ibdiags: Increase maximum number of CPUs")
Signed-off-by: Suwan Sun <swimlessbird@gmail.com>
Signed-off-by: Ying Lu <luying_hhu@163.com>
=> ibdiags: fix small buffer

providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h
ULP can get more error information of CQ though verbs.
=> libhns: Add vendor_err information for error WC

providers/hns/hns_roce_u_hw_v2.c
When a non-inline WR reuses a WQE that was used for inline the last time,
the remaining inline flag should be cleared.
Fixes: cbdf5e32a855 ("libhns: Reimplement verbs of post_send and post_recv for hip08 RoCE")
Fixes: 82fc508a6625 ("libhns: Add support for UD inline")
=> libhns: Forcibly rewrite the inline flag of WQE

tests/test_qp.py
The QP state is queried using IBV_QP_STATE, so make sure to compare the
"qp_state" attribute instaed of "cur_qp_state"
Fixes: 79f6e8ee2920 ("tests: Correct query QP attributes")
=> tests: Fix QP state verification

librdmacm/examples/mckey.c, librdmacm/man/mckey.1
The rdma_create_qp createflags option IBV_QP_CREATE_BLOCK_SELF_MCAST_LB
should prevent multicast loopback. However, this feature seems to be
broken on a lot of RDMA NICs and there is no way to test this with the
existing RDMA tools. So add an option to mckey in order to allow to send
multicast messages without loopback. mckey's default has been and will
continue to be to loopback all multicast messages.
Loopback of multicast messages can have surprising effects because all
messages sent out also have to be processed locally by all members of
the multicast group. This usually also includes the sender.
In order to test multicast loop execute the following in two windows
on a host connected to an RDMA fabric.
First session (Receiver)
mckey -b <RDMA IP address> -m239.1.2.1
Second session …
=> rdma-core: Add support for multicast loopback prevention to mckey

providers/qedr/qelr_verbs.c
Make sure to verify the comp_mask before trying to create QP.
Fixes: cae4a99ae679 ("libqedr: add support for XRC-SRQ's.")
=> libqedr: Verify the comp_mask before create qp

providers/hns/hns_roce_u_hw_v2.c
The Local Invalid operation sets so flag, otherwise clears so flag.
Fixes: a9ae7e9bfb5d ("libhns: Add local invalidate MR support for hip08")
=> libhns: Forcibly rewrite the strong-order flag of WQE

providers/rxe/rxe-abi.h, providers/rxe/rxe.c, providers/rxe/rxe.h
From acb5adec594851bde7f2efa0654c3c815e0cab6b Mon Sep 17 00:00:00 2001
From: Bob Pearson <rpearsonhpe@gmail.com>
Date: Thu, 24 Jun 2021 15:29:04 -0500
Subject: [PATCH v2 0/2] Providers/rxe: Replace AV by AH for UD sends
These patches contains the changes to the rxe provider to match the
kernel patch series with a similar name.
v2:
As suggested by Jason Gunthorp moved the AV struct out of rxe_send_wqe
and into rxe_wr in the ud struct in the wr union at the original offset.
This maintains ABI compatibility with old kernels or rdma-core but
simplifies the code.
Bob Pearson (2):
Update kernel headers
Providers/rxe: Replace AV by AH for UD sends
kernel-headers/rdma/rdma_user_rxe.h |  16 +++-
providers/rxe/rxe-abi.h             |   2 +
providers/rxe/rxe.c                 | 117 …
=> rxe AV object support

providers/irdma/user.h, providers/irdma/uverbs.c
Return specific WC errors for certain type of error
events as opposed to a generic IBV_WC_FATAL_ERR.
In particular,
Return IBV_WC_MW_BIND_ERR for memory window
related asynchronous events.
Return IBV_WC_RETRY_EXC_ERR when transport retry
counter is exceeded.
Fixes: 14a0fc824f16 ("rdma-core/irdma: Implement device supported verb APIs")
=> providers/irdma: Report correct WC errors

debian/ibverbs-providers.maintscript
i40iw provider was removed and replaced by irdma provider. Remove the
obsolete conffile.
Fixes the following warning:
libibverbs: Warning: couldn't load driver 'libi40iw-rdmav34.so':
libi40iw-rdmav34.so: cannot open shared object file: No such file or
directory
Fixes: dbbd9dcd ("rdma-core/i40iw: Remove provider i40iw")
---
The second argument (`prior-version`) for `rm_conffile` is intentionally left empty because I'm not sure what to do here. There are already two major releases with this issue.
This also raises the question of why uninstallation is not removing all created conffiles?
Thanks,
Firas
=> debian: Remove i40iw provider conffile

providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
HIP09 set a new BAR space for SQ doorbell. Each SQ doorbell has an
independent BAR space and the size is 64KB. SQ doorbell share
the same BAR space with direct WQE.
Signed-off-by: Yixing Liu <liuyixing1@huawei.com>
=> libhns: Use new SQ doorbell register for HIP09

util/mmio.h
The below commit added a new implementation of mmio_memcpy_x64() for
ARM which was broken. The destination buffer must be advanced so we
don't copy to the same 64 bytes.
Fixes: 159933c37 ("libhns: Add support for direct wqe")
=> util: Fix mmio memcpy on ARM

librdmacm/rsocket.c
Application requires that nonblocking accept calls progress without
application intervention, similar to the connect calls.
So reuse existing connect_svc, add new rsocket returned by rs_accept()
to the connect_svc. Because connect service monitors the rsocket continuously,
so cm event such like RDMA_CM_EVENT_DISCONNECTED can be handled during
rsocket being polled in rpoll. This prevent server's acceptor be waiting
for new msg on rsocket after client exist without executing rclose/rshutdown.
For more informations about connect_svc addition and cleanup, see: 659c4f9
Signed-off-by: raygift <bgtickt@gmail>.com
=> rsocket: fix raccept can't handle disconnected cm event 

libibverbs/man/ibv_advise_mr.3.md
According to the linux kernel implementation by mlx5[1], EINVAL will be
returned in the case the avdice is IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE but
the specified MR in the scatter gather list is not registered as writable
access.
[1]: https://elixir.bootlin.com/linux/v5.13.11/source/drivers/infiniband/hw/mlx5/odp.c#L1719
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
=> man page: Fix return value for ibv_advise_mr()

providers/bnxt_re/verbs.c
For work requests with inline data, the WQE size is not calculated
correctly. Fix this by calling bnxt_re_get_sqe_hdr_sz to get the correct
WQE header size.
Fixes: 66aba73d4a7a ("bnxt_re/lib: Move hardware queue to 16B aligned indices")
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
=> bnxt_re/lib: Fix the Send WQE size calulation for inline data

providers/mlx5/qp.c, tests/test_mlx5_raw_wqe.py
Fix to prevent unexpected WC opcode when RAW WQE is used.
In addition, add some pyverbs patch to cover the problematic scenario.
=> mlx5: Fix to prevent unexpected WC opcode 

providers/bnxt_re/verbs.c
qp->jrqq can be NULL in SRQ case or when accessed from error path.
Avoid segfault by adding check before accessing qp->jrqq and qp->jsqq.
Fixes: f92837e29fd4 ("bnxt_re/lib: consolidate hwque and swque in common structure")
Signed-off-by: Selvin Xavier <selvin.xavier@broadcom.com>
=> bnxt_re/lib: Check pointer validity while freeing queue pointers

libibverbs/man/ibv_create_cq_ex.3, libibverbs/man/ibv_wr_post.3.md, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c
The first two bugfixes are about the hns driver, the remaining bugfixes are
about the verbs manual.
Wenpeng Liang (3):
libhns: Fix out-of-bounds write when filling inline data into extended
sge space
libhns: Fix wrong HIP08 version macro
verbs: Fix a typo
Xinhao Liu (1):
verbs: Fix description of manual for ibv_wc_read_byte_len function
libibverbs/man/ibv_create_cq_ex.3 |  2 +-
libibverbs/man/ibv_wr_post.3.md   |  4 ++--
providers/hns/hns_roce_u.h        |  3 +--
providers/hns/hns_roce_u_hw_v2.c  | 40 +++++++++++++++++++++----------
4 files changed, 32 insertions(+), 17 deletions(-)
=> Miscellaneous bugfixes

libibverbs/verbs.h, providers/hns/hns_roce_u_verbs.c, providers/irdma/uverbs.c, providers/mlx5/qp.c, providers/rxe/rxe.c
Check for a non null MR, address and length
before allowing bind operation.
Also, add check to make sure the MR and MW are in
same PD before posting a bind MW op.
Fixes: 14a0fc824f16 ("rdma-core/irdma: Implement device supported verb APIs")
=> providers/irdma: Validate input before memory window bind

debian/changelog, debian/copyright, debian/ibacm.lintian-overrides, debian/infiniband-diags.lintian-overrides, debian/rdma-core.lintian-overrides, debian/srptools.lintian-overrides
Import the changes from the Debian upload 39.0-1:
* Update year in copyright
* Update overrides for lintian 2.114
* Override obsolete-command-in-modprobe.d-file lintian error
* Override spare-manual-page lintian complaint
* Add Debian uploads up to version 39.0-1
=> Changes from Debian upload 39.0-1

redhat/rdma-core.spec
Backport commit 12e8ad3d89ac for redhat specific spec file to fix
broken pkgconf files.
Fixes: 3888efcdfbce ("redhat: copy stock spec for RH customization")
=> redhat: fix CMake flags

libibverbs/neigh.c
`__THROW` is a glibc-internal macro, as indicated by the
preceding double underscore. The absence of this macro breaks
builds on musl.
Bug: https://bugs.gentoo.org/828894
=> Do not use `__THROW` in prototypes

libibverbs/init.c, util/util.c, util/util.h
Prior to this change, setting some of the variables to "0" would be confusingly interpreted as enabling the feature.
=> libibverbs: consistently parse environment variables in ibverbs_init

buildlib/rdma_functions.cmake
In cmake, there are only LINK_PRIVATE and LINK_PUBLIC options (no LINK).
This patch fixes cmake link property (LINK_PRIVATE) for static library.
See:
https://cmake.org/cmake/help/latest/command/target_link_libraries.html
Signed-off-by: Wonsup Yoon <pusnow@kaist.ac.kr>
=> cmake: Fix cmake link property for static library

CMakeLists.txt, buildlib/RDMA_Sparse.cmake, buildlib/rdma_functions.cmake, buildlib/rdma_man.cmake, kernel-headers/CMakeLists.txt
When using rdma-core via cmake's add_subdirectory, CMAKE_SOURCE_DIR
points project's root directory, and build fails. This patch replaces
CMAKE_SOURCE_DIR with PROJECT_SOURCE_DIR. It enables builing rdma-core
via add_subdirectory.
Signed-off-by: Wonsup Yoon <pusnow@kaist.ac.kr>
=> cmake: Use PROJECT_SOURCE_DIR in cmake

pyverbs/cmid.pyx, pyverbs/cq.pyx, pyverbs/qp.pyx, tests/test_efa_srd.py, tests/test_qpex.py, tests/utils.py
This series adds various error flow tests on post send/receive operations, and adds instances of these tests for UD and SRD.
=> tests: Add tests for various error flows

CMakeLists.txt, srp_daemon/CMakeLists.txt, srp_daemon/srp_daemon.rules, srp_daemon/srp_daemon.rules.in, srp_daemon/start_on_all_ports.in
While debian uses /bin/systemctl, SUSE only supports /usr/bin/systemctl,
causing srp_daemon to fail silently starting on all ports.
Detect at built which path is the right one and use it.
Fixes: b03beb142e0d ("srp_daemon: Call systemctl properly from udev")
=> srp_daemon: Detect proper path to systemctl

providers/rxe/rxe.c
Recent test case additions in tests/test_qpex.py surfaced three
API errors in rxe.c for post_recv. Two errors were returned with
the wrong sign and an immediate error was not returned if the qp
was in the reset state. This patch fixes these errors.
Signed-off-by: Bob Pearson <rpearsonhpe@gmail.com>
=> Providers/rxe: Fix bugs in rxe_post_recv

CMakeLists.txt, buildlib/fixup-include/sys-auxv.h, util/CMakeLists.txt, util/mmio.c, util/mmio.h, util/s390_mmio_insn.h, util/udma_barrier.h
Hi All,
In the existing MMIO implementation s390 relies on special syscalls to
access PCI memory. This was necessary as s390 originally only had
special privileged instructions for accessing PCI memory. With z15
however comes support for 4 new PCI memory I/O (MIO) instructions which
operate on virtually mapped PCI memory spaces.
While these are still special PCI access instructions instead of real
MMIO they behave much more like standard MMIO access. There is a load
like instruction _pcilgi_, a store like instruction _pcistgi_ a block store
variant for efficient memcpy _pcistbi_ and a write barrier instruction
_pciwb_. The load and store variants always operate on a 64 bit register
but only load/store the right most  bytes of the register controlled by
a length value in a paired register …
=> Exploit s390's new and enhanced PCI memory I/O (MIO) instructions

providers/mlx5/mlx5.c
Add the upcoming BlueField-4 and ConnectX-8 device IDs.
=> mlx5: Update the list of the PCI supported devices

providers/hns/hns_roce_u.c, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_abi.h, providers/hns/hns_roce_u_hw_v1.c, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h, providers/hns/hns_roce_u_verbs.c
Support for creating an extended CQ using ibv_create_cq_ex(). Support
extended CQ to use the new polling mechanism provided by ofed. The last two
patches refactor of the polling function.
=> Add support for creating extended CQ

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_devx_alloc_msi_vector.3.md, providers/mlx5/man/mlx5dv_devx_create_eq.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_vfio.c, providers/mlx5/mlx5_vfio.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/dma_util.pyx, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5_vfio.pyx, pyverbs/providers/mlx5/mlx5dv.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, tests/mlx5_base.py, tests/mlx5_prm_structs.py, tests/test_mlx5_pp.py, tests/test_mlx5_vfio.py
This series in the mlx5 vfio driver area enables a DEVX based application the below new functionality.
- Register and get asynchronous events (e.g. port up/down) once occurred.
- Work with a CQ in an interrupt mode instead of polling, this mode may reduce power usage in the system when it’s needed.
To let that work we introduced the below new DEVX APIs:
- mlx5dv_devx_alloc_msi_vector / mlx5dv_devx_free_msi_vector - to allocate/free msi vector.
- mlx5dv_devx_create_eq / mlx5dv_devx_destroy_eq - to create/destroy EQ objects.
Detailed man pages were added to describe the expected usage.
With the above functionally in place, a vfio application which uses the DEVX interface has the ability to achieve the above goals.
A pyverbs test which uses the new APIs was added to demonstrate a use case of …
=> mlx5: Extend vfio to support async events and CQ interrupt mode

buildlib/template.pc.in
According to [1], `CMAKE_INSTALL_<DIR>` variables are allowed to be either
relative or absolute. This means one should never prefix to them, in
case they are already absolute. Use `CMAKE_INSTALL_FULL_<DIR>` instead, to
not end up with double prefix when the build system uses absolute paths.
This patch fixes broken rdma-core *.pc files in
https://github.com/nixos/nixpkgs.
[1] https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
=> pkg-config: fix double prefixed libdir= and includedir=

providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h, providers/hns/hns_roce_u_verbs.c
The ofed provides a new set of post send APIs for extended QP. With the new
APIs, users can post send WR more efficiently. The hns driver provides
support for the new APIs.
Signed-off-by: Xinhao Liu <liuxinhao5@hisilicon.com>
Signed-off-by: Yixing Liu <liuyixing1@huawei.com>
=> libhns: Extended QP supports the new post send mechanism

librdmacm/examples/rping.c, providers/mlx5/dbrec.c, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/qp.c, providers/mlx5/verbs.c
This series includes few enhancements in mlx5 driver as follows.
- Fix to be IB spec compliant with regards to post_send/recv() based on QP state.
- Fix rping to match the IB spec when external QP is used.
- Optimize dbrec data structure to achieve better performance.
- Fix to determine wqe buffer allocation type per QP type - the legacy compatibility mode.
=> mlx5: Few enhancements including rping related fix

suse/rdma-core.spec
This reverts commit 6b748e875b242957e420adac3b8da59060a53701.
riscv has been made dma coherent by: 63b41f22a9f5 ("util: Add barriers support for RISC-V")
Fixes: 6b748e875b24 ("suse: fix build for riscv64")
=> Revert "suse: fix build for riscv64"

providers/efa/efa_io_defs.h, providers/efa/verbs.c
Used to indicate completion of Tx WQEs due to unresponsive remote.
=> efa: Add unresponsive remote completion error

srp_daemon/srp_daemon.c, srp_daemon/start_on_all_ports.in
The srp_daemon uses the InfiniBand specific features and cannot work
with other networks. So let's check the link layer and prevent running
the srp_dameon with unsupported networks. It is needed to avoid running
redundant srp_daemon instances and noise in the logs. The change is
primarily helpful for hosts that mix InfiniBand and RoCE devices.
Signed-off-by: Sergey Gorenko <sergeygo@nvidia.com>
=> srp_daemon: Prevent starting when the link layer is not InfiniBand

CMakeLists.txt
Make cmake fails if systemctl is not found automatically, unless
its path is manually set using -DSYSTEMCTL_BIN
This fixes build issues on debian systems where the minimal chroot does
not contain systemd.
Fixes: 05a19e050278 ("srp_daemon: Detect proper path to systemctl")
Reported-by: Benjamin Drung <benjamin.drung@ionos.com>
=> cmake: Add -DSYSTEMCTL_BIN option to set path to systemctl

MAINTAINERS
Doug retired from managing rdma-core, so let's change his entry from
maintainer to previous author.
=> MAINTAINERS: Update Doug Ledford's entry

MAINTAINERS
Remove Mike, outdated mailing lists, and change my address to Cornelis. After the
spinout from Intel we apparently neglected to update.
Signed-off-by: Dennis Dalessandro <dennis.dalessandro@cornelisnetworks.com>
=> MAINTAINERS: Update hfi1 and qib entries

librdmacm/cma.c
When rdma-core is built with "-DENABLE_RESOLVE_NEIGH=0", it skips
linkage to libnl library. This causes to ibv_idx to stay in its default
value (-1).
Update the match function to treat such scenario to be the same as
not-supported by the kernel flow.
Fixes: 28da4a8deb06 ("librdmacm: Rely on IB device index if available")
Signed-off-by: Mark Zhang <markzhang@nvidia.com>
Reviewed-by: Leon Romanovsky <leonro@nvidia.com>
=> librdmacm: Don't rely on IB device index if not available

providers/mlx5/dr_action.c, providers/mlx5/dr_devx.c, providers/mlx5/man/mlx5dv_devx_create_eq.3.md, providers/mlx5/man/mlx5dv_devx_obj_create.3.md, providers/mlx5/man/mlx5dv_devx_qp_modify.3.md, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_vfio.c, providers/mlx5/qp.c, providers/mlx5/verbs.c
This series handles the EREMOTEIO return code upon DEVX usage.
When a DEVX command is executed by FW and failed, EREMOTEIO is returned to indicate the caller that the command status and syndrome are available in the outbox.
- Add this info to the DEVX man pages.
- Translate the EREMOTEIO to the real error when DEVX is used internally.
- Align VFIO DEVX APIs return codes to the regular DEVX APIs.
=> mlx5: Handle the EREMOTEIO upon DEVX usage

debian/rules
DMA coherence has recently been added for RISC-V.
See commit 63b41f22a9f5 ("util: Add barriers support for RISC-V")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
=> debian: add riscv64 to COHERENT_DMA_ARCHS

tests/base.py
Avoid the following failure when running the test_rdmacm_async_udp_traffic
test over the qedr provider, this is happening because UD QP is not
supported by the qedr provider.
```
ERROR: test_rdmacm_async_udp_traffic (tests.test_rdmacm.CMTestCase)
File "/home/rdma-core/tests/test_rdmacm.py", line 57, in test_rdmacm_async_udp_traffic
self.two_nodes_rdmacm_traffic(CMAsyncConnection, self.rdmacm_traffic,
File "/home/rdma-core/tests/base.py", line 370, in two_nodes_rdmacm_traffic
raise(res)
pyverbs.pyverbs_error.PyverbsRDMAError: Failed to Create QP. Errno: 95, Operation not supported …
```
=> tests: Skip test if QP type is not supported

tests/base.py
Avoid the following failure when running test_resize_cq over the qedr provider
as UD QP is not supported.
```
ERROR: test_resize_cq (tests.test_cq.CQTest)
Test resize CQ, start with specific value and then increase and decrease
File "/home/rdma-core/tests/test_cq.py", line 107, in test_resize_cq
self.create_players(CQUDResources, cq_depth=3)
File "/home/rdma-core/tests/test_cq.py", line 93, in create_players
self.client = resource(**self.dev_info, **resource_arg)
File "/home/rdma-core/tests/test_cq.py", line 22, in __init__
super().__init__(dev_name, ib_port, gid_index)
File "/home/rdma-core/tests/base.py", line …
```
=> tests: Skip test_resize_cq if QP type is not supported

librdmacm/examples/rdma_xclient.c, librdmacm/examples/rdma_xserver.c
Running rdma_xclient on a system with CX-5, yields the following
error:
$ rdma_xclient -s 192.168.77.1 -c x
rdma_xclient: start
rdma_create_ep: Invalid argument
rdma_xclient: end -1
Enabling dynamic tracing of the mlx5/qp.c file gives:
infiniband mlx5_0: create_qp:3035:(pid 53349): Create QP type 9 failed
This is because the rdma_xclient sets the max_recv_{wr,sge} in the
ibv_qp_init_attr struct before calling rdma_create_ep().
An XRC_SEND QP type shall not have a receive queue and an XRC_RECV QP
type shall not have a send queue.
Fixed by only configuring the send/recv queue in rdma_xserver/xclient
respectively.
Fixes: 6bda3d049bcf ("rdma_xserver/client: Add new test apps")
=> rdma_xserver/xclient: Make recv/send WQs disjunctive

pyverbs/mr.pyx
after this patch:
mw = MW:
Rkey		: 12345678
Handle		: 4
MW Type		: IBV_MW_TYPE_2
mr = MR:
lkey		: 432134
rkey		: 432134
length		: 1024
buf		: 9403912345678
handle		: 2
Reported-by: Bob Pearson <rpearsonhpe@gmail.com>
=> pyverbs/mr.pyx: Make MR and MW print style indentical

providers/mlx5/dr_ste_v2.c, providers/mlx5/qp.c
This series handles the below 2 items.
- Add support for modify IP ECN action for CX7 in the DR area.
- Fix a check for SQ overflow in bind mw.
=> mlx5: Misc. items

librdmacm/cma.c
Fix mem leak for allocated port array
Fixes: 1b9125689fec ("cma: Workaround for rdma_ucm kernel bug")
Signed-off-by: Kirill Martynov <k.martynov@yadro.com>
=> cma: Release allocated port array

pyverbs/qp.pyx
srq is supported by the commit:1ca14a974892. Update its usage.
Signed-off-by: Liu, Changcheng <changcheng.liu@aliyun.com>
=> pyverbs: update srq parameter usage in QPInitAttr

pyverbs/cmid.pyx, pyverbs/device.pyx, pyverbs/libibverbs.pxd
- After ```rdma bind/resolve addr``` operation, it can get the dev name and port num.
Add API to get these information.
There's below scenario to use rdmacm:
1. create rdma_cm_id
2. resolve addr and route to server
3. get which device is used, create extra ibv_context and ibv_pd to create QP
4. send QP info in the private data space when calling rdma_connect.
5. rdma_connect failed. e.g. get rejected event such as that server doesn't start running the service.
6. repeat 1 & 2 & 4 until get the response event from server. There's no need to go through the 3 step again. 
- fix error when creating Context with cmid without setting device name
=> pyverbs: add property to get cmid's dev name and port num

librdmacm/rsocket.c
There is memory allocation for (nfds + 1) elements, but actually less space is allocated (1 byte for new element instead of sizeof(struct pollfd)). This is caused by operators precedence mistake.
Signed-off-by: Mikhail Sokolovskiy <sokolmish@gmail.com>
=> rsockets: Fix allocation size

debian/ibverbs-providers.symbols, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_crypto_login_create.3.md, providers/mlx5/man/mlx5dv_dek_create.3.md, providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/man/mlx5dv_wr_mkey_configure.3.md, providers/mlx5/man/mlx5dv_wr_set_mkey_crypto.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, providers/mlx5/verbs.c, pyverbs/device.pxd, pyverbs/device.pyx, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv_crypto.pxd, pyverbs/providers/mlx5/mlx5dv_crypto.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/test_mlx5_crypto.py
This series improves the existing AES-XTS functionality as of below.
- Add new AES-XTS single block capability while fixing some issues in previous code.
- Add new crypto login DV APIs to enable supporting plaintext DEKs.
- Improve and clarify man pages in few places.
In addition, some pyverbs stuff was added to demonstrate and test both plaintext and wrapped DEKs by using the new crypto login APIs.
=> mlx5: Improve the AES-XTS functionality

debian/ibverbs-providers.symbols, kernel-headers/rdma/mlx5_user_ioctl_cmds.h, providers/mlx5/dr_action.c, providers/mlx5/dr_dbg.c, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_create_steering_anchor.3.md, providers/mlx5/man/mlx5dv_dr_flow.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5dv.h, providers/mlx5/mlx5dv_dr.h, providers/mlx5/verbs.c
This series expose steering anchor DV APIs to allow users to re-inject packets back into default NIC pipeline for additional processing.
Specifically,
mlx5dv_create_steering_anchor() - creates a steering anchor which can be used as a destination in a FTE or via software steering to inject packets back into the kernel.
mlx5dv_dr_action_create_dest_root_table() - creates a packet destination root table action to inject packets back into a specific priority inside the root table.
The matching kernel part was sent already into rdma-next.
=> mlx5: Expose steering anchor DV APIs

tests/test_mr.py
[root@rdma-server rdma-core]# git grep 'Verify that illegal flags combination fails as expected'
tests/test_mr.py:        Verify that illegal flags combination fails as expected
tests/test_mr.py:        Verify that illegal flags combination fails as expected
This description will be printed if verbose is on.
I'm going to add pyverbs tests to the LKP CI, unique description can help
LKP to distinguish the case.
Link: https://github.com/intel/lkp-tests/pull/146
=> tests/test_mr.py: make cases description unique

tests/mlx5_base.py
Update the mlx5 devices list to include the new ConnectX-8 and
BlueField-4 devices.
=> tests/mlx5: Update the PCI ids to include new devices

providers/mlx5/dr_dbg.c
Add missing comma to matcher builder dump line.
=> mlx5: DR, Fix missing comma in matcher builder dump line

tests/test_mr.py
Replaced the argument 'unit' with 'gpu' to fix following error for the DmaBufMRTest:
TypeError: __init__() got an unexpected keyword argument 'unit'
Fixed: ffa97cb59f82 ("tests: Let PyverbsAPITestCase have one default device")
Signed-off-by: Wei Xu <xuwei5@hisilicon.com>
=> tests/test_mr.py: Change the argument of DmaBufMR to fix the TypeError

redhat/rdma.modules-setup.sh, suse/module-setup.sh
The `rdma` dracut module installs udev rules that can cause `rdma-load-modules@rdma.service` to load kernel modules listed in `rdma.conf`.  That file mentions the `xprtrdma` and `svcrdma` modules (both of which are aliases for `rpcrdma` in kernel 5.18) but the dracut module doesn't install them in the initrd.  If they're not installed by other means, this causes warnings in the journal:
systemd-modules-load[...]: Failed to find module 'xprtrdma'
systemd-modules-load[...]: Failed to find module 'svcrdma'
Before systemd 244, it also causes `rdma-load-modules@rdma.service` to fail entirely.
Fix by explicitly installing those modules in the initrd.
See also https://bugzilla.redhat.com/show_bug.cgi?id=2117375.
Fixes: 8bb38f6cb1b2 ("redhat: update dracut setting")
Fixes: 775241089e26 ("suse: …
=> Install xprtrdma/svcrdma kmods in redhat/suse dracut modules

debian/.gitignore
When building a Debian package in place, several files will be created in `debian/`. Add them to `.gitignore`.
=> .gitignore: Add generated files during Debian package build

debian/ibverbs-providers.symbols, kernel-headers/rdma/efa-abi.h, providers/efa/CMakeLists.txt, providers/efa/efa.c, providers/efa/efa.h, providers/efa/efa_io_defs.h, providers/efa/efadv.h, providers/efa/libefa.map, providers/efa/man/efadv_create_cq.3.md, providers/efa/man/efadv_query_device.3.md, providers/efa/verbs.c, pyverbs/providers/efa/efa_enums.pyx, pyverbs/providers/efa/efadv.pxd, pyverbs/providers/efa/efadv.pyx, pyverbs/providers/efa/efadv_enums.pxd, pyverbs/providers/efa/libefa.pxd, tests/efa_base.py, tests/test_efadv.py, tests/utils.py
This PR adds support for EFA extended CQ with a new capability to get source GID through EFA DV.
It consists of EFA provider changes, updated EFA kernel module ABI, EFA pyverbs, and a corresponding test.
Matching kernel patch:
[https://lore.kernel.org/linux-rdma/20220809151636.788-1-mrgolin@amazon.com/T/#u](https://lore.kernel.org/linux-rdma/20220809151636.788-1-mrgolin@amazon.com/T/#u)
=> efa: Add DV CQ with source GID capability

providers/mlx5/man/mlx5dv_mkey_check.3.md
Enhance the man page to better clarify the behavior if several errors exist in one block.
=> mlx5: Enhance the mlx5dv_mkey_check man page

libibverbs/examples/asyncwatch.c
musl defines strdupa via a macro which uses alloca() therefore include
the header to get the prototype
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> examples: Include alloca.h for strdupa

tests/base.py, tests/test_addr.py
test_create_ah() or test_destroy_ah() always triggered the following
error on SoftRoCE because the specified gid index didn't work.
$ bin/run_tests.py --dev rxe_enp0s5 --gid 1 -v tests.test_addr.AHTest.test_create_ah
test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah. ... ERROR
ERROR: test_create_ah (tests.test_addr.AHTest)
Test ibv_create_ah.
File "/root/rdma-core/tests/test_addr.py", line 51, in test_create_ah
raise ex
File "/root/rdma-core/tests/test_addr.py", line 47, in test_create_ah
AH(pd, attr=ah_attr)
File "addr.pyx", line 410, in pyverbs.addr.AH.__init__
pyverbs.pyverbs_error.PyverbsRDMAError: …
=> tests: Pass the specified gid index to u.get_global_route()

CMakeLists.txt, MAINTAINERS, README.md, debian/control, debian/copyright, kernel-headers/CMakeLists.txt, libibverbs/verbs.h, providers/erdma/CMakeLists.txt, providers/erdma/erdma.c, providers/erdma/erdma.h, providers/erdma/erdma_abi.h, providers/erdma/erdma_db.c, providers/erdma/erdma_db.h, providers/erdma/erdma_hw.h, providers/erdma/erdma_verbs.c, providers/erdma/erdma_verbs.h, redhat/rdma-core.spec
Hello all,
This PR introduces the Elastic RDMA Adapter (ERDMA) userspace provider driver, and the patchset for review purpose was sent to the linux-rdma mail list already [1]. The kernel driver of ERDMA can refer this link [2]. 
The main feature of ERDMA userspace provider includes: supports RC QP, supports RDMA Write/Send/RDMA Read/Immediate opcode in post_send, supports post_recv, and supports CQs with polling mode and event mode. Now we does not support SRQ yet.
Besides, this PR has already issued the review suggestions, including:
- Fix coding style issues
- Remove unnecessary _memset()_.
- Remove some magic number in the code.
Thanks,
Cheng Xu
[1] https://lore.kernel.org/all/20211224065522.29734-1-chengyou@linux.alibaba.com/
[2] …
=> erdma: Elastic RDMA Adatper (ERDMA) userspace provider driver

tests/mlx5_base.py, tests/test_qpex.py, tests/utils.py
When testing fails, we got below confusing error message due to the wrong errno:
u.rdma_traffic(client, server, self.iters, self.gid_index, self.ib_port,
File "rdma-core/tests/utils.py", line 1013, in rdma_traffic
poll_cq(client.cq)
File "rdma-core/tests/utils.py", line 577, in poll_cq
raise PyverbsRDMAError('Completion status is {s}'.
pyverbs.pyverbs_error.PyverbsRDMAError: Completion status is local QP operation error. Errno: 2, No such file or directory
That's because PyverbsRDMAError(msg, errno) accept the 2nd parameter as errno.
=> tests: poll_cq: Don't pass wc.status to PyverbsRDMAError

providers/irdma/umain.h, providers/irdma/uverbs.c
irdma issues a reflush via a modify QP to ERROR op to report completions for WR's posted once the QP is in error state.
However, this reflush modify attributes is incorrectly keyed off the last QP QP attributes by an application which might or might not be a modify to error. In the later case, a flush WQE is missed.
Explicitly set the attr.qp_state and attr_mask during a reflush modify to move the QP to error state once its in error state. Remove ibv_qp attributes from irdma_uqp struct
Fixes: 14a0fc8 ("rdma-core/irdma: Implement device supported verb APIs")
Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>
=> providers/irdma: Explicitly set QP modify attributes for reflush

providers/irdma/uk.c
Send with invalidate verb call can pass in an
uninitialized s/g array with 0 sge's which is
filled into irdma WQE and causes a HW asynchronous event.
Fix this by using the s/g array in irdma post send only when its valid.
Fixes: 3bebdf5 ("rdma-core/irdma: Add user/kernel shared libraries")
Signed-off-by: Tatyana Nikolova tatyana.e.nikolova@intel.com
=> providers/irdma: Use s/g array in post send only when its valid

libibverbs/man/ibv_reg_mr.3, libibverbs/memory.c
Run the following sample code and reproduce segfault:
```
struct memstruct {
char local[2048];
char remote[2048];
};
int main()
{
struct rdma_addrinfo hints = {0}, *rai;
struct ibv_qp_init_attr init_attr;
struct rdma_event_channel *channel;
struct rdma_cm_id *cm_id;
struct ibv_pd *pd;
struct memstruct *mem;
ibv_fork_init();
hints.ai_flags = RAI_PASSIVE;
hints.ai_port_space = RDMA_PS_TCP;
assert(!rdma_getaddrinfo("10.2.16.102", "7471", &hints, &rai));
assert(channel = rdma_create_event_channel());
assert(!rdma_create_id(channel, &cm_id, NULL, RDMA_PS_TCP));
assert(!rdma_bind_addr(cm_id, rai->ai_src_addr));
assert(pd = ibv_alloc_pd(cm_id->verbs));
mem = mmap(NULL, sizeof(*mem), PROT_READ | PROT_WRITE,
MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
assert(mem != MAP_FAILED);
assert(ibv_reg_mr(pd, …
```
=> verbs: Allow aligned address & size only for fork init

debian/changelog, debian/control, debian/infiniband-diags.lintian-overrides, debian/rdma-core.lintian-overrides
* Update overrides for lintian 2.115.2
* Bump Standards-Version to 4.6.1
This is a follow-up merge request to #1206. Change to #1026: Keep the old lintian overrides for the CI pipeline (which uses lintian on Ubuntu 20.04).
=> Changes from Debian upload 42.0-1

pyverbs/mr.pyx
Fix spelling mistake of underlying.
Fixes: cc6eb6dd7b73 ("pyverbs: Add support for memory window creation")
=> Fix spelling mistake of underlying

util/udma_barrier.h
MIPS has the capability to issue memory barriers.  Implement this using a full (heavy) barrier.  This is the only variant that is guaranteed to exist on all hardware.  Other barriers are only available on mipsr6 or some special earlier implementations.  However even on the former the kernel uses a full barrier for safety due to not yet trusting their reliability.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881731
See: https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00605-2B-CMPCOHERE-AFP-01.01.pdf
See: https://github.com/torvalds/linux/blob/master/arch/mips/include/asm/sync.h
=> util: Add barriers support for MIPS

redhat/rdma-core.spec
Pandoc is removed in RHEL 9.0 and no longer a build requirement.
Reflect this in the spec file.
Signed-off-by: Shiraz Saleem <shiraz.saleem@intel.com>
=> redhat/spec: Drop pandoc requirement for RHEL 9.0 build

buildlib/centos6.spec, debian/rdma-core.install, debian/rdma-core.lintian-overrides, kernel-boot/CMakeLists.txt, kernel-boot/persistent-ipoib.rules.in, redhat/rdma-core.spec, suse/rdma-core.spec
This rdma-core Debian package ships the udev rule `70-persistent-ipoib.rules` and installs it under `/etc/udev/rules.d`, which is reserved for user-installed files.
Install `70-persistent-ipoib.rules` into `/usr/share/doc/rdma-core` instead of `/etc/udev/rules.d` and document to copy this file into `/etc/udev/rules.d` before editing.
Bug-Debian: https://bugs.debian.org/958385
=> Install 70-persistent-ipoib.rules into docs instead of /etc

libibverbs/man/ibv_reg_mr.3, libibverbs/memory.c
Unfortunately, this change broke HW steering in DPDK. The reason to it that length can be unaligned on newer kernel.
This reverts commit 561cbce90cf4ef097d80efdcd68d619fa0ddb266.
=> Revert "verbs: Allow aligned address & size only for fork init"

providers/efa/efa.c
Add 0xefa2 devices to the pciid match table.
Signed-off-by: Michael Margolin <mrgolin@amazon.com>
=> efa: Add EFA 0xefa2 PCI ID

rdma-ndd/rdma-ndd.service.in
ProtectHostName prevents dynamic name changes to be noticed by the service. This means that on a system with no static hostname, rdma-ndd is started with a hostname 'localhost' and is not aware of new hostname retreived through a DHCP lease.
Fixes: 384b75b5f624 ("rdma-ndd: systemd hardening")
=> rdma-ndd: disable systemd ProtectHostName feature

infiniband-diags/smpquery.c, libibnetdisc/ibnetdisc.h, util/node_name_map.c
Both utilities truncate node description up to 63 bytes instead 64 bytes. 
Node description fields declared as char array of IB_SMP_DATA_SIZE bytes. 
Last character for compatibility with c-string set to zero. 
In this case node description will be truncated from 64 bytes to 63 bytes. 
Size of node description fields was enlarged to the IB_SMP_DATA_SIZE + 1 bytes for using last character for zero char without truncated node description
Signed-off-by: Gregory Linschitz <gregoryl@nvidia.com>
=> Fix max length of node description (ibnetdiscover and smpquery)

providers/mlx5/man/mlx5dv_create_steering_anchor.3.md
`allow to do` is wrong. It should be `allow one to do` or `allow doing`.
lintian found this typo.
=> Fix grammar mistake of "allow doing"

debian/rdma-core.maintscript
Commit b9ddb7f8013b274e55727ec390960960b95ae7fa installed `70-persistent-ipoib.rules` into docs instead of `/etc`. Remove `/etc/udev/rules.d/70-persistent-ipoib.rules` on upgrade if it was not modified by the user.
=> debian: Remove /etc/udev/rules.d/70-persistent-ipoib.rules on upgrade

Documentation/testing.md, pyverbs/mr.pyx, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/CMakeLists.txt, tests/base.py, tests/base_rdmacm.py, tests/cuda_utils.py, tests/mlx5_base.py, tests/mlx5_prm_structs.py, tests/test_cuda_dmabuf.py, tests/test_mlx5_cuda_umem.py, tests/utils.py
Add tests that cover RDMA traffic over MR/UMEM DMA BUF.
In both cases, the memory is a CUDA-allocated memory.
=> tests: add coverage for rdma cuda dmabuf

redhat/rdma-core.spec
On RHEL9 similar to Fedora33 ninja-build requires explicitly passing builddir path as part of the migration to out-of-source builds. Treat RHEL>=9 same as Fedora>=33.
Signed-off-by: Michael Margolin <mrgolin@amazon.com>
=> redhat: Support rpmbuild on RHEL9

providers/mlx5/mlx5_vfio.c, providers/mlx5/qp.c
This series includes a few fixes in mlx5 driver as of below:
- Handle properly BSF segment when a UMR WQE overlaps the end of the SQ.
- Fix some issues when creating a mkey over vfio.
- Fix mlx5dv_get_vfio_device_list() based on valgrind memcheck report.
=> mlx5: Misc. fixes

tests/test_odp.py, tests/utils.py
These patches add new testcases for ODP (test_odp.py).  Currently, only Send/Recv operations are checked, and other operations are not tested with ODP at all. This patchset cleans-up the ODP test code and add four new testcases. I confirmed these new testcases succeeded with RFC implementation of Explicit ODP on rxe[1].
The new testcases succeeded also with ConnectX-6, but currently the ODP Atomic tests are skipped with my device. This is because the capability for RC (rc_odp_caps) is not filled with IB_ODP_SUPPORT_ATOMIC in internal_fill_odp_caps(). However, it seems the device can actually handle Atomic operations. I am not sure if this is a bug of the device or not. If anybody from NVIDIA knows why rc_odp_caps is unfilled, please let me know
cf. …
=> tests: ODP testcases for RDMA Write/Read and Atomic operations

providers/rxe/rxe-abi.h, providers/rxe/rxe.c, providers/rxe/rxe.h
Add a subroutine rxe_create_srq_ex to implement ibv_create_srq_ex for the rxe driver. Minor related cleanups.
Signed-off-by: Bob Pearson <rpearsonhpe@gmail.com>
=> providers/rxe: Implement create_srq_ex

infiniband-diags/dump_fts.c, infiniband-diags/ibroute.c, infiniband-diags/ibtracert.c
This fix related to the previous commit d974c4e398d281ce2993c44f865f5161480307f2 / PR(#1237)
dump_fst/ibroute/ibtracert truncate node description up to 63 bytes instead 64 bytes. 
Node description field declared as char array of IB_SMP_DATA_SIZE bytes. 
Last character for compatibility with c-string set to zero. 
In this case node description will be truncated from 64 bytes to 63 bytes. 
Size of node description fields was enlarged to the IB_SMP_DATA_SIZE + 1 bytes 
for using last character for zero char without truncated node description
Signed-off-by: Gregory Linschitz <gregoryl@nvidia.com>
=> ibdiags: Fix max length of node description (dump_fst/ibroute/ibtracert)

providers/mlx5/dr_action.c, providers/mlx5/dr_arg.c, providers/mlx5/dr_dbg.c, providers/mlx5/dr_domain.c, providers/mlx5/dr_icm_pool.c, providers/mlx5/dr_ptrn.c, providers/mlx5/dr_send.c, providers/mlx5/dr_ste_v0.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv_dr.h
This series includes fixes and improvements in the DR area, mainly in the pattern and arguments area.
Specifically,
- Fixes an issue causing fallback from pattern/args to legacy modify header mode and some following issues in this area.
- Fixes an issue when both svlan and cvlan matches are provided.
- Improve to adds memory statistics for domain object.
- Improve to calculate the threshold of each pool according to its type.
- Improve to enable up to 64 modifications in modify-header action.
=> mlx5: DR, Fixes and improvements 

CMakeLists.txt, util/bitmap.c, util/tests/CMakeLists.txt, util/tests/bitmap_test.c
This series includes fixes and improvements to the bitmap functions that were rewritten in February due to licensing.
Fixes memory access errors with the mlx5 Direct Rules API, as reported by valgrind:
> ==55638== Invalid read of size 8
> ==55638==    at 0x408E4C7: bitmap_find_first_bit (bitmap.c:57)
> ==55638==    by 0x40566EE: dr_buddy_update_upper_bitmap (dr_buddy.c:164)
> ==55638==    by 0x4056A3A: dr_buddy_alloc_mem (dr_buddy.c:199)
> ==55638==    by 0x4059EDA: dr_icm_handle_buddies_get_mem (dr_icm_pool.c:436)
> ==55638==    by 0x4059EDA: dr_icm_alloc_chunk (dr_icm_pool.c:483)
> ==55638==    by 0x4060AAF: dr_ste_htbl_alloc (dr_ste.c:540)
> ==55638==    by 0x406CF26: dr_table_init_nic (dr_table.c:71)
> ==55638==    by 0x406D1F3: dr_table_init (dr_table.c:124)
> ==55638==    by …
=> util: bitmap: tests, fixes and improvements

providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/qp.c, providers/mlx5/verbs.c, providers/mlx5/wqe.h, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/test_mlx5_crypto.py
This series adds support for multi-block AES-XTS encryption based on device capabilities.
It includes also some pyverbs test to cover this new functionality.
=> mlx5: Add support for multi-block AES-XTS encryption

tests/test_mlx5_cuda_umem.py
Since 'rdma cuda dmabuf' tests were added, it is impossible to run any test without installing scapy package. However, not all users need to run the new tests specific to mlx5. This patch fixes the issue.
=> tests: Let pyverbs tests run without scapy package

tests/test_qpex.py
Zero bytes messages can be used for keep alive check in the RC mode, but there is no test to check the behaviour. This patch adds the test of RDMA zero-byte Write to the qpex testcases.
Signed-off-by: Daisuke Matsuda <matsuda-daisuke@fujitsu.com>
=> tests: Add a test of RDMA zero-byte Write

tests/test_qpex.py
Recently, a regression was introduced into RXE in
commit: 686d348476ee ("RDMA/rxe: Remove unnecessary mr testing") which can be triggered by a zero length RDMA read.
Add this scenario to cover it.
Links: https://lore.kernel.org/linux-rdma/20221202110157.3221952-1-matsuda-daisuke@fujitsu.com/
=> tests: Add RDMA READ zero length scenario

util/mmio.c
rdma-core added udma_barrier support for MIPS in:
https://github.com/linux-rdma/rdma-core/commit/b7c428344ea96d446f6ffe31c620a238a7f25c9e This commit is present in rdma-core version >= 43.0. See also: https://github.com/linux-rdma/rdma-core/pull/1225 Before this commit, coherent dma support was disabled for MIPS.
util/mmio.c functions are compiled when coherent dma support is enabled. They are always using indirect functions, to select at runtime the best function implementation. It is currently used for x86 sse_mmio_write64_be(), and s390x mmio_memcpy_x64_mio(). In the MIPS case, there is ifunc used to always resolve the same function (namely, resolve_mmio_write64_be() will always select and return pthread_mmio_write64_be().
rdma-core includes a detection of the compiler support for the …
=> util: mmio: fix build on MIPS with binutils >= 2.35

libibverbs/verbs.h
Make integer conversions explicit to silent the following warnings/errors:
```
./build/include/infiniband/verbs.h: In function ‘__ibv_reg_mr’: 
./build/include/infiniband/verbs.h:2550:53: error: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Werror=sign-conversion]
2550 | return ibv_reg_mr(pd, addr, length, access);
|                                     ^~~~~~
./build/include/infiniband/verbs.h: In function ‘__ibv_reg_mr_iova’:
./build/include/infiniband/verbs.h:2573:64: error: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Werror=sign-conversion]
2573 | return ibv_reg_mr_iova(pd, addr, length, iova, access);
|                                                ^~~~~~
./build/include/infiniband/verbs.h: In function ‘ibv_create_srq_ex’: …
```
=> verbs: Make integer conversions explicit

debian/rules
Commit b7c428344ea96d446f6ffe31c620a238a7f25c9e ("util: Add barriers support for MIPS") added support for coherent DMA support for MIPS. Therefore add the 64-bit MIPS architectures `mips64`, `mips64el`, `mips64r6`, and `mips64r6el` to `COHERENT_DMA_ARCHS`.
Bug-Debian: https://bugs.debian.org/1026088
=> debian: Add 64-bit MIPS architectures to COHERENT_DMA_ARCHS

pyverbs/providers/mlx5/mlx5dv.pyx
Expose the UAR C object pointer from its pyverbs class for external python usage.
=> pyverbs: Expose UAR C pointer

debian/control, debian/rules
Commit 698f40ecc32bf59fb87691c3437302f63bec3cc4 updated the compat level to version 10, but did not increase the minimum debhelper version.
The systemd sequence is now enabled by default since compat level 10.
Fixes: 698f40ecc32bf59fb87691c3437302f63bec3cc4 ("debian: Update compat to 10")
=> debian: Update debhelper to 10

debian/changelog, debian/copyright, debian/ibverbs-providers.install, debian/watch
* debian: Query api.github.com for release tarballs
* debian: Exclude libmana.so from ibverbs-providers
* debian: Update year in copyright
* debian: Add Debian uploads up to version 44.0-1
See individual commits for details.
=> Changes from Debian upload 44.0-1

debian/rules
Commit b7c428344ea96d446f6ffe31c620a238a7f25c9e ("util: Add barriers support for MIPS") added support for coherent DMA support for MIPS. All MIPS architectures needs to be added to `COHERENT_DMA_ARCHS` (not just the 64-bit variants).
The list of architectures that support coherent DMA gets very long, because most architectures support it. So inverse the list to make it easier to read.
Bug-Debian: https://bugs.debian.org/1026088
=> debian: Add 32-bit MIPS architectures to COHERENT_DMA_ARCHS

CMakeLists.txt, libibnetdisc/CMakeLists.txt
This specific error from Ubuntu 20.4:
2023-01-26T08:15:31.4858000Z make[2]: Entering directory '/__w/1/s/rdma-core-45.0' 2023-01-26T08:15:31.4859279Z if [ -e /usr/bin/python3 ]; then \ 2023-01-26T08:15:31.4861846Z 	dh_auto_configure "--" "-GNinja" "-DDISTRO_FLAVOUR=Debian" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc" "-DCMAKE_INSTALL_SYSTEMD_SERVICEDIR:PATH=/lib/systemd/system" "-DCMAKE_INSTALL_INITDDIR:PATH=/etc/init.d" "-DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib" "-DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=/var/lib" "-DCMAKE_INSTALL_RUNDIR:PATH=/run" "-DCMAKE_INSTALL_UDEV_RULESDIR:PATH=/lib/udev/rules.d" "-DCMAKE_INSTALL_PERLDIR:PATH=/usr/share/perl5" "-DENABLE_STATIC=1"  \ 2023-01-26T08:15:31.4865385Z 			-DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 \ …
=> buildlib: Fix build errors in old debian

providers/rxe/rxe.c, providers/rxe/rxe.h
librxe sets wqe->ssn to an incrementing value kept in qp->ssn for all send work requests, but there is nothing in either the provider library or the kernel rxe driver that consumes this field. Clean things up by removing this unnecessary work.
Keep the ssn field in the ABI file rdma_user_rxe.h for the forseeable future, although a patch to remove the corresponding kernel code that keeps an ssn in the QP structure and copies the value into each WQE will be submitted too.
Signed-off-by: Roland Dreier <roland@enfabrica.net>
=> providers/rxe: Remove unused "ssn" field from QP and WQE

providers/rxe/rxe.c, tests/test_qpex.py, tests/utils.py
this length will be set to FETH for FLUSH operation
Fixes: 20a37f32ceee ("providers/rxe: Add new API ibv_wr_flush()")
=> providers/rxe: Add missing flush length

providers/mlx5/dr_send.c, providers/mlx5/mlx5dv_dr.h
The field max_inline_size in dr_domain_info is no longer used; remove the field and a buggy reference to it.
Fixes: 2dbeaf37f460 ("mlx5: DR, Add infrastructure for multi QPs")
Signed-off-by: Josh Fried <joshuafried@gmail.com>
=> mlx5: fix inline send bug for DR

tests/cuda_utils.py
Skip CUDA tests in case cuda-python package is installed but no CUDA-cappable device is found.
=> tests: Skip CUDA tests if there is no CUDA device

providers/erdma/erdma_verbs.c, providers/erdma/erdma_verbs.h
Hello,
This PR includes two commits. 
In the first commit, we refactor create_qp/destroy_qp implementation. The original implementation of create_qp/destroy_qp does everything in a single function, it is not friendly. Refactor this and separate resources initialization/destruction into each sub functions.
In the second commit, we adds fork support.
Thanks,
Cheng Xu
=> providers/erdma: Refactor create_qp/destroy_qp implementation and add fork support

tests/mlx5_base.py, tests/mlx5_prm_structs.py, tests/test_mlx5_devx.py
Add a test that creates a QP in devx with dbr_less_mode and uses it for traffic.
When dbr_less_mode is used the doorbell records are not updated by the user.
=> tests: Add test for devx DBR-less mode data path

kernel-headers/rdma/hns-abi.h, providers/hns/hns_roce_u.c, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_abi.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_hw_v2.h, providers/hns/hns_roce_u_verbs.c
The patchset mainly fixes and refactors the code relate to inline
features and supports cqe inline in user space.
1.#1-3: Fix the problem of sge
2.#4-7: rq inline related patches(handle compatibility, refactor
rq inline, add new interface to support rq inline)
3.#8: support cqe inline
The kernal space part is named "[PATCH for-next 0/3] Refactor rq inline and add cqe inline".
https://lore.kernel.org/lkml/Y6w2aRPSXAv4s5Pp@unreal/T/
Haoyue Xu (1):
Update kernel headers
Luoyouming (7):
libhns: Use a constant instead of sizeof operation
libhns: Fix ext_sge num error when post send
libhns: Fix the problem of sge nums
libhns: Add compatibility handling for rq inline
libhns: Refactor rq inline
libhns: Add RQ inline support for ibv_wc_*()
libhns: Support cqe inline
kernel-headers/rdma/hns-abi.h …
=> [PATCH rdma-core 0/8] Fix sge num bug, refactor rq inline, support cqe inline

providers/mlx5/dr_dbg.c, providers/mlx5/dr_devx.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste.h, providers/mlx5/dr_ste_v1.c, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv_dr.h
This series includes a few improvements in the DR area, it includes:
- Add support to match on IB layer 4 header layout in ste_v1 format.
- Add the ability to dump some extra information.
- Use an additional capability for RC QP FL support when RoCE capability is disabled.
=> mlx5: DR, Few improvements

providers/mlx5/verbs.c
Turn on IBV_ATOMIC_GLOB atomic cap bit when it's supported by the device.
=> mlx5: Report IBV_ATOMIC_GLOB when supported

suse/rdma-core.spec
SUSE policy is that shared lib packages are named %{libname}%{lib_major_version} unless the libname ends with a digit (ie libmlx4, libmlx5) in which case the package should be %{libname}-%{lib_major_version}
Fixes: 443f196deee0 ("mana: Microsoft Azure Network Adapter (MANA) RDMA provider")
=> suse: fix package name for libmana

kernel-headers/rdma/efa-abi.h, kernel-headers/rdma/hns-abi.h, libibverbs/man/ibv_query_qp_data_in_order.3.md, libibverbs/verbs.c, libibverbs/verbs.h, providers/efa/efa.c, providers/efa/verbs.c, providers/efa/verbs.h, providers/mlx5/verbs.c, pyverbs/libibverbs_enums.pxd, pyverbs/qp.pyx
Add definition for ibv_query_qp_data_in_order flags to allow querying for specific capabilities related to data polling support, currently adding 128 bytes in order flag (LL128).
Adopt existing code and add support in EFA provider.
=> Add ibv_query_qp_data_in_order flags

pyverbs/mem_alloc.pyx, tests/base.py, tests/mlx5_prm_structs.py, tests/test_mlx5_dr.py, tests/test_odp.py, tests/utils.py
This series adds a new SW Steering test and improve ODP tests by explicitly invalidating the MRs to make sure a page fault occurs.
In addition, adjusts the way we get the net-interface to be dependent on both the device name and port.
=> tests: add and improve some tests

redhat/rdma-core.spec
rdma-core release uses .tar.gz
suse/rdma-core.spec also uses .tar.gz
=> redhat: Update source filename in spec file

pyverbs/mem_alloc.pyx
As documented in the bits/mman-linux.h header file, the header should
never been included directly. sys/mman.h should be included and it will
include bits/mman-linux.h. This matters because bit/mman-linux.h does
not exist in some older copies of glibc-headers. sys/mman.h will pull in
the correct headers for the the installed version of glibc-headers.
Fixes: 4c0d33d ("pyverbs: Add madvise python wrapper function ")
=> pyverbs: Remove include of bits/mman-linux.h

tests/efa_base.py, tests/mlx5_base.py, tests/test_cuda_dmabuf.py, tests/test_efa_srd.py, tests/test_efadv.py, tests/test_mlx5_cq.py, tests/test_mlx5_dc.py, tests/test_mlx5_rdmacm.py, tests/test_mr.py, tests/test_odp.py, tests/test_qpex.py, tests/test_shared_pd.py, tests/utils.py
Multiple fixes for traffic util functions:
1. Add RDMA write with imm opcode to send util
2. Fix double naming of remote address in players
3. Fix ambiguous use of QP opcode in traffic functions
4. Fix wrong send opcode use in traffic util
In addition add tests for SRD RDMA write with and without imm.
=> Multiple fixes for traffic util functions and tests for SRD RDMA write

libibverbs/man/ibv_post_send.3
s/IBV_ZERO_BASED/IBV_ACCESS_ZERO_BASED/
Trivial one-liner, but having the actual spelling makes it easier to search for the variable in the code.
=> man page: correct IBV_ZERO_BASED to IBV_ACCESS_ZERO_BASED

Documentation/stable.md
Currently Azure generates release changelogs by diffing the new tag and the overall latest github release ( git log new_tag ^latest_release). This means that the changelog usually contains all the commits from the stable branch (vXX.0..vXX.N) and not just the one added from the latest release in this branch (vXX.N-1..vXX.N).
This commits changes the stable branch creation process so that azure-pipelines-release.yml will create the changelog using the latest github release in this stable branch.
=> stable: Tune stable branch creation process

providers/hns/hns_roce_u_hw_v2.c
It is not necessary to check the type of the queue on post_send and post_recv since the QP type that cannot be supported will be rejected when it is created.
Check for srq in post_recv has also been removed, because the RQ of QP bound to srq is empty and will return immediate error in post_recv.
Besides, remove the unused parameter ctx.
=> libhns: Remove unnecessary QP checks

providers/bnxt_re/main.c
Adding support for RoCE VF device ID 0x1809
=> bnxt_re/lib: Add device id for RoCE Hyper V VF

providers/bnxt_re/verbs.c
This series includes 3 patches that fixes issues when qp is re-used  and destroyed.
=> bnxt_re/lib: QP error and reuse handling

providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c
Generic updates to bnxt_re library. Includes a bug fix for atomic operations, few optimizations to data path and adding send_with_inval support.
=> bnxt_re/lib: library updates

CMakeLists.txt
The macro CHECK_C_SOURCE_COMPILES that CMakeLists.txt is using is defined in the module CheckCSourceCompiles. That module is included indirectly via CheckCCompilerFlag.
It was reported in Fedora Bugzilla, that a recent cmake 3.27.0-rc1 removed the indirect inclusion of the macro, breaking the rdma-core build:
https://bugzilla.redhat.com/show_bug.cgi?id=2214541
The build error message:
```
-- Detecting C compile features - done
CMake Error at buildlib/RDMA_EnableCStd.cmake:63 (CHECK_C_SOURCE_COMPILES):
Unknown CMake command "CHECK_C_SOURCE_COMPILES".
Call Stack (most recent call first):
CMakeLists.txt:209 (RDMA_Check_C_Compiles)
```
The change in cmake broke the build in many more projects, so cmake restored compatibility in -rc2:
https://gitlab.kitware.com/cmake/cmake/-/issues/24991 …
=> build: include the module CheckCSourceCompiles

libibverbs/examples/devinfo.c, libibverbs/man/ibv_devinfo.1
By default, ibv_devinfo will list all the RDMA devices in the system.
=> libibverbs: Fix ibv_devinfo help message

providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c
Adapt hns userspace driver and obtain packet type from CQE for MPI APP.
=> libhns: Change arrangement in SL to adapt MPI APP

kernel-headers/rdma/bnxt_re-abi.h, providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/db.c, providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c
Enable Low latency push support for Broadcom Adapters.
=>  bnxt_re/lib: Enable low latency push support

tests/base.py, tests/efa_base.py, tests/mlx5_base.py, tests/test_atomic.py, tests/test_cq.py, tests/test_cq_events.py, tests/test_cqex.py, tests/test_cuda_dmabuf.py, tests/test_efa_srd.py, tests/test_efadv.py, tests/test_flow.py, tests/test_mlx5_cq.py, tests/test_mlx5_crypto.py, tests/test_mlx5_dc.py, tests/test_mlx5_dr.py, tests/test_mlx5_flow.py, tests/test_mlx5_lag_affinity.py, tests/test_mlx5_mkey.py, tests/test_mlx5_raw_wqe.py, tests/test_mlx5_sched.py, tests/test_mlx5_timestamp.py, tests/test_mlx5_udp_sport.py, tests/test_mr.py, tests/test_odp.py, tests/test_parent_domain.py, tests/test_qpex.py, tests/test_relaxed_ordering.py
Some of the tests' common functions (such as resource creation and rkeys exchange) were massively duplicated.
This series cleans this wherever it's applicable with minimal modifications.
=> tests: Remove code duplication

providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c, pyverbs/providers/mlx5/libmlx5.pxd, pyverbs/providers/mlx5/mlx5dv.pyx, pyverbs/providers/mlx5/mlx5dv_enums.pxd, tests/mlx5_base.py, tests/test_mlx5_dc.py, tests/utils.py
This series exposes the maximum number of outstanding RDMA read/atomic per DC QP as a requester or a responder.
In addition, it includes some pyverbs stuff that uses those new capabilities.
=> mlx5: Expose max outstanding RDMA read/atomic per DC QP

libibverbs/man/ibv_alloc_parent_domain.3
Typo in this man page can be seen here:
- https://man7.org/linux/man-pages/man3/ibv_alloc_parent_domain.3.html
There is an additional quotation mark for the `*context"` parameter. This PR corrects it. See screenshot:
Before:
After:
=> Typo in ibv_alloc_parent_domain.3

providers/mlx5/mlx5_vfio.c, util/interval_set.c, util/interval_set.h
Currently for some virtual addresses mlx5_vfio_reg_mr() uses a very large IOVA page size, which wastes a lot of memory and might not even be supported in some cases.
This series refactors the calculation to make sure it won't waste more than 1G of IOVA address space.
=> mlx5: Refactor the mlx5_vfio_reg_mr() calculation for IOVA page size

libibverbs/verbs.h
Our customer reported the below warning whe using Clang v16.0.4 and C++20, on a code that includes the header "/usr/include/infiniband/verbs.h":
error: bitwise operation between different enumeration types ('ibv_access_flags' and 'ib_uverbs_access_flags') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
mem->mr = ibv_reg_mr(dev->pd, (void*)start, len, IBV_ACCESS_LOCAL_WRITE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/infiniband/verbs.h:2514:19: note: expanded from macro 'ibv_reg_mr'
((access) & IBV_ACCESS_OPTIONAL_RANGE) == 0))
~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
According to the article "Clang 11 warning: Bitwise operation between different enumeration types is deprecated":
C++20's P1120R0 deprecated bitwise operations …
=> verbs: fix compilation warning with C++20

providers/irdma/uverbs.c
Taking into account a reserved entry to detect overflow.
Fixes: 14a0fc824f16 ("rdma-core/irdma: Implement device supported verb APIs")
=> providers/irdma: Fix CQ size validation

tests/irdma_base.py, tests/test_cq.py
The test_resize_cq assumes that when shrinking an active CQ with unpolled entries it fail with an EINVAL error, but the irdma hardware is implementing the resize CQ differently and allowing to shrink a CQ without losing the unpolled entries.
To avoid the test_resize_cq failure for irdma devices, skip the test case.
=> tests: Skip CQ shrinking for irdma devices

tests/test_rdmacm.py
The irdma driver doesn't support modifying the ack timeout - skip the test for irdma devices.
=> tests: Skip ack_timeout test for irdma devices

tests/base.py, tests/test_mr.py
Move attribute query out of base create_players.
Not all vendors support all query_qp attribute mask values and this breaks all tests. It is only required for a single test suite, so move it there as it was prior to PR https://github.com/linux-rdma/rdma-core/pull/1349/
Fixes: 78f6a6556dc4 ("tests: Remove code duplication")
=> Fix failing tests due to query_qp attribute mask

tests/CMakeLists.txt
The patch that added irdma_base.py forgot to update CMakeLists.txt.
Fixes: 371028ff ("tests: Skip CQ shrinking for irdma devices")
=> tests: Add irdma_base.py

tests/test_efa_srd.py
Added event enabled cq tests over SRD, with new and old send.
=> tests: Add event-enabled tests over SRD

CMakeLists.txt, buildlib/FindLTTngUST.cmake, providers/efa/CMakeLists.txt, providers/efa/efa_trace.c, providers/efa/efa_trace.h, providers/efa/verbs.c
Add support for LTTng: The LTTng User Space Tracing (LTTng-UST) library allows any C/C++ application to be instrumented for and traced by LTTng.
Add CMake flag to compile in LTTng support for providers who added LTTng traces, without suppling this flags the tracing code will be compiled out without any influence on other code.
Also add initial support for EFA tracing: post receive, send and completion.
=> Add general support for LTTng tracing and traces for EFA provider

providers/mlx5/dr_action.c, providers/mlx5/dr_arg.c, providers/mlx5/dr_domain.c, providers/mlx5/dr_matcher.c, providers/mlx5/dr_rule.c, providers/mlx5/dr_send.c, providers/mlx5/dr_ste.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv_dr.h, tests/mlx5_prm_structs.py, tests/test_mlx5_dr.py, tests/utils.py
This series in the DR area includes a few extensions and improvements as of below.
- Optimize argument sending in multi-QP mode.
- Add a check for unsupported and reserved fields in the match param
- Remove table level check to enable some extra functionality.
- In rehash write the line in the entry immediately to save allocations and improve performance.
- Support new sizes for pre-allocated fixed matcher tables.
- Add support for matching on bth_a bit.
In addition, a pyverbs test was added for matching on the bth_a bit.
=> mlx5: DR, Few extensions and improvements 

tests/base_rdmacm.py, tests/rdmacm_utils.py, tests/test_rdmacm.py
In case of dual port the wrong port was used for AH creation.
=> tests: Fix rdmacm async udp

kernel-headers/rdma/bnxt_re-abi.h, providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/db.c, providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/memory.c, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c, util/util.c, util/util.h
The idea behind this series is to prevent Doorbell drops
on some of the Broadcom adapters that require Doorbell
moderation. This is achieved by pacing the doorbell writes
into the hardware FIFO. The rate at which individual doorbells
are written needs to be dynamically adjusted, because
it depends on the ability of the hardware to drain the
FIFO and on the number and behavior of individual
doorbell writers. When congestion is detected by the user
library, it notifies the driver and driver adjust the
pacing parameters dynamically in a shared page, which will
be used for pacing the Doorbells.
=> bnxt_re/lib: Doorbell Drop Prevention

debian/control
The lsb-base package became a transitional package to sysvinit-utils which is an essential package.
=> debian: Drop obsolete versioned dependency on lsb-base

providers/irdma/uverbs.c
Make sure to verify that the provided max_send_wr and max_recv_wr are in the supported range.
Fixes: 14a0fc824f16 ("rdma-core/irdma: Implement device supported verb APIs")
=> providers/irdma: Verify max_send_wr and max_recv_wr

buildlib/RDMA_BuildType.cmake, suse/rdma-core.spec
- Fix to CMake when using RELWITHDEBINFO has spaces 
- Drop old RPM macros
=> Minor fixes

providers/bnxt_re/main.c, providers/bnxt_re/verbs.c, providers/bnxt_re/verbs.h
Add the support for dmabuf verb for bnxt devices.
=> bnxt_re/lib: Add dmabuf support in bnxt_re

buildlib/azp-checkpatch
- Get and return the error types
- Fail when errors are detected
- Upgrade UNKNOWN_COMMIT_ID to errors so Fixes tags point to real commits
=> buildlib: change checkpatch behaviour in AZP

providers/bnxt_re/verbs.c
Make sure to return EINVAL when the passed max_recv_wr or max_send_wr are out of the supported range.
=> providers/bnxt_re: Fix return value for bnxt_re_check_qp_limits()

redhat/rdma.modules-setup.sh
According to the ABI doc this item supposed to have sub elements (yes they does) [1]
It fixes the issue of /etc/rdma/mlx4.conf  not loaded at initramfs time, in hostonly  (default) mode.
[1] https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband
=> /sys/class/infiniband_verbs/uverbs0 is a directory

suse/rdma-core.spec
modprobe mlx4.conf is not available on non dma-coherent arch. This causes rpmbuild to fail on armv7.
Fixes: f5a69fbd96dc ("suse: Change install path for modprobe.d")
=> suse: fix issue on non dma-coherent system

infiniband-diags/ibtracert.c
Avoid memory leak in find_mcpath() by freeing the allocated memory.
Fixes: https://github.com/linux-rdma/rdma-core/commit/e4d681de516743f6a0d94d679b8332c57c71528f ("Diags: Renamed openib-diags to infiniband-diags")
=> ibtracert: Fix memory leak

pyverbs/device.pyx, pyverbs/libibverbs.pxd, tests/test_device.py
A new field active_speed_ex was added to ibv_port_attr to support the new XDR speed.
Update PyVerbs and tests accordingly.
=> pyverbs: Add support for XDR speed 

tests/CMakeLists.txt, tests/mlx5_prm_structs.py, tests/test_mlx5_dr.py, tests/test_srq.py
Add tests that cover SRQ modify and query APIs.
The series also includes a minor fix and an adjustment related to mlx5 SW steering tests and PRM packets.
=> tests: Add SRQ tests and some adjustments

debian/libibnetdisc5.symbols, infiniband-diags/CMakeLists.txt, infiniband-diags/ibdiag_common.c, infiniband-diags/iblinkinfo.c, infiniband-diags/ibnetdiscover.c, infiniband-diags/ibportstate.c, infiniband-diags/ibqueryerrors.c, libibmad/dump.c, libibmad/fields.c, libibmad/iba_types.h, libibmad/mad.h, libibnetdisc/CMakeLists.txt, libibnetdisc/ibnetdisc.c, libibnetdisc/ibnetdisc.h, libibnetdisc/libibnetdisc.map
This PR add support XDR speed decoding to the:
- libibumad 
- infinabnd-diags
- ibnetdiscover
- iblinkinfo
- ibqueryerrors
- ibportstate
=> XDR speed decoding support 

debian/control
No changes are needed to support the new Debian policy version. See https://www.debian.org/doc/debian-policy/ for details.
=> debian: Bump Standards-Version to 4.6.2

kernel-headers/rdma/hns-abi.h, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_db.c, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
Compared with normal doorbell, using record doorbell can shorten the process of ringing the doorbell and reduce the latency.
During SRQ creation, the kernel driver will allocate doorbell buffer and notify userspace whether the SRQ record doorbell is enabled with the flag HNS_ROCE_RSP_SRQ_CAP_RECORD_DB. The userspace driver will decide whether to use record doorbell or normal doorbell based on this flag in post SRQ recv process.
This patch relies on the corresponding kernel patch: RDMA/hns: Support SRQ record doorbell
=> libhns: Support SRQ record doorbell

providers/irdma/osdep.h, providers/irdma/uk.c, providers/irdma/umain.h, providers/irdma/user.h, providers/irdma/uverbs.c
In the function irdma_post_recv, the function irdma_copy_sg_list is not needed since the struct irdma_sge and ibv_sge have the similar member variables. The struct irdma_sge can be replaced with the struct ibv_sge.
This change follows along the lines of the irdma kernel patch [1]
[1] https://patchwork.kernel.org/project/linux-rdma/patch/20211030104226.253346-1-yanjun.zhu@linux.dev/
=> providers/irdma: Remove unnecessary copy of sg list

tests/test_srq.py
According to the IB Spec, Vol 1, Rel-1.6.2022.07-15b: 10.2.9.3 SHARED RECEIVE QUEUE MODIFICATION:
"If the HCA supports the modification of the maximum number of outstanding SRQ WRs, then Consumer may request to change the maximum number of outstanding WRs through the Modify SRQ verb. The CI returns the actual maximum number of WQEs that can be outstanding on the SRQ, this value must be greater than or equal to the number requested."
Change the max_wr assert to greater or equal to the requested value (instead of equal).
In addition, remove max_sge modification as it's irrelevant and not supported.
=> tests: Fix test_resize_srq

libibverbs/enum_strs.c, libibverbs/libibverbs.map.in, libibverbs/verbs.h, providers/mlx5/CMakeLists.txt, providers/mlx5/mlx5_trace.c, providers/mlx5/mlx5_trace.h, providers/mlx5/qp.c, providers/rxe/CMakeLists.txt, providers/rxe/rxe.c, providers/rxe/rxe_trace.c, providers/rxe/rxe_trace.h
Hi,
I'd like to introduce LTTng based tracepoints for RXE into rdma-core for trouble shooting/performance monitor..
An sample of python script:
```
#!/usr/bin/env python3
import argparse
import bt2
import collections
import sys
def stats(args):
stats = {}
tcm_it = bt2.TraceCollectionMessageIterator(args.tracepoints)
for msg in tcm_it:
if type(msg) is not bt2._EventMessageConst:
continue
event = msg.event
if event.cls.name != "rdma_core_rxe:post_send":
continue
dev = str(event.payload_field["dev"])
if args.device != None and args.device != dev:
continue;
qpn = event.payload_field['src_qp_num']
if args.qpn != None and args.qpn != qpn:
continue;
opcode = event.payload_field['opcode']
if args.opcode != None and args.opcode != opcode:
continue;
key = dev + "-" + str(qpn)
qpstats = …
```
=> providers/rxe: Add tracepoint for post send

providers/mlx5/mlx5_trace.h, providers/mlx5/qp.c
As part of adding rdma_tracepoint() to _mlx5_post_send() the total length of the SGs is calculated unconditionally even if the trace point mechanism is compiled out.
The above extra code in the data path must be prevented.
As such, the trace point was changed to include some exiting data as of num_sge.
In addition, drop the dummy trace point function and have an empty definition for rdma_tracepoint as was done for rxe and the efa drivers.
=> mlx5: Fix the rdma_tracepoint() code

providers/mana/mana.c, providers/mana/mana.h, providers/mana/qp.c, providers/mana/wq.c
The checks for those sizes are already done in the kernel driver since day one. The checks in rdma-core are redundant. Remove them to make the code easier to maintain.
=> Remove redundant code for checking max queue sizes and max sgl sizes

providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/verbs.c, providers/bnxt_re/verbs.h
Update library with some code refactoring and fixes.
=> bnxt_re/lib: General Updates

kernel-headers/rdma/bnxt_re-abi.h, kernel-headers/rdma/rdma_netlink.h, providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/verbs.c
Optimize the memory usage of the driver and library. Avoids some of the power of 2 rounding up code while creating the resources like QP/CQ/MRs.
=> bnxt_re/lib: Optimize memory usage by the HW resources

libibverbs/man/ibv_reg_mr.3
Detail the impact of using IBV_ACCESS_RELAXED_ORDERING on the API, as it can change the visible ordering of transport message data placement. This level of detail is required for developers to understand the impact of setting the bit.
The formating of the memory registration flags is updated as a result of this change, but only the relaxed ordering details are updated.
=> verbs/man/mr: Describe the visible behavior of relaxed ordering

libibnetdisc/ibnetdisc.c
When the duplicate port is added to the map cl_qmap_insert() returns pointer to existing value and the new entry is left unused that results in leak:
==1606814== 2,624 bytes in 41 blocks are definitely lost in loss record 1 of 1
==1606814==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1606814==    by 0x5174B59: add_to_portlid_hash (ibnetdisc.c:704)
==1606814==    by 0x517638E: recv_port_info (ibnetdisc.c:379)
==1606814==    by 0x51789B0: process_one_recv (query_smp.c:200)
==1606814==    by 0x5178EF7: process_mads (query_smp.c:276)
==1606814==    by 0x51755E7: ibnd_discover_fabric (ibnetdisc.c:817)
==1606814==    by 0x109229: main (in /vagrant/go/gpu/ib-ict-manager/a.out)
The solution is to free new item if it was not added to the map. …
=> ibnetdisc: Fix leak in add_to_portlid_hash

kernel-headers/rdma/hns-abi.h, providers/hns/hns_roce_u_abi.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
The first 2 patches improve the performance of creating AH, relying on a corresponding kernel patch.
The rest patches are several bugfixes.
=> Bugfixes and improvements for libhns

providers/mlx5/dr_action.c, providers/mlx5/dr_ste_v1.c, providers/mlx5/mlx5dv_dr.h
This series in the DR area includes the below two fixes.
- Use the correct destination vport while considering whether the function is ECPF or PF.
- Allow two different domains on the same GVMI to share the same ASO CT action.
=> mlx5: DR, Few fixes

debian/ibverbs-providers.symbols, kernel-headers/rdma/efa-abi.h, providers/efa/CMakeLists.txt, providers/efa/efadv.h, providers/efa/libefa.map, providers/efa/man/CMakeLists.txt, providers/efa/man/efadv_query_mr.3.md, providers/efa/verbs.c, pyverbs/providers/efa/efa_enums.pyx, pyverbs/providers/efa/efadv.pxd, pyverbs/providers/efa/efadv.pyx, pyverbs/providers/efa/efadv_enums.pxd, pyverbs/providers/efa/libefa.pxd, tests/test_efadv.py
This PR is adding a new EFA DV interface to query for MR attributes, with an initial implementation that returns PCIe bus IDs used by the device to reach the MR to write data for receive, RDMA read, and RDMA write receive operations.
Documentation was updated accordingly and pyverbs layer and a test to cover this new functionality are being added.
=> Add query MR EFA direct verb

tests/test_qp.py
Extend test_qp coverage for all possible cases with the query_data_in_order function.
=> Extend QP query_data_in_order test

util/udma_barrier.h
The 'sync' instruction for MIPS was defined in MIPS-II as taking no operands. MIPS32 extended the define of 'sync' as taking an optional unsigned 5 bit immediate.
As a result, replace "sync 0" by "sync" to fix the following build failure on mips4 raised since version 43.0 and
https://github.com/linux-rdma/rdma-core/commit/b7c428344ea96d446f6ffe31c620a238a7f25c9e:
```
/tmp/ccrBy9fV.s: Assembler messages:
/tmp/ccrBy9fV.s:994: Error: invalid operands `sync 0'
```
Fixes:
- http://autobuild.buildroot.org/results/2ab22a3ec4287fc15ff6a90d8715b4897b32a933
=> util/udma_barrier.h: fix mips4 build

providers/bnxt_re/main.h, providers/bnxt_re/verbs.c
Some optimizations in data path for Broadcom devices. This series implements some Doorbell moderation techniques to avoid some latency in data path and help to reduce the Doorbell HW FIFO congestion.
=> bnxt_re/lib: Reduce the Doorbells during SRQ and CQ handling

tests/__init__.py
tests (unittest.loader._FailedTest.tests) ... ERROR
====================================================================== ERROR: tests (unittest.loader._FailedTest.tests)
---------------------------------------------------------------------- Traceback (most recent call last):
File "/home/leonro/src/rdma-core/tests/__init__.py", line 43, in load_tests
standard_tests.addTests(loader.loadTestsFromModule(mod, pattern))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestLoader.loadTestsFromModule() takes 2 positional arguments but 3 were given
---------------------------------------------------------------------- Ran 1 test in 0.002s
FAILED (errors=1)
=> tests: Fix runtime error in python 3.12

librdmacm/rsocket.c
Set rsocket SQ INLINE to RS_MSG_SIZE for iWARP.
=> rstream [RFC]: Set INLINE data for iWARP

providers/efa/efa_trace.h, providers/efa/verbs.c
This PR adds some additional info to EFA completion trace events.
=> providers/efa: Add src_qp and ah_num to completion trace event

providers/bnxt_re/db.c, providers/bnxt_re/main.h, providers/bnxt_re/verbs.c
Toggle bit to be used in cut off ack Doorbell needs to be copied from the Cut off CQ entry. Fix the same.
Also, format the variable declarations to reverse xmas tree style.
Fixes: d5d79c8f50cb ("bnxt_re/lib: Get the shared CQ toggle page")
=> bnxt_re/lib: Fix the toggle bit changes in resize cq path

buildlib/azure-pipelines.yml
All branches that were built on travis (v < 25.0)  are long dead and new stable branches (v50+) were not supported.
Simplify the regexp so that all stable branches trigger an Azure build.
=> buildlib: update azure trigger branches

debian/changelog, debian/control, debian/copyright, debian/libibnetdisc5.symbols
*  debian: fix minimum version for new libibnetdisc symbols
* debian: update years in debian/copyright
* debian: use unversioned library names in description
* debian: Add Debian uploads up to version 50.0-1
See individual commits for details.
=> Changes from Debian upload 50.0-1

providers/qedr/qelr_main.c
Fix the error flow of qelr_alloc_context() by making sure to free the allocated resources.
Fixes: cae4a99ae679 ("libqedr: add support for XRC-SRQ's.")
=> providers/qedr: Fix qelr_alloc_context error flow

libibverbs/memory.c
ibv_fork_init will now check if IBV_FORK_UNNEEDED is true, and if so will skip initialization of mm_root.  Environment variables like IBV_FORK_SAFE and UCX_IB_FORK_INIT are silently ignored when the kernel has the necessary fork support.
=> libibverbs: ignore IBV_FORK_SAFE et.al. when kernel has fork support

pyverbs/dmabuf_alloc.c
Fix the following error:
rdma-core-50.0/pyverbs/dmabuf_alloc.c: In function ‘drm_open’: rdma-core-50.0/pyverbs/dmabuf_alloc.c:122:28: error: assignment to ‘int (*)(struct drm *, uint64_t,  uint32_t *, int)’ {aka ‘int (*)(struct drm *, long long unsigned int,  unsigned int *, int)’} from incompatible pointer type ‘int (*)(struct drm *, size_t,  uint32_t *, int)’ {aka ‘int (*)(struct drm *, unsigned int,  unsigned int *, int)’} [-Wincompatible-pointer-types]
122 |                 drm->alloc = amdgpu_alloc;
=> pyverbs: Fix build failure

providers/bnxt_re/bnxt_re-abi.h, providers/bnxt_re/db.c, providers/bnxt_re/main.h, providers/bnxt_re/memory.c, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c
Implements few helper functions for better code maintainability. Allocates the queue memory and the shadow queue memory together and manage the  pointer for accessing the queue memory and shadow queue memory. Also splits some big functions to smaller sub functions.
=> bnxt_re/lib: Code refactoring in the resource allocation verbs

providers/efa/verbs.c
Fix arguments to rdma_tracepoint in efa_process_ex_cqe() and efa_process_cqe().
Fixes: 62c31f66310f ("providers/efa: Add src_qp and ah_num to completion trace event")
=> providers/efa: Fix arguments to rdma_tracepoint

librdmacm/man/rdma_set_local_ece.3.md
librdmacm: adjust ECE function name in man page
Replace `ibv_get_ece()` with `ibv_query_ece()`.
Fixes: 97f8668eb53e ("librdmacm: Document ECE API")
=> librdmacm: adjust ECE function name in man page

providers/qedr/qelr.h, providers/qedr/qelr_main.c, providers/qedr/qelr_verbs.c
Update the qedr provider to use the generic logging API and remove the unused debugging files.
=> providers/qedr: Use the generic logging API

CMakeLists.txt
Currently cmake script will override PYTHON_EXECUTABLE if specified in command line.
This patch should fix it. Now if PYTHON_EXECUTABLE is not empty it will be used and python version discovery will not run.
=> Make it possible to override PYTHON_VERSION when invoking cmake

kernel-headers/rdma/hns-abi.h, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_abi.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
=> libhns: Support DSCP for userspace

librdmacm/examples/cmatose.c, librdmacm/examples/cmtime.c, librdmacm/examples/common.c, librdmacm/examples/common.h, librdmacm/examples/mckey.c, librdmacm/examples/rping.c, librdmacm/examples/rstream.c, librdmacm/examples/udaddy.c, librdmacm/man/cmtime.1
There's a need to analyze and improve the CM flow.  To support that, significantly update the cmtime test to provide additional data and make it more suitable to be extended.
Changes include: Code cleanups and restructuring.  Reduce test overhead.  Replace rdma_cm management of QPs with direct QP manipulation, to get better timings of the cost of creating and modifying QPs.  Expand timing to include other steps.  Provide additional data as output.  Switch to improved time stamp calls.  Enable execution of CM paths without interacting with HW QPs.
New output looks like this:
```
Client warmup
Creating IDs
Binding addresses
Resolving addresses
Resolving routes
Creating QPs
Allocating verbs resources
Modify QPs to INIT
Connecting
Disconnecting
Destroying QPs
Destroying IDs
Connect (1000) QPs …
```
=> librdmacm/cmtime: Rework of cmtime example

providers/bnxt_re/verbs.c
Library expects ilog2 of psn_size while calculating the stride. ilog32 returns log2(v) + 1 and the calculation fails since the psn size is a power of 2 value. Fix by passing psn_size - 1.
Fixes: 0a0e0d0114c5 ("bnxt_re/lib: Adds MSN table capability for Gen P7 adapters")
=> bnxt_re/lib: Fix the stride calculation for MSN/PSN area

librdmacm/examples/CMakeLists.txt, librdmacm/examples/cmtime.c, librdmacm/examples/common.c, librdmacm/examples/common.h, librdmacm/man/cmtime.1
The primary objective of this series is to add multi-thread support to the cmtime app. Multi-threading is added by abstracting and generalizing the work queue abstraction used by cmtime.  (If there's a usable version of a work queue suitable for rdma-core use, I can switch to that if needed.)  The series also adds:
- Ability to 'mimic' QP operations, by replacing QP calls with sleeps.  This allows testing at scales where QP resources may not be available.
- Add out-of-band synchronization mechanism to enable more precise timing of different testing steps.
- Remove incomplete, complex, and unnecessary error handling.  Just abort test on unexpected errors.
The final version of cmtime could use a review to verify that it is capturing the data as intended.
=> librdmacm/cmtime: Add multi-thread support

providers/hns/hns_roce_u.c, providers/hns/hns_roce_u_db.c, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
This PR contains serveral bugfixes and cleanups.
=> libhns: Bugfixes and cleanups

librdmacm/cma.c
This PR introduces two fixes in librdmacm, details exist as part of the commit logs.
=> librdmacm: Misc. fixes

kernel-headers/rdma/efa-abi.h, kernel-headers/rdma/mana-abi.h, kernel-headers/rdma/rdma_netlink.h, providers/efa/efa_io_defs.h, providers/efa/efadv.h, providers/efa/man/efadv_create_cq.3.md, providers/efa/man/efadv_create_qp_ex.3.md, providers/efa/man/efadv_query_device.3.md, providers/efa/verbs.c, pyverbs/providers/efa/efa_enums.pxd, pyverbs/providers/efa/efadv.pyx, pyverbs/providers/efa/libefa.pxd
This PR extends the EFA direct verbs to enable creation of QPs which RQs do not require explicit receive work requests to anticipate incoming RDMA write with immediate. A new work completion query function allows checking whether a work completion is unsolicited.
Related kernel patch: https://lore.kernel.org/all/20240506104859.9225-1-mrgolin@amazon.com/
=> efa: Add unsolicited RDMA write with immediate receive support

providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
The first patch optimizes cqe inline in srq scenario.
The second one is a bugfix that add checks for input param.
=> libhns: One optimization and one bugfix

debian/ibverbs-providers.lintian-overrides
The libhns library is named `libhns1` instead of `libhns-1`.
Fixes: cf6d9149f8f5 ("libhns: Introduce hns direct verbs")
=> debian: Correct libhns library name in lintian override

providers/mlx5/cq.c
We saw deadlock in mlx5_destroy_qp() if ibv_start_poll() returns EBUSY failure.
According to reference (https://man7.org/linux/man-pages/man3/ibv_create_cq_ex.3.html), if ibv_start_poll() returns error, ibv_end_poll() shouldn't be called.
Therefore, we must release the CQ lock in mlx5_start_poll() if mlx5dv_get_clock_info() returns error e.g. EBUSY.
=> fix potential CQ deadlock in mlx5 provider

libibverbs/examples/xsrq_pingpong.c
0f93a15897a32 ("verbs: Set default MTU for the xsrq ping-pong to be 1024")
Signed-off-by: Honggang LI <honggangli@163.com>
=> verbs: update xsrq_pingpong usage message

CMakeLists.txt
Canonical `libdrm` package installation results in headers installed at `\usr\include\libdrm.` The current `CMakeLists.txt` installation script searches the headers only in the `drm` suffix, where headers are found in RedHat-based distros.  This is not the canonical location. I propose adding the canonical path `libdrm`, also used in distros like archlinux. Cuurently such distros must patch the main `CMakeLists.txt`  file before installation.
https://gitlab.archlinux.org/archlinux/packaging/packages/rdma-core
=> Added suffix libdrm to CMakeLists.txt for drm

debian/rules
The provider `hns` requires coherent DMA and will not build on architectures that lack coherent DMA. So exclude trying to install them on those architectures.
Bug-Debian: https://bugs.debian.org/1073050
=> debian: exclude hns provider on archs without coherent DMA

kernel-headers/rdma/ib_user_ioctl_cmds.h, kernel-headers/rdma/mana-abi.h, kernel-headers/rdma/mlx5_user_ioctl_cmds.h, libibverbs/cmd_cq.c, libibverbs/cmd_write.h, libibverbs/driver.h, libibverbs/libibverbs.map.in, providers/mlx5/verbs.c
This series adds support for creating a CQ with a large UAR page index.
The first patch addresses a bug by explicitly failing any creation attempt where the index value exceeds 16 bits, preventing overflow.
Subsequent patches provide the necessary support to allow CQ creation with an index of up to 32 bits.
This series aligns with the kernel series that have already been submitted to rdma-next.
=> mlx5: Add support for creating a CQ with a large UAR page index

providers/mana/CMakeLists.txt, providers/mana/cq.c, providers/mana/doorbells.h, providers/mana/gdma.h, providers/mana/mana.c, providers/mana/mana.h, providers/mana/manadv.c, providers/mana/qp.c, providers/mana/rollback.h, providers/mana/shadow_queue.h, providers/mana/wr.c
This patch series aims to provide RC QP functionality to mana.
=> providers/mana: RC QPs

providers/bnxt_re/db.c
Doorbell FIFO information register is a 32 bit register. Reading it as a 64bit from the BAR area may give wrong values. So change the variable pointer to 32 bit.
Fixes: ef9d1cd30a27 ("bnxt_re/lib: Implement doorbell pacing algorithm")
=> bnxt_re/lib: Fix doorbell fifo register read

providers/hns/hns_roce_u.c, providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
This series adds support for thread domain and parent doamin in libhns. When QP/CQ/SRQ are associated to a PAD holding a TD, they'll be set to lock-free mode, and all locks will be drop in data path to improve performance.
=> libhns: Support lock-free for data path

kernel-boot/rdma_rename.c, kernel-headers/rdma/rdma_netlink.h
This series avoids the device renaming step if the name is provided by userspace.
It aligns with the corresponding kernel series that has already been accepted into rdma-next.
=> kernel-boot: Avoid the device renaming step if the name is provided by userspace

kernel-boot/rdma-load-modules@.service.in, redhat/rdma.modules-setup.sh, suse/module-setup.sh
Fixed an issue where the RDMA service was killed during switch to root. Added a wants symlink for initrd.target in the dracut arrangement and Before=initrd.target to the systemd service to ensure it runs and completes during initrd.
=> Ensure RDMA service loads modules in initrd

CMakeLists.txt
Without these arguments quoted, cmake 3.30.0 fails with
```
CMake Error at CMakeLists.txt:550 (if):
if given arguments:
"EXISTS" "/usr/include" "/usr/include/libdrm/i915_drm.h" "AND" "EXISTS" "/usr/include" "/usr/include/libdrm/amdgpu_drm.h"
Unknown arguments specified
```
=> cmake: Avoid "Unknown arguments specified"

librdmacm/rsocket.c
When the cm_svc_run thread starts, the four element size rss will be allocated to svc->contexts. When the rss reallocates memory due to an increase in the number of elements in the cm_svc_process_sock function, the rss will point to a new address, but the cm_svc_run function does not get the new address again, leading to an exception in the future
=> Fix for cm_svc_run

debian/libibumad3.symbols, libibumad/CMakeLists.txt, libibumad/libibumad.map, libibumad/man/umad_open_smi_port.3, libibumad/umad.c, libibumad/umad.h
Added umad_open_smi_port which operates the same as umad_open_port, but ensures the port opened is an SMI port.
=> libibumad: Add function that opens SMI ports

providers/hns/hns_roce_u_hw_v2.c
According to the man page ibv_wr_post.3.md,
"The provider should provide locking to ensure that ibv_wr_start() and ibv_wr_complete()/abort() form a per-QP critical section where no other threads can enter."
Currently the exception branch of wr_start() is not locked, add a lock here.
Fixes: 36446a56eea5 ("libhns: Extended QP supports the new post send mechanism")
=> libhns: Fix no locking in the exception branch of wr start()

debian/ibverbs-providers.symbols, kernel-headers/rdma/mlx5_user_ioctl_cmds.h, kernel-headers/rdma/mlx5_user_ioctl_verbs.h, libibverbs/cmd_mr.c, libibverbs/driver.h, providers/bnxt_re/verbs.c, providers/efa/verbs.c, providers/irdma/uverbs.c, providers/mlx5/CMakeLists.txt, providers/mlx5/libmlx5.map, providers/mlx5/man/CMakeLists.txt, providers/mlx5/man/mlx5dv_get_data_direct_sysfs_path.3.md, providers/mlx5/man/mlx5dv_reg_dmabuf_mr.3.md, providers/mlx5/mlx5.h, providers/mlx5/mlx5_api.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c
This patch series aims to enable multi-path DMA support, allowing an mlx5 RDMA device to issue DMA commands through multiple paths.
This feature is critical for improving performance and achieving line rates in environments where issuing PCI transactions over one path may be significantly faster than over another. These differences can arise from various PCI generations in the system or the specific system topology.
The series introduces the following two mlx5 DV APIs:
mlx5dv_reg_dmabuf_mr() -  This API allows applications to register a memory region (MR) based on dma-buf with specific mlx5 device flags to request the data direct functionality.
mlx5dv_get_data_direct_sysfs_path() - This API returns the sysfs path of the data direct device associated with a given RDMA device.
Detailed man …
=> Introducing Multi-Path DMA support for mlx5 RDMA device

libibverbs/driver.h
Previously, the token pasting operator was not being applied to any of the PROVIDER_DRIVER macro aguments, so every provider's constructor had the same name of "drv__register_driver".
Now, these constructors will be named using the provider name as the prefix, resulting in names like "irdma_register_driver".
=> verbs: Use provider name when generating provider constructor

kernel-headers/rdma/bnxt_re-abi.h, providers/bnxt_re/main.c, providers/bnxt_re/verbs.c
Enable the Variable size Work Queue entry support for Gen P7 adapters. This would
help in the better utilization of the queue memory and pci bandwidth due to the
smaller send queue Work entries.
=> bnxt_re/lib: Variable size Work Queue entry support for Gen P7 adapters

providers/cxgb4/cq.c
t4_cqe_common pointer not updated in c4iw_flush_hw_cq(), so it always process first hw_cqe only even though cq contains multiple cqe, this patch resolves the issue by updating the t4_cqe_common pointer.
Fixes: 37e77d53e757 ("cxgb4: Add support for 64Byte cqes")
=> cxgb4: update t4_cqe_common pointer in c4iw_flush_hw_cq()

debian/libibmad5.symbols, libibmad/CMakeLists.txt, libibmad/libibmad.map, libibmad/mad.h, libibmad/register.c
This series includes the below changes in libibmad:
- Remove mad_register_port_client() from mad.h as it's not actually exported from the library.
- Expose the XDR speed decoding functions from the library.
Further details exist in the commit logs.
=> libibmad: Misc. items

providers/mlx5/cq.c
Update the mlx5_sig_err output for sig_type and domain to only include a 3-bit value, ensuring strict compliance with the device specification.
=> mlx5: Fix mlx5_sig_err output for sig_type and domain

kernel-headers/rdma/bnxt_re-abi.h, providers/bnxt_re/db.c, providers/bnxt_re/main.h, providers/bnxt_re/verbs.c
Implements the UAPI call to get the SRQ toggle page.
Also, get the toggle bit from the shared page and
use it while arming the SRQ.
=> bnxt_re/lib: SRQ toggle support for GenP7 adapters

providers/bnxt_re/db.c, providers/bnxt_re/memory.h, providers/bnxt_re/verbs.c
Couple of fixes in resize_cq path.. Also, report the vendor error status.
=> bnxt_re/lib: driver fixes in resize_cq path

infiniband-diags/ibstat.c
ibstat relies on umad_get_ca() to retrieve device's statistics. However, in case the latter function fails on a certain device, ibstat panics and exits before processing and displaying other device's statistics which may be obtainable.
Thus, warn on failed device query and continue querying the remaining devices instead of an early exit.
=> ibdiags: Do not panic on ibstat query failure

pyverbs/cq.pyx, tests/mlx5_base.py, tests/mlx5_prm_structs.py, tests/test_mlx5_devx.py, tests/test_mlx5_mkey.py, tests/utils.py
Extend ODP coverage by adding ODP over DevX and ODP with indirect mkey tests.
The series includes a minor test fix and an exposure of the CQ C object for Python users' usage.
=> tests: Extend ODP coverage

providers/rxe/rxe.c
The rkeys are being calculated the same way, so just use the helper instead.
=> rxe: use ibv_inc_rkey helper for generating type 1 bind rkey

libibverbs/verbs.h
The macro name should be [IBV_ACCESS_OPTIONAL_RANGE](https://github.com/linux-rdma/rdma-core/blob/v54.0/libibverbs/verbs_api.h#L97) instead of  ```IBV_OPTIONAL_ACCESS_RANGE```
=> libibverbs: correct access range bits flag name

kernel-headers/rdma/efa-abi.h, kernel-headers/rdma/mlx5-abi.h, kernel-headers/rdma/rdma_netlink.h, providers/mlx5/cq.c, providers/mlx5/man/mlx5dv_create_qp.3.md, providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/mlx5_ifc.h, providers/mlx5/mlx5dv.h, providers/mlx5/verbs.c
This series introduces the data direct placement (DDP) functionality for the mlx5 provider over the DV API.
This feature allows WRs on the receiver side of the QP to be consumed out of order, permitting the sender side to transmit messages without guaranteeing arrival order on the receiver side.
When enabled, the completion ordering of WRs remains in-order, regardless of the Receive WRs consumption order.
When the application understands the new rules for processing CQEs/etc. it sets a new DV bit during QP creation.
The relevant man pages were extended to describe the expected usage and the semantics for DDP.
Further details exist as part of the commit messages.
The matching kernel series was sent already to rdma-next.
=> mlx5: Introduce data direct placement (DDP) over the DV API

providers/bnxt_re/verbs.c, tests/test_cq.py
bnxt_re driver implement the CQ shrinking operation in a way that allows users to shrink CQ with a size smaller than the existing CQE and still have access to old CQEs please see:
- https://github.com/linux-rdma/rdma-core/pull/1315
The test_resize_cq assumes that when shrinking an active CQ with unpolled entries it fail with an EINVAL error, which is not true for bnxt_re devices.
To avoid this failure for bnxt we skip part of the test that expect EINVAL.
=> tests: Skip CQ shrinking for bnxt_re devices.

kernel-headers/rdma/efa-abi.h, kernel-headers/rdma/rdma_netlink.h, providers/efa/efadv.h, providers/efa/man/efadv_create_qp_ex.3.md, providers/efa/verbs.c, pyverbs/providers/efa/efadv.pyx, pyverbs/providers/efa/libefa.pxd
Add SL parameter to EFA create QP direct verb and pass it to the kernel.
Update Pyverbs and documentation accordingly.
The related kernel patches are [here](https://lore.kernel.org/all/20241015174242.3490-1-mrgolin@amazon.com/).
=> Add QP service level in EFA DV

providers/hns/hns_roce_u_hw_v2.c
Two bugfixes in post_send flow
=> libhns: Two bugfixes in post_send flow

libibnetdisc/ibnetdisc_cache.c, librdmacm/examples/cmtime.c, providers/mlx5/dr_vports.c, pyverbs/providers/mlx5/mlx5dv.pyx
Recently, I updated my host to fedora40 and rebuilt the rdma-core. The compiler complained a few warnings.
gcc: gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)
```
make -C build 2>&1 | grep -i -A3 -B1 warning
[ 37%] Building C object librdmacm/CMakeFiles/rspreload.dir/preload.c.o
/home/lizhijian/rdma-core/librdmacm/preload.c:1175:5: warning: no previous prototype for ‘__fxstat’ [-Wmissing-prototypes]
1175 | int __fxstat(int ver, int socket, struct stat *buf)
|     ^~~~~~~~
[ 37%] Linking C shared module ../lib/librspreload.so
--
/home/lizhijian/rdma-core/providers/mlx5/dr_vports.c: In function ‘dr_vports_table_del_wire’:
/home/lizhijian/rdma-core/providers/mlx5/dr_vports.c:247:36: warning: ‘prev’ may be used uninitialized [-Wmaybe-uninitialized]
247 |                         prev->next = …
```
=> Fix compiling warnings on fedora40

util/udma_barrier.h
Change the barrier APIs for IO to reflect that Armv8-a is other-multi-copy atomicity memory model.
Armv8-a memory model has been strengthened to require other-multi-copy atomicity. This property requires memory accesses from an observer to become visible to all other observers simultaneously [3]. This means
a) A write arriving at an endpoint shared between multiple CPUs is
visible to all CPUs
b) A write that is visible to all CPUs is also visible to all other
observers in the shareability domain
This allows for using cheaper DMB instructions in the place of DSB for devices that are visible to all CPUs
Please refer to [1], [2] and [3] for more information.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=22ec71615d824f4f11d38d0e55a88d8956b7e45f
[2] …
=> util/udma_barrier.h: adjust ARMv8 memory barriers

buildlib/azure-pipelines-release.yml
By default, AZP creates a release on Github names vXX.YY which does not match the format currently used: rdma-core-XX.YY This changes the release name to match the expected format.
Fixes: 936cf8e17cf3 ("build/azp: Have Azure Pipelines create releases when tags are made")
=> buildlib: set a proper name when creating a github release

providers/mlx5/cq.c
When using cq_ex inteface, if the user destroys the QP associated with the current work completion, the next ibv_next_poll() call will cause a use-after-free error since it needs to access the QP that has already been destroyed through cq->cur_rsc inside get_req_context().
Fix this error by resetting the cq->cur_rsc in __mlx5_cq_clean if it is associated with the QP to be destroyed.
=> mlx5: invalidate cq->cur_rsc when QP is destroyed inside a polling batch

pyverbs/device.pyx
Add missing width to the width_to_str mapping array.
=> pyverbs: Add 12X to width_to_str mapping array

providers/bnxt_re/main.h, providers/bnxt_re/verbs.c
Initialize the qp with a push buffer during QP create. Use the push buffer directly in post_send, instead of getting it using a bit map. This avoids few cpu cycles in data path.
This is adding a limiation where the first 15 QPs
of any application works in push mode.
=> bnxt_re/lib: Avoid getting push buffer from data path.

providers/efa/efa.h, providers/efa/verbs.c
Remove the CQ doorbell offset on munmap to get the aligned address provided by mmap.
When using the unaligned address IB core gets wrong VMA to its umap close callback with private data NULL so it doesn't drop the reference on the mmap entry. This means that we don't remove the entry from the mmap xarray and when requesting to close the device it fails because of open resources on it.
Fixes: 94ed75b42a2d ("efa: CQ notifications support")
=> efa: Fix CQ doorbell unmap on CQ destroy

providers/bnxt_re/main.c, providers/bnxt_re/main.h, providers/bnxt_re/verbs.c, providers/bnxt_re/verbs.h
Add WR API send functions
Add the support for the following WR API send
functions
- wr_rdma_write
- wr_rdma_write_imm
- wr_send
- wr_send_imm
- wr_rdma_read
- wr_atomic_cmp_swp
- wr_atomic_fetch_add
=> bnxt_re/lib: Add support WR APIs

debian/libibmad5.symbols, debian/libibumad3.symbols, infiniband-diags/smpquery.c, libibmad/CMakeLists.txt, libibmad/libibmad.map, libibmad/mad.h, libibmad/rpc.c, libibumad/CMakeLists.txt, libibumad/libibumad.map, libibumad/man/umad_get_smi_gsi_pair_by_ca_name.3, libibumad/man/umad_get_smi_gsi_pairs.3, libibumad/umad.c, libibumad/umad.h
Add support SMI/GSI separation
This patch adds support SMI/GSI separation in XDR-supported HCAs by
introducing new APIs and structures in libibumad and libibmad.
In libibumad:
- Add umad_get_smi_gsi_pairs() and umad_get_smi_gsi_pairs_by_name().
- Introduce umad_ca_pair to represent SMI/GSI pairs.
In libibmad:
- Add mad_rpc_open_port2() and mad_rpc_close_port2().
- Return an ibmad_ports_pair structure from mad_rpc_open_port2().
In smpquery:
- Demonstrate the new API to retrieve SMI/GSI details and properly
use the SMI or GSI port based on the call type:
- GMP calls (e.g., resolve_portid_str()) use the GSI port.
- SMP calls (e.g., smp_query_via()) use the SMI port.
=> Add support for XDR infiniband tools

providers/hns/hns_roce_u_hw_v2.c
The sl and src_qpn fields in recv-WC are not filled when the QP is UD and has an SRQ. Here fix it.
In addition, UD QP does not support RQ INLINE and CQE INLINE features. Reorder the related if-else statements to reduce the number of conditional checks in IO path.
Fixes: 061f7e1757ca ("libhns: Refactor the poll one interface")
=> libhns: Fix missing fields for SRQ WC

tests/test_device.py
Avoid running the test_get_pkey_index test on devices that are not IBV_NODE_CA, also make sure to use the get_device_list().
=> tests: Fix test_get_pkey_index

tests/test_device.py
Make sure to iterate over all the devices from get_device_list().
=> tests: test_device: Fix the use of get_device_list()

debian/changelog, debian/control, debian/ibverbs-providers.install, debian/libibmad5.symbols, debian/libibumad3.symbols, debian/libibverbs-dev.install, debian/rules
* debian: Bump Standards-Version to 4.7.0
* debian: add IBMAD_1.4@IBMAD_1.4 symbol (fixes 57b50e2064f4)
* debian: run wrap-and-sort
* debian: Add Debian uploads up to version 55.0-1
* libibumad: Correct symbols for new API to support SMI/GSI seperation (fixes be54b52e94be)
* libibmad: Correct symbols for new API to support SMI/GSI seperation (fixes fb11e5a40402)
* debian: Switch to automatically created -dbgsym packages
See individual commits for details. Switch to automatically created -dbgsym packages should be safe, because since the stable releases support it.
=> Changes from Debian upload 55.0 1 plus fixes

providers/bnxt_re/verbs.c
Avoid memory leak in bnxt_re_create_cq() by freeing "cq->mem".
Fixes: d035125e3643 ("bnxt_re/lib: Refactor CQ create verb implementation")
=> providers/bnxt_re: Fix memory leak

infiniband-diags/dump_fts.c, infiniband-diags/ibaddr.c, infiniband-diags/ibccconfig.c, infiniband-diags/ibccquery.c, infiniband-diags/ibdiag_sa.c, infiniband-diags/ibdiag_sa.h, infiniband-diags/iblinkinfo.c, infiniband-diags/ibping.c, infiniband-diags/ibportstate.c, infiniband-diags/ibqueryerrors.c, infiniband-diags/ibroute.c, infiniband-diags/ibsendtrap.c, infiniband-diags/ibsysstat.c, infiniband-diags/ibtracert.c, infiniband-diags/mcm_rereg_test.c, infiniband-diags/perfquery.c, infiniband-diags/saquery.c, infiniband-diags/sminfo.c, infiniband-diags/vendstat.c, libibnetdisc/ibnetdisc.c
Use API supporting SMI/GSI separation to fix the following infiniband-diags tools:
- ibnetdisc
- dump_fts
- ibaddr
- ibccconfig
- ibccquery
- iblinkinfo
- ibping
- ibportstate
- ibqueryerrors
- ibroute
- ibsendtrap
- ibsysstat
- ibtracert
- mcm_reregtest
- perfquery
- sminfo
- vendstat
=> Fix infiniband-diags tools to support planarized network

tests/base.py
Avoid the following failure when running test_rdmacm_async_udp_traffic over the qedr provider because the test is not supported:
test_rdmacm_async_udp_traffic (tests.test_rdmacm.CMTestCase) ... Player active got: Failed to Create QP. Errno: 95, Operation not supported ERROR
=> tests: Skip test_rdmacm_async_udp_traffic

librdmacm/cma.c
When an RNIC with `node_guid` 0 is present, `rdma_resolve_addr` succeeds with `ADDR_RESOLVED` but subsequent device initialization can fail. This occurs because `ucma_query_addr` and `ucma_query_route` skip device initialization when the kernel returns a zero `node_guid`, leading to NULL pointer access in `ucma_process_addr_resolved`.
Add explicit `NULL` checks for `id->verbs` after `ucma_query_addr` and `ucma_query_route` calls. Return `ENODEV` error if device initialization fails, ensuring proper error propagation instead of crashes.
Note: `ucma_query_addr` must still return success in this case as it's used for probing `AF_IB` support, which intentionally skips device initialization.
This is easily reproducible with this RNIC configuration and C code:
```shell
$ ibv_devinfo
hca_id: …
```
=> librdmacm: prevent NULL pointer access during device initialization

libibumad/umad.c
Updated the find_preferred_port function to ensure the same port number is set for SMI/GSI
devices when they belong to the same device.
This prevents selecting different ports for the same device.
=> libibumad: Change find_preffered_port

infiniband-diags/ibdiag_common.c, libibnetdisc/ibnetdisc.c
Added get_port_info_for_cap_mask to retrieve the correct port information for determining the cap_mask -
in the case of a Switch we should be using port 0, In other cases it should be the current port.
This function is now utilized with the ibnd_get_agg_linkspeedext methods in ibdiag_common to ensure accurate handling.
=> infiniband-diags: use correct port info to get cap_mask for ibnd_get_agg_linkspeedextsup

providers/mana/cq.c, providers/mana/gdma.h, providers/mana/mana.c, providers/mana/mana.h, providers/mana/qp.c, providers/mana/shadow_queue.h, providers/mana/wr.c
This patch series addresses several small bugs:
- Use correct return values
- Posting WRs with zero SGEs
- Fix modify_qp to Init and Rts
Then it adds support of the following features:
- signal all RC QPs
- polling error CQEs and providing error completions
=> providers/mana: fixes + error CQEs

redhat/rdma-core.spec
Add the missing systemd restart bits for the rdma-load-modules.
=> redhat: Add missing rdma-load-modules systemd scriptlets

providers/hfi1verbs/verbs.c, providers/ipathverbs/verbs.c, providers/rxe/rxe.c
Fix the following issue:
overrun-buffer-arg: Overrunning struct type ibv_modify_srq of 24 bytes by passing it to a function which accesses it at byte offset 31 using argument "32UL".
=> providers: Fix overrun-buffer-arg issues

pyverbs/wr.pyx, tests/base.py, tests/test_mlx5_dr.py, tests/test_mlx5_vfio.py, tests/test_qp.py
Extend basic QP tests with RD atomic.
Allow RecvWR to have 0 SGEs in PyVerbs (it was required to have at least one).
The series includes adjustments to fix corner case failures such as race, specific unsupported platforms, etc.
=> tests: Add QP basic test and enhance stability

infiniband-diags/man/ibportstate.8.in.rst, infiniband-diags/man/ibroute.8.in.rst, infiniband-diags/man/ibstat.8.in.rst, infiniband-diags/man/ibstatus.8.in.rst, infiniband-diags/man/ibtracert.8.in.rst, infiniband-diags/man/sminfo.8.in.rst, infiniband-diags/man/smpdump.8.in.rst, infiniband-diags/man/smpquery.8.in.rst, infiniband-diags/man/vendstat.8.in.rst
An empty line is needed just after "::" as explained in https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks
=> ibdiags: fix the usage of literal block indicators in the man pages

providers/mlx5/mlx5.h
The current length of `mlx5_context.hostname` is a 40 bytes long. According to `gethostname`'s man-page, and also the standard of POSIX. The maximum length is `HOST_NAME_MAX`, which is 64 bytes.
And also, the [RFC1034](https://datatracker.ietf.org/doc/html/rfc1034#section-3.1), the maximum length is also about 64 bytes.
So, I made this patch to follow the standards.
=> mlx5: fix max length of hostname

pyverbs/cq.pyx
This allows using pollfd to wait with a timeout, e.g. as in https://www.rdmamojo.com/2013/03/09/ibv_get_cq_event/
I found it hard to use `ibv_get_cq_event` in a race-free way without setting the fd to `O_NONBLOCK`.
=> pyverbs: Expose fd of ibv_comp_channel.

providers/mana/mana.c, providers/mana/mana.h
Add support for dma-buf MR verb API in mana.
=> providers/mana: Add dma-buf support

providers/efa/verbs.c
EFA supports 16 bit length for receive buffers, but will receive only up to MTU size messages, so the rest of the receive buffer is unused. Posting a 64KB buffer will end up wrapping around to zero. Instead, Truncate it to the maximum size, which is higher than EFA MTU.
Reviewed-by: Michael Margolin <mrgolin@amazon.com>
Reviewed-by: Yonatan Nachum <ynachum@amazon.com>
=> efa: Fix receive SGE length overflow

providers/qedr/qelr_verbs.c
Fix the following issue:
providers/qedr/qelr_verbs.c:703:2: var_decl: Declaring variable "rc" without initializer. providers/qedr/qelr_verbs.c:726:2: uninit_use: Using uninitialized value "rc".
Fixes: cae4a99ae679 ("libqedr: add support for XRC-SRQ's.")
=> qedr: Fix uninit_use issue

providers/cxgb4/verbs.c
Error: UNINIT (CWE-457): [#def102] [important]
providers/cxgb4/verbs.c:280:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:303:2: uninit_use: Using uninitialized value "resp.srqid".
Error: UNINIT (CWE-457): [#def103] [important]
providers/cxgb4/verbs.c:420:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:443:2: uninit_use: Using uninitialized value "resp.qid_mask".
Error: UNINIT (CWE-457): [#def104] [important]
providers/cxgb4/verbs.c:523:2: var_decl: Declaring variable "resp" without initializer.
providers/cxgb4/verbs.c:547:2: uninit_use: Using uninitialized value "resp.qid_mask".
=> cxgb4: Fix uninit_use issues

providers/mlx4/mlx4.c, providers/mlx4/verbs.c
Fix multiple uninitialized values and overrun issues found in the mlx4 provider.
=> mlx4: Fix uninitialized values and overrun

providers/vmw_pvrdma/pvrdma_main.c, providers/vmw_pvrdma/qp.c
Fix the following issues:
Error: UNINIT (CWE-457): [#def152] [important]
providers/vmw_pvrdma/pvrdma_main.c:115:2: var_decl: Declaring variable "resp" without initializer. providers/vmw_pvrdma/pvrdma_main.c:122:2: uninit_use: Using uninitialized value "resp.qp_tab_size".
Error: UNINIT (CWE-457): [#def153] [important]
providers/vmw_pvrdma/qp.c:111:2: var_decl: Declaring variable "resp" without initializer.
providers/vmw_pvrdma/qp.c:150:2: uninit_use: Using uninitialized value "resp.srqn".
Fixes: 4c8ed14eb6b7 ("vmw_pvrdma: Add SRQ support")
=> vmw_pvrdma: Fix uninit_use issue

providers/bnxt_re/main.h
The pointer used in the destination buffer is not correctly type casted, because of which the data gets corrupted while copying. The issue is seen in the previous adapters that has the low latency push enabled. Fixing the pointer casting.
Fixes: 52d0870c3eac ("bnxt_re/lib: Enable low latency push")
Reported-By: Kamal Heib <kheib@redhat.com>
=> bnxt_re/lib: Fix the data copy during the low latency push path

tests/test_odp.py, tests/test_qpex.py
tests: Apply unified naming convention to zero size tests
tests: Force page fault for ODP atomic testcases
For the better coverage of test scenarios, it is better to force page fault in ODP atomic testcases.
=> tests: small improvement and fix

CMakeLists.txt, libibverbs/examples/CMakeLists.txt, libibverbs/verbs.h
Fix cast-align warning with verbs_get_ctx().
Casting using uint8_t * pointer arithmetic may generate a cast-align warning, when using "-Wcast-align=strict" compilation flag.
Fix it by using uintptr_t instead of uint8_t *.
=> libibverbs: Fix cast-align warning with verbs_get_ctx().

providers/ocrdma/ocrdma_main.c, providers/ocrdma/ocrdma_verbs.c
Fix the following issues:
Error: UNINIT (CWE-457): [#def138] [important]
providers/ocrdma/ocrdma_main.c:118:2: var_decl: Declaring variable "resp" without initializer. providers/ocrdma/ocrdma_main.c:132:2: uninit_use: Using uninitialized value "resp.dev_id".
Error: UNINIT (CWE-457): [#def140] [important]
providers/ocrdma/ocrdma_verbs.c:359:2: var_decl: Declaring variable "resp" without initializer.
providers/ocrdma/ocrdma_verbs.c:373:2: uninit_use: Using uninitialized value "resp.rq_dbid".
Error: UNINIT (CWE-457): [#def141] [important]
providers/ocrdma/ocrdma_verbs.c:469:2: var_decl: Declaring variable "resp" without initializer.
providers/ocrdma/ocrdma_verbs.c:504:2: uninit_use: Using uninitialized value "resp.qp_id".
Fixes: ede311583f51 ("Added libocrdma files")
=> ocrdma: Fix uninit_use issues

providers/rxe/rxe.c
Fix the following issues:
Error: UNINIT (CWE-457): [#def142] [important]
providers/rxe/rxe.c:584:2: var_decl: Declaring variable "resp" without initializer. providers/rxe/rxe.c:600:2: uninit_use_in_call: Using uninitialized value "resp.mi.size" when calling "mmap".
Error: UNINIT (CWE-457): [#def143] [important]
rdma-core-54.0/providers/rxe/rxe.c:623:2: var_decl: Declaring variable "resp" without initializer.
rdma-core-54.0/providers/rxe/rxe.c:639:2: uninit_use_in_call: Using uninitialized value "resp.mi.size" when calling "mmap".
Fixes: e05647a484a5 ("providers/rxe: Implement create_srq_ex")
=> rxe: Fix uninit_use_in_call issues

libibumad/umad.c
Updated start index from 1 to 0 in:
- count_ports_by_guid
- umad_get_smi_gsi_pairs
- umad_find_active
This fix should add support for switches
(In HCA port 0 will be null and skipped)
Fixes: be54b52e94be ("libibumad: Add new API to support SMI/GSI seperation")
=> libibumad: Fix iteration index for switches

providers/mana/shadow_queue.h
Use release/acquire semantics for the shadow queue.
It ensures synchronization between sender and poller threads.
=> providers/mana: improve synchronization on the shadow queue

providers/mlx4/verbs.c
This reverts commit 4d92ff74aa3d4a4b0181ea0db103377c7034dcb4.
A regression was found when testing resize_cq using pyverbs.
Fixes: 4d92ff74aa3d ("mlx4: Fix overrun-buffer-arg")
=> Revert "mlx4: Fix overrun-buffer-arg"

providers/hfi1verbs/verbs.c, providers/ipathverbs/verbs.c, providers/rxe/rxe.c
This reverts commit f14033565dc0152bb2902046a1c2464a61eb652c. Avoid regression that could introduced as the lower level functions are supposed to accept the full size of the struct including the driver data portion.
Fixes: f14033565dc0 ("providers: Fix overrun-buffer-arg issues")
=> Revert "providers: Fix overrun-buffer-arg issues"

providers/hns/hns_roce_u.h, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_verbs.c
This PR contains some recent cleanup and bugfixes for libhns.
=> libhns: Cleanup and Bugfixes

buildlib/azp-checkpatch
kernel.org added DDOS protection from AI bot scrappers, which causes to the "urllib.error.HTTPError: HTTP Error 403: Forbidden" error while executing azp=checkpatch test.
Official solution is to set meaningful User-agent, so do it.
=> azp: Overcome kernel.org AI protection check

providers/mthca/memfree.c
mthca: Fix malloc() return value without detecting null pointer
=> mthca: Fix malloc() return value without detecting null pointer

providers/hns/CMakeLists.txt, providers/hns/hns_roce_u_hw_v2.c, providers/hns/hns_roce_u_trace.c, providers/hns/hns_roce_u_trace.h
Add support for LTTng tracing. For now it is used for post_send, post_recv and poll_cq.
=> libhns: Add support for LTTng tracing

libibumad/umad.c
In case the local IB interface is broken and some of its ports have zero GUIDs, the tools will fail and cannot be used, even if the correct interface is selected. The fix in umad_get_smi_gsi_pairs skips ports with zero GUIDs.
=> libibumad: Skip Zero GUIDs local port interfaces

srp_daemon/srp_sync.c
srp_daemon: Fix malloc() return value without detecting null pointer
=> srp_daemon: Fix malloc return value without detecting null pointer

libibverbs/cmd_srq.c, providers/hns/hns_roce_u_verbs.c
The issue of the last commit was found when I created a XRC SRQ in lock-free mode but failed to destroy it because of the refcnt check added in the previous commit.
The failure was because the PAD was acquired through ibv_srq->pd in destroy_srq(), while ibv_srq->pd wasn't assigned when the SRQ was created by ibv_create_srq_ex(). So let's assign ibv_srq->pd in the common ibv_icmd_create_srq() , so that drivers can get the correct pd no matter which api the SRQ is created by.
=> libhns: Bugfixes and one debug improvement

librdmacm/rsocket.c
Fix use of uninitialized ret, 'ret' may be used uninitialized at librdmacm\rsocket.c line 2703.
This is because it is possible that the 'ret' assignment logic may not be executed due to the empty &rs->iomap_queue in line 2647
=> rsocket: Fix use of uninitialized ret

librdmacm/examples/rping.c
Fix typos in comments. 110 line comment field error in./librdmacm/examples/rping. c file, modify iff to if
=> rping: Fix typos in comments

infiniband-diags/ibdiag_sa.c
When realloc() fails on line 142 of infiniband-diags/ibdiag_sta. c, it will cause the loss of the umad's original memory reference, resulting in a leak of the original memory.
The modified logic is to store the result in a temporary variable new_umad before calling realloc, which can avoid directly overwriting the original pointer umad and prevent losing the reference to the original memory when realloc fails.
=> ibdiag_sa: Fix memory leak in sa_query()

kernel-headers/rdma/ib_user_verbs.h, libibverbs/examples/devinfo.c, libibverbs/man/ibv_query_device_ex.3, libibverbs/verbs.h, pyverbs/device.pyx, pyverbs/libibverbs_enums.pxd, tests/test_odp.py, tests/test_qpex.py, tests/utils.py
RDMA FLUSH[1] and ATOMIC WRITE[2] were added to rxe, but they cannot run
in the ODP mode as of now. This series is for the userspace enablement.
The former three patches correspond to an uapi change in the kernel.
(**v1/merged**) https://lore.kernel.org/linux-rdma/20250418051345.1022339-1-matsuda-daisuke@fujitsu.com/T/#t
The latter four add definitions of ODP capabilities and rdma-core testcases for the new features.
For kernel-side enablement in rxe, please see:
(**Updated v3/merged**) https://lore.kernel.org/linux-rdma/20250324075649.3313968-1-matsuda-daisuke@fujitsu.com/T/#t
[1] [for-next PATCH 00/10] RDMA/rxe: Add RDMA FLUSH operation
https://lore.kernel.org/lkml/20221206130201.30986-1-lizhijian@fujitsu.com/
[2] [PATCH v7 0/8] RDMA/rxe: Add atomic write operation …
=> RDMA FLUSH and ATOMIC WRITE with ODP

libibverbs/verbs.h
Cosmetic: fix typo ("protetion" -> "protection") in comments for `ibv_import_pd()` and `ibv_unimport_pd()`.
=>  libibverbs: Fix typos in comments in verbs.h

providers/efa/efa_trace.h, providers/efa/verbs.c
Extend the existing post_send tracepoints to have length in the events.
=> efa: Add WQE length to post_send tracepoint

providers/mlx5/man/mlx5dv_query_device.3, providers/mlx5/mlx5.c, providers/mlx5/mlx5dv.h, pyverbs/providers/mlx5/mlx5_enums.pxd, pyverbs/providers/mlx5/mlx5dv.pyx
Add a flag to indicate BlueFlame support through mlx5dv_query_device().
This can be used by an application to consider whether BlueFlame is supported by the device.
A matching pyverbs patch was added as well.
=> mlx5: Expose BlueFlame capability

providers/rxe/rxe.c
ibv_advise_mr(3) has been available only in mlx5, but it is now possible to use it with rxe because the ODP feature was already merged.
This change enables the library API for user-space applications.
There are kernel-side patches to handle prefetching requests in the kernel:
cf. https://lore.kernel.org/linux-rdma/20250522111955.3227-1-dskmtsd@gmail.com/T/#t
**(merged)**
=> rxe: Prefetching pages with ibv_advise_mr(3)

providers/rxe/rxe.c
Fix a bug in rxe cq_ex polling where the cq lock is unlocked twice causing undefined behavior. According the man page, the user should call `cq_end_poll` even if `cq_next_poll` returns ENOENT. This fix removes the `pthread_spin_unlock` call in `cq_next_poll` so that it is correctly called only once in `cq_end_poll`.
Fixes: e3af50b ("Provider/rxe: Implement Ibv_create_cq_ex verb")
=> rxe: Fix double unlock in cq_ex polling

debian/libibverbs1.symbols, kernel-headers/rdma/efa-abi.h, kernel-headers/rdma/ib_user_ioctl_cmds.h, kernel-headers/rdma/rdma_netlink.h, libibverbs/CMakeLists.txt, libibverbs/cmd_dmah.c, libibverbs/cmd_mr.c, libibverbs/driver.h, libibverbs/dummy_ops.c, libibverbs/libibverbs.map.in, libibverbs/man/CMakeLists.txt, libibverbs/man/ibv_alloc_dmah.3.md, libibverbs/man/ibv_reg_mr.3, libibverbs/verbs.c, libibverbs/verbs.h, providers/mlx5/mlx5.c, providers/mlx5/mlx5.h, providers/mlx5/verbs.c
This patch series introduces a new DMA Handle (DMAH) object, along with its corresponding verbs for allocation and deallocation. (i.e. ibv_alloc_dmah(), ibv_dealloc_dmah())
The DMAH object encapsulates attributes relevant for DMA transactions.
While initially intended to support TLP Processing Hints (TPH) [1], the design is extensible to accommodate future features such as PCI multipath for DMA, PCI UIO configurations, traffic class selection, and more.
This addition enables applications to allocate an opaque DMA handle that can be used to optimize DMA and RDMA operations associated with a registered memory region.
Additionally, we introduce a new verb named ibv_reg_mr_ex() with its corresponding ioctl (i.e. UVERBS_METHOD_REG_MR) on the MR object.
This verb consolidates multiple reg_mr …
=> verbs: RDMA support for DMA handle

pyverbs/pd.pyx, pyverbs/providers/mlx5/mlx5dv_objects.pyx, pyverbs/spec.pyx, tests/utils.py
The series includes two small test fixes related to Ipv6Spec class and mlx5 flow tests.
The head of the series consists of a patch adjusting Pyverbs' PD return type to be compatible with Cython 3.x.
=> tests: Fixes and Cython 3.x adjustment

libibverbs/cmd_cq.c
With CQ creation with external memory support the max number of attributes was increased but was left unchanged in the cmd declaration.
Fixes: 8d0ce825e0cc ("libibverbs: Add option to pass CQ buffers to kernel")
=> libibverbs: Fix create CQ max number of attributes

libibverbs/man/ibv_query_qp_data_in_order.3.md, libibverbs/verbs.c, libibverbs/verbs.h
EFA can support 128 bytes blocks write in-order for some Grace platforms. Move the check on x86 architecture to the mlx5 provider implementation.
Reviewed-by: Michael Margolin <mrgolin@amazon.com>
Reviewed-by: Yonatan Nachum <ynachum@amazon.com>
=> verbs: Allow query only device support for QP data in order

tests/test_mlx5_dmabuf.py
Set new cuda flag when creating FD for mlx5 dmabuf.
This flag is mandatory for data-direct traffic.
=> tests: Update PCIE mapping flag of mlx5 DMABUF

tests/test_mlx5_flow.py
Add missing TX capability check in test_flow_rdma_transport_domain_traffic.
The test only validated RX flow table support, but should also check both RX and TX flow table capabilities.
=> tests: Fix RDMA transport domain test capability validation

infiniband-diags/ibdiag_sa.c, infiniband-diags/ibqueryerrors.c
- Use mad_rpc_open_port_2 inside sa_get_handle
- Update handle members according to gsi port from mad_rpc_open_port2
- Replace umad_close_port in mad_rpc_close_port_2 inside sa_free_handle
This fixes behavior where we can take smi handle by mistake. mad_rpc_open_port2 does inside umad_open_port and umad_register, so we just need to assign the relevant values to the handle.
Fixes: aaf9f699c10f ("ibqueryerrors: Use API supporting SMI/GSI seperation")
=> infiniband-diags: Fix sa_get_handle to use smi/gsi API
